### ISSUE TITLE
accents on characters inside \textit{} are incorrectly positioned

### ISSUE THREAD

**Issue by kevinbarabash** [KaTeX/KaTeX#1099]
<img width="1088" alt="screen shot 2018-01-27 at 12 59 58 am" src="https://user-images.githubusercontent.com/1044413/35469155-91448f4c-02fd-11e8-99ca-53960714ceef.png">

We need to take into account the skew (as well as the height of the character).

**Comment by edemaine** [comment]
I've tracked the bug down to [these lines](https://github.com/Khan/KaTeX/blob/e4fe1c89d48585252e96b0f7d414b37d883aed70/src/buildCommon.js#L146-L160) of `buildCommon.mathDefault`

**Comment by edemaine** [comment]
The bug seems to stem from the choice of font. `$A$` renders an A in font family KaTeX_Math style italic, while `$\textit{A}$` renders an A in font family KaTeX_Main style italic.  KaTeX correctly detects this, and uses the *differing* metrics already in `fontMetricsData.js`:

```js
    "Math-Italic": {
        "47": [0.19444, 0.69444, 0, 0, 0],
        "65": [0, 0.68333, 0, 0.13889, 0.75],
        ...
    }, ...
    "Main-Italic": {
        ...
        "65": [0, 0.68333, 0, 0, 0.74333],
        ...
    },
`

0.13889 is the correct skew.  0 is not.

I assume the choice of fonts is "correct" (though we could of course use the math font for a letter A if we wanted...), so the "real" problem is the font metrics.  @kevinbarabash, any idea why the font metrics for Main-Italic would be different from the font metrics for Math-Italic, when the symbols look the same?

**Comment by kevinbarabash** [comment]
@edemaine not sure.  I'd have to see what we're doing in katex-fonts.  There is post-processing we do to some of the glyphs after extracting the paths from the source fonts.
