### ISSUE TITLE
audit duplicate definitions

### ISSUE THREAD

**Issue by kevinbarabash** [KaTeX/KaTeX#1128]
#1069 adds `'\lbrack` and `\rbrack` even though we already support them.  This is b/c there are multiple ways to define things in LaTeX/KaTeX.  It would be nice if we had a way to audit duplicate definitions.  Creating a central lookup for all defined commands/functions, symbols, macros, and environments might be one way of doing so.

**Comment by edemaine** [comment]
Can we add a custom lint process?

**Comment by ylemkimon** [comment]
Fixed by #1955.
