### ISSUE TITLE
\limits after \operatorname

### ISSUE THREAD

**Issue by Danmou** [KaTeX/KaTeX#1242]
Currently, using \limits after \operatorname gives the following error:
```
ParseError: KaTeX parse error: Limit controls must follow a math operator
```

Desired behavior:
`$\operatorname{E}\limits_x$` should place the x underneath the E, just like `$\max\limits_x$`

**Comment by ylemkimon** [comment]
To achieve the desired behavior, you should use `\operatorname*`, which isn't supported in the KaTeX yet.
