### ISSUE TITLE
Screenshotter test for Lap

### ISSUE THREAD

**Issue by ronkok** [KaTeX/KaTeX#1353]
It has proven difficult to get a valid screenshotter test for the `\rlap`, `\llap`, etc, series of functions. Screenshots created in Docker have varied from the same tests in Travis by a single vertical pixel and it isn't clear why that happens.

In order to resolve PR #1162 and thereby fix two rendering bugs, #1162 removed the screenshotter test for "Lap".

So this issue is a challenge to get that test to work successfully. The test code for Lap in `ss_data.yaml` is currently commented out.

**Comment by rrandallcainc** [comment]
I'm curious if the canvas rendering that I'm working on would help with these inconsistencies. Although, that might not be a good solution.

One potential workaround I can think of is supply an optional "tolerance" for the lap screenshot, and keep it very small (i.e. 0.01%).

**Comment by ylemkimon** [comment]
Closed via #1919 .
