### ISSUE TITLE
screenshotter hangs looking for host IP

### ISSUE THREAD

**Issue by kevinbarabash** [KaTeX/KaTeX#1394]
`Looking for host IP among 127.0.0.1, [::1], [fe80::1], [fe80::1020:3f09:a037:5997], 10.105.60.144, [fe80::bc48:7fff:fe76:d872], [fe80::1af5:2646:f63:f2d8], [fe80::276d:8f87:fe8f:2e5], [fe80::aede:48ff:fe00:1122]`

I got a new computer recently so I installed the latest docker which is `Version 18.03.1-ce-mac65 (24312)`.  Which version of docker are people running?

**Comment by edemaine** [comment]
I'm running `Docker version 17.06.0-ce, build 02c1d87` on Linux, so maybe the major version number is the culprit...

**Comment by kevinbarabash** [comment]
I'll try installing the previous version to see if that fixes it.  Thanks.

**Comment by kevinbarabash** [comment]
No luck.  This isn't really a blocker since we can grab screenshots from circleci.  I'll try to debug when I have more time.

**Comment by ylemkimon** [comment]
This is probably because we have hackish way of detecting the host IP on Docker for Mac:
https://github.com/Khan/KaTeX/blob/65569249be316362d2d8fca24b582dd003885c8a/dockers/Screenshotter/screenshotter.js#L326-L365

**Comment by ylemkimon** [comment]
Could you try commenting out following:
https://github.com/Khan/KaTeX/blob/65569249be316362d2d8fca24b582dd003885c8a/dockers/Screenshotter/screenshotter.js#L160-L165
?

**Comment by kevinbarabash** [comment]
Now it fails with the following message:
```
khan/KaTeX/dockers/Screenshotter/screenshotter.js:243
            throw new Error("Failed to connect selenium server.");
            ^

Error: Failed to connect selenium server.
    at Socket.<anonymous> (khan/KaTeX/dockers/Screenshotter/screenshotter.js:243:19)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Failed taking screenshots, stopping and removing a3e3f54bd271
```

**Comment by kevinbarabash** [comment]
I tried running `node dockers/Screenshotter/screenshotter.js` but it failed b/c it can't set the window size.  I think my local geckodriver/Firefox is too new.

Anyway, I feel like there's a fair amount of complexity with trying to communicate with the selenium running inside the docker from outside.  I wonder if mounting a folder would be any easier.  I know there were issues with mounting folders on some systems back in the day but maybe those issues have been resolved.

**Comment by kevinbarabash** [comment]
This is pretty low priority though b/c it's working on travis and circleci and people can grab screenshots from there as need be.

**Comment by ylemkimon** [comment]
Is this still an issue?

**Comment by kevinbarabash** [comment]
I haven't run the screens hotter in a while.  I'll reopen if it's still a problem whenever I end up running it again.
