### ISSUE TITLE
support \let

### ISSUE THREAD

**Issue by ylemkimon** [KaTeX/KaTeX#1413]
`\let` copies the content of a command into a new command.

**Comment by edemaine** [comment]
Thanks for making this an issue. I've been wondering about how to do this. It's easy for macros, but trickier for symbols and functions (when those symbols/functions later get replaced by macros).  Will probably require some additions to macro support.

**Comment by ylemkimon** [comment]
@edemaine I don't know exactly how `\let` exactly works, but I think it can be achieved using snapshotting(cloning) `MacroExpander`. Since there may be at most 1 or 2 `\let`s, I don't think there will be much overhead.
