### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by ylemkimon** [KaTeX/KaTeX#1468]
https://help.github.com/articles/about-issue-and-pull-request-templates/

**Comment by kevinbarabash** [comment]
Cool.  What do people think about having two issue templates: one for bug reports and one for feature requests?  We also have "discussion" issues from time to time.  Is there a way to bypass the template?  If not maybe we should also have a "discussion" template.

**Comment by edemaine** [comment]
Some suggestions for what to include in the bug-report template, off the top of my head:
* KaTeX version (with some basic instructions about how to measure `katex.version` -- I wonder if we should also add a `\katex@version` macro that can be used within KaTeX?).
* Web framework they're using (either that they're developing in, or an existing website).
* A pointer to common issues in the README that they should check first.

For feature requests, I'd suggest an explicit request for how you'd achieve the requested effect in regular LaTeX, if that's possible.

**Comment by ylemkimon** [comment]
> Is there a way to bypass the template?

If multiple issue templates exist, template selection page will be shown with `create a regular issue` button to bypass them:

![](https://help.github.com/assets/images/help/issues/new-issue-page-with-multiple-templates.png)

**Comment by kevinbarabash** [comment]
Cool!
