### ISSUE TITLE
Convert `for` array iterations to array functions

### ISSUE THREAD

**Issue by ylemkimon** [KaTeX/KaTeX#1616]
From [Airbnb style guide](https://github.com/airbnb/javascript):

> Use `map()` / `every()` / `filter()` / `find()` / `findIndex()` / `reduce()` / `some()` / ... to iterate over arrays

```javascript
const numbers = [1, 2, 3, 4, 5];

// bad
let sum = 0;
for (let num of numbers) {
  sum += num;
}
sum === 15;

// good
let sum = 0;
numbers.forEach((num) => {
  sum += num;
});
sum === 15;

// best (use the functional force)
const sum = numbers.reduce((total, num) => total + num, 0);
sum === 15;

// bad
const increasedByOne = [];
for (let i = 0; i < numbers.length; i++) {
  increasedByOne.push(numbers[i] + 1);
}

// good
const increasedByOne = [];
numbers.forEach((num) => {
  increasedByOne.push(num + 1);
});

// best (keeping it functional)
const increasedByOne = numbers.map(num => num + 1);
```

Ref: https://github.com/Khan/KaTeX/pull/1469#discussion_r203921764

**Comment by VinVaz** [comment]
Can I work on this one?

**Comment by kevinbarabash** [comment]
@VinVaz got for it. :)

**Comment by kevinbarabash** [comment]
One thing to call out is that these functions will make `flow` typing harder.

**Comment by ylemkimon** [comment]
@kevinbarabash Actually, it'll be easier to flow-type, as it understands those functions cannot mutate the array.

**Comment by kevinbarabash** [comment]
Things like `filter` don't work quite as expect if you're trying to filter out elements of a certain type in the hope that the resultant array will be typed correctly.  If you know how to get around this and other similar issues I would be forever grateful.

**Comment by SakaRicky** [comment]
Hi,
Is this issue still open for I'm interested in contributing through it as my first contribution.

**Comment by SakaRicky** [comment]
Sorry I now see the close tag

**Comment by Santosh1176** [comment]
Hi, is this issue still open? As I am seeing the open tag, can take a stab at this?
