### ISSUE TITLE
How to use inline equation with KaTex

### ISSUE THREAD

**Issue by devon** [KaTeX/KaTeX#166]
Does something like $a=b-1$ works?

Thank you.

**Comment by mpascucci** [comment]
Hello,

maybe you want to use a specific class for elements that should be converted to latex, and convert all elements of that class to latex.


example:
`<p>This equation : <span class="my_latex">f(x)=0</span></p>`

with this script at the end of the body:
```
    <script type="text/javascript">
      var els = document.getElementsByClassName("my_latex");
      //alert(els[0].textContent);
      for (var i =0; i< els.length; i++) {
        e = els[i]
        e.id = "latex_temp_id"
        katex.render(e.textContent, latex_temp_id);
        e.id = "";
      }
    </script>
```
