### ISSUE TITLE
\KaTeX of KaTeX and test.tex (texcmp) does not match

### ISSUE THREAD

**Issue by ylemkimon** [KaTeX/KaTeX#1703]
![mathrm](https://user-images.githubusercontent.com/888148/45166982-2ba35200-b233-11e8-9935-8bf50d622240.png)

https://github.com/Khan/KaTeX/blob/f71f469d4b3ca97654702a0807e736d176f4c4c5/src/macros.js#L711-L714

https://github.com/Khan/KaTeX/blob/f71f469d4b3ca97654702a0807e736d176f4c4c5/test/screenshotter/test.tex#L16-L22

**Comment by kevinbarabash** [comment]
We could define the `test.tex` to match our macro. 😛
