### ISSUE TITLE
Macro Expansion and Function Arguments Don't Work Together

### ISSUE THREAD

**Issue by maths22** [KaTeX/KaTeX#1720]
What do I expect: `\text\AA` to render as Å
What happens: `\text\AA` generates an error `(ParseError: KaTeX parse error: Got function '\r' as argument to '\text' at position 1: \̲r̲ ̲A)`

Why does this happen?  KaTeX expands macros before processing function arguments

Refs #924

**Comment by edemaine** [comment]
What's happening is that `\text\AA` is macro-expanding to `\text\r A` which obviously doesn't work (it should be `\text{\r A}`.  This does seem related to #924.  We could fix this instance now by tweaking the macro `\AA` to wrap in braces, which @ronkok has done for other macros, and is probably worth doing as an interim fix.  It'd be nice to fix it properly at the expansion/parsing level... I'm just not quite sure how.
