### ISSUE TITLE
Better insulate KaTeX from external CSS rules

### ISSUE THREAD

**Issue by Loginisalreadytaken** [KaTeX/KaTeX#175]
Using word-wrap: break-word; in html misplaces some fraction and sqrt lines, mainly in IE9. Certain settings in my general css are still affecting the math (they don't look exacly the same as in the demo), but I'll track them down and report back.

I guess this one could be fixed by adding word-wrap: normal; to .katex.

Also, thanks a lot for your work on this.. 1MB on drive compared to 166MB for MathJax. I just need simple math for elementary and early high school.

**Comment by kevinb7** [comment]
We probably could be doing more to insult KaTeX from external styles.  Would you be interested in submitting a pull request?

**Comment by gagern** [comment]
> We probably could be doing more to insulate KaTeX from external styles.

Perhaps we should have a look at [reset stylesheets](https://perishablepress.com/a-killer-collection-of-global-css-reset-styles/) and port the relevant portions from one or more of these to the `katex` class. Although I notice that none of them seems to mention `word-wrap`. :worried:

Another thing worth considering would be prefixing all CSS class names used by KaTeX with `katex_` or something similar. The KaTeX CSS is written in such a way that all its definitions only affect things inside a top level KaTeX element, but the converse is not true. For example, a page using a class `a` to denote its article headlines, or whatever, might well break the KaTeX logo which uses `a` for its second letter.

**Comment by kevinb7** [comment]
My preference we be to try the reset approach.

**Comment by gagern** [comment]
These are not two different approaches to the same problem, or not really. The reset stylesheet avoids interference with low-specificity settings and inherited properties while the namespace avoids interaction with non-inherited high-specificity rules.

**Comment by ylemkimon** [comment]
This can be now easily achieved by using frameworks such as Angular or React or web technology such as shadow DOM.
