### ISSUE TITLE
\fbox fails to inherit color from css

### ISSUE THREAD

**Issue by HenrySeed** [KaTeX/KaTeX#1772]
When colouring a Katex rendered field with CSS, it mostly works great, however the \fbox latex tag fails to recolour itself, and stays black.

<img width="894" alt="screen shot 2018-11-02 at 3 00 31 pm" src="https://user-images.githubusercontent.com/5369727/47889708-27e92000-deb0-11e8-8513-bcb2b34102fe.png">

Is it recommended to instead use some Latex form of colouring?

**Comment by edemaine** [comment]
@HenrySeed Yes, `\fbox` uses the current LaTeX color.  Try e.g. `\color{red}\fbox{hi}`: 
![image](https://user-images.githubusercontent.com/2218736/47890512-87e6b480-de25-11e8-87af-2e45e0ee3166.png)

You may want `\fcolorbox`, which lets you control the frame and background colors.  See https://katex.org/docs/support_table.html

**Comment by HenrySeed** [comment]
@edemaine Cool Ill use the `\color` tag. Is the coloring via HTML a supported feature or just an unintended side affect?

**Comment by kevinbarabash** [comment]
This is an interesting question.  So setting the color using `\textcolor` from the `xcolor` package results in the following:
```
\textcolor{green}{\fbox{a couple of words}}
```
This makes me think that if a CSS style updates the color of text it should also update the color `\fbox`.

**Comment by edemaine** [comment]
@kevinbarabash Agreed, it seems intuitive for `\fbox` to use the "default color".  It also seems to be technically possible, at least for `\fbox`: current we have a rule
```css
border: 0.04em solid black
```
but if we replace it with the `.fcolorbox` rule:
```css
border: 0.04em solid
```
it seems to just inherit the current color (including a default of black).

@ronkok Do you think there would be downsides to this?

**Comment by ronkok** [comment]
No objections here.

**Comment by edemaine** [comment]
Cool, then I put a PR together in #1847.
