### ISSUE TITLE
Leftright does not use buildGroup

### ISSUE THREAD

**Issue by spontaliku-softaria** [KaTeX/KaTeX#1777]
As far as I see, commands in delimsizing.js does not utilize buildGroup and build HTML with own functions from delimiter.js. I believe this prevents clean implementation of #835, creates bugs in PRs like #1698, and eventually breaks #809. Handlers unwrapping child delimiter are a part of the problem too (I mean `delim: delim.text` instead of `delim: delim` + further `buildGroup(delim)`).

**Comment by spontaliku-softaria** [comment]
What would be the best way to fix this? Does it need to be fixed in the first place?

**Comment by kevinbarabash** [comment]
@spontaliku-softaria can you point to which handlers are unwrapping child delimiters?  In general I think any place where we inspect or modify HTML that's already been built for child nodes is a bad idea.  I think this is what you're talking about, but I want to be sure before offering suggestions.

**Comment by spontaliku-softaria** [comment]
@kevinbarabash it's about HTML builder: https://github.com/Khan/KaTeX/blob/f4e24183d6d8f302e55bd0d588468489c2ba4e27/src/functions/delimsizing.js#L183 builds using delimiter.js and built nodes are never seen by buildGroup.

**Comment by spontaliku-softaria** [comment]
General idea is that I supposed buildGroup is called for each group, which allows unified modifications for every tree node built by parser (in my case parsed tree is external). Please correct me if this thing about buildGroup is not the case.

**Comment by kevinbarabash** [comment]
```
    htmlBuilder: (group, options) => {
        assertParsed(group);
        // Build the inner expression
        const inner = html.buildExpression(group.body, options, true,
            ["mopen", "mclose"]);
        ...
    }
```
`buildExpression` calls `buildGroup`.  Could you be more specific about what's being built in delimsizing.js that isn't being seen by `buildGroup`?

**Comment by spontaliku-softaria** [comment]
Sorry I wasn't specific enought and obfuscated the problem. Yes, inner expression is fine, but the problem is left and right delimiters themselves: `\\left` and `\\right` both have `delim` which is normal tree node but it is being "unwrapped" (leftright handler returns only the symbol instead of the whole node) and htmlBuilder uses `delimiter.leftRightDelim` which (I believe) does not call buildGroup (because it has no group at all due to unwrapping).

So, the one who wants to attach some data to `\\left(` or `\\right)` is unable to do so because data from nodes for `(` or `)` is not used.

**Comment by spontaliku-softaria** [comment]
This issue seems to be super specific to one use-case.
