### ISSUE TITLE
Comment at end of line within environment causes parse error

### ISSUE THREAD

**Issue by mmaloon** [KaTeX/KaTeX#1779]
In version 0.10.0 (no issue in 0.10.0-rc.1), I am getting parse errors when inside an environment I have a comment at the end of a line, followed by a line that starts with a command
```
\begin{aligned}
  a&=b+c \\ % comment
  \text{d}+e&=f
\end{aligned}
```
`KaTeX parse error: Expected & or \\ or \cr or \end at position 41: …\\ % comment \̲t̲e̲x̲t̲{d}+e&=f \end{a…`

**Comment by edemaine** [comment]
@mmaloon Thanks for reporting this bug!

@ylemkimon I'm guessing this was from one of the parser changes, maybe the raw/url string reader? We should also add some tests to catch such regression in the future.
