### ISSUE TITLE
katex.render double encodes HTML entities in MathML

### ISSUE THREAD

**Issue by antons** [KaTeX/KaTeX#1782]
`katex.render` double encodes HTML entities in MathML. For example, the following formula:

```latex
x < y
```

Produces an element with the following MathML:

```html
<math>
  <semantics>
    <mrow><mi>x</mi><mo>&amp;lt;</mo><msup><mi>y</mi><mn>2</mn></msup></mrow>
    <annotation encoding=\"application/x-tex\">x &amp;lt; y^2</annotation>
  </semantics>
</math>
```

`&amp;lt;` is produced, `&lt;` is expected.

`katex.renderToString` is not affected by the issue (`element.innerHTML = katex.renderToString` produces expected output).

**Comment by ylemkimon** [comment]
What version of KaTeX are you using?

**Comment by antons** [comment]
0.10.0. I can reproduce the issue on katex.org as well ([screenshot](https://user-images.githubusercontent.com/129705/48673629-09d81c80-eb4c-11e8-94a6-72816b46e57e.png) with `.katex-mathml` visible).

**Comment by antons** [comment]
@kevinbarabash I intentionally made the `.katex-mathml` visible to demonstrate that `&lt;` was double encoded.

Here’s the full HTML produced, including both HTML and MathML, that shows that HTML entities are double-encoded in MathML, but not in HTML:

```html
<span class="katex">
  <span class="katex-mathml">
    <math>
      <semantics>
        <mrow>
          <mi>
            x
          </mi>
          <mo>
            &amp;lt;
          </mo>
          <mi>
            y
          </mi>
        </mrow>
        <annotation encoding="application/x-tex">
          x &amp;lt; y
        </annotation>
      </semantics>
    </math>
  </span>
  <span class="katex-html" aria-hidden="true">
    <span class="base">
      <span class="mord mathdefault">x</span>
      <span class="mrel">&lt;</span>
    </span>
    <span class="base">
      <span class="mord mathdefault" style="margin-right: 0.03588em;">y</span>
    </span>
  </span>
</span>
```

**Comment by kevinbarabash** [comment]
<img width="649" alt="screen shot 2018-11-20 at 9 26 08 pm" src="https://user-images.githubusercontent.com/1044413/48816484-59674580-ed10-11e8-9b74-366c62b99c83.png">

I see what you're saying.  That explains why this screenshot looks the way it does.
