### ISSUE TITLE
\TeX is rendered incorrectly with \Huge and \footnotesize things

### ISSUE THREAD

**Issue by fennecf0x** [KaTeX/KaTeX#1786]
![katex](https://user-images.githubusercontent.com/41368919/48829048-aa307a00-edb4-11e8-8f82-ac59668f15e3.png)

The size of 'E' does not change. Same problem occurs with 'A' in \LaTeX and \KaTeX.

**Comment by edemaine** [comment]
Indeed, LaTeX renders `$$\text{\Huge\TeX}$$` as 
![image](https://user-images.githubusercontent.com/2218736/48846939-58fd9780-ed6e-11e8-989b-8a34dd7b343c.png), so this is a bug.  Thanks for the report!
