### ISSUE TITLE
Force border-spacing to 0

### ISSUE THREAD

**Issue by bergwerf** [KaTeX/KaTeX#1799]
Hi, I was rendering some latex inside a table with `border-spacing: 1em;` and it produced stuff like this: 
![image](https://user-images.githubusercontent.com/4458965/49299753-cf15a300-f4c0-11e8-839d-763e9fff4839.png)

After some poking I found that setting `border-spacing: 0;` on `.katex` solved this problem. I would think that resetting all important CSS properties is intended, so perhaps this rule is still missing?

**Comment by kevinbarabash** [comment]
This appears to be a specific case of #175.  PRs in this area are definitely welcome.  I'm going to close this issue as a duplicate.
