### ISSUE TITLE
How to use KaTex

### ISSUE THREAD

**Issue by linwaytin** [KaTeX/KaTeX#1804]
Hello, I am trying to use this library, but have no idea how to make it work.

My HTML code is following:
```
<!DOCTYPE HTML>
<html>
    <head>
	<meta charset="UTF-8">
	<title>Test Katex</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/katex.css" integrity="sha384-xNwWFq3SIvM4dq/1RUyWumk8nj/0KFg4TOnNcfzUU4X2gNn3WoRML69gO7waf3xh" crossorigin="anonymous">
        <script defer src="https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/katex.js" integrity="sha384-UP7zD+aGyuDvxWQEDSRYcvoTxJSD82C6VvuEBktJZGo25CVhDstY9sCDHvyceo9L" crossorigin="anonymous"></script>
    </head>

    <body>
    <p><span id="element">...</span></p>
    <script>
    katex.render("f(a,b,c) = (a^2+b^2+c^2)^3", element, {throwOnError: false});
    </script> 
    </body>
</html>
```

The resulting webpage showed only ... which is the original content in the span.
I followed the instruction in the doc [https://katex.org/docs/api.html](https://katex.org/docs/api.html)
Obviously I missed something, but I cannot figure it out.

Thank you.

**Comment by edemaine** [comment]
In your JavaScript code, `element` is undefined. You need to write `document.getElementById('element')` instead.

You might also consider using the autorender extension (see the documentation), which makes this substantially easier.

**Comment by linwaytin** [comment]
That works. It seems that I have to put the `katex.render()` inside a function, and then trigger the function by an event. I will try the autorender extension.

Thanks a lot.

**Comment by edemaine** [comment]
Glad you got it working!

**Comment by kevinbarabash** [comment]
The weird thing about the `id` attribute is that it actually adds entries to the `window` object (when it can) so `element` should defined after page load.  I would avoid any reliance on this behavior since it will fail if the id matches an non-writeable entry in `window`.
