### ISSUE TITLE
hphantom not exactly as wide as visible expression

### ISSUE THREAD

**Issue by bergwerf** [KaTeX/KaTeX#1805]
It appears the `hphantom` does not have exactly the same width as the content that is hidden. To reproduce, put `a\frac{1}{2}=a\\a\hphantom{\frac{1}{2}}=a` in the demo box at katex.org. Replace `hphantom` with `phantom` to see that the normal phantom command does show correct behavior.

| `\hphantom` | `\phantom` |
|--|--|
| ![image](https://user-images.githubusercontent.com/4458965/50190757-c4fdfc00-032a-11e9-84cc-329411c5431c.png) | ![image](https://user-images.githubusercontent.com/4458965/50190778-d941f900-032a-11e9-8b06-4758b0670ce2.png)

**Comment by ronkok** [comment]
Yep, that;s a bug. I think I see the problem. The `\hphantom` should be given a `mord` class, just like what it contains. That would cause the correct spacing to the relation to its right. 

I think I wrote the `\hphantom` code. I'll see if I work something up to fix it.
