### ISSUE TITLE
Jest problem on Windows

### ISSUE THREAD

**Issue by ronkok** [KaTeX/KaTeX#1810]
Since PR #1798 was merged, I can no longer run `yarn test:jest`. I get the error message:
```
yarn run v1.12.3
$ NODE_PATH=./:$NODE_PATH jest
'NODE_PATH' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm working on a Windows box, if that matters. `flow` still works.

**Comment by edemaine** [comment]
I noticed the same problem on Windows. @ylemkimon Was there a reason for that change?

**Comment by kevinbarabash** [comment]
This change was from #1784.  I think we can fix this using `modulePaths` in the jest config.  I'll can put up a PR for this.
