### ISSUE TITLE
Warning: No character metrics for '中' in style 'Main-Regular'

### ISSUE THREAD

**Issue by upupming** [KaTeX/KaTeX#1817]
When I write Chinese characters in a math code block:

```latex
$$
f(x) = 测试中文
$$
```

They will be rendered properly but I still got a warning like this in the console:

```node
katex.js:5308 No character metrics for '中' in style 'Main-Regular'
```

This is a screenshot:

![image](https://user-images.githubusercontent.com/24741764/50574395-feeafa00-0e22-11e9-820a-194588842254.png)

Follow the call stack, I can see the warning was logged at: https://github.com/KaTeX/KaTeX/blob/8346294bf30b438379bea17f5e626fb546f55d62/src/buildCommon.js#L82-L85

I have tried setting `strict` option to `false`. But it only disables `LaTeX-incompatible` warning, the problem above still exists. Could you please explain what does this mean, and how can I avoid it?

**Comment by kevinbarabash** [comment]
This is a know issue, but it's good to have a github issue to track it.  There are a few ways that we can look at addressing this:
- use something like https://github.com/nippur72/ifdef-loader to only include the offending code in development
- add a option to show warnings in production
- measure glyphs at runtime to get metrics (this is slow)
- wait for browsers to ship the Font Metrics API that supposed to be part of the upcoming Houdini set of CSS APIs

I think we should do one of the first two items to resolve this issue and then open a separate issue for getting accurate metrics for all glyphs.  I think adding an option to control whether we see these warnings and have it default to `off` is probably the way to go.
