### ISSUE TITLE
"argmax" and "argmin" not possible to write

### ISSUE THREAD

**Issue by filipre** [KaTeX/KaTeX#1818]
Hi, 

I have troubles to write a proper "arg max" and "arg min" such that the argument is *below* the operator and in the center and not *next* to it. 

It should look like this:

<img width="94" alt="screenshot 2019-01-01 at 18 25 38" src="https://user-images.githubusercontent.com/8502198/50574937-b0256c00-0df2-11e9-937a-fdad927220bd.png">

I tried
```
\arg\min_{A, B}
\operatorname{argmin}_{A, B}
\DeclareMathOperator{\argmin}{arg\,min}
\operatorname{argmin}_{\hbox{A, B}}
```

Do you have an idea how to make this work? Am I missing some obvious solution?

Thanks
René

**Comment by edemaine** [comment]
Here's how we define `\limsup` macro:

```js
"\\mathop{\\operatorname{lim\\,sup}}\\limits"
```

So you could do the same with `argmin` (or `arg\,min`) either by passing a string like above for a macro, or as a one-off (or `\def`) in TeX like so:

```latex
\mathop{\operatorname{arg\,min}}\limits
```

**Comment by filipre** [comment]
Wow, thats awesome! 

Is there any reason not to add this macro to KaTeX? If not, then I would like to implement this as my first contribution.

**Comment by edemaine** [comment]
I agree that it would be a useful macro. Is it defined in any existing LaTeX package(s)? We generally aim to reproduce LaTeX behavior, so that would be ideal.

**Comment by filipre** [comment]
I opened #1820. Sadly I could not find any package that defined `\argmax` nor `\argmin`. It seems like, everyone always defines them on their own. Also, there does not seem to be a consensus how to define it "properly". Therefore, I created a new section at the very bottom of the `macros.js` file. 

I still believe it makes sense to add it, because in KaTeX it's not possible (?) to define custom math operators on the go. Once we find out, that it has been implemented in some other package, we can still move it to the right place.

**Comment by edemaine** [comment]
I found a definition of `\argmin` and `\argmax` in the [CTAN `statmath` package](https://ctan.math.illinois.edu/macros/latex/contrib/statmath/statmath.pdf) as
```latex
\DeclareMathOperator{\argmin}{arg\,min}
\DeclareMathOperator{\argmax}{arg\,max}
```
which I think matches your definition.

**Comment by filipre** [comment]
ah, alright. I put a reference to that package and updated the PR.
