### ISSUE TITLE
Feature request: show math as tex commands

### ISSUE THREAD

**Issue by upupming** [KaTeX/KaTeX#1819]
It would be nice if I can inspect Tex Commands of the math equation as [MathJax does](https://www.mathjax.org/#demo):

![image](https://user-images.githubusercontent.com/24741764/50581185-45c40880-0e92-11e9-9cb2-cd34d688ca23.png)

**Comment by edemaine** [comment]
This could be a reasonable add-on. I'm personally not a huge fan, but I imagine people coming from MathJax might enjoy it.

You might be interested in KaTeX's copy-tex add-on which enables copy/pasting math and getting the LaTeX source code.

**Comment by upupming** [comment]
Thanks, the contrib code helps and it is just what I need! Now I'm going to close it.
