### ISSUE TITLE
\dfrac and \cfrac are rendered too big inside \xrightarrow

### ISSUE THREAD

**Issue by fennecf0x** [KaTeX/KaTeX#1822]
```latex
\dfrac a b
\xrightarrow [2.\, \dfrac c d]
             {1.\, \displaystyle\frac c d}
\xrightarrow [4.\, \normalsize \dfrac c d]
             {3.\,\Large \displaystyle\frac c d}
{ \displaystyle \frac e f }
```
yields 
![image](https://user-images.githubusercontent.com/41368919/50679662-b6605600-1047-11e9-9bae-c7d416bd358c.png)
even in the display mode.

`2.\, \dfrac c d` is rendered like `\Large` applied. (2. and 3. have the same size, and `\normalsize` in 4. restore that.)

**Comment by ronkok** [comment]
@fennecf0x Thank you for reporting this bug. I see where the problem occurs and I should be able to write up a PR tomorrow that will fix the problem.
