### ISSUE TITLE
Cannot make linebreaks in mathematical formula using KaTeX

### ISSUE THREAD

**Issue by tivewsalaeharad** [KaTeX/KaTeX#1824]
I'm trying to create an Android vidget that shows mathematical formula, using KaTeX library and WebView. The problem is that I cannot configure it to automatical wrapping of formulae, that are bigger, than screen.

My java code:

```
    WebView webView = new WebView(SpaceActivity.this);
    webView.getSettings().setJavaScriptEnabled(true);
    webView.getSettings().setCacheMode(WebSettings.LOAD_NO_CACHE);
    webView.setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT));
    webView.setPadding(2, valueViewer.getTextPadding(), 2, valueViewer.getTextPadding());
    String html = "<!DOCTYPE html>\n" +
            "<html>\n" +
            "    <head>\n" +
            "        <meta charset=\"UTF-8\">\n" +
            "        <title>Auto-render test</title>\n" +
            "        <link rel=\"stylesheet\" type=\"text/css\" href=\"file:///android_asset/katex/katex.min.css\">\n" +
            "        <script type=\"text/javascript\" src=\"file:///android_asset/katex/katex.min.js\"></script>\n" +
            "        <script type=\"text/javascript\" src=\"file:///android_asset/katex/contrib/auto-render.min.js\"></script>\n" +
            "    </head>\n" +
            "    <body>\n" +
            "        " + expression + // variable, containing formula in TeX-format
            "        <script>\n" +
            "          renderMathInElement(\n" +
            "              document.body\n" +
            "          );\n" +
            "        </script>\n" +
            "    </body>\n" +
            "</html>";
    webView.getSettings().setSupportZoom(true);
    webView.loadDataWithBaseURL("file:///android_asset/", html, "text/html", "utf-8", null);
```

Earlier I used MathJax library, but it is much slower than KaTeX, plus, when I give new formula to MathJax-related vidget, it flashes and diddles, making unbeautiful performance.

How can I configure KaTeX for line wrapping?

**Comment by edemaine** [comment]
@tivewsalaeharad Could you give an example of the LaTeX expression you're trying to render?

**Comment by tivewsalaeharad** [comment]
> @tivewsalaeharad Could you give an example of the LaTeX expression you're trying to render?

Of course:

$$(a^x)' = \lim_{\Delta x \to 0} \frac{a^{x + \Delta x} - a^x}{\Delta x} = \lim_{\Delta x \to 0} \frac{a^x (a^{\Delta x} - 1)}{\Delta x} = a^x \lim_{\Delta x \to 0} \frac{a^{\Delta x} - 1}{\Delta x} = \begin{bmatrix} \frac1{n} = a^{\Delta x} - 1 \\ \Delta x = \log_a(\frac1{n} +1) \\ n \to \infty \end{bmatrix} = {a^x \lim_{n \to \infty} \frac1{n\log_a (\frac1{n} +1)}} ={\frac{a^x}{\log_a \lim\limits_{n \to \infty} (\frac1{n} +1)^n}} = {\frac{a^x}{\log_a e}} = a^x \ln a$$

In MathJax after flashing and diddling in performs in such way

![tojwuvxwkrc](https://user-images.githubusercontent.com/25724579/50740396-ac348800-11fe-11e9-93d7-ccdff75a66d7.jpg)

**Comment by ronkok** [comment]
@tivewsalaeharad Try using `\displaystyle` inside a pair of `$…$` delimiters. Avoid `$$…$$` if you want automatic line breaks.  KaTeX, like TeX, does not do automatic line breaks in display mode.

**Comment by tivewsalaeharad** [comment]
> @tivewsalaeharad Try using `\displaystyle` inside a pair of `$…$` delimiters. Avoid `$$…$$` if you want automatic line breaks. KaTeX, like TeX, does not do automatic line breaks in display mode.

@ronkok thank you, but there are some bugs:
1) this way deprecates \small and other scaling, I need, for example in big fractions, when I need to mimimize formula text

2) fraction lines are absent

![1](https://user-images.githubusercontent.com/25724579/50742205-d09d5e00-1218-11e9-8554-b163ee7f2a35.png)
![2](https://user-images.githubusercontent.com/25724579/50742206-d09d5e00-1218-11e9-8888-4fa5bebcb1f9.png)

3) automatical word wrap doesn't occur

**Comment by edemaine** [comment]
@tivewsalaeharad Would manual line breaks suffice for your purposes? If so, you could use `\\` in `$$...$$`.

As @ronkok points out, KaTeX does not do automatic line breaks within `$$...$$`, only within `$...$`, the same as LaTeX. You might be able to force low-quality automatic line breaking in `$$...$$` with some CSS mangling, perhaps:
```css
.katex-display > .katex { white-space: normal }
```

`$\displaystyle ...$` should be what you want.  I imagine the first two bugs you list apply equally well to `$$...$$` as they shouldn't matter either way.
1. What is `\Tiny`? I've never heard of this sizing macro. `\tiny` is the smallest LaTeX size.
2. Sounds like you're running into a `\frac` bug, perhaps #1775. As far as we understand, these are bugs in the web browser.

**Comment by tivewsalaeharad** [comment]
@edemaine I'm looking for automatic line breaks, because (for instance) user can rotate mobile, and app is to re-arrange wrapping.

I set $..$, \displaystyle and ```.katex-display > .katex { white-space: normal }```, formulae had been wrapped, but began to overlap. This is on laptop:

![image](https://user-images.githubusercontent.com/25724579/50804565-90fd7180-12ff-11e9-8af9-e1331ba286e1.png)

```\Tiny``` is scaling, used in MathJax between ```\small``` and ```\tiny```, perhaps it's just not supported in KaTeX.

**Comment by edemaine** [comment]
Did you try `$\displaystyle ...$` without the CSS hack? It should auto line break at relations like `=`. Here's your example which seems to be working fine:

![screenshot_20190107-220056_chrome](https://user-images.githubusercontent.com/2218736/50807379-18c78980-12c8-11e9-913c-c5bedca7f806.jpg)

**Comment by edemaine** [comment]
It wraps on katex.org if you turn off displayStyle in the settings menu (click on the gear). This is the equivalent of using `$` instead of `$$`.

**Comment by edemaine** [comment]
Closing this, as it's represented by other requests for automatic line breaking in display math (e.g. #1023).
