### ISSUE TITLE
KaTeX false matches

### ISSUE THREAD

**Issue by BenjaminHoegh** [KaTeX/KaTeX#1830]
KaTeX have some false matches that I would like to report.

## Types
As we know there are two types of matchs in TaX/MathJax: inline and block

> "By default, the tex2jax preprocessor defines the LaTeX math delimiters, which are `\(...\)` for in-line math, and `\[...\]` for displayed equations. It also defines the TeX delimiters `$$...$$` for displayed equations, but it does not define `$...$` as in-line math delimiters. That is because dollar signs appear too often in non-mathematical settings, which could cause some text to be treated as mathematics unexpectedly."

**Inline:**
1. `\( ... \)`
3. `$ ... $` optional setting, not recommended

**Block:**
1. `\[ ... \]`
2. `$$ ... $$`
3. `\begin` & `\end`

## My Test

Using this little test I find some issues. See the [result here](http://jsfiddle.net/Ranazomic/15zwqkvj/5/)

_NOTE: no match means that we expect no match_
```
$$ Don't match$
$Don't match$$
\\$Don't match\\$
$Don't match\\$
\\$Don't match\\$

$$ match $$ don't match nested $$ match $$

$$$ Don't match $$
$$ Don't match $$$
\\$$ Don't match$$
$$ Don't match\\$$
\\$$ Don't match\\$$

\( match \)
\( 1 \(  nested match  \) 3 \)

\\( Don't match \\)
\( Don't match \\\\)
\\\\( Don't match \\\\)

\[ match \]
\[ 1 \[ nested match \] 3 \]

\\\\[ Don't match \\]
\\[ Don't match \\\\]
\\\\[ Don't match \\\\]

\begin{equation} match \end{equation}
\begin{equation} 1 \begin{equation} nested match \end{equation} \end{equation}

\\\\begin{equation} Don't match \\end{equation}
\\begin{equation} Don't match \\\\end{equation}
\\\\begin{equation} Don't match \\end{equation}
```

in case you need a little help how this can be done, [see this link](https://regex101.com/r/wP2aV6/25)

**Comment by kevinbarabash** [comment]
Can you post which cases are matching when they shouldn't be matching?

**Comment by BenjaminHoegh** [comment]
> Can you post which cases are matching when they shouldn't be matching?

http://jsfiddle.net/Ranazomic/5joe4zLx/2/

**Comment by kevinbarabash** [comment]
I see, we want `\\$$` to behave in the same way that `\\$` does.  I seems like the four failing cases are:
```
$$ Don't match $$$
\\$$ Don't match$$
$$ Don't match\\$$
\\$$ Don't match\\$$
```
Is that correct?

**Comment by edemaine** [comment]
@BenjaminHoegh @pzinn Thanks to PR #2679, the master branch now has an improved auto-render script. Could one of you test whether these false matches are still falsely matching, and whether they should be fixed?
