### ISSUE TITLE
Matrix rendering broken

### ISSUE THREAD

**Issue by milosgajdos83** [KaTeX/KaTeX#1831]
Whilst migrating my blog to [hugo](https://gohugo.io/) I came across an issue with Katex where matrices are not being rendered properly in the HTML produced by hugo.

Take for example the following matrix defintion:
```
$$ X = \left[\begin{array} {rrr} 3.381563 & 3.389113 
4.527875 & 5.854178 
2.655682 & 4.411995 
\vdots & \vdots \end{array}\right] $$
```

When I paste it to the Katex playground it renders just fine, which makes me think there is something else funky at play.

See the following `js` error in the Chrome console and the result of the rendering:

<img width="1357" alt="screen shot 2019-01-11 at 19 02 25" src="https://user-images.githubusercontent.com/1392526/51054311-60a22580-15d4-11e9-9e41-195a166dccd7.png">

I suspect some this might be some strange CSS issue as the rendered HTML looks like this:

<img width="1054" alt="screen shot 2019-01-11 at 19 05 30" src="https://user-images.githubusercontent.com/1392526/51054357-892a1f80-15d4-11e9-877d-74ad20e348e4.png">

Which does not seem right at all. Could someone give me some pointers as to how to fix this if possible? 

Thanks

**Comment by edemaine** [comment]
@milosgajdos83 You might have better luck asking on a hugo forum. Presumably hugo, or the hugo-KaTeX plugin (if there is one), is doing something wrong here.  Your screenshot suggests that KaTeX is running (causing it to print a warning, not an error, so presumably it's mostly working) yet the text is not actually getting replaced.  It's pretty hard to tell why that's happening; it's unlikely to be a KaTeX issue.

Searching around the hugo link you sent, perhaps http://nosubstance.me/post/a-great-toolset-for-static-blogging/ (linked from https://gohugo.io/content-management/formats/#issues-with-markdown) is a helpful starting point.

**Comment by milosgajdos83** [comment]
Thanks @edemaine, I will keep digging. Seems like some random parser shenanigans. I will close this issue now and should I figure out solution I'll pop in and let you know.

**Comment by mbourne** [comment]
@milosgajdos83 Hugo is trying to be helpful and is assuming you want line breaks where you have them in your text. So in your array it is adding a &lt;br&gt; at the line breaks and so it messes up KaTex. I assume you have the variable hardlineBreak set to true, and perhaps you'll need to set it to false. See this section: https://gohugo.io/content-management/formats/#blackfriday-extensions Alternatively (and probably better, becausse you probably do want hardlineBreak to be true elsewhere), you could enter your math all on one line, and it should work fine.

**Comment by milosgajdos83** [comment]
@mbourne I don't have any extra Blackfriday extensions settings enabled so I assume, based on the documentation they should be disabled. I've tried nevertheless explicitly disabling it by listing empty extension for blackfriday:

```
[blackfriday]
  extensions = []
```

This however has no effect on the rendering whatsoever.

Your second suggestions, however somewhat does resolve the problem, alas it places all matrix elements on the same line - it seems `\\` does not create an extra line between matrix lines:

<img width="713" alt="screen shot 2019-01-12 at 00 51 02" src="https://user-images.githubusercontent.com/1392526/51066762-2c465d80-1604-11e9-8948-f736ade2f0c1.png">

Is there any way I can enter that extra line  should I decide to go with your second suggestion since it does point in the right direction.

Thank you for pointing me in the right direction.

**Comment by milosgajdos83** [comment]
Major breakthrough \o/

Escaping the `\\` solves the problem:

```
$$ \left[\begin{array} {rrr} 3.381563 & 3.389113 \\\\ 4.527875 & 5.854178 \\\\ 2.655682 & 4.411995 \\\\ \vdots & \vdots \end{array}\right] $$
```

I suspect now we've gone full circle to what @edemaine was suggesting to have a look at: https://gohugo.io/content-management/formats/#issues-with-markdown

I suspect if I modify the code which uses `katex` and add the `displayMath` math "hack" mentioned in hugo documentation I should be fine.

**Comment by edemaine** [comment]
It does seem a shame that all this rendering is happening at page load. One of the cool things about KaTeX is that you can render at compile time. This might be in better fitting with hugo (it's a static page generator, right?) but would presumably require a parser/plugin of some sort.

**Comment by milosgajdos83** [comment]
Totally agree with you @edemaine Yes hugo is a static page generator -- that's it. The thing which sort of makes it seem "dynamic" are various themes which add all kinds of javascript addons to the rendered HTML.
