### ISSUE TITLE
How to recreate this usage of sideset in KaTeX?

### ISSUE THREAD

**Issue by sorenbug** [KaTeX/KaTeX#1832]
```tex
{\sideset{_\alpha^\beta}{_\gamma^\delta}{\mathop{\begin{pmatrix}a&b\\c&d\end{pmatrix}}}}
```
![image](https://user-images.githubusercontent.com/7751296/51064360-1f018280-15b4-11e9-84ec-3ac97fff3ad4.png)

**Comment by stevem6** [comment]
There are likely to be a number of ways of simulating this. Here are just two of them:
```
\phantom{\begin{pmatrix}a\\b\end{pmatrix}}^{\normalsize\beta}_{\normalsize\alpha}\begin{pmatrix}a&b\\c&d\end{pmatrix}^{\normalsize\,\delta}_{\normalsize\,\gamma}

\begin{matrix}\beta\\[2ex]\alpha\end{matrix}\begin{pmatrix}a&b\\c&d\end{pmatrix}\begin{matrix}\delta\\[2ex]\gamma\end{matrix}
```
and the 2 methods give respectively:
![image](https://user-images.githubusercontent.com/21204267/51075909-e3d18300-1689-11e9-9da1-6a1815ce5a15.png)

**Comment by sorenbug** [comment]
Thank you!
