### ISSUE TITLE
Pure native android support

### ISSUE THREAD

**Issue by manoj-madanmohan-toppr** [KaTeX/KaTeX#1840]
Is there any plan to build a port of this for native android? We were hoping to render Katex directly on an android customview, without any kind of webview in between

Has any thought gone onto this? Is this feasible?

**Comment by edemaine** [comment]
This is related to alternate output mechanisms, in particular, Canvas (#251) and SVG (#375) which require explicit layout (whereas current rendering definitely relies on an HTML rendering engine for layout). We haven't implemented any such alternative output mechanisms; they are possible in principle, but it's a rather large effort. 

If you wanted to avoid a V8 engine too, this would involve porting a ton of JavaScript code into Android Java -- I'm not aware of such an effort, and this is less likely to happen, as it would fork the code.

**Comment by kevinbarabash** [comment]
In order to do this we really need to hammer out an intermediate representation and then migrate existing code to use this representation.  Once we have that we can work on separate backends.  Echoing what @edemaine said, this is a rather large effort.  I wonder if it would be easier to adapt an existing Java-based TeX rendered for use on Android.

**Comment by karino2** [comment]
We are doing somewhat similar thing. (though not exactly the same as this issue).

https://github.com/karino2/kotlitex/

This is basically

- port KaTeX to kotlin
- port canvas-latex to android native canvas

Of course kotlin is different language and sometime it's impossible to map 1 by 1 from node code to kotlin code.
But we try to keep code as equal as possible.

We are not yet even in alpha stage, but basic structure of code is determined and current code base already show some feasibility of our idea.

**Comment by ylemkimon** [comment]
Closing in favor of existing issues.
