### ISSUE TITLE
\clap changes spacing between \mathop and \left(

### ISSUE THREAD

**Issue by spontaliku-softaria** [KaTeX/KaTeX#1849]
Latex `\mathop{1}\clap|\left(\right)` and `\mathop{1}\left(\right)` has different width:
![screenshot_20190218_170311](https://user-images.githubusercontent.com/6647438/52974130-40b60c80-339f-11e9-958e-25472f6975a9.png)
![screenshot_20190218_170344](https://user-images.githubusercontent.com/6647438/52974132-43186680-339f-11e9-960f-d7be53820902.png)

Better demonstration (reproduces with \sin too):
![peek 2019-02-18 17-08](https://user-images.githubusercontent.com/6647438/52974338-eff2e380-339f-11e9-9d2f-79493d40c000.gif)

\smash and \mathclap are affected too.

**Comment by edemaine** [comment]
@spontaliku-softaria That is how LaTeX works, so it is considered correct (if somewhat counterintuitive) behavior by KaTeX.  Here's an example rendered with LaTeX:

```latex
\begin{array}{l}
\mathop{1}\mathclap|\left(\right)\\
\mathop{1}\left(\right)
\end{array}
```

![image](https://user-images.githubusercontent.com/2218736/52974550-fed19a00-338f-11e9-8ad7-ef3a5ed9e916.png)

And the same example rendered with KaTeX:

![image](https://user-images.githubusercontent.com/2218736/52974593-1a3ca500-3390-11e9-950f-4e5199978e07.png)

TeX is pretty complicated in terms of spacing, but if you don't want to affect the op-style spacing, you probably mean something like this:

```latex
\mathop{1\mathclap|}\left(\right)
```
