### ISSUE TITLE
how to use katex in vueJS ,is there some demo,like the angular-katex

### ISSUE THREAD

**Issue by leoluu** [KaTeX/KaTeX#1850]
Hi ,how to use katex in vueJS ,is there some demo,like the angular-katex, which allow lable 
```
<!-- Tag element -->
<katex>x^2</katex>

<!-- Attribute -->
<div katex>x^2</div>

<!-- Attribute value -->
<div katex="x^2"></div>

<!-- expr attribute value -->
<katex expr="x^2"></katex>

<!-- Bind to scope
  $scope.tex = {pow: 'x^2'}
  -->
<katex bind="tex.pow"></katex>

<!-- Set display mode -->
<katex expr="x^2" display-mode></katex>
```

**Comment by edemaine** [comment]
I have no experience with VueJS, but did you try either of these modules?
* https://github.com/lucpotage/vue-katex
* https://github.com/dangvanthanh/vue-a11y-katex

**Comment by leoluu** [comment]
yeah,I have try ,and it not support auto-render,

**Comment by edemaine** [comment]
Indeed, I doubt you'd want to use auto-render with either of these packages (or VueJS in general). But you shouldn't need auto-render; that's just one way to trigger calling KaTeX on all math expressions, and these packages should fully replace that with a different Vue-compatible way.

**Comment by kevinbarabash** [comment]
I'd give one those packages a try.
