### ISSUE TITLE
Need example complete HTML file that uses KaTeX to render a few LaTeX formulas

### ISSUE THREAD

**Issue by johnm719** [KaTeX/KaTeX#1855]
I have MathJax working, but need an example HTML that uses KaTeX so I can see what must be changed to switch to KaTeX.

**Comment by ylemkimon** [comment]
Please refer to https://github.com/KaTeX/KaTeX#starter-template and https://katex.org/docs/api.html.

**Comment by rafal-mi** [comment]
This is not an answer as there are no complete examples here. All that you get is _katex is not defined_.

**Comment by mbourne** [comment]
Some time ago I submitted 2 starter templates which appear to have languished there ever since. https://github.com/KaTeX/KaTeX/issues/3662#issuecomment-1157379062

I never did figure out how to submit a PR.
