### ISSUE TITLE
Bundling only woff fonts

### ISSUE THREAD

**Issue by ramjyroo** [KaTeX/KaTeX#1857]
USE_TTF=false USE_WOFF2=false yarn build seems to be required other than setting the @use-ttf and @use-woff2 in the fonts.less to ensure the dist/fonts only contains woff.

Can this be documented.

**Comment by ylemkimon** [comment]
Unfortunately, manually setting LESS variables no longer works. The environment variable settings are documented on https://katex.org/docs/font.html. Any suggestion on its improvement is welcome!
