### ISSUE TITLE
Reenable Greenkeeper

### ISSUE THREAD

**Issue by ylemkimon** [KaTeX/KaTeX#1858]
It seems the Yarn version of Greenkeeper has been updated and it preserves the integrity field.

This may need contacting them as we renamed the repo: https://greenkeeper.io/faq.html#renamed-repo.

CC @kevinbarabash

**Comment by kevinbarabash** [comment]
I can do that.

**Comment by kevinbarabash** [comment]
Sorry for dragging my heels on this.  We should maybe look at dependabot for this instead.

**Comment by kevinbarabash** [comment]
I've added dependabot.  We use it for a few projects at work and it seems to work well with yarn.lock files out of the box.  If it works well I'll disable our greenkeeper setup.

**Comment by kevinbarabash** [comment]
It just sent us five PRs, lol.

**Comment by edemaine** [comment]
Make that ten. 😃 By the way, do you know why every PR is getting two Codecov reports?  Github folds one of them as "similar" in the web interface, but I get two Codecov emails for every PR. ☹️

**Comment by kevinbarabash** [comment]
I didn't realize it was every PR that was get two Codecov reports.  I can report the issue to them.  I think part of it may be because we run things on PRs and branches.

**Comment by kevinbarabash** [comment]
I've turned this setting on, hopefully that'll help things:
<img width="887" alt="Screen Shot 2019-07-08 at 11 12 38 PM" src="https://user-images.githubusercontent.com/1044413/60856690-062a0080-a1d6-11e9-8cc0-b8269da7c654.png">

We may also want to try:
<img width="1255" alt="Screen Shot 2019-07-08 at 11 14 16 PM" src="https://user-images.githubusercontent.com/1044413/60856721-21950b80-a1d6-11e9-9845-5e83e85eef34.png">
