### ISSUE TITLE
Test on latest browsers and Safari

### ISSUE THREAD

**Issue by ylemkimon** [KaTeX/KaTeX#1859]
#1842 has shown that KaTeX may break on new browsers. We should consider testing on latest browsers.

**Comment by edemaine** [comment]
Agreed. The last time I tried upgrading Selenium, all/most of the screenshot tests changed.  Probably in small ways, and probably still worth doing, but it's going to be an annoyance.

**Comment by kevinbarabash** [comment]
I wonder if we might be able to leverage browserstack to help with this.

**Comment by ylemkimon** [comment]
@kevinbarabash Unfortunately, we cannot use Browserstack to test PRs, as it require a private API key.

**Comment by kevinbarabash** [comment]
BrowserStack has a free program for open source projects, https://www.browserstack.com/open-source.  According to https://www.browserstack.com/automate/continuous-integration they support CircleCI.  One of their requirements is that we display their logo on our github page or website and link to BrowserStack.com.

**Comment by ylemkimon** [comment]
Edge is now based on Chromium, so one less browser to test :smile:
