### ISSUE TITLE
howto debug broken redering (css leaks?)

### ISSUE THREAD

**Issue by haraldschilly** [KaTeX/KaTeX#1860]
This is an issue, but probably also a question. I'm developing cocalc.com and when attempting to update 0.10 or 0.10.1, some renderings are broken. It is broken in the newest Chrome and Firefox browsers, hence I think it must be something with the page's css styling itself.

The only problem is, I haven't figured out what it is. I have checked the styles for all those nested katex elements, and I haven't found anything. Is there a general way how to work this out, or some ideas how to debug that?

Below is a screenshot how it looks. The first problem was that the c isn't inside of the circle for the new copyright sign, and the second issue is that the horizontal fraction bar for `\frac` doesn't show up. The integral looks fine, although again, the fraction bar is lost. 

![screenshot from 2019-02-22 15-45-32](https://user-images.githubusercontent.com/207405/53249647-e972ad80-36b8-11e9-8300-f234a6466399.png)

and well, it's also a bugreport, because I would expect that katex is robust against anything that's going on here

**Comment by ylemkimon** [comment]
![image](https://user-images.githubusercontent.com/888148/53259847-7ea29000-3713-11e9-8be5-631956800b87.png)

On the right side of the developer console, you can see applied styles and their sources for the selected element. Could you check them?

**Comment by edemaine** [comment]
We could try to help debug if you could send a (link to) a complete working/broken example.

**Comment by haraldschilly** [comment]
well, I'm a webdev myself. I checked this, and also several ones of the styles nested above. Maybe I should ask the other way around: can you tell me how the horizontal bar in such a `\frac` is rendered? Is it a border of a div? I'm not familiar with your source code, so that might take a while to figure out. With that knowledge, I am more confident to actually find the relevant element.

**Comment by ylemkimon** [comment]
@haraldschilly Currently, fraction bars are rendered using a `span` with `border-bottom` and `min-height`. We went through several trials and errors regarding the horizontal bar (see previous issues), so if old KaTeX resides, it may render incorrectly:

![image](https://user-images.githubusercontent.com/888148/53300260-24770b80-3888-11e9-84e5-7411718cc449.png)

 But judging by the font of `x` and `y` from your screenshot, unless intended, it seems KaTeX styles have not been loaded correctly.

**Comment by ylemkimon** [comment]
Note that there is a full-working demo on [our website](https://katex.org/), so you can try and compare the correct rendering.

**Comment by haraldschilly** [comment]
Sorry for taking your time, this was all my mistake. There was a configuration mishap and well, if anyone else has this issue, there is a CSS file for an older version of KaTeX :dizzy_face:

However, thank's for pointing out how the fraction line is done.
