### ISSUE TITLE
CLI output for example equation doesn't render

### ISSUE THREAD

**Issue by JoeUX** [KaTeX/KaTeX#1864]
In the 0.10.1 CLI, I ran `npx katex -i C:/Tools/Katex-1.txt -o C:/Tools/Katex-out.html`

Where Katex-1.txt contains the example equation from the docs: `c = \\pm\\sqrt{a^2 + b^2}`

I've tried rendering the resulting HTML in browsers directly, and on CodePen, but it's broken in all cases. The CodePen, with the full HTML syntax that KaTeX created [is here](https://codepen.io/joeduarte/pen/JxgeXj).

Pasting the contents of katex.css into CodePen's CSS box slightly improved the situation, but as you can see below, the equation is still broken across three lines, and it's displaying the letters pm instead of the plus-minus sign.

![katex error](https://user-images.githubusercontent.com/8071692/53294991-3c765e80-37a6-11e9-8d1c-bc998386b90c.PNG)

Browsers are Edge 18, Firefox 65, and Chrome 72, all on Windows 10. The rendering is the same in all three browsers.

How does the CLI output normally work? Does it require katex.css? The font code seems to use relative paths. Is this a font problem? How would we normally configure the fonts?

**Comment by ylemkimon** [comment]
There is no need to escape backslash in the CLI (unless needed by the shell you're using): `c = \pm\sqrt{a^2 + b^2}`.

**Comment by JoeUX** [comment]
Thanks! That fixed it. I didn't catch the escaping. Thanks again.
