### ISSUE TITLE
markdown-it: some sort of clash between katex and webpack-dev-server

### ISSUE THREAD

**Issue by songololo** [KaTeX/KaTeX#1865]
I'm using [Vuepress](https://vuepress.vuejs.org/) (a static site generator) to parse markdown to `html`. 

It uses `markdown-it` for markdown parsing. When I try to use plugins for katex, some sort of issue arises which causes the `webpack-dev-server` to launch incredibly slowly, as in around 30+ minutes.

Here is a minimal example repo [`markdown-katex-debug`](https://github.com/songololo/markdown-katex-debug).

The same issue doesn't happen with production builds (also via webpack).

I've tried various katex flavoured plugins, and they all seem to cause the same behaviour:
[`markdown-it-texmath`](https://github.com/goessner/markdown-it-texmath)
[`@iktakahiro/markdown-it-katex`](https://github.com/iktakahiro/markdown-it-katex)
[`@neilsustc/markdown-it-katex`](https://github.com/yzhang-gh/markdown-it-katex)
[`@mathssyfy/markdown-it-katex`](https://github.com/DavidCouronne/mathssyfy/tree/master/packages/markdown-it-katex)

(Note, the original `markdown-it-katex` is no longer maintained, hence the proliferation of forks...)

Any ideas on what the source of the issues might be and how, in general, `markdown-it` implementations might proceed so as not to clash with `webpack-dev-server` / `vuepress`?

**Comment by ylemkimon** [comment]
Could you upload your webpack configuration?

**Comment by songololo** [comment]
The `webpack` configuration is set by `vuepress`, which I believe is defined in [this folder](https://github.com/vuejs/vuepress/tree/master/packages/%40vuepress/core/lib/webpack) of their repo.

**Comment by songololo** [comment]
This is the [`dev.js`](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/core/lib/dev.js) script invoked when running `vuepress dev`

**Comment by kevinbarabash** [comment]
I don't know enough about `markdown-it` to say what the issue is.  In terms of the length of time things are taking, if these plugins are inserting the HTML as `markdown-it` enters a node then it may result in `markdown-it` also parsing the HTML that these plugins are inserting.

**Comment by kevinbarabash** [comment]
@songololo how long does a build take with webpack (as opposed to webpack-dev-server)?

**Comment by songololo** [comment]
@kevinbarabash it was quite slow, I seem to recall in the region of 30m.

**Comment by kevinbarabash** [comment]
Wow, that's really slow. 😞 It is mostly like an issue with the plugin itself and not with katex itself as katex is pretty fast at rendering things.  I suggest opening tickets against the plugin repos, they should be able to better determine what the issue is. 🤞
