### ISSUE TITLE
Mhchem not loaded on katex.org

### ISSUE THREAD

**Issue by danielhollas** [KaTeX/KaTeX#1866]
Hi!

I tried to enable mhchem extension that shipped in the new 0.10.1 version on my site. It seems to work although some rendering seems a bit odd (will make another issue for that) so I wanted compare with katex.org test page. It seems that mhchem is not loaded there. I realize that might be by design since mhchem is an extension, but maybe in this case it is worth it to add?

**Comment by ylemkimon** [comment]
For now, you can load the extension by running `javascript:var a=document.createElement('script');a.src='https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/contrib/mhchem.min.js';document.body.appendChild(a)` in the developer console or the address bar.

**Comment by edemaine** [comment]
Nice workaround @ylemkimon.

I think including the mhchem extension in the online demo is a good idea -- show off all our features -- and should be easy to do (just another `<script>` tag, as above).  In that spirit, we could also consider including the `copy-tex` extension -- though that's more useful when there's a mix of inline math and formulas.

**Comment by kevinbarabash** [comment]
It seems like there shouldn't be too much work to add it the demo page.

**Comment by mothas** [comment]
@kevinbarabash I was looking for a 'good first issue'. If I have understood this issue right, the changes required for this fix isn't on the repo, but on the website [katex.org](https://katex.org/), right?

**Comment by edemaine** [comment]
@mothas The website is on (or published from) the repo, in the `website` directory (built via Docusaurus -- run `yarn` and `yarn start` in that directory to run a test server, after `yarn build`ing in the root directory).

**Comment by mothas** [comment]
I have made a PR #1932 for this issue. Let me know if it looks good. 

This is my first time contributing to a project. So apologies in advance in case I missed anything.

**Comment by danielhollas** [comment]
Hmm, to do this properly, don't you also need to update the release script to support versioning?

**Comment by edemaine** [comment]
@danielhollas I *think* our `update-sri.js` script already handles this, but I've asked for confirmation. Discussion about this should take place on the PR itself, #1932.
