### ISSUE TITLE
\clap has visible width in Safari

### ISSUE THREAD

**Issue by KazimirPodolski** [KaTeX/KaTeX#1867]
In Safari:

![](https://gitlab.softaria.com/web-editor/web-editor/uploads/c07800e0605c3cabc607f653b0ef2063/image.png)
Should be like this (as it is in Chrome):

![](https://gitlab.softaria.com/web-editor/web-editor/uploads/69e34fa35410712fea0a9d3105168c84/image.png)

**Comment by ronkok** [comment]
I grow weary of Safari weirdness. 

Sometime in the next week, I'll take a look and see if something can be done. No guarantee that I'll succeed.

**Comment by ronkok** [comment]
@spontaliku-softaria This is just a note to say I have not forgotten this issue. I work on a Windows box, so my access to Safari is limited. Next week some new iPads will be available. I'll buy one and see if I can do something here.

**Comment by ronkok** [comment]
@spontaliku-softaria I'm sorry. I tried many ways to squash this and every one failed. Safari is picking up an extraneous width on a span deep within KaTeX's main function for vertical alignment. There is a [standing issue](https://github.com/KaTeX/KaTeX/issues/1409) to rewrite that function using CSS flex. It's possible that such a change would fix this issue. Until then, I can think of no way to resolve this.

**Comment by ronkok** [comment]
Back one last time to say that I've found a fix. This should work properly in the next release.
