### ISSUE TITLE
Positioning of subscript/indexes (in fractions)?

### ISSUE THREAD

**Issue by BairDev** [KaTeX/KaTeX#1872]
This is probably rather a support question. We are using v0.10.1 and have serious problems with the positioning of some elements in formulas, especially regarding height.

The details can be found in this [SO question](https://stackoverflow.com/questions/55162556/fix-wrong-position-of-fractions-and-subscript-in-katex-js).

I've tried the same tex code in the [try box of katex](https://katex.org/#demo) and it works perfectly.

I've also tried to use `katex.render()` with a completely naked div, but the result is the same. I'm using the katex.css file and do not overwrite the properties for `.katex` and the descendant elements.

I'd be grateful for any hint, what I could miss here.

**Comment by edemaine** [comment]
For one, it looks like the fonts aren't loading on your site. Did you check the JavaScript console for failure-to-load messages? Also, which browser?

Also, you should really post a full example of your input file, and otherwise describe your environment (pure HTML or something else?).

**Comment by BairDev** [comment]
@edemaine Thanks for the fast response. Indeed the _KaTeX_Main-Regular.woff[2]_ file is not loaded. I'm currently trying to add it, which is a little bit complicated due to our development/build process.

**Comment by BairDev** [comment]
OK, the reason for this problem was, that we used the Katex CSS only party. When I use the original CSS only it works fine.
