### ISSUE TITLE
Show Katex: I made a quick <katex-element> for Katex this morning

### ISSUE THREAD

**Issue by georges-gomes** [KaTeX/KaTeX#1904]
Hi, I thought it would be easier to use for non-programmers inside HTML pages.

`<katex-element>\sqrt{x}</katex-element>`

https://github.com/georges-gomes/katex-element

- Only for recent browsers.
- Not working 100% but happy to work it out

Cheers

**Comment by kevinbarabash** [comment]
Nice!  It's probably best to keep this as an external library.  If you want, please add a link to your project in https://github.com/KaTeX/KaTeX/blob/master/docs/libs.md.

**Comment by georges-gomes** [comment]
Pull request done 👍 I guess you can just close this issue :D
Have a nice day all!

**Comment by kevinbarabash** [comment]
@georges-gomes thanks for the pull request and for making this custom element.
