### ISSUE TITLE
CLA bot is not working

### ISSUE THREAD

**Issue by ylemkimon** [KaTeX/KaTeX#1913]
After we moved to KaTeX repo, it seems the CLA bot (@khanbot) is no longer working.

Is the repo still bounded by the CLA?

CC @kevinbarabash

**Comment by kevinbarabash** [comment]
Hmm... it may not be.  I can look into it next week.

**Comment by kevinbarabash** [comment]
I found the repo and the instructions for this.  I'll try adding `KaTeX/KaTeX` tomorrow. 🙂

**Comment by kevinbarabash** [comment]
I started working on this.  The bot uses a heroku git remote.  I'm trying to get the info for that remote so that I can update it.

**Comment by kevinbarabash** [comment]
I have all the info I need to do this now.  I'm going to create a new heroku app for CLAbot/khanbot and will add this repo, the font repo, and some other Khan repos this Friday.🤞

**Comment by ylemkimon** [comment]
@kevinbarabash The bot still doesn't seem to be working.

**Comment by edemaine** [comment]
Is there a manual way to trigger the bot?  #2127 needs this.

**Comment by ylemkimon** [comment]
Actually there have been multiple PRs merged without the CLA.

**Comment by kevinbarabash** [comment]
I scheduled some time Friday morning to work on this.  Sorry for the delay.

**Comment by kevinbarabash** [comment]
`clabot` is working now.  Sorry for dragging my feet on this.

**Comment by edemaine** [comment]
Should we do retroactive clabot actions on past merged PRs that were missing CLA (that @ylemkimon mentioned)?

**Comment by ylemkimon** [comment]
It seems `[clabot:check]` works for previous PRs. There are 16 contributions without the CLA signed: https://github.com/KaTeX/KaTeX/graphs/contributors?from=2019-01-13&to=2019-10-12&type=c.

**Comment by ylemkimon** [comment]
However, the CLA states:
> You accept and agree to the following terms and conditions for Your **present and future** Contributions submitted to Khan Academy.

so IANAL, but it may not be effective for past contributions.

**Comment by edemaine** [comment]
IANAL either, but if we ask them in the thread about a specific PR, I think it might be clear that "present" includes the present PR...?  We could also include a clarifying message next to `[clabot:check]` .  @kevinbarabash?

**Comment by kevinbarabash** [comment]
It should be fine if we do `[clabot:check]`s on the PRs from those 16 contributors and say that our clabot was offline for a bit but it's working now.  Some of those contributors may already have signed.  I can double check the spreadsheet.  @mpolyak doesn't have to sign because he's a KA employee.

**Comment by ylemkimon** [comment]
- [ ] #1820
- [ ] #1823
- [ ] #1833
- [ ] #1870
- [ ] #1905
- [ ] #1943
- [ ] #1953
- [ ] #1956
- [ ] #1962
- [ ] #1997
- [ ] #2049
- [ ] #2069
