### ISSUE TITLE
Can a macro return html?

### ISSUE THREAD

**Issue by abagshaw** [KaTeX/KaTeX#1916]
Is it possible to define a macro that directly returns html?

```javascript
defineMacro('\\abc', '<div class="abc"></div>');
```

**Comment by ronkok** [comment]
@abagshaw Not yet. There is a [pending PR](https://github.com/KaTeX/KaTeX/pull/1437) that will add `\class` but it is not yet merged into KaTeX master. On it and some other items, we're working out the security implications before merging.

**Comment by kevinbarabash** [comment]
The problem with defining a macro to return HTML is that the macro system works with TeX tokens not HTML.  Once the `\html` command proposed in #1596 is implemented you'll be able to define macros like:
```js
defineMacro('\\abc', '\\html{<div class="abc"></div>');
```
I'm going to close this as a duplicate.
