### ISSUE TITLE
Does katex support the \quantity like Mathjax ?

### ISSUE THREAD

**Issue by ykx456654** [KaTeX/KaTeX#1917]
tex:  \quantity{2.5}{m/s}

mathjax: 
<img width="150" alt="WX20190331-180343@2x" src="https://user-images.githubusercontent.com/13938795/55287742-7b1fba00-53df-11e9-9ff0-5b6c55c8f943.png">

**Comment by ronkok** [comment]
KaTeX does not support `\quantity`. For that matter, the MathJax [demo](https://www.mathjax.org/#demo) does not support it either. Perhaps it is part of some extension.

An alternate is `\pu`, but only where the `mhchem` extension is present.

Is there a LaTeX package that supports `\quantity`?

**Comment by ykx456654** [comment]
Yes,there is a Mathjax extension for [siunitx](https://ctan.org/pkg/siunitx).

**Comment by edemaine** [comment]
siunitx looks like a neat package. Somewhat large, so might take some time to implement.

However, siunitx doesn't seem to implement `\quantity`. Do you know what package that comes from? Or perhaps you mean `\SI`?

**Comment by kevinbarabash** [comment]
#817 is related.

**Comment by kevinbarabash** [comment]
It feels like this could maybe be accomplished with macros, but would require some parsing of the text in the second argument similar to what the mhchem extension does.
