### ISSUE TITLE
Cannot install via JSPM due to faulty permissions in NPM tarball

### ISSUE THREAD

**Issue by jonaslm** [KaTeX/KaTeX#1920]
**Describe the bug:**
The package cannot normally be installed via jspm (through the npm release) because the directory in the NPM tarball seems to have insufficient permissions (and jspm isn't clever enough to override them).

The jspm error that gets thrown:
```
warn Error on download for npm:katex
     Error: EACCES: permission denied, open '/home/redacted/.jspm/packages/npm/katex@0.10.1/CHANGELOG.md'
```

The folder that gets created at `/home/redacted/.jspm/packages/npm/katex@0.10.1`:
```
drw-rw-rw-  2 redacted redacted 4.0K Feb 22 05:29 'katex@0.10.1'/
```

As you can see, the folder lacks execute permissions.

A related bug report from jspm-cli: https://github.com/jspm/jspm-cli/issues/2414

To be clear, the symptom could be remedied by jspm-cli overriding the permissions in the NPM release. But the underlying problem could be fixed by setting the correct permissions in the NPM release.

**To Reproduce:**
1. Set up a jspm project
2. Run `jspm install npm:katex`
3. Error occurs during installation

**Expected behavior:**
The package should install without errors.

**Environment (please complete the following information):**
 - KaTeX Version: 0.10.1
 - Device: Desktop
 - OS: Ubuntu 18.04
 - Browser: N/A
 - Version: N/A

**Additional context:**
The problem can be worked around by installing the package with `sudo` and then retroactively fixing the owners and permissions of the installed files manually.

**Comment by edemaine** [comment]
I confirmed that https://registry.npmjs.org/katex/-/katex-0.10.1.tgz explicitly lists directories, but without execute bits:
```
drw-rw-rw- 0/0               0 2019-02-21 23:29 package
drw-rw-rw- 0/0               0 2019-02-21 03:21 package/contrib
drw-rw-rw- 0/0               0 2019-02-21 23:29 package/dist
drw-rw-rw- 0/0               0 2019-02-21 03:21 package/src
drw-rw-rw- 0/0               0 2019-02-21 03:21 package/contrib/auto-render
drw-rw-rw- 0/0               0 2019-02-21 03:21 package/contrib/copy-tex
drw-rw-rw- 0/0               0 2019-02-21 03:21 package/contrib/mathtex-script-type
drw-rw-rw- 0/0               0 2019-02-21 03:21 package/contrib/mhchem
drw-rw-rw- 0/0               0 2019-02-21 23:29 package/dist/contrib
drw-rw-rw- 0/0               0 2019-02-21 23:29 package/dist/fonts
drw-rw-rw- 0/0               0 2019-02-20 10:34 package/src/environments
drw-rw-rw- 0/0               0 2019-02-21 03:21 package/src/functions
drw-rw-rw- 0/0               0 2019-02-21 03:21 package/contrib/auto-render/test
```
As a result, `tar zxf` indeed fails with a permission error (on Linux). By contrast, earlier tarballs don't seem to explicitly list directories, so it works fine.

@ylemkimon from which architecture did you release 0.10.1? Could this be from a change in the release script? In any case, I think we should modify the release script to do the equivalent of `chmod -R a+X` (make all directories executable by everyone) and maybe for safety `chmod a+r` (make everything world readable).

**Comment by ylemkimon** [comment]
I'm releasing from Windows, which strangely reports 666 for all files and directories. Unfortunately, packing is done by Yarn, which I don't have control of. I'll manually create a tar and use it in future releases.

**Comment by kevinbarabash** [comment]
@edemaine is the execute bit on directories necessary to create new files within them?

**Comment by edemaine** [comment]
@kevinbarabash The execute bit is necessary to list files in the directory, which is required for doing much of anything with the directory. (Though I think it's technically possible to write to a directory without execute bit, I don't think you can easily put files in a subdirectory.)
