### ISSUE TITLE
Math in line with the text using $ .. $ instead of \ (.. \)

### ISSUE THREAD

**Issue by MathSalomon** [KaTeX/KaTeX#1926]
Hi.

I have a website in html5 where I put the rendering code of KaTeX v0.10.1 between the `<head> .. </ head>` tags

`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.css" 
    integrity="sha384-dbVIfZGuN1Yq7/1Ocstc1lUEm+AT+/rCkibIcC/OmWo5f0EA48Vf8CytHzGrSwbQ" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.js" 
    integrity="sha384-2BKqo+exmr9su6dir+qCw08N2ZKRucY4PrGQPPWU1A7FtlCGjmEGFqXCv5nyM5Ij" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/contrib/auto-render.min.js" 
    integrity="sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>`

And it displays the mathematical symbols delimited with `$$ .. $$` and with `\ [ .. \]`, but it does not work when I want to put mathematics in line with the text, that is, mathematical symbols inside a paragraph with simple dollar `$ .. $`, instead only works `\( .. \)`

I've already tried putting the following in the  `<body>..>/body>` :

```
<script>
    renderMathInElement(document.body,{delimiters: [
    					{left: "$", right: "$", display: false},
					  {left: "$$", right: "$$", display: true}
]});

</script>
```

but nothing.

The website where I am doing this testing is:

https://matematicauniversitaria.com/matlai/
(notice the $y^2$ that appears there)

Any suggestions?

**How do I make the mathematical symbols appear in line with the text using $ ... $?**

Thanks in advance.

**Comment by ronkok** [comment]
@MathSalomon Try putting the `$$` search string before `$`, as in:
```
<script>
    renderMathInElement(document.body,{delimiters: [
      {left: "$$", right: "$$", display: true},
      {left: "$", right: "$", display: false}
    ]});
</script>
```

**Comment by MathSalomon** [comment]
> @MathSalomon Try putting the `$$` search string before `$`, as in:
> 
> ```
> <script>
>     renderMathInElement(document.body,{delimiters: [
>       {left: "$$", right: "$$", display: true},
>       {left: "$", right: "$", display: false}
>     ]});
> </script>
> ```
Thank you. I just did it like you said, putting
`<script>
    renderMathInElement(document.body,{delimiters: [
      {left: "$$", right: "$$", display: true},
      {left: "$", right: "$", display: false}
    ]});
</script>`
inside the labels `<body> .. </body>`
But it does not work, look how my page was:
https://matematicauniversitaria.com/matlai/
everything works except the simple dollar `$..$`

**Comment by ronkok** [comment]
I do not pretend to be an expert in security issues.  I don't really know the intended effect of declarations like `integrity="sha384-...`  or how `defer` might interact with that sort of thing. I do that if I strip that out and move the `renderMathInElement` script to the end of the `body`, then the page loads fine. To be specific, my `<head>` includes:
```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.css">
<script src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/contrib/auto-render.min.js" crossorigin="anonymous"></script>
```
and the `renderMathInElement` comes after the math.

**Comment by MathSalomon** [comment]
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.css">
> <script src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.js" crossorigin="anonymous"></script>
> <script src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/contrib/auto-render.min.js" crossorigin="anonymous"></script>

@ronkok Thank you. I see that it works.
I have put in `<head>..</head>`
`    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.css">
    <script src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/contrib/auto-render.min.js" crossorigin="anonymous"></script>`

and the `renderMathInElement` in the` head`, not in the `body`.

All right up there, but how do I renderise `\[.. \]`? because I see that it is now disabled.

By the way, the code that includes `integrity =" sha384 -... `had been copied from the starter template at https://github.com/KaTeX/KaTeX#starter-template
I hope someone tells me what advantages that code brings, which, I suppose, is the most current.

**Comment by ronkok** [comment]
To include `\[.. \]`, add it to the search strings, as in:
```
<script>
    renderMathInElement(document.body,{delimiters: [
      {left: "$$", right: "$$", display: true},
      {left: "$", right: "$", display: false},
      {left: "\[", right: "\]", display: true},
      {left: "\(", right: "\)", display: false}
    ]});
</script>
```

Regarding, `integrity =" sha384 -...`, that's not something I can comment on knowledgeably. Others should feel free to chime in.

**Comment by MathSalomon** [comment]
> To include `\[..\]`, add it to the search strings, as in:
> 
> ```
> <script>
>     renderMathInElement(document.body,{delimiters: [
>       {left: "$$", right: "$$", display: true},
>       {left: "$", right: "$", display: false},
>       {left: "\[", right: "\]", display: true},
>       {left: "\(", right: "\)", display: false}
>     ]});
> </script>
> ```
@ronkok I've put that code as you said, but I can not render the `\[ .. \]`. I already checked for any possible syntax errors but nothing.
Check, please
https://matematicauniversitaria.com/matlai/index5.html

**Comment by ronkok** [comment]
Ah yes, silly mistake. The `\` character needs an escape.
```
<script>
    renderMathInElement(document.body,{delimiters: [
      {left: "$$", right: "$$", display: true},
      {left: "$", right: "$", display: false},
      {left: "\\[", right: "\\]", display: true},
      {left: "\\(", right: "\\)", display: false}
    ]});
</script>
```

**Comment by MathSalomon** [comment]
@ronkok  Excellent, thank you very much 👍 💯
