### ISSUE TITLE
Add a way to use MathML rendering

### ISSUE THREAD

**Issue by ylemkimon** [KaTeX/KaTeX#1928]
Thanks to @ronkok, we now have a quite decent MathML output.

It'd be nice to have a way to easily switch to it.

**Comment by kevinbarabash** [comment]
We'll probably want to have separate screenshot tests for MathML rendering as well.  Right now we always render MathML but hidden.  I wonder if we should switch to rendering HTML by default and then allow people to choose HTML, MathML, or both and leave it up to people to hide MathML if they want to.

**Comment by kevinbarabash** [comment]
This can be closed now that #1966 has been merged.
