### ISSUE TITLE
Would it be helpful to provide a PR that ports KaTeX to TypeScript?  

### ISSUE THREAD

**Issue by steveluc** [KaTeX/KaTeX#1938]
> Before requesting a feature, please search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Link to or name of a (La)TeX package that provides the same feature:**
KaTeX's general goal is to render as LaTeX does.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by steveluc** [comment]
Hi.  I am interested in contributing to KaTeX but would find it easier to work with the project if it were in TypeScript.  If the team is already planning to use TypeScript, I can volunteer to do the port.

**Comment by edemaine** [comment]
@steveluc We currently use [Flow](https://flow.org/) for type checking. I'm not an expert on TypeScript but at a high level they look pretty similar. I'm not aware of any plans to move to TypeScript.

P.S. Including a template but not actually filling it out isn't very helpful...

**Comment by kevinbarabash** [comment]
@steveluc there's quite a bit of overlap between flow and typescript.  I'm curious what parts of using typescript would make KaTeX easier to work on.
