### ISSUE TITLE
how resize subscript and superscripts

### ISSUE THREAD

**Issue by MathSalomon** [KaTeX/KaTeX#1939]
Hi. I have the following doubt.
Is there any way to reduce the size of subscripts and superscripts?
On my minimized test page https://prob.matematicauniversitaria.com/ I have the code:

`<head><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.css" integrity="sha384-dbVIfZGuN1Yq7/1Ocstc1lUEm+AT+/rCkibIcC/OmWo5f0EA48Vf8CytHzGrSwbQ" crossorigin="anonymous">`
`<script defer src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.js" integrity="sha384-2BKqo+exmr9su6dir+qCw08N2ZKRucY4PrGQPPWU1A7FtlCGjmEGFqXCv5nyM5Ij" crossorigin="anonymous"></script>`
`<script defer src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/contrib/auto-render.min.js" integrity="sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script></head>`

In my style sheet I have put:
`.katex{ 
    font-size: 100%; 
      }`

Look at the page, the superscript is bigger than normal.

Any help please.

Thanks in advance.

**Comment by mbourne** [comment]
@MathSalomon Your own style sheet needs to come **after** the call to the katex.min.css. (Currently your style sheet is just being overwritten by later style directives).

Then you'll find all of the math is at 1em, and matches the surrounding text, thus making the subscripts and superscripts look an appropriate size, like this:

![image](https://user-images.githubusercontent.com/7541940/56259215-d7cfe400-6104-11e9-92d0-c76843d793a6.png)

**Comment by kevinbarabash** [comment]
It looks like things are working now.  @mbourne thanks for diagnosing the issue.
