### ISSUE TITLE
Where do I write my macros?

### ISSUE THREAD

**Issue by MathSalomon** [KaTeX/KaTeX#1940]
Hi. On my testing website http://prob.matematicauniversitaria.com I want to use the following macro

`\newcommand{\sen}{\operatorname{sen}}`

so that instead of presenting **sin x**, it shows **sen x** (sine in spanish)

How would you insert it in the CSS style file?

Thanks in advance.

**Comment by kevinbarabash** [comment]
`\newcommand{\sen}{\operatorname{sen}}\sen x` works fine on katex.org.  Please see the bottom of https://katex.org/docs/options.html on how to define macros in the options object passed to `katex.render()` for an alternative.
