### ISSUE TITLE
\not is not working in Safari

### ISSUE THREAD

**Issue by fredrik-johansson** [KaTeX/KaTeX#1941]
**Describe the bug:**
See the page http://fungrim.org/entry/9ee8bc.html which has been rendered server-side.

Someone reported to me that on Safari on Mac, the `\not\in` sign in  `s \not\in \mathbb{Z}_{\ge 1}` is displayed erroneously as an `\in` sign. See the attached screenshot below.

It looks correct for me on both Firefox and Chrome on Linux, so it might be a Safari+Mac bug; in that case, perhaps KaTeX could work around it in some way.

The same person also reported that the problem occurs with `\not=, \not\equiv`.

**(La)TeX code:**
``\left(s \in \mathbb{C}\right) \mathbin{\operatorname{and}} \left(s \not\in \mathbb{Z}_{\ge 1}\right)``

**Expected behavior:**
The `\not\in` sign should appear as a `\not\in` sign.

**Screenshots:**
![image](https://user-images.githubusercontent.com/368838/56285076-9ba57f00-6116-11e9-9757-b39f2558988a.png)

**Environment:**
 - KaTeX Version: 0.10.1
 - Device: MacBook
 - OS: macOS 10.14.4
 - Browser: Safari
 - Version: 12.1 (14607.1.40.1.4)

**Additional context:**
The server side rendering was done with node v10.14.2, KaTeX 0.10.1.

**Comment by fredrik-johansson** [comment]
Simpler example: this shows that `\notin` works, only `\not\in` is broken:

![image](https://user-images.githubusercontent.com/368838/56286044-fd66e880-6118-11e9-8260-0878a968dfe9.png)

**Comment by kevinbarabash** [comment]
It looks like `\not` is not working in Safari at all.

**Comment by edemaine** [comment]
If I recall correctly, @ylemkimon fixed this issue in master but we haven't released it yet.

**Comment by alexjbest** [comment]
@edemaine it seems like a lot of people are having this issue (I guess #1937 is also this, and https://github.com/LMFDB/lmfdb/issues/2953, https://github.com/benweet/stackedit/issues/1460) do you have a timeline for the next release seeing as this is a pretty bad bug mathematically?

**Comment by kevinbarabash** [comment]
I just looked at https://github.com/KaTeX/KaTeX/compare/v0.10.1...master and @edemaine is correct.  It's fixed but not released yet.  I can do a 0.10.2 release this evening to get the fix out.

**Comment by edemaine** [comment]
@kevinbarabash Keep in mind that we need to rollback `\includegraphics` in releases for now...

**Comment by damienpereira** [comment]
@kevinbarabash do you know when the 0.10.2 will be released?

**Comment by kevinbarabash** [comment]
@damienpereira sometime in the coming week. 🤞

**Comment by JMSS-Unknown** [comment]
0.10.2 was released 13 days ago, should this be closed?

**Comment by kevinbarabash** [comment]
Thanks for the reminder.
