### ISSUE TITLE
Can not render some specified expression

### ISSUE THREAD

**Issue by Harrypotterrrr** [KaTeX/KaTeX#1942]
> Before reporting a bug
- [X] Check [common issues](https://katex.org/docs/issues.html).
- [X] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [X] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**

**Some** expression showed as below can not be rendered in correct way, I guess there is something wrong with katex interpreting the LaTeX code.

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
$$ L =  \underbrace{ \frac{1}{N} \sum_i L_i }_\text{data loss} +   \underbrace{ \lambda R(W) }_\text{regularization loss} $$
```
and this,
```latex
$$
L = \frac{1}{N} \sum_i \sum_{j\neq y_i} \left[ \max(0, f(x_i; W)_j - f(x_i; W)_{y_i} + \Delta) \right]  + \lambda \sum_k\sum_l W_{k,l}^2
$$
```

**Expected behavior:**

Above code segments failed to show in right way, but most of `latex` code can be rendered successfully in browser. Please refer to `Screenshots`. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/28552583/56290299-6f5d2300-6155-11e9-90d1-bb42e4799170.png)

however, it render this formula successfully in [katex demo site](https://katex.org/#demo)

![image](https://user-images.githubusercontent.com/28552583/56290784-78022900-6156-11e9-9568-48eba3b53152.png)

**Environment (please complete the following information):**
 - KaTeX Version:  I use `Starter template` to import KaTeX. The script is showed in `Additional context`
 - Device: PC Chrome
 - OS: Windows 10
 - Browser: Chrome & Edge 
 - Version: The latest I promise

**Additional context:**
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.css" integrity="sha384-dbVIfZGuN1Yq7/1Ocstc1lUEm+AT+/rCkibIcC/OmWo5f0EA48Vf8CytHzGrSwbQ" crossorigin="anonymous">

<!-- The loading of KaTeX is deferred to speed up page rendering -->
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.js" integrity="sha384-2BKqo+exmr9su6dir+qCw08N2ZKRucY4PrGQPPWU1A7FtlCGjmEGFqXCv5nyM5Ij" crossorigin="anonymous"></script>

<!-- To automatically render math in text elements, include the auto-render extension: -->
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/contrib/auto-render.min.js" integrity="sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI" crossorigin="anonymous"  onload="renderMathInElement(document.body);"></script>
```

**Comment by edemaine** [comment]
Can you check whether there are any console error messages? Could you post a complete HTML file e.g. on gist?

**Comment by Harrypotterrrr** [comment]
> Can you check whether there are any console error messages? Could you post a complete HTML file e.g. on gist?

Oh! i am really sorry for my mistake! I have checked my html over and over again, but overlook one severe problem that`<em>` has been inserted into latex code for I used vscode `markdown-pdf` extension to convert markdown format into html/pdf before.
Please change the label of this issue and delete it if it can.
Sorry for my mistake again 😭, and sincerely appreciate your help!

**Comment by edemaine** [comment]
Glad you found the error!  No problem.
