### ISSUE TITLE
Problem with a readme badge

### ISSUE THREAD

**Issue by enterpreneur369** [KaTeX/KaTeX#1963]
> Before requesting a feature, please search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Is your feature request related to a problem? Please describe.**
Hi, you have a problem with you readme file. In the begining "Greenkeeper badge"

**Describe the solution you'd like:**
Show the badge correctly

**Link to or name of a (La)TeX package that provides the same feature:**
no apply

**Describe alternatives you've considered:**
no apply

**Additional context:**
In the readme file

**Comment by danielhollas** [comment]
This is likely because Greenkeeper is currently not enablet (#1858)

**Comment by enterpreneur369** [comment]
Ok, thank you @danielhollas

**Comment by kevinbarabash** [comment]
@danielhollas thank you for the reminder.  I need to take care of that.
