### ISSUE TITLE
\substack command not working

### ISSUE THREAD

**Issue by mightymicha** [KaTeX/KaTeX#1967]
> Before reporting a bug
- [X] Check [common issues](https://katex.org/docs/issues.html).
- [X] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [X] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
Hi, katex does not seem to recognize the substack command described [here](https://tex.stackexchange.com/questions/153490/atop-vs-substack-for-multiple-lines-under-a-sum).

**To Reproduce:**
1. Go to [katex.org](https://katex.org/)
2. Type `T_{\substack{Up \\ Down}}`
3. Error message: 
> KaTeX parse error: Undefined control sequence: \substack at position 4: T_{\̲s̲u̲b̲s̲t̲a̲c̲k̲{Up \\ Down}}
4. Workaround (see first link): `T_{Up \atop Down}`

**Expected behavior:**
`Up` should be rendered upon `Down`
**Screenshots:**
See step 4

**Environment (please complete the following information):**
- Version on [katex.org](https://katex.org/)

**Comment by alexjbest** [comment]
Substack is not supported, as per https://github.com/KaTeX/KaTeX/blob/5806b240b342b964bcde3441d3ae7bfa7222c3b4/docs/support_table.md . So this isn't so much a bug as a feature/enhancement request.

**Comment by edemaine** [comment]
Agreed.  (Though https://katex.org/docs/support_table.html is the correct link for the documentation.)

I think `\substack` would be doable, in particular by redefining the `\\` macro inside the argument.  I'd have to look at its definition to be sure.

**Comment by ylemkimon** [comment]
Closed via #1969.
