### ISSUE TITLE
KaTeX auto-render appears to be incompatible with strict Content-Security-Policy settings

### ISSUE THREAD

**Issue by VorpalBlade** [KaTeX/KaTeX#1968]
KaTeX auto-render appears to be incompatible with strict Content-Security-Policy settings.

Because of the onload handler for `auto-render.min.js`, `'unsafe-inline'` is required in the Content-Security-Policy header sent by the server (instead of just 'self' for self-hosted KaTeX and, if using a CDN, said CDN).

**To Reproduce:**
1. Set up a server with a strict Content-Security-Policy that allows loading the javascript files for KaTeX but not unsafe-inline.
2. Use auto-render plugin.
3. Observe it not working & error in browser console.

**Expected behavior:**
One of the following:
* Unsafe-inline should not be needed.
* It should be documented that unsafe-inline is required for auto-render.

I tried to get it working using the described [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_inline_script), but that doesn't seem to work for onload, or I did something wrong. That could be another option to document (if it is possible to get it to work). Though [this stackoverflow post](https://stackoverflow.com/questions/11668469/refused-to-execute-inline-event-handler-because-of-content-security-policy#14937822) seems to suggest that won't work? (I'm not a JS guru.)

**Environment (please complete the following information):**
 - KaTeX Version: 0.10.1
 - Device: Desktop
 - OS: Ubuntu 18.04
 - Browser: Chromium and Firefox both tested
 - Version: Chromium 73.0.3683.86 & Firefox 66.0.3

**Comment by kevinbarabash** [comment]
This is a server configuration issue.  Since the server is configured without `unsafe-inline` it shouldn't allow any javascript files loaded from a CDN to run.  I had a look at the MDN page you linked to and `nonce` seems like it might do the trick but I've never used it before.

**Comment by Jieiku** [comment]
I actually had a heck of a time getting this setup in a way that did not cause a security violation with strict CSP.

For anyone that finds this issue, I have resolved it.

First things first, the example documentation: https://katex.org/docs/browser.html

Look at the "Starter template" it uses `onload=`, that is the first thing you must Avoid, do NOT use `onload=` anywhere.

What I did instead was set a class for the script element `class=".prestyle"`

I then use a js file to process these, thereby making that onload event no longer inlined.

here is my prestyle.js file:

```javascript
!function(){
    const items = document.querySelectorAll('.preStyle');
    items.forEach(item => {
      item.rel = 'stylesheet';
    });
}();
```

Then for the autorender example: https://katex.org/docs/autorender.html

You will see that they are not loading those options through a script, this is infact unsafe-inline script, Even if you place it in the head. what you should do instead is place this into a file: https://github.com/Jieiku/abridge/blob/master/static/katexoptions.js

So long as you dont actually use any unsafe-inline then KaTeX will work with a strict CSP in place, unfortunately those without a lot of knowledge HTML, javascript, and CSP will use the examples from the katex.org documentation and wonder why KaTeX is violating their CSP policy.

For a full working example look here: https://abridge.netlify.app/overview-math/

The repository: https://github.com/Jieiku/abridge

Also you can see that this site gets a perfect observatory score:  https://observatory.mozilla.org/analyze/abridge.netlify.app

**Comment by Jieiku** [comment]
I am thinking maybe you did not click on [the link](https://abridge.netlify.app/overview-math/) to the site that shows me having it working? You could right click on the page and view source and see that I am already doing that:

```html
<script defer src="https://abridge.netlify.app/katex.min.js?h=227b0d7444756f6c547b03fea4a0942699218aac0782a88f5c394893b1b306ee" integrity="sha384-ljao5I1l+8KYFXG7LNEA7DyaFvuvSCmedUf6Y6JI7LJqiu8q5dEivP2nDdFH31V4"></script>
  <script defer src="https://abridge.netlify.app/mathtex-script-type.min.js?h=77e47ddc5b3af990445375441fbbbfab3f9bd368823ca10f98b2448117f6f8c5" integrity="sha384-jiBVvJ8NGGj5n7kJaiWwWp9AjC+Yh8rhZY3GtAX8yU28azcLgoRo4oukO87g7zDT"></script>
  <script defer src="https://abridge.netlify.app/auto-render.min.js?h=cb7f4ca60ed5dc3e258415f8c7a3b46d4a93578a52adf83011f18a7f190e7602" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR"></script>
  <script defer src="https://abridge.netlify.app/katexoptions.js?h=985b3e06694b8dcc88803ccd09b98d90d6300b1d9e2139c6ea3a2ffb20b128b3" integrity="sha384-0p9nuTTppSkKuNOiOLPLTG+Nu49i2qUHVtd5/vtGH3ntJyxh7cTZ2ZgDul8b0RiQ"></script>
```

however..... This is the line in question where I use `class="preStyle"` to change `rel="preload"` to `rel="stylesheet"` after the page has loaded.

```html
<link rel="preload" as="style" class="preStyle" href="https://abridge.netlify.app/katex.min.css" integrity="sha384-ZPe7yZ91iWxYumsBEOn7ieg8q/o+qh/hQpSaPow8T6BwALcXSCS6C6fSRPIAnTQs" crossorigin="anonymous" />
```

If you look at this line you will see that it shows rel="preload", this is good for downloading the file in a non render blocking manner (my site also has a perfect [lighthouse score](https://web.dev/measure/?url=https%3A%2F%2Fabridge.netlify.app))

Using the prestyle.js script that adds rel="stylesheet" alows you to use the downloaded css file after the page has loaded (non render blocking.)

You could technically simplify it by changing the line to this, but it wont be deferred (It will be a render blocking element):

```html
<link rel="stylesheet" href="https://abridge.netlify.app/katex.min.css" integrity="sha384-ZPe7yZ91iWxYumsBEOn7ieg8q/o+qh/hQpSaPow8T6BwALcXSCS6C6fSRPIAnTQs" />
```
