### ISSUE TITLE
Break in tall delimiters

### ISSUE THREAD

**Issue by OisinMoran** [KaTeX/KaTeX#1975]
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
Left and right floor brackets, when containing a large expression, appear to to break in the middle. This disappears on zooming but makes for suboptimal rendering.

**(La)TeX code:**
```latex
5 = \left\lfloor{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{(4!)!}}}}}}\right\rfloor
```

**Expected behavior:**
Expected vertical bar portion of left and right floor braces to be continuous.

**Screenshots:**
Taken from [the demo](https://katex.org).
![image](https://user-images.githubusercontent.com/8939851/57576342-3ca50280-7455-11e9-8b66-26c231afeb04.png)

**Environment (please complete the following information):**
 - KaTeX Version: 0.10.1
 - Device: Desktop
 - OS: Ubuntu 18.10
 - Browser: Chrome
 - Version: 74.0.3729.131 (Official Build) (64-bit)

**Comment by kevinbarabash** [comment]
We could probably use SVG to avoid this situation.  @OisinMoran are you seeing similar issues with tall parens and tall square brackets?

**Comment by OisinMoran** [comment]
Yes, with
```latex
5 \ne \left[{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{(4!)!}}}}}}\right]
```
I get:
![image](https://user-images.githubusercontent.com/8939851/57618311-f34ed300-757a-11e9-887d-826cff257438.png)

And with
```latex
5 \ne \left({\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{(4!)!}}}}}}\right)
```
I get:
![image](https://user-images.githubusercontent.com/8939851/57618362-11b4ce80-757b-11e9-864b-97b2c428e891.png)

**Comment by kevinbarabash** [comment]
Thanks for confirming my suspicions.

**Comment by ronkok** [comment]
I think this can be fixed without SVG.  We just need to adjust the vertical alignment calculation in `makeStackedDelim()`. That calculation should include a small overlap where glyphs meet. Otherwise floating point rounding error can result in the gap we see in @OisinMoran's screenshots. 

I'll take a look sometime in the next week.
