### ISSUE TITLE
MathML is not updating in Chrome

### ISSUE THREAD

**Issue by balakrishnan1978** [KaTeX/KaTeX#1985]
I have used **Linux OS** and **KaTeX Version 0.10.2**.

When i have updated HTML equation with **contenteditable="true"** option the **MathML** is updating in **Firefox** and not updating in **Chrome**. Please find attached the screenshot for your reference. 

See **\mathcal{XYZ}** is editable and updated in MathML-Firefox and not updated in MathML-Chrome.

How to solve this issue?

![Chrome_Mathml](https://user-images.githubusercontent.com/5443482/58330859-71518a80-7e55-11e9-9257-69bd8b581e17.png)
![Firefox_MathML](https://user-images.githubusercontent.com/5443482/58330702-1e77d300-7e55-11e9-96b5-6130d8e4a77f.png)

**Comment by edemaine** [comment]
KaTeX is a rendering engine, and does not control (or try to control) when rendering or rerendering happens. Likely this is a WeTeX issue, so you should raise the issue there.
