### ISSUE TITLE
will KaTeX support latex3

### ISSUE THREAD

**Issue by seuliang** [KaTeX/KaTeX#1988]
latex3 has better support for package programming, and it seems to be stable after mang years' development.
will katex support this?

latex3 website：  
[https://www.latex-project.org/latex3/](https://www.latex-project.org/latex3/)

**Comment by edemaine** [comment]
Was there a specific feature you're interested in?

We're in the early stages of supporting package programming features, but slowly making KaTeX a more friendly environment. Definitely LaTeX 3 features are reasonable to add to KaTeX.

**Comment by seuliang** [comment]
I think the html page could be printed to pdf with page devided correctly.  
I also  want to know whether Katex could build latex source code and layout template as beautiful as texlive does technically? 
three are some similar github projects:   
[LaTeX.js  ](https://github.com/michael-brade/LaTeX.js )  
[https://github.com/brucemiller/LaTeXML ](https://github.com/brucemiller/LaTeXML) support package programming

**Comment by edemaine** [comment]
@seuliang KaTeX is just a math rendering engine; it won't render full LaTeX documents. Plausibly, a project like LaTeXML could use KaTeX for math rendering, though I don't know whether that's practical.
