### ISSUE TITLE
First character of array doesn't get its own group

### ISSUE THREAD

**Issue by edemaine** [KaTeX/KaTeX#1989]
The following should render 111, but it currently renders as 22:
```latex
\def\x{1}\begin{matrix}\def\x{2}&\x\end{matrix}\x
```

As described in `test/katex-spec.js` (see TODO), before the environment gets called, `{matrix}` gets consumed which means that the `\def` gets executed, before we can create a group. :-(

This is a general issue with the way `nextToken` works, so it's going to be difficult to fix.

**Comment by kevinbarabash** [comment]
Interesting.  By `nextToken` were you referring to `expandNextToken`?

**Comment by edemaine** [comment]
I meant the internal `nextToken` variable that gets refreshed when we consume a token, and thus before we know what we're parsing next, which is one token too early.

**Comment by kevinbarabash** [comment]
There are probably a lot of places where we rely on the current behavior and we'd have to update those places.
