### ISSUE TITLE
a bug in src/Namespace.js 

### ISSUE THREAD

**Issue by seuliang** [KaTeX/KaTeX#1993]
view code at [top[name] = this.current[name];](https://github.com/KaTeX/KaTeX/blob/88d9a8a4df296a5d4f7acaf5454bdadb365e48d3/src/Namespace.js#L109)

I think it sgould be 
```
this.undefStack[this.undefStack.length - 1][name] = this.current[name];
```

**Comment by edemaine** [comment]
@seuliang I don't understand.  You seem to be suggesting replacing
```js
            const top = this.undefStack[this.undefStack.length - 1];
            if (top && !top.hasOwnProperty(name)) {
                top[name] = this.current[name];
            }
```
with
```js
            const top = this.undefStack[this.undefStack.length - 1];
            if (top && !top.hasOwnProperty(name)) {
                this.undefStack[this.undefStack.length - 1][name] = this.current[name];
            }
```
These seem identical to me, because `top` is set to `this.undefStack[this.undefStack.length - 1]`.

**Comment by seuliang** [comment]
sorry, you are right.
I'm new to javascript.
