### ISSUE TITLE
Integral limits with brackets don't work

### ISSUE THREAD

**Issue by jessebett** [KaTeX/KaTeX#1996]
I am trying to render an integral with limits that require subscripts so I'll need to wrap them with braces. However, KaTeX is breaking whenever there are braces present in the limits:

`$$ z(t_1) = z(t_0) + \int_a^b f(z(t),t,\theta) dt $$` works

`$$ z(t_1) = z(t_0) + \int_{a}^{b} f(z(t),t,\theta) dt $$` fails with no error.

In particular the only difference is the inclusion of braces in the limits (which will be needed for subscripts).

![image](https://user-images.githubusercontent.com/4240549/58986698-fc167b80-87ab-11e9-9367-2641be883aa2.png)

**Comment by danielhollas** [comment]
I tried to reproduce and it renders just fine on katex.org

![image](https://user-images.githubusercontent.com/9539441/58996769-ed56b580-87f9-11e9-96d3-3f2de3a350aa.png)

You may need to include the specifics of your KaTeX setup.

**Comment by jessebett** [comment]
@danielhollas sorry about that. I'm setting this up inside a remark slideshow. 

Here is how I load KaTeX:
```
<html>
  <head>
    <title>Title</title>
    <meta charset="utf-8" />
    <style>
      @import url("style.css");
    </style>
  </head>
  <body>
    <script src="https://gnab.github.io/remark/downloads/remark-latest.min.js"></script>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.css"
      integrity="sha384-yFRtMMDnQtDRO8rLpMIKrtPCD5jdktao2TV19YiZYWMDkUR5GQZR/NOVTdquEx1j"
      crossorigin="anonymous"
    />

    <!-- The loading of KaTeX is deferred to speed up page rendering -->
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.js"
      integrity="sha384-9Nhn55MVVN0/4OFx7EE5kpFBPsEMZxKTCnA+4fqDmg12eCTqGi6+BB2LjY8brQxJ"
      crossorigin="anonymous"
    ></script>

    <!-- To automatically render math in text elements, include the auto-render extension: -->
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/contrib/auto-render.min.js"
      integrity="sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI"
      crossorigin="anonymous"
      onload="renderMathInElement(document.body);"
    ></script>
    <script type="text/javascript">
      var options = { ratio: "16:9", sourceUrl: "slides.md" };
      var renderMath = function() {
        renderMathInElement(document.body, {
          delimiters: [
            // mind the order of delimiters(!?)
            { left: "$$", right: "$$", display: true },
            { left: "$", right: "$", display: false },
            { left: "\\[", right: "\\]", display: true },
            { left: "\\(", right: "\\)", display: false }
          ]
        });
      };
      var slideshow = remark.create(options, renderMath);
    </script>
  </body>
</html>
```

And then inside the `slides.md` the relevant section is just what you've written:

`$$ z(t_1) = z(t_0) + \int_{0}^{1} f(z(t),t,\theta) dt $$` 

Which breaks with the braces but renders correctly without.

**Comment by edemaine** [comment]
Presumably `remark` is what's causing the problem. (You can test by removing it, or seeing how remark renders without calling KaTeX.) Maybe you want to use a package like [Remark Math](https://github.com/Rokt33r/remark-math) instead of using `auto-render`.

**Comment by danielhollas** [comment]
wild guess: it's possible that the remark engine is interfering with KaTeX,
I've seen such problems with another MD engine. It would probably be
helpful if you could test it without it.

**Comment by jessebett** [comment]
@edemaine it looks like Remark Math requires serving with npm instead of just having everything rendered in browser, I'd definitely like to avoid this. I don't believe remark has a capacity to render without KaTeX.

I am following the remark wiki, with updated KaTeX, here: https://github.com/gnab/remark/wiki/LaTeX-Using-KaTeX.

@danielhollas do you mean test remark without KaTeX or the other way around. I believe you've already shown that KaTeX can do this correctly on the katex.org demo, I'm not sure how to see why it's breaking here as there is no error message.

**Comment by edemaine** [comment]
@jessebett Looking at your example, it's probably the `_` that's causing trouble, as that triggers italics in Markdown. If you prefix each `_` with a backslash (`\_`), your example should work.

I'm not an expert in Remark Math, but it does say that it can be done client-side (though the example they show uses webpack).  The general issue is interplay between Markdown syntax and LaTeX syntax, and without using a plugin for your Markdown parser, you will get this type of interference.

**Comment by jessebett** [comment]
@edemaine  it does appear that something to do with italics is happening. However, `\_` does not change anything...

![image](https://user-images.githubusercontent.com/4240549/59050644-d3988b00-8858-11e9-9fee-0810fc636129.png)

**Comment by jessebett** [comment]
Actually, @edemaine  you are correct. I missed one `\_` and doing so fixed it. Thanks! I will link this thread as an issue in remark.

**Comment by edemaine** [comment]
Great! Glad you got it working.
