### ISSUE TITLE
bad rendering @Edge and @chrome 

### ISSUE THREAD

**Issue by xedex1111** [KaTeX/KaTeX#1998]
Hi. I try katex for the first time and i see, that the rendering in Edge is really bad in the newer version more than that. In chrome is that approximatly the same. I updated from v.7.11 to v.10.2 because i need the underbrackets and look at that. it has new renderuing problems. Maybe i do something wrong. Please help me solve that fail. ubuntu16 for pi3/apache2/ Edge 42.17xxx/Chrome 74.x 

Here are the pics (first edge, 2nd chrome) to compare that view with underbrackets, katex v10.2
[
![edge](https://user-images.githubusercontent.com/51515279/59150573-02b02780-8a26-11e9-949e-d756b930e2d0.PNG)
](url)
![chrome](https://user-images.githubusercontent.com/51515279/59150656-ef518c00-8a26-11e9-8a26-9cdbb6ace933.PNG)

then the pics (1st edge, 2nd chrome) without the brackets, katex v10.2 
![edge2](https://user-images.githubusercontent.com/51515279/59150665-1ad47680-8a27-11e9-98e2-f20d7560e423.PNG)

and @last the pics (1st edge, 2nd chrome) with v.7.11 without brackets
![edge3](https://user-images.githubusercontent.com/51515279/59150680-5a9b5e00-8a27-11e9-80dc-fe6737b82c67.PNG)
![chrome3](https://user-images.githubusercontent.com/51515279/59150682-64bd5c80-8a27-11e9-8445-7fe35dab597a.PNG)

br, xed

**Comment by edemaine** [comment]
Can you post LaTeX source code, and ideally a full HTML example?  Does the same LaTeX work on the demo on https://katex.org?

**Comment by xedex1111** [comment]
ok i am surprised. it looks like that i have an bug in my 2400 rows code, because in an fresh miniversion it looks normal. see pic and code
![edge4](https://user-images.githubusercontent.com/51515279/59151614-44e16500-8a36-11e9-8008-f6ad3a910ade.PNG)

    <!DOCTYPE html>
    <html lang="de" xml:lang="de">
	<head>
    <title>Mathematik</title>
		<meta charset="UTF-8"/>
    
    <link rel="stylesheet" href="../../scripts/css/cv_main.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="../../scripts/css/1_main_dokumente.css"/>
		
		<script src="../../scripts/js/DL/cindyJS_v0.7.11/build/js/Cindy.js"></script>
		
		
		<link rel="stylesheet" href="scripts/katex.min.css">
		<link rel="stylesheet" href="scripts/katex.css">
		<script type='text/javascript' src='scripts/katex.min.js'></script>
		<script type='text/javascript' src='scripts/katex.js'></script>
		<script src="buch_mathematik.js"></script>			
	</head>
	<body>
		<script>
			document.write('<table id="myUL">');
			for (NR_i = 0; NR_i < Pruefungsstoff.length; NR_i++) {
				document.write(
					'<tr valign="top"><td style="width:100px;"><a id="' + Pruefungsstoff[NR_i].a_href + '" >' +
					Pruefungsstoff[NR_i].index.join("<br>") + 
					'</a></td><td style=" text-align:justify;"><a>' + 
					Pruefungsstoff[NR_i].inhalt +
					'</a></td></tr>' 
				);
			}
			document.write('</table>');									
		</script>
		
		<script> // Informatik - Analysis T1
			katex.render("\\int_{0}^{2\\pi} = x \\cdot cosx \\cdot dx", ue_informatik_2019_blatt_8_1_1);
			katex.render("\\int_{0}^{2\\pi} = x^2 \\cdot cosx \\cdot dx", ue_informatik_2019_blatt_8_1_2);
			katex.render("\\int_{0}^{2\\pi} = (sinx)^2 dx", ue_informatik_2019_blatt_8_1_3);
			katex.render("c) \\text{ } (sinx)^2+(cosx)^2=1", ue_informatik_2019_blatt_8_1_4);
			katex.render("\\int_{0}^{2\\pi} = x \\cdot cosx \\cdot dx = \\left\\{ \\begin{array}{ll} f = x & dg = cosx \\cdot dx \\\\ df = 1 & g = sinx \\end{array} \\right\\}", ue_informatik_2019_blatt_8_1_1_1);
			katex.render("= fg - \\int_{0}^{2\\pi}df \\cdot g = \\left( x \\cdot sinx \\right) |_{0}^{2\\pi} - \\int_{0}^{2\\pi} 1 \\cdot sinx \\cdot dx", ue_informatik_2019_blatt_8_1_1_2);
			katex.render("= 2\\pi \\cdot sin(2\\pi) - 2 \\cdot 0 \\cdot sin(0) - \\int_{0}^{2\\pi} 1 \\cdot sinx \\cdot dx = \\left\\{ \\begin{array}{ll} f = 1 & dg = sinx \\cdot dx \\\\ df = 0 & g = -cosx \\end{array} \\right\\}", ue_informatik_2019_blatt_8_1_1_3);
			//katex.render("= (- (1 \\cdot (-cosx)))|_{0}^{2\\pi} - \\int_{0}^{2\\pi} 1 \\cdot sinx \\cdot dx ", ue_informatik_2019_blatt_8_1_1_4);
			katex.render("= \\underbrace{2\\pi \\cdot sin(2\\pi) - 2 \\cdot 0 \\cdot sin(0)}_{=0} - \\int_{0}^{2\\pi} 1 \\cdot sinx \\cdot dx = \\left\\{ \\begin{array}{ll} f = 1 & dg = sinx \\cdot dx \\\\ df = 0 & g = -cosx \\end{array} \\right\\}", ue_informatik_2019_blatt_8_1_1_3);
		</script>
		
	</body>
</html>
damn. so its time to find the problem in my code. i will post the conflict area if i found it and thx for the idea to do that.

**Comment by xedex1111** [comment]
@edemaine Hi. Me again. It looks like that it corralate with that CindyJs script part. If you need the hole code i will publish, but i tried to run the function without that part and katex worked like a charm.  
		
    CindyJS({
	  // https://cindyjs.org/ref/createCindy.html
	  canvasname:cName,
	  defaultAppearance: { fontFamily: "sans-serif", textsize: txt_size, lineSize: 0.5, pointSize: 3.0 },
	  //defaultAppearance: {},
	  scripts: "cs*",
	  //movescript: "csmove",
	  movescript: sName,
	  geometry: gslp,
	  //use: ["CindyGL", "katex"],
	  //use: ["katex"]
	  //axes: true,
	  grid:grid_size,
	  //snap:true,
	  transform: [{
	  //visibleRect: [100, 200, 200, -200]
	  visibleRect: [visibleRect_x_plus_nach_links, visibleRect_y_plus_nach_oben, visibleRect_c, visibleRect_d]
      }]
	});

**Comment by kevinbarabash** [comment]
@xedex1111 is there some other CSS in play that's affecting the KaTeX CSS?

**Comment by xedex1111** [comment]
@kevinbarabash hi. sure. my own CSS files for that page. i will try today to find the fail. thx for the direction to search for it

**Comment by xedex1111** [comment]
@kevinbarabash it looks like i used different kind of katex files. i remember that i download the files direct from the katex site. It looks like that you can't use the files in combination. if you use just the files from cindyJS for katex it works like a charm :) my fault sry for that thread.
