### ISSUE TITLE
Node.js wrapper with SVG output?

### ISSUE THREAD

**Issue by Pomax** [KaTeX/KaTeX#2000]
In order for my [Primer on Bezier Curves](https://pomax.github.io/bezierinfo) to stay performant, I'm running LaTeX conversion of all the math offline, generating some 200 SVG images of which the dimensions can be checked so that the actual page can "preallocate" the space necessary and never have reflow occur from images loading in. However, that's a tricky process:

- there's a content parser that finds `\[ ... \]` blocks, and extracts the text,
- that text gets wrapped with some latex pre/postamble, and saved as `.tex` file in a temp dir
- process.spawn is call to run latex on that .tex file
- process.spawn is then called to run pdfcrop on the resulting pdf file, and
- process.spawn is then called to run pdf2svg on the cropped pdf
- the resulting SVG is then read in by node.js as normal file, and its width/height/viebox values are used to determine which width/height attribute values to set for the actual on page `<img>` element.

This sounds crazy, and it _is_ crazy, but it's the only way to generate good looking SVG files (I used mathjax-node for a while, but it ran significantly slower than that chain). Of course, it would be so much better if I could instead use KaTeX directly in node to simplify this whole process to "extract text, convert to SVG in-memory using KaTeX, check dimensions".

As such, is it possible to use KaTeX in node context? (I don't see anything in the README.md that suggests there is)

And I guess related, is it possible to make KaTeX generate SVG rather than HTML code?

**Comment by ylemkimon** [comment]
Unfortunately, KaTeX only supports HTML output for now. See #375.

**Comment by edemaine** [comment]
But if you're OK with HTML output, then yes, you can definitely run KaTeX server-side!  Just pass the contents of `\[ ... \]` blocks (excluding the `\[` and `\]`) into `katex.renderToString` to get the HTML that should replace the block.  Does this suffice for your application?

**Comment by Pomax** [comment]
Hm, it might - is there additional CSS necessary or is katex output self-contained?

**Comment by edemaine** [comment]
You need to include katex.min.css, in particular to set the f

**Comment by Pomax** [comment]
cheers
