### ISSUE TITLE
Use semantic-release to simplify releases

### ISSUE THREAD

**Issue by kevinbarabash** [KaTeX/KaTeX#2011]
semantic-release determines what version to bump to when releasing based on commit messages, see https://github.com/semantic-release/semantic-release for details.  This may take a bit of work to integrate this into our existing release script.

As a first step though we could adopt https://github.com/semantic-release/commit-analyzer which would enforce a specific commit message style which would be helpful in manually determining which version to bump to.

**Comment by ylemkimon** [comment]
There is a GitHub bot that enforces Conventional Commits spec: https://github.com/apps/semantic-pull-requests.

**Comment by kevinbarabash** [comment]
@ylemkimon nice find.  Let's give it a try.

**Comment by kevinbarabash** [comment]
I think we'll probably want to use `titleOnly: true` since we squash merge.  Are there any other settings you think would be useful?
