### ISSUE TITLE
Support for \style{}

### ISSUE THREAD

**Issue by venkateshwarans** [KaTeX/KaTeX#2029]
> Before requesting a feature, please search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Is your feature request related to a problem? Please describe.**

When I am trying to render a latex - `\frac{\style{font-size:14px}R\style{font-size:14px}{\mathit=}\style{font-size:14px}\rho\style{font-size:14px}{\mathit\;}\style{font-size:14px}l}{\style{font-size:14px}A}` 
<img width="345" alt="Screenshot 2019-07-10 at 4 20 27 PM" src="https://user-images.githubusercontent.com/38975782/60963550-b9a60880-a32e-11e9-9eda-3c972867b60e.png">
The latex is generated using Wiris's MathType Plugin.

**Link to or name of a (La)TeX package that provides the same feature:**

KaTeX's general goal is to render as LaTeX does.
When the same latex is entered here - http://www.wiris.com/editor/demo/en/developers - it renders as expected.

**Comment by kevinbarabash** [comment]
@venkateshwarans is this feature from an existing LaTeX package?  Also, I'm curious why `\style{font-size:14px}` is repeated so many times in the example you gave.

**Comment by edemaine** [comment]
I believe this is a feature of [MathJax's HTML library](http://docs.mathjax.org/en/latest/tex.html#html), not LaTeX. Still, now that we have the `trust` setting, we probably should add all of those features:
* `\href` (already done)
* `\class` (#1437)
* `\cssId` (#1437)
* `\style` (this issue)

So, thanks for the feature request!

**Comment by venkateshwarans** [comment]
> @venkateshwarans is this feature from an existing LaTeX package? Also, I'm curious why `\style{font-size:14px}` is repeated so many times in the example you gave.

In our project, we are using CKEditor to let other create questions and answers which might have Mathematical and Chemistry equations. This is one such question created using CKEditor and Wiris Math plugin. The same question renders correctly here:  http://www.wiris.com/editor/demo/en/developers

![image](https://user-images.githubusercontent.com/38975782/61019820-2b2a9900-a3b9-11e9-9a06-5098d527b49c.png)
