### ISSUE TITLE
Change dependabot settings to only open PRs for security issues

### ISSUE THREAD

**Issue by kevinbarabash** [KaTeX/KaTeX#2035]
The number of PRs we're getting from dependabot is a little ridiculous.  I've enabled the following settings:
<img width="473" alt="Screen Shot 2019-07-13 at 8 09 31 PM" src="https://user-images.githubusercontent.com/1044413/61177753-32fd5f80-a5aa-11e9-89a7-a8730d15b3dc.png">

If anyone feels that we should turn off these settings let me know.

**Comment by kevinbarabash** [comment]
I'm going to close all non-security related PRs from dependabot.

**Comment by kevinbarabash** [comment]
I changed it again since PRs for security issues are important even if they require a change to package.json and not just yarn.lock.  There's some secondary settings about when to make changes to package.json.  Currently the default is selected.
<img width="550" alt="Screen Shot 2019-07-13 at 8 12 28 PM" src="https://user-images.githubusercontent.com/1044413/61177771-92f40600-a5aa-11e9-9bc4-dc29eda9d935.png">

**Comment by kevinbarabash** [comment]
One library I wouldn't mind getting automatic updates for even if there aren't security issues is `flow`.  Maybe dependabot has some sort of config file where that can be specified.

**Comment by edemaine** [comment]
Part of this is probably because we haven't been running greenkeeper for a while, but Friday's updates might be something more.  Maybe we should remove some dependencies 😃.  Is there a way to just update for "major" revisions (second number, not third), to cut down?

Regarding "Update strategy", I think it'd be a little nicer to update `package.json`, but not a big deal either way.

**Comment by ylemkimon** [comment]
I've opened #2311 to enable GitHub Dependabot:

> I think we should enable it for all dependencies as (1) KaTeX build process may break even if it's minor update as in #2301, (2) it's easier to review and fix when there are few changes to the dependency, and (3) performance and compatibility might improve.
>
> By default, it raises a maximum of five pull requests, and this value is configurable. I think this is a reasonable amount.

**Comment by ylemkimon** [comment]
Closing as #2311 is merged.
