### ISSUE TITLE
Add lemma, proof and theorem environment

### ISSUE THREAD

**Issue by LEXUGE** [KaTeX/KaTeX#2038]
**Describe the solution you'd like:**
Provide these three environment just like LaTeX does

**Link to or name of a (La)TeX package that provides the same feature:**
Lemma, Proof and Theorem environment.

**Describe alternatives you've considered:**
I tried to render that by myself, but is not that perfect.

**Comment by kevinbarabash** [comment]
Which LaTeX packages are these environments defined in?

**Comment by edemaine** [comment]
There are many, but `amsthm` is probably a good starting point.  However, these really only work in text mode, not math mode, so they're probably pretty out-of-scope for KaTeX for the time being.

**Comment by LEXUGE** [comment]
> There are many, but `amsthm` is probably a good starting point. However, these really only work in text mode, not math mode, so they're probably pretty out-of-scope for KaTeX for the time being.

OK, so any work around here?

**Comment by edemaine** [comment]
@LEXUGE You can format the theorems in HTML, like the rest of your text, and just use KaTeX for the mathematics part.  Or you could use a larger LaTeX &rarr; HTML conversion system (ideally one that supports KaTeX, though I don't know one off hand).  Or you could write your own regular expressions to implement some basic LaTeX functionality like theorems, such as [this piece of code I wrote](https://github.com/edemaine/coauthor/blob/master/lib/formats.coffee).
