### ISSUE TITLE
Quotes in delimiters?

### ISSUE THREAD

**Issue by Evidlo** [KaTeX/KaTeX#2043]
I have some generated HTML which contains LaTeX embedded in <script> tags.

Inline math looks like this

```
<script type="math/tex">X</script>
```

and block math looks like this

```
<script type="math/tex; mode=display">
MI(i_1, \hat{i_2}) = H(i_1) + H(\hat{i_2}) - H(i_1, \hat{i_2})
</script>
```

How do I properly escape these quotes?

I've tried a few variations involving `&quot;`, but none seem to work.

**Comment by edemaine** [comment]
@Evidlo I'm not sure what exactly you're asking.  If you don't want that to be treated as HTML, you would do something like 
```html
&lt;script type="math/tex"&gt;X&lt;/script&gt;
```
Are you trying to get this to parse with KaTeX's auto-render, using delimiters to catch `<script>` tags?

**Comment by Evidlo** [comment]
Yes, I'm trying to tell `renderMathInElement` to parse script tags.

``` html
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/contrib/auto-render.min.js" integrity="sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI" crossorigin="anonymous" onload="renderMathInElement(document.body,{delimiters: [{left: '<script type=&quot;math/tex; mode=display&quot;>', right: '<' + '/script>', display: true}, {left: '<script type=&quot;math/tex&quot;>', right: '<' + '/script>', display: false}]});"></script>     

```

**Comment by edemaine** [comment]
That should (only) work if the HTML is escaped, as above.  (Also, a typo: `renderMathInElement` should be `katex.renderMathInElement`.)  Are you able to control the HTML?  If not, you'll need another solution.  You might be able to call `katex.render` directly on the `<script>` elements, but I'm worried they'll get processed by the browser first...

**Comment by edemaine** [comment]
OK, I threw together a little code that seems to do the trick ([Codepen](https://codepen.io/edemaine/pen/agexYr)) but then I remembered that [there's a contributed extension that does exactly this](https://github.com/KaTeX/KaTeX/tree/master/contrib/mathtex-script-type).  You should use that extension instead of auto-render.
