### ISSUE TITLE
Whats the proper way to include katex css and fonts in a project?

### ISSUE THREAD

**Issue by nikita-skobov** [KaTeX/KaTeX#2055]
If somebody is making a react spa and wants to include katex, what is the proper way to include the css and fonts?

My project structure currently looks like this:
```sh
public/
    index.html
    katex.min.css
    fonts/
        KaTeX_{all the various katex font files...}
src/
    index.js
    # other files
```

index.js includes the katex npm package, and the katex.min.css and katex fonts provide the styling for the katex to be rendered properly. I downloaded katex.min.css and the katex fonts from https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/

I would like to know:
1. Am I breaking any licensing rules if I redistribute the katex fonts and katex css on my own website?
2. Is there a better way to include these files in my project (other than using the link tag)?

**Comment by ylemkimon** [comment]
KaTeX is licensed under [the MIT license](https://github.com/KaTeX/KaTeX/blob/master/LICENSE), which allows practically everything, as long as you include copyright and license notices (the file above).
