### ISSUE TITLE
possible to use same katex.render for more then one span

### ISSUE THREAD

**Issue by xedex1111** [KaTeX/KaTeX#2056]
hi. is it possible to use 

    katex.render("\\int_0^2 xe^{2x}dx", span1);

for more then one span as an example

    katex.render("\\int_0^2 xe^{2x}dx", span1, span2);

? exists some smart ways to do that? br

**Comment by edemaine** [comment]
```js
[span1, span2].forEach((span) => katex.render("\\int_0^2 xe^{2x}dx", span);
```

This parses the text twice, but I doubt that incurs too much overhead.  Is there a particular motivation for rendering to multiple spans?

**Comment by xedex1111** [comment]
big thx!
