### ISSUE TITLE
Restrict editing the wiki to maintainers

### ISSUE THREAD

**Issue by ylemkimon** [KaTeX/KaTeX#2058]
I'm not sure how or why, but the https://github.com/KaTeX/KaTeX/wiki/Function-Support-in-KaTeX page keeps getting re-created by people. As it might affect SEO and may be used for spamming, I think we should restrict editing.

**Comment by kevinbarabash** [comment]
@ylemkimon thanks for noticing this issue.  I've restricting editing of the wiki to those people with push access.
