### ISSUE TITLE
0.11.x release planning

### ISSUE THREAD

**Issue by kevinbarabash** [KaTeX/KaTeX#2064]
In the past we've had alphas and betas, but I think moving straight to 0.11.0 and release patches if necessary is probably the way to go.

Before creating a release though, I'm curious if there are any PRs that should be considered for review/inclusion in this release.

**Comment by ronkok** [comment]
Pull requests #2032 and #2040  were both written in response to issue #2031. One or the other of those PRs should be reviewed and merged. They go in somewhat different directions, so they cannot both be merged as is. We need to pick one. Or perhaps merge both, but in that case, at least one would need to be substantially modified.

**Comment by edemaine** [comment]
@ronkok raised a possible alternative way to implement #2040. I can look at that, especially if anyone feels strongly about it. I agree that it would be good to merge (and I prefer it to #2032 though I may be biased :smile:).

**Comment by kevinbarabash** [comment]
I'll look at things this weekend.

**Comment by kevinbarabash** [comment]
Now that #2040 has been merged this is no longer blocked.  I'll put up a publish PR later today.
