### ISSUE TITLE
If the rendering area contains Chinese, the rendering error will be reported.

### ISSUE THREAD

**Issue by wcdxhl0117** [KaTeX/KaTeX#2073]
Hello, I am currently using KaTeX to do LaTeX formula analysis, its performance is really excellent, but in the use process, there is a problem that when LaTeX contains Chinese, rendering will error! Does KaTeX not support Chinese? Or does it need special configuration?

**Comment by edemaine** [comment]
Chinese should be supported, though if you use it outside `\text` mode you will get a warning without changing the `strict` setting. Could you give an example of what input causes an error?

**Comment by wcdxhl0117** [comment]
> \text

Thank you very much for supporting Chinese. I didn't pass special characters like Chinese through' \text {}'. I was too careless. Thank you.
