### ISSUE TITLE
\gray not supported

### ISSUE THREAD

**Issue by mpolyak** [KaTeX/KaTeX#2074]
As part of an effort to upgrade KaTeX from version `0.9` to the current version `0.11` on www.khanacademy.org we ran an audit of published math content on the site, to compare parse errors using `KaTeX 0.11` vs the (currently used) `KaTeX 0.9` library version.

We found that that expressions using `\gray` fail to parse with `KaTeX 0.11`:
```
ParseError: KaTeX parse error: Expected '}', got '#' at position 18: …extcolor{gray}{#̲#1}
```

Here are some examples:
```
\gray{1}
```
```
\gray6
```
```
\gray 1
```
```
\gray9 \times \gray3
```
```
\gray{\text{apple}}
```

These all fail to parse with the above error.

**Comment by kevinbarabash** [comment]
I was able to repro this on katex.org.  Interestingly, `\red{1}` works fine.

**Comment by edemaine** [comment]
@mpolyak Thanks for finding and reporting this! I've created #2075 which should fix the issue.

**Comment by mpolyak** [comment]
Thank you @edemaine!
