### ISSUE TITLE
\href{} Produces Huge number of elements (1 per character)

### ISSUE THREAD

**Issue by Pugio** [KaTeX/KaTeX#2079]
Katex is producing huge number of <span> elements when wrapping text within the `\href{}` directive. I can't see any immediate reason to suddenly produce 1 span per character, rather than just simply wrapping the range of identically styled characters in the <a> tag.
[jsfiddle](https://jsfiddle.net/0a7e6fx1/3/)

I am generating a lot of text, and don't want the overhead of adding hundreds of spans for each link.

**(La)TeX code:**
```latex
\text{\href{https://google.com}{abcdefghijk}}
```

**Expected behavior:**
![image](https://user-images.githubusercontent.com/286180/63327182-1276b100-c371-11e9-818f-8b1cb41abdd9.png)

**Environment (please complete the following information):**
 - KaTeX Version: 0.10.2
 - Device: Desktop
 - OS: macOS 10.13.6
 - Browser: Chrome
 - Version: 76

**Comment by edemaine** [comment]
@Pugio Thanks for the report. For reference, here is the current generated HTML:

![image](https://user-images.githubusercontent.com/2218736/63350099-c6a11900-c32a-11e9-950e-4d336f03885c.png)

Looking at the code, it seems we call `buildCommon.tryCombineChars` only in the outermost `\text` functions.  So e.g. `\text{\href{https://google.com}{\text{abcdefghijk}}}` generates the desired code, but e.g. `\text{\href{https://google.com}{{abcdefghijk}}}` doesn't.  I think ideally every group in text mode (and not just the calls to `\text...`) should call `buildCommon.tryCombineChars`.

**Comment by Pugio** [comment]
Thank you for responding to this so quickly. The PR you created looks good (though I don't possess enough project knowledge to comment much) – I've wrapped my code in an extra inner `\text{}` and it looks good now, thank you!

**Comment by kevinbarabash** [comment]
#2080 is a partial fix for this.  There are still some spans that could potentially be combined but aren't because of the italics correction.  I'll open a separate ticket for the remaining work.
