### ISSUE TITLE
Quick question: Is there a way to build a custom katex bundle that's smaller in size?

### ISSUE THREAD

**Issue by pkrumins** [KaTeX/KaTeX#2083]
Hey there,

I'd like to use this library for one of my projects but it's too large – over 200KB minified! I checked the readme and documentation but couldn't find a good answer, so I'm asking here. Is there a way to build a custom version that's smaller in size by selecting things that I need and skipping ones I don't need? Thanks!

Sincerely,
Peter Krumins

**Comment by edemaine** [comment]
I think the short answer is "no, there's no existing way". We'd be open to suggestions. What might you want to omit? LaTeX is a complicated beast.

The gzipped size is 69k. Is that considered large? What is your application?

**Comment by pkrumins** [comment]
Hi Erik,

Thanks for your response.

I missed that it's usually served gzipped and took the raw byte size as the measure. The size of 69k is looking much better. However, as a hopeless minimalist, this is still looking large for me.

My application is [MathURLs.com](https://MathURLs.com) – a neat math news aggregator. Two of the math news sources include the top questions from Math Overflow and Math Exchange. As my news aggregator collects only the titles, they contain very tiny amounts of simple LaTeX formulas, such as functions, fractions, exponents, integrals, greek letters and special math symbols. I definitely don't need macros, environments, and other complicated things that wouldn't appear in the titles.

Sincerely,
Peter Krumins

**Comment by edemaine** [comment]
Perhaps you'd be happier if you rendered on the server, so you never need to send the KaTeX source code to the client?

I'd have to check, but I suspect that the bulk of the KaTeX code is the many symbols it supports, and not features like macro expansion (which would also be nearly impossible to remove at this point, as many basic features are implemented by macros).

**Comment by ronkok** [comment]
There has been some movement lately to provide [better support for MathML](https://mathml.igalia.com/). If all the browsers ever do support MathML, then it would be possible to create a subset of KaTeX that did only the LaTeX-to-MathML conversion. Such a version would be smaller because it could omit the fonts and the SVGs.

Sorry I don't have a solution that works right away.

MathURLs.com looks cool, by the way.

**Comment by edemaine** [comment]
I realize that we already have a `yarn analyze` tool that gives interactive display of what's large in the KaTeX bundle.  Here's a static rendering (based on gzipped size):

![image](https://user-images.githubusercontent.com/2218736/63529302-749af780-c4d2-11e9-84a5-c07ef2636b9a.png)

I think this confirms my hypothesis.  Out of the ~600kb total uncompressed size, `symbols.js` and `fontMetricsData.js` alone take 131kb.  All `functions` take another 137kb, and features defined by macros (`macros.js`) take another 35kb.  The SVG images (`svgGeometry.js`) take only 23kb.

I've always thought `symbols.js` was somewhat inefficiently encoded as a sequence of function calls, but gzip should take care of that.  It's going to be hard to cut these down without knowing exactly which symbols you need, and I can't imagine it being worth the effort...  If you want your client bundle smaller, I'd use server-side rendering.

**Comment by pkrumins** [comment]
Thanks for the analysis! Yes, it looks like it's not worth the effort. My application is written in PHP so I don't think I can render it server-side but I think I know what I'll do – I'll make sure I use a gzipped version of the library and then it will be a 69kb increase (in my original question I forgot about compression.)
