### ISSUE TITLE
huge scripting and rendering times

### ISSUE THREAD

**Issue by xedex1111** [KaTeX/KaTeX#2092]
hi. i have huge rendering(6s+) and scripting(12s+) times with v0.11 and v0.10
could you take a look at my code and tell me what i did wrong? i also tried to change that to cindyJS v0.8.7 katex scripts and i was surprised that the loading time for the hole page was under 4s, but it has still some fails. many of text was not full rendered. maybe thats the reason why the loading time was under that time. any ideas to reduce the loading times would be fine. oh yeah. don't be to hard with my code. i restruct the hole code to reduce the loading time because the original one has 35s+. thats the reason why nothing is really well programmed. the rendering times are just for the button "buch" the other parts takes also there times. the katex scripts are to implement by yourself. thx, br
[files.zip](https://github.com/KaTeX/KaTeX/files/3573694/files.zip)
![loadingTimes](https://user-images.githubusercontent.com/51515279/64242182-5e932b00-cf05-11e9-84b7-6c7981b9c07d.PNG)

**Comment by kevinbarabash** [comment]
There are 2000+ calls to `katex.render` in the code.  My hunch is that it's a DOM mutation issue.  Could you look at the flame chart in the profiler and see what functions are taking a long time?  Also, I'm curious what happens if you replace `katex.render` with `katex.renderToString`.  That should give us an idea of whether it's a DOM issue or not.

**Comment by ylemkimon** [comment]
Could you capture the Bottom-Up tab and Call Tree tab?

**Comment by xedex1111** [comment]
Hi. Sorry for my late response! 
@ylemkimon: times_bottom_up and times_call_tree are with katex.render command but with an modified code. thats the reason why the loading times are smaller then the original post.

@kevinbarabash The problem with your katex.renderToString command is, that i didnt get any rendered functions and i think the best idea is atm to write my hole code new with more buttons which loads and render just the part of the code new which is needed. the new pictures are not anymore with that same code as i posted it. i know, i know! not cool. for the next issues i will make a original backup of the hole code before i set the thread. sry. is my fault. 

![times_bottom_up](https://user-images.githubusercontent.com/51515279/65878819-388b6a00-e38f-11e9-96b3-f35f2639e999.JPG)
![times_call_tree](https://user-images.githubusercontent.com/51515279/65878821-39240080-e38f-11e9-8854-f709d75ab957.JPG)

**Comment by kevinbarabash** [comment]
The output of `katex.renderToString` would still have to be injected into the page.  From the profiling data you posted, it looks like there's a lot of layout/recalculate style going on in webfont.js.  Do you know what that's doing?
