### ISSUE TITLE
rendering problems in chrome 76.0.x

### ISSUE THREAD

**Issue by xedex1111** [KaTeX/KaTeX#2095]
Hi. I found a bug for the overline command. Don't know what to do, but that's not cool if some students take a look with the wrong browser. for and with which browser is katex designed to let them know in which browser they have to take a look if they want to learn?  br
![problem_chrome](https://user-images.githubusercontent.com/51515279/64944587-f7fbfe80-d86e-11e9-8d0f-e28e835aba79.JPG)

**Comment by edemaine** [comment]
@xedex1111 KaTeX should work in Chrome, Firefox, Safari, and Edge, so what you're seeing is buggy behavior.  Can you answer the following:
1. Does your example work in the demo app on `katex.org`?  I just tried a simple subset (`0=\overline{p(z)}=p(\overline z)`) and it worked fine:
![image](https://user-images.githubusercontent.com/2218736/64957173-4fdc3a80-d85a-11e9-8209-86dc4abaa5c4.png)
2. Does your example work if you zoom into the page (ctrl-`+`)?  I suspect that this might be a "minimum border line width" issue surfacing yet again...
3. Which version of KaTeX are you using?

**Comment by xedex1111** [comment]
1. is answerd
2. is the right answer! after zooming i get the right view at 100% and 80%. 90% is not his favorite. that was the point. big thx. 
3. katex_v10_2

**Comment by edemaine** [comment]
It's sad that we can't get all zoom levels to work (in Chrome -- I think it's a bug in Chrome), but at least it works at 100%.

**Comment by xedex1111** [comment]
no problem. it's a lot of work to bring all kind of different browsers under perfekt functionality. i understand that. just wanted to tell you, that i found a little bug and just wanted to know for which browser katex works with the minimum fails. nobody is perfect and you are also not paid as gigants like microsoft to handle that easier without stress of money and programmers. its a great and usefull product for all scientists, teachers and learner! gj @ the team
