### ISSUE TITLE
KaTeX to SVG or canvas

### ISSUE THREAD

**Issue by thosgood** [KaTeX/KaTeX#2096]
Now that https://github.com/KaTeX/KaTeX/pull/251 has been closed, are there any plans for supporting KaTeX rendering to SVG/canvas/PNG/any other formats?

**Comment by kevinbarabash** [comment]
I think https://github.com/KaTeX/KaTeX/issues/376 would be a blocker for this.

**Comment by kevinbarabash** [comment]
This is a duplicate of #504 and #375.
