### ISSUE TITLE
katex css not correctly in safari

### ISSUE THREAD

**Issue by yokins** [KaTeX/KaTeX#2097]
**Describe the bug:**
I need to display a formula in cordova, which is correct in chrome, but not in safari.
Because the formula is inserted into the rich text, I can only render the HTML code.
In the meantime, I'm using VUE, so I'm just going to go straight as follow:

```html
  <div class="question" v-html="question.html"></div>
```
i also import css in script
```javascript
import 'katex/dist/katex.min.css'
```

the question object:
![image](https://user-images.githubusercontent.com/45431050/65014948-ba70a180-d952-11e9-9d0b-38b22477224a.png)

display in chrome
![image](https://user-images.githubusercontent.com/45431050/65014752-1d156d80-d952-11e9-80fb-416d4b6a4362.png)

display in safari
![image](https://user-images.githubusercontent.com/45431050/65014766-2999c600-d952-11e9-968e-005465d72649.png)

so how can i fix it?

**Comment by kevinbarabash** [comment]
@yokins can you link to a public facing page that demostrates this iissue?  The following code works on katex.org: `\frac{1}{3}x^2 \times \frac{1}{3} \times 2`.

<img width="818" alt="Screen Shot 2019-09-22 at 3 21 27 PM" src="https://user-images.githubusercontent.com/1044413/65393272-ad85f080-dd4c-11e9-965a-c992ceb2fd6f.png">
