### ISSUE TITLE
Making of Byrne’s Euclid

### ISSUE THREAD

**Issue by mbourne** [KaTeX/KaTeX#2101]
This is not an issue, but as there doesn't appear to be anywhere else to share it, here goes.

Many of you will find this interesting, I believe (sorry if you've seen it before):

https://www.c82.net/blog/?id=79 (Making of Byrne’s Euclid, by Nicholas Rougeux)

His approaches to work around MathJax (from about 1/2 way down) are interesting, especially his SVG stretchy bracket hacks.

He's produced an impressive document.

**Comment by kevinbarabash** [comment]
I really appreciate the attention to detail, especially the alignment of dotted/dashed lines relative to the shapes they encompass.  I wish though that Byrne would've modernized things a bit more than he did as it would've made the content accessible to more people.
