### ISSUE TITLE
Not equal (\ne) sign doesn't render correctly the slash sign

### ISSUE THREAD

**Issue by hrroga** [KaTeX/KaTeX#2109]
It seems the slash sign on top of the equal sign is broken.

I have the latest version of Katex in my project. Below is a screenshot taken in the latest version of Firefox. Also in Chrome is the same thing.

![Screenshot_2019-10-04 Ushtrimi 5 - Mësimi 2G - Matematika 12 Sputnik](https://user-images.githubusercontent.com/14089134/66205153-f030bc80-e6ac-11e9-8255-5972f011cfc6.png)

**Comment by edemaine** [comment]
If you go to the demo on katex.org, do you see the same thing?  I see:

![image](https://user-images.githubusercontent.com/2218736/66205666-f8bccf00-e67b-11e9-9fc8-4c439ec23805.png)

It looks like you either aren't including the font files, or they're getting overridden in the CSS.  Note in particular how the numbers look very different.  If you send a complete working example, we can try to help.

**Comment by hrroga** [comment]
True, the font is overriden with a Google Font. Now that I removed it it's okay, but I have to use my font of choice. Everything else with math expressions seems fine with this font (and other; I also tried Roboto), but this equal sign is the only thing until now that I have found to render incorrectly. Anything else I can do?

**Comment by edemaine** [comment]
KaTeX doesn't really support font overriding, I'm afraid.  I'm not sure if it's currently possible to override just numbers and letters and avoid overriding symbols, but that's the behavior you'd want...

**Comment by edemaine** [comment]
You could also try redefining the behavior of `\neq` to instead do ```\mathrel{\char`≠}``` which produces a literal not-equal character which should work in other fonts.  You can do this easily via the `macros` functionality, or via a `\def`.

**Comment by hrroga** [comment]
I see. Great, thank you so much!

**Comment by tony** [comment]
re: [workaround](https://github.com/KaTeX/KaTeX/issues/2109#issuecomment-538369554) from @edemaine, thank you!

[`macros`](https://katex.org/docs/options.html#:~:text=%23cc0000)-,macros,-%3A%20object.%20A) looks like this for me:

```javascript
katex.render(
  text,
  element,
  {
    macros: {
      '\\neq': '\\mathrel{\\char`≠}',
    },
  },
)
```

**Comment by gavox** [comment]
This is what I was looking for! 
Please tell me, ¿where should I find my macros file? ¿what's its name?

Thanks
