### ISSUE TITLE
\vec{r} doesn't  work: arrow on the top disappeared

### ISSUE THREAD

**Issue by dawnarc** [KaTeX/KaTeX#2112]
**Describe the bug:**
The arrow of `\vec{r}` doesn't display.  
But `\widetilde{ac}`, `\tilde{a}` and `\overrightarrow{AB}` worked fine.

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
$$\vec{r}$$
```

**Screenshot**
![2019-10-07 21_20_40- Math Check which side of a plane points are on](https://user-images.githubusercontent.com/3351764/66315452-6bfa6580-e948-11e9-94cd-d44cd851c10a.png)

**Environment (please complete the following information):**
 - KaTeX Version: 0.11.1
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome, FIreFox, Edge

**Comment by edemaine** [comment]
Here's what I see on the katex.org demo site, on Chrome on Windows 10:

![image](https://user-images.githubusercontent.com/2218736/66316463-b8f92000-e8e5-11e9-9a13-5b3d8cac2067.png)

Can you confirm you see the same?  If so, there's something specific to your environment, which we'll need to know more about to diagnose.

**Comment by dawnarc** [comment]
Sorry for my mistake, I found it's the bug of theme of Hugo, when I changed the theme, `\vec{r}` worked fine. Thanks very much for @edemaine .
