### ISSUE TITLE
`\limits` inside `\mathchoice` doesn't do what I expect

### ISSUE THREAD

**Issue by JohnTasto** [KaTeX/KaTeX#2114]
I'm not sure if this is a bug or my own misunderstanding. I'm trying to write a macro that lets me make big operators that render similarly to existing big operators in all modes. Here's what I have:

```
\def \bigop #1 {\mathchoice
  {\mathop{\huge#1}\limits}
  {\raisebox-2.5pt{$\Large#1$}}
  {\raisebox-1.75pt{$\normalsize#1$}}
  {\raisebox-1.1pt{$\scriptsize#1$}}
}
\def \bige {\bigop\exists}
```

In ```\displaymode```, ```\bige``` renders incorrectly, as though `\limits` isn't there. However, when written without ```\mathchoice```, it works:

```
\def \bigop #1 {\mathop{\huge#1}\limits}
\def \bige {\bigop\exists}
```

![bigop](https://user-images.githubusercontent.com/5026892/66419378-e2cf4700-e9b8-11e9-9c55-17fdc23d8737.png)

[Live demo](https://katex.org/?data=%7B%22displayMode%22%3Atrue%2C%22leqno%22%3Afalse%2C%22fleqn%22%3Afalse%2C%22throwOnError%22%3Atrue%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22warn%22%2C%22trust%22%3Afalse%2C%22code%22%3A%22%5C%5Cdef%20%5C%5Cbigop%20%231%20%7B%5C%5Cmathchoice%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5Chuge%231%7D%5C%5Climits%7D%5Cn%20%20%7B%5C%5Craisebox-2.5pt%7B%24%5C%5CLarge%231%24%7D%7D%5Cn%20%20%7B%5C%5Craisebox-1.75pt%7B%24%5C%5Cnormalsize%231%24%7D%7D%5Cn%20%20%7B%5C%5Craisebox-1.1pt%7B%24%5C%5Cscriptsize%231%24%7D%7D%5Cn%7D%5Cn%5C%5Cdef%20%5C%5Cbige%20%7B%5C%5Cbigop%5C%5Cexists%7D%5Cn%5C%5Ctexttt%7B%5C%5Ctextbackslash%20mathchoice%7D%20%5C%5C%5C%5C%5Cn%5C%5Cbegin%7Barray%7D%7Bcccc%7D%5Cn%20%20%5C%5Ctexttt%7B%5C%5Ctextbackslash%20displaystyle%7D%20%26%5Cn%20%20%5C%5Ctexttt%7B%5C%5Ctextbackslash%20textstyle%7D%20%26%5Cn%20%20%5C%5Ctexttt%7B%5C%5Ctextbackslash%20scriptstyle%7D%20%26%5Cn%20%20%5C%5Ctexttt%7B%5C%5Ctextbackslash%20scriptscriptstyle%7D%20%5C%5C%5C%5C%5Cn%20%20%5C%5Cdisplaystyle%20%5C%5Cbige_k%5En%5C%5Csum_k%5En%20%26%5Cn%20%20%5C%5Ctextstyle%20%5C%5Cbige_k%5En%5C%5Csum_k%5En%20%26%5Cn%20%20%5C%5Cscriptstyle%20%5C%5Cbige_k%5En%5C%5Csum_k%5En%20%26%5Cn%20%20%5C%5Cscriptscriptstyle%20%5C%5Cbige_k%5En%5C%5Csum_k%5En%5Cn%5C%5Cend%7Barray%7D%20%5C%5C%5C%5C%5B1em%5D%5Cn%5Cn%5C%5Cxcancel%5C%5Ctexttt%7B%5C%5Ctextbackslash%20mathchoice%7D%20%5C%5C%5C%5C%5Cn%5C%5Cdef%20%5C%5Cbigop%20%231%20%7B%5C%5Cmathop%7B%5C%5Chuge%231%7D%5C%5Climits%7D%5Cn%5C%5Cdef%20%5C%5Cbige%20%7B%5C%5Cbigop%5C%5Cexists%7D%5Cn%5C%5Ctexttt%7B%5C%5Ctextbackslash%20displaystyle%7D%20%5C%5C%5C%5C%5Cn%5C%5Cdisplaystyle%20%5C%5Cbige_k%5En%5C%5Csum_k%5En%20%5C%5C%5C%5C%5Cn%22%7D)
The Katex.org demo is not great btw - the preview cuts off at the bottom, it can't be scrolled, and when I try making the text smaller to make everything fit, the text editor suddenly gets really narrow and preview gets even smaller. The one at https://katex.org/#demo is only mildly annoying, but the permalinked version is unusable - at least in Chrome on Windows.

Is there any way to see a final macro expansion before it gets rendered to mathml?

**Comment by edemaine** [comment]
@JohnTasto Could you test with actual LaTeX to see whether this is a bug with KaTeX or a misunderstanding?

**Comment by JohnTasto** [comment]
@edemaine It looks like neither works in LaTeX - it always puts sups and subs off to the side unless they're hanging directly off a `\limits`. What makes it work then in the non-`\mathchoice` macro here?

**Comment by edemaine** [comment]
@JohnTasto I did the same test and found the same. :-(

Thinking about how `\mathchoice` is implemented in KaTeX, I see why this doesn't work in KaTeX: `\mathchoice` is implemented as a "function" instead of a "macro", meaning that it's isn't expanded/resolved during macro expansion but rather at HTML/MathML rendering time.  (The reason I did it this way is that, currently we don't know which style we're in until rendering time.  This might be fixable, but it is the case currently.)

Both `\mathchoice` and `\limits` are TeX built-ins, so it's difficult to understand their workings (we need to look at the TeX source code).  But it seems plausible that it's a similar issue (`\mathchoice` happens at output instead of macro expansion time) ~~or else maybe something like `\mathchoice` generates a group or something that separates the `\limits` from the `^`/`_`~~.  Indeed, [the TeXbook](http://www.ctex.org/documents/shredder/src/texbook.pdf#page=162) says "TeX actually typesets all four subformulas [of `\mathchoice`], before it chooses the final one, because the actual style is not always known at the time a `\mathchoice` is encountered" and [the source code](http://tug.org/texlive/devsrc/Build/source/texk/web2c/tex.web) turns `\mathchoice` into "choice nodes" which are probably processed later than macro expansion.

In LaTeX, a workaround is to use `\if@display`:

```latex
\def\bigop#1{\if@display
  \mathop{\huge #1}\limits
\else
  #1
\fi
}
```

(Note that you really shouldn't have a space between `#1` and `{` in a `\def` like in your example.)

`\if`s are challenging to implement in KaTeX, but not impossible...

**Comment by JohnTasto** [comment]
@edemaine Thanks for your reply. Makes sense, just not very intuitive. I would love to see more macro functionality in KaTeX, such as `\if`, though `\@ifnextchar` can already do a lot. I was able find a limited workaround using a bunch of `\@ifnextchar` and a whole lot of repetitive code:

```tex
\def \@eatfourth #1#2#3#4{#1#2#3}
\def \@eatfifth  #1#2#3#4#5{#1#2#3#4}
\def \@MathOpDisplay      #1{\raisebox{-4.7pt }{\huge      $#1$}}
\def \@MathOpText         #1{\raisebox{-2.5pt }{\Large     $#1$}}
\def \@MathOpScript       #1{\raisebox{-1.75pt}{\normalsize$#1$}}
\def \@MathOpScriptScript #1{\raisebox{-1.1pt }{\scriptsize$#1$}}
\def \@MathOpNone #1{\mathchoice
  {\mathop{\@MathOpDisplay     {#1}}}
  {\mathop{\@MathOpText        {#1}}}
  {\mathop{\@MathOpScript      {#1}}}
  {\mathop{\@MathOpScriptScript{#1}}}}
\def \@MathOpSub #1#2#3{\mathchoice
  {\mathop{\@MathOpDisplay     {#1}}\limits#2_{#3}}
  {\mathop{\@MathOpText        {#1}}       #2_{#3}}
  {\mathop{\@MathOpScript      {#1}}       #2_{#3}}
  {\mathop{\@MathOpScriptScript{#1}}       #2_{#3}}}
\def \@MathOpSup #1#2#3{\mathchoice
  {\mathop{\@MathOpDisplay     {#1}}\limits#2     ^{#3}}
  {\mathop{\@MathOpText        {#1}}       #2     ^{#3}}
  {\mathop{\@MathOpScript      {#1}}       #2     ^{#3}}
  {\mathop{\@MathOpScriptScript{#1}}       #2     ^{#3}}}
\def \@MathOpSubSup #1#2#3#4{\mathchoice
  {\mathop{\@MathOpDisplay     {#1}}\limits#2_{#3}^{#4}}
  {\mathop{\@MathOpText        {#1}}       #2_{#3}^{#4}}
  {\mathop{\@MathOpScript      {#1}}       #2_{#3}^{#4}}
  {\mathop{\@MathOpScriptScript{#1}}       #2_{#3}^{#4}}}
\def \@MathOpSupSub #1#2#3#4{\@MathOpSubSup{#1}{#2}{#4}{#3}}
\def \@MathOpSubFirst #1#2#3{\@ifnextchar^
  {\@eatfifth\@MathOpSubSup{#1}{#2}{{#3}}}
            {\@MathOpSub#1#2{#3}}}
\def \@MathOpSupFirst #1#2#3{\@ifnextchar_
  {\@eatfifth\@MathOpSupSub{#1}{#2}{{#3}}}
            {\@MathOpSup#1#2{#3}}}
\def \@MathOpCheckSus #1#2{
  \@ifnextchar_{\@eatfourth\@MathOpSubFirst{{#1}}{#2}}{
  \@ifnextchar^{\@eatfourth\@MathOpSupFirst{{#1}}{#2}}{
                               \@MathOpNone{{#1}}}}}
\def \@MathOpEatLimits #1#2{
  \@ifnextchar\limits  {\@eatfourth\@MathOpEatLimits{{#1}}{\limits}}{
  \@ifnextchar\nolimits{\@eatfourth\@MathOpEatLimits{{#1}}{\nolimits}}{
                                    \@MathOpCheckSus{{#1}}{#2}}}}
\def \DeclareMathOperator #1{
  \@ifnextchar\limits  {\@eatfourth\@MathOpEatLimits{{#1}}{\limits}}{
  \@ifnextchar\nolimits{\@eatfourth\@MathOpEatLimits{{#1}}{\nolimits}}{
                                   \@MathOpEatLimits{{#1}}{{{}}}}}}
```

I'm pretty sure `\operatorname*` is supposed to do pretty much what this does, but I wasn't able to get it to do anything except insert an asterisk. I just now realized that [Markdown Preview Enhanced](https://shd101wyy.github.io/markdown-preview-enhanced/#/), where I spend most my time with KaTeX, is about 5 months out of date, so that's probably why!

I don't think `\@ifnextchar` handles spaces quite right. I found whenever there is a group, then a space, and then a character you want to check, all it can detect is that space. At least some elements other than groups seem to be fine. For instance, this:
```tex
\DeclareMathOperator \exists _ {k=0}^ {n-1}
```
makes stuff like this:
![MathOp good](https://user-images.githubusercontent.com/5026892/66545183-01375e80-eaef-11e9-954f-0afd408166fc.png)
[Live demo](https://katex.org/?data=%7B%22displayMode%22%3Atrue%2C%22leqno%22%3Afalse%2C%22fleqn%22%3Afalse%2C%22throwOnError%22%3Atrue%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22warn%22%2C%22trust%22%3Afalse%2C%22code%22%3A%22%5C%5Cdef%20%5C%5C%40eatfourth%20%231%232%233%234%7B%231%232%233%7D%5Cn%5C%5Cdef%20%5C%5C%40eatfifth%20%20%231%232%233%234%235%7B%231%232%233%234%7D%5Cn%5C%5Cdef%20%5C%5C%40MathOpDisplay%20%20%20%20%20%20%231%7B%5C%5Craisebox%7B-4.7pt%20%7D%7B%5C%5Chuge%20%20%20%20%20%20%24%231%24%7D%7D%5Cn%5C%5Cdef%20%5C%5C%40MathOpText%20%20%20%20%20%20%20%20%20%231%7B%5C%5Craisebox%7B-2.5pt%20%7D%7B%5C%5CLarge%20%20%20%20%20%24%231%24%7D%7D%5Cn%5C%5Cdef%20%5C%5C%40MathOpScript%20%20%20%20%20%20%20%231%7B%5C%5Craisebox%7B-1.75pt%7D%7B%5C%5Cnormalsize%24%231%24%7D%7D%5Cn%5C%5Cdef%20%5C%5C%40MathOpScriptScript%20%231%7B%5C%5Craisebox%7B-1.1pt%20%7D%7B%5C%5Cscriptsize%24%231%24%7D%7D%5Cn%5C%5Cdef%20%5C%5C%40MathOpNone%20%231%7B%5C%5Cmathchoice%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5C%40MathOpDisplay%20%20%20%20%20%7B%231%7D%7D%7D%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5C%40MathOpText%20%20%20%20%20%20%20%20%7B%231%7D%7D%7D%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5C%40MathOpScript%20%20%20%20%20%20%7B%231%7D%7D%7D%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5C%40MathOpScriptScript%7B%231%7D%7D%7D%7D%5Cn%5C%5Cdef%20%5C%5C%40MathOpSub%20%231%232%233%7B%5C%5Cmathchoice%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5C%40MathOpDisplay%20%20%20%20%20%7B%231%7D%7D%5C%5Climits%232_%7B%233%7D%7D%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5C%40MathOpText%20%20%20%20%20%20%20%20%7B%231%7D%7D%20%20%20%20%20%20%20%232_%7B%233%7D%7D%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5C%40MathOpScript%20%20%20%20%20%20%7B%231%7D%7D%20%20%20%20%20%20%20%232_%7B%233%7D%7D%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5C%40MathOpScriptScript%7B%231%7D%7D%20%20%20%20%20%20%20%232_%7B%233%7D%7D%7D%5Cn%5C%5Cdef%20%5C%5C%40MathOpSup%20%231%232%233%7B%5C%5Cmathchoice%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5C%40MathOpDisplay%20%20%20%20%20%7B%231%7D%7D%5C%5Climits%232%20%20%20%20%20%5E%7B%233%7D%7D%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5C%40MathOpText%20%20%20%20%20%20%20%20%7B%231%7D%7D%20%20%20%20%20%20%20%232%20%20%20%20%20%5E%7B%233%7D%7D%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5C%40MathOpScript%20%20%20%20%20%20%7B%231%7D%7D%20%20%20%20%20%20%20%232%20%20%20%20%20%5E%7B%233%7D%7D%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5C%40MathOpScriptScript%7B%231%7D%7D%20%20%20%20%20%20%20%232%20%20%20%20%20%5E%7B%233%7D%7D%7D%5Cn%5C%5Cdef%20%5C%5C%40MathOpSubSup%20%231%232%233%234%7B%5C%5Cmathchoice%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5C%40MathOpDisplay%20%20%20%20%20%7B%231%7D%7D%5C%5Climits%232_%7B%233%7D%5E%7B%234%7D%7D%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5C%40MathOpText%20%20%20%20%20%20%20%20%7B%231%7D%7D%20%20%20%20%20%20%20%232_%7B%233%7D%5E%7B%234%7D%7D%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5C%40MathOpScript%20%20%20%20%20%20%7B%231%7D%7D%20%20%20%20%20%20%20%232_%7B%233%7D%5E%7B%234%7D%7D%5Cn%20%20%7B%5C%5Cmathop%7B%5C%5C%40MathOpScriptScript%7B%231%7D%7D%20%20%20%20%20%20%20%232_%7B%233%7D%5E%7B%234%7D%7D%7D%5Cn%5C%5Cdef%20%5C%5C%40MathOpSupSub%20%231%232%233%234%7B%5C%5C%40MathOpSubSup%7B%231%7D%7B%232%7D%7B%234%7D%7B%233%7D%7D%5Cn%5C%5Cdef%20%5C%5C%40MathOpSubFirst%20%231%232%233%7B%5C%5C%40ifnextchar%5E%5Cn%20%20%7B%5C%5C%40eatfifth%5C%5C%40MathOpSubSup%7B%231%7D%7B%232%7D%7B%7B%233%7D%7D%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7B%5C%5C%40MathOpSub%231%232%7B%233%7D%7D%7D%5Cn%5C%5Cdef%20%5C%5C%40MathOpSupFirst%20%231%232%233%7B%5C%5C%40ifnextchar_%5Cn%20%20%7B%5C%5C%40eatfifth%5C%5C%40MathOpSupSub%7B%231%7D%7B%232%7D%7B%7B%233%7D%7D%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7B%5C%5C%40MathOpSup%231%232%7B%233%7D%7D%7D%5Cn%5C%5Cdef%20%5C%5C%40MathOpCheckSus%20%231%232%7B%5Cn%20%20%5C%5C%40ifnextchar_%7B%5C%5C%40eatfourth%5C%5C%40MathOpSubFirst%7B%7B%231%7D%7D%7B%232%7D%7D%7B%5Cn%20%20%5C%5C%40ifnextchar%5E%7B%5C%5C%40eatfourth%5C%5C%40MathOpSupFirst%7B%7B%231%7D%7D%7B%232%7D%7D%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5C%5C%40MathOpNone%7B%7B%231%7D%7D%7D%7D%7D%5Cn%5C%5Cdef%20%5C%5C%40MathOpEatLimits%20%231%232%7B%5Cn%20%20%5C%5C%40ifnextchar%5C%5Climits%20%20%7B%5C%5C%40eatfourth%5C%5C%40MathOpEatLimits%7B%7B%231%7D%7D%7B%5C%5Climits%7D%7D%7B%5Cn%20%20%5C%5C%40ifnextchar%5C%5Cnolimits%7B%5C%5C%40eatfourth%5C%5C%40MathOpEatLimits%7B%7B%231%7D%7D%7B%5C%5Cnolimits%7D%7D%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5C%5C%40MathOpCheckSus%7B%7B%231%7D%7D%7B%232%7D%7D%7D%7D%5Cn%5C%5Cdef%20%5C%5CDeclareMathOperator%20%231%7B%5Cn%20%20%5C%5C%40ifnextchar%5C%5Climits%20%20%7B%5C%5C%40eatfourth%5C%5C%40MathOpEatLimits%7B%7B%231%7D%7D%7B%5C%5Climits%7D%7D%7B%5Cn%20%20%5C%5C%40ifnextchar%5C%5Cnolimits%7B%5C%5C%40eatfourth%5C%5C%40MathOpEatLimits%7B%7B%231%7D%7D%7B%5C%5Cnolimits%7D%7D%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5C%5C%40MathOpEatLimits%7B%7B%231%7D%7D%7B%7B%7B%7D%7D%7D%7D%7D%7D%5Cn%5Cn%5Cn%5C%5Cdef%20%5C%5CbigE%20%7B%5C%5CDeclareMathOperator%20%5C%5Cexists%7D%5Cn%5C%5Cdef%20%5C%5CKL%20%7B%5C%5Ckern%7B32pt%7D%7D%5Cn%5C%5Cdef%20%5C%5CKS%20%7B%5C%5Ckern%7B%202em%7D%7D%5Cn%5C%5Cdef%20%5C%5Coptop%20%7B%5C%5Cunderline%7B%5C%5Cvphantom%7C%5C%5CKL%7D%7D%5Cn%5C%5Cdef%20%5C%5Copbot%20%7B%20%5C%5Coverline%7B%5C%5Cvphantom%7C%5C%5CKL%7D%7D%5Cn%5C%5Cdef%20%5C%5Csfi%20%7B%5C%5Ctextsf%20%5C%5Ci%7D%5Cn%5C%5Cdef%20%5C%5Coptest%20%231%232%7B%5Cn%20%20%5C%5Cbegin%7Baligned%7D%20%20%5C%5Coptop%5C%5C%5C%5C%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%231%7D%20%20%5C%5Ctextrm-%5C%5C%5C%5C%20%5C%5Copbot%20%5C%5Cend%7Baligned%7D%5Cn%20%20%5C%5Cbegin%7Baligned%7D%20%26%5C%5Coptop%5C%5C%5C%5C%26%5C%5Ctextrm-%20%20%20%20%20%20%20%20%20%20%20%20%7B%232%7D%20%20%20%20%20%20%20%20%20%20%5C%5C%5C%5C%26%5C%5Copbot%20%5C%5Cend%7Baligned%7D%20%5C%5CKS%5Cn%20%20%5C%5Cbegin%7Baligned%7D%20%20%5C%5Coptop%5C%5C%5C%5C%20%20%20%20%20%20%20%20%20%20%20%5C%5Ctextstyle%7B%231%7D%20%20%5C%5Ctextrm-%5C%5C%5C%5C%20%5C%5Copbot%20%5C%5Cend%7Baligned%7D%5Cn%20%20%5C%5Cbegin%7Baligned%7D%20%26%5C%5Coptop%5C%5C%5C%5C%26%5C%5Ctextrm-%20%20%5C%5Ctextstyle%7B%232%7D%20%20%20%20%20%20%20%20%20%20%5C%5C%5C%5C%26%5C%5Copbot%20%5C%5Cend%7Baligned%7D%20%5C%5CKS%5Cn%20%20%5C%5Cbegin%7Baligned%7D%20%20%5C%5Coptop%5C%5C%5C%5C%20%20%20%20%20%20%20%20%20%20%20%20_%7B%231%7D%20%20%20%5E%7B%231%7D%20%20%5C%5Ctextrm-%5C%5C%5C%5C%20%5C%5Copbot%20%5C%5Cend%7Baligned%7D%5Cn%20%20%5C%5Cbegin%7Baligned%7D%20%26%5C%5Coptop%5C%5C%5C%5C%26%5C%5Ctextrm-%20%20%20_%7B%232%7D%20%20%20%5E%7B%232%7D%20%20%20%20%20%20%20%20%20%20%5C%5C%5C%5C%26%5C%5Copbot%20%5C%5Cend%7Baligned%7D%20%5C%5CKS%5Cn%20%20%5C%5Cbegin%7Baligned%7D%20%20%5C%5Coptop%5C%5C%5C%5C%20%20%20%20%20%20%20%20%20%20%5E%7B%5E%7B%231%7D%7D_%7B_%7B%231%7D%7D%20%5C%5Ctextrm-%5C%5C%5C%5C%20%5C%5Copbot%20%5C%5Cend%7Baligned%7D%5Cn%20%20%5C%5Cbegin%7Baligned%7D%20%26%5C%5Coptop%5C%5C%5C%5C%26%5C%5Ctextrm-%20%5E%7B%5E%7B%232%7D%7D_%7B_%7B%232%7D%7D%20%20%20%20%20%20%20%20%20%5C%5C%5C%5C%26%5C%5Copbot%20%5C%5Cend%7Baligned%7D%5Cn%7D%5Cn%5C%5Cbegin%7Bgathered%7D%5Cn%20%20%5C%5Cmathclap%7B%5C%5Ctextsf%7Bdisplaystyle%7D%7D%20%5C%5CKL%5C%5CKS%5C%5CKL%5C%5Ckern1pt%5Cn%20%20%5C%5Cmathclap%7B%5C%5Ctextsf%7Btextstyle%7D%7D%20%20%20%20%5C%5CKL%5C%5CKS%5C%5CKL%5C%5Ckern1pt%5Cn%20%20%5C%5Cmathclap%7B%5C%5Ctextsf%7Bscriptstyle%7D%7D%20%20%5C%5CKL%5C%5CKS%5C%5CKL%5C%5Ckern1pt%5Cn%20%20%5C%5Cmathclap%7B%5C%5Ctextsf%7Bscriptscriptstyle%7D%7D%20%5C%5C%5C%5C%5Cn%20%20%5C%5Coptest%7B%5C%5CbigE%20%20%20%20%20%20%20%20%20%5E%7Bn-1%7D_%7Bk%3D0%7D%5C%5Csfi%7D%7B%5C%5Csum%20%20%20%20%20%20%20%20%20%5E%7Bn-1%7D_%7Bk%3D0%7D%20%5C%5Csfi%7D%5C%5C%5C%5C%5B-2em%5D%5Cn%20%20%5C%5Coptest%7B%5C%5CbigE%20%20%5C%5Climits_%7Bk%3D0%7D%5E%7Bn-1%7D%5C%5Csfi%7D%7B%5C%5Csum%20%20%5C%5Climits_%7Bk%3D0%7D%5E%7Bn-1%7D%20%5C%5Csfi%7D%5C%5C%5C%5C%5B-1.5em%5D%5Cn%20%20%5C%5Coptest%7B%5C%5CbigE%5C%5Cnolimits_%7Bk%3D0%7D%5E%7Bn-1%7D%5C%5Csfi%7D%7B%5C%5Csum%5C%5Cnolimits_%7Bk%3D0%7D%5E%7Bn-1%7D%20%5C%5Csfi%7D%5C%5C%5C%5C%5Cn%5C%5Cend%7Bgathered%7D%5Cn%22%7D)
but this:
```tex
\DeclareMathOperator\exists_{k=0} ^{n-1}
```
glitches out like this:
![MathOp bad](https://user-images.githubusercontent.com/5026892/66545242-1e6c2d00-eaef-11e9-89c6-64ab46fafe2f.png)

I tried this in LaTeX, and it renders correctly with whitespace there. I can't think of a good workaround, but it isn't super important, and maybe I should just go try getting KaTeX updated in Markdown Preview Enhanced so I can use `\operatorname*`!

**Comment by edemaine** [comment]
@JohnTasto Wow, that's an impressive amount of macro trickery, especially impressive given KaTeX's limited `\def` support! Nice to see `\@ifnextchar` in action.

I believe the issue with spaces is #924, which @ylemkimon is working on in #2085, but it might be something specific to `\@ifnextchar`.  I should take a look at it.

But wow, you're right that `\operatorname*` can do what you want (provided you upgrade), thanks to @ronkok's recent implementation of it.  Here's an example:

```latex
\operatorname*{\mathchoice{\huge \exists}{\large \exists}{\exists}{\exists}}_x^y 
\textstyle
\operatorname*{\mathchoice{\huge \exists}{\large \exists}{\exists}{\exists}}_x^y 
```
![image](https://user-images.githubusercontent.com/2218736/66588147-d33b3400-eb59-11e9-83b4-0f845fef4ddb.png)

**Comment by JohnTasto** [comment]
@edemaine It was a fun puzzle to work out at least. At some point I want to try bracket matching - I just need to improvise a counter somehow. Now that you've fixed how `/@ifnextchar` handles spaces, I think it's possible.

I don't think there are any bugs here now; should I close this issue? Do you close it? Thank you for all of your help.

**Comment by edemaine** [comment]
Yep, I was going to suggest closing.  However, it might be worth opening a feature request for `\if@display` -- what do you think?  While `\operatorname*` does what you want here, it seems like it might be handy, given how it behaves better at the macro level.

What do you mean by "bracket matching"?  Something like #806?  We really ought to implement counters (#2121) so that you don't have to improvize! (though it does make for a fun puzzle)

**Comment by JohnTasto** [comment]
@edemaine Yes, kind of like that, but I often like to manually size them. I was also thinking about coloring them to help visually when they get cluttered, inspired by [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2). I don't mind annotating the opening bracket, but I'd like it to also apply to the matching closing bracket automatically. It would need to count up for each nested opening bracket and then back down for closing brackets to find the matching one. I think it's possible without a counter, just log n macros for a maximum nest depth n. I'm not sure it will work if the brackets span any `&`s though.

As for `\if@display`, I am nowhere near a La/Tex expert, so I don't even know what all features are missing. I'm all for any additional macro capabilities though, and that one sounds pretty useful. I'll definitely be picking up a copy of the TexBook after perusing the pdf you linked - way better than trying to piece things together from blogs and Q/A sites!
