### ISSUE TITLE
\cr and \newline should not take an optional size argument

### ISSUE THREAD

**Issue by ylemkimon** [KaTeX/KaTeX#2119]
**Describe the bug:**
```latex
\begin{matrix}
  a&b \cr[10px]
  c&d
\end{matrix}
a\newline[10px]b
```

**Expected behavior:**
`\cr` and `\newline` should not take an optional size argument

**Comment by edemaine** [comment]
Somehow I thought that `\\` was macroed to `\cr` in an array environment, but it turns out it's macroed to `\@arraycr` which does `*` and `[` processing.  Good catch!

```latex
\def\array{......\let\\\@arraycr.......}
\def\@arraycr{%
  ${\ifnum0=`}\fi\@ifstar\@xarraycr\@xarraycr}
\def\@xarraycr{\@ifnextchar[\@argarraycr{\ifnum0=`{\fi}${}\cr}}
\def\@argarraycr[#1]{%
  \ifnum0=`{\fi}${}\ifdim #1>\z@ \@xargarraycr{#1}\else
   \@yargarraycr{#1}\fi}
```

**Comment by ronkok** [comment]
Our documentation says that 

> Acceptable line separators include: `\\`, `\cr`, `\\[distance]`, and `\cr[distance]`.

Not only that, but for some time the auto-render extension had a bug that prevented `\\[distance]` from working. So `\cr[distance]` was the *only* row-spacing method that auto-render users could use. 

We can be confident that this change will break some existing pages. Is it really worth it?

**Comment by edemaine** [comment]
Good point. One option is to put it in `strict`, so by default it incurs a warning, which is easily hidden. This could be nice for those trying to dump their code into LaTeX, which is one of the main reasons for `strict`.

**Comment by hudakh** [comment]
The documentation hasn't been updated to say that the optional size argument is no longer allowed.
