### ISSUE TITLE
\boxed box does not change with text color.

### ISSUE THREAD

**Issue by willymcallister** [KaTeX/KaTeX#2128]
> Before reporting a bug
- [ DONE ] Check [common issues](https://katex.org/docs/issues.html).
- [ DONE ] Check the bug is reproducible in [the demo](https://katex.org).
- [ DONE ] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
Boxed renders only in black, regardless of text color.

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
$\boxed{v = \text V_0 \cos \omega_\circ t}$
```

**Expected behavior:**
The color of the box should be the same as the color of the rendered formula. This becomes apparent when I switch my site to dark mode. The text goes to silver but the box stays black. 

Visit: https://spinningnumbers.org/a/lc-natural-response-derivation.html
Click on the DARK button at the top right of the title bar to enter Dark mode.
Then search for "Lots of things cancel" to see the boxed formula. 
Or, open this link to visit the same place:
https://spinningnumbers.org/a/lc-natural-response-derivation.html#voltage

**Screenshots:**

<img width="534" alt="Screen Shot Light" src="https://user-images.githubusercontent.com/17035787/67055016-5aa91a00-f0fb-11e9-9b2e-c0ce0783a73c.png">

<img width="532" alt="Screen Shot Dark" src="https://user-images.githubusercontent.com/17035787/67013840-a41c4980-f0a8-11e9-8370-79da9c32736c.png">

**Environment (please complete the following information):**
 - KaTeX Version: "0.10.0",
 - Device: Desktop
 - OS: MacOS Mojave 10.14.6
 - Browser: Chrome
 - Version:  77.0.3865.120 (Official Build) (64-bit)

**Comment by edemaine** [comment]
Thanks for the report!

For what it's worth, LaTeX color changing has the intended behavior:
```latex
\color{green} \boxed{hi}
```
![image](https://user-images.githubusercontent.com/2218736/67055681-0ca20f80-f117-11e9-9192-567611b9d259.png)

It looks like we could replace the explicit `color: green; border-color: green` produced by this code with `color: inherit; border-color: inherit` and it would work in the case of CSS overriding `color`.  @ronkok, can you think of any downsides of this?

**Comment by ronkok** [comment]
No objections. We want to make sure that `\color` takes precedence over any text color inherited from the HTML page, but that should fall into place if we just change the CSS for `fbox`. `\color` is applied inline so it will have higher precedence. 

I'll work up a PR.
