### ISSUE TITLE
How to align over multiple expressions

### ISSUE THREAD

**Issue by HughGrovesArup** [KaTeX/KaTeX#2129]
More of a help request than a bug / issue. Apologies if there is another forum I should be asking this on.

I'm trying to align multiple equations on a page. Sometimes these equations are separated by explanatory text and so I can't use \being{aligned}. Can anyone suggest a way to achieve this? They are all of a "simple" format i.e.

a = b + c
Some explanatory text, but could be large chunks of HTML like images.
f_ckp = e * j

(I would like the equations aligned at the equals!)

**Comment by edemaine** [comment]
This is ugly, but I think the best way (even in LaTeX) is something like this:

```latex
$$\phantom{f_ckp}\mathllap{a} = b + c$$

$$f_ckp = \mathrlap{e * j}\phantom{b+c}$$
```

See https://katex.org/docs/supported.html#overlap-and-spacing for details on spacing commands.

**Comment by HughGrovesArup** [comment]
Thanks for the reply. In actuality my layout is not so simple, could be many (hundreds even) of seperate equations on a page.

My current solution is to break each equation into two parts using HTML and left / right align them next to each other (like below):

[      a][= b + c              ]
[Some text inbetween  ]
[  f_ck][= e * j                ]

This almost works until you have a "tall" equation like \frac{x}{y} as the baseline of what goes before and comes after breaks. Maybe I could vphantom my equations to get the baseline of the symbol before the equals correct...

**Comment by edemaine** [comment]
You could also do something like `\hspace{1in}\mathllap{...} =` where `1in` is designed to be larger than any left-hand side, to avoid embedding some formulas within others.

One other weird HTML solution would be to use a table, and for "Some text inbetween" do a multicolumn cell...  Are you using `vertical-align: baseline`? I would have expected that to vertically line up the two halves...

**Comment by mbourne** [comment]
@HughGrovesArup  I use ASCIIMath for math input, so have never had the luxury of using LaTeX-based methods for aligning equations.

My solution is to find how far (in pixels) the first equal sign is from the left margin of the element, then indent all the following subsequent lines of the math that same distance.

Each block of math that I want to do this for is contained in a &lt;div&gt; with class name "alignEquals". I loop over those divs  (`selector[i]`) and then loop over the &lt;p&gt; tags (`ps`) containing math within those divs.

    ps = selector[i].getElementsByTagName('p');
    for(k=0;k<ps.length;k++) {
      if(k == 0) {
        if(ps[0].getElementsByClassName('mrel')[0]) {
          eqSignPos = ps[0].getElementsByClassName('mrel')[0].offsetLeft;
        }
      } else if (ps[k].innerHTML.indexOf("=") > 0) {
        ps[k].style.marginLeft = eqSignPos+"px";
      }
    }

You can see it in action on this page: https://www.intmath.com/complex-numbers/12-parallel-ac-circuits.php in the "Answer" drop-down for Example 1. (You'll see text intermingled within the aligned equations in the portion after "Now we convert everything...".)

I haven't found any issues with "tall" equations using this technique and there have been no noticeable performance issues.

My requirement has only been for equations with unchanging left hand sides, like:

a = b + c
= 2 + 3
= 5

In your case, you could modify this approach to loop through once to find the "most left" equal sign in your block (it would be the second one in the example you gave), keeping track of the indents required for all lines of the block in an array, then loop through again to indent everything properly.

**Comment by HughGrovesArup** [comment]
Ah yes I'm another engineer trying to show line-by-line working out of examples.

I tried modifying from vertical-align top to vertical-align baseline, but because my format is similar to mbourne's the result is not as desired.

vertical-algin: baseline
![image](https://user-images.githubusercontent.com/40033911/67190961-c5eb3880-f3e8-11e9-964b-25de8257e117.png)

vertical-align: top
![image](https://user-images.githubusercontent.com/40033911/67191054-e3b89d80-f3e8-11e9-8478-d7ec7106dc38.png)

I am effectively doing the table & left-indenting trick - I have several inline-block elements with fixed widths:

[left-margin 20%][description 20%][symbol 10%][working out 50%]
[left-margin 20%][some text 60%][right-margin 20%]
[left-margin 20%][description 20%][symbol 10%][working out 50%]

I had thought that if I included a \vphantom of the first line of the working-out it would solve my issues, but it doesn't seem to be working.

My output appears in a few different places so getting the appropriate javascript on all of the endpoints is a bit problematic.

I've created a quick codepen for my situation. It almost works apart from the baselines being messed up for the "tall" equations. I can probably live with it if I have to, would be nice if it was perfect though!

https://codepen.io/HughGrovesArup/pen/oNNBvdN

**Comment by mbourne** [comment]
Percentage widths would be problematic for visitors on a phone:

![image](https://user-images.githubusercontent.com/7541940/67204650-9405c080-f440-11e9-800d-b800297cbdf8.png)

Actually, if the left-hand variable is different, it implies it's a new expression, and it would seem OK if the equals are not aligned (these are normal `\aligned` expressions):

![image](https://user-images.githubusercontent.com/7541940/67204554-53a64280-f440-11e9-8c58-0c2bd9fa4b11.png)

You could get away with using blockquote, depending on the width of your left hand side. I feel it would be less hassle and look better than your "tables" approach.

**Comment by edemaine** [comment]
Regarding vertical alignment, it seems like you'd benefit from using multiple rows in your table (equivalent), one for each right-hand side, instead of using `{aligned} ` which will indeed make vertical alignment difficult.

**Comment by HughGrovesArup** [comment]
Thanks @edemaine - that unlocked it for me. Had become so used to using \aligned I didn't think to ditch it!

**Comment by kevinbarabash** [comment]
You might be able to get the vertical alignment looking better when using tables by using a `\phantom` and `\lap` with a copy of the expression from the right column in the left column of the first row.
