### ISSUE TITLE
Adding an option for user-defined snippets

### ISSUE THREAD

**Issue by themattgabriel** [KaTeX/KaTeX#2150]
**Describe the solution you'd like:**
- The user would be more efficient and be able to define snippets to save time on repetitive tasks such as adding abbreviations or definitions
- The user would be able to add user-defined snippets by simply going to the menu bar under Tools.
- The user would be able to edit a JSON file to add the snippets such as this sample format from VS Code:
    ```jsonc
	// Place your snippets for markdown here. Each snippet is defined under a snippet name and has a prefix, body and 
	// description. The prefix is what is used to trigger the snippet and the body will be expanded and inserted. Possible variables are:
	// $1, $2 for tab stops, $0 for the final cursor position, and ${1:label}, ${2:another} for placeholders. Placeholders with the 
	// same ids are connected.
	// Example:
	// "Add a definition": {
	// 	"prefix": "def",
	// 	"body": [
	// 		"${1:WordToDefine}';",
	// 		"~ ${2:Definition}"
	// 	],
	// 	"description": "Instantly add template for definitions"
	// }
    ```

**Describe alternatives you've considered:**
Boostnote has this feature but adding the snippet is integrated in the app instead of being a JSON file that can be edited.

**Additional context:**
Boostnote snippet gif

![](https://user-images.githubusercontent.com/1447602/43974392-485b9880-9c8f-11e8-9215-a91a6001b504.gif)

**Comment by ylemkimon** [comment]
TeX macros are supported by KaTeX, which can be passed as an object to `options`.
