### ISSUE TITLE
possible to implement <a href...-Tag in \\text{}?

### ISSUE THREAD

**Issue by xedex1111** [KaTeX/KaTeX#2152]
Hi. Want to ask if it is possible to include an <a href"#bla">link to</a> in an text{} function?
Example:

    span = kapitel_3_6_11; katex.render('||\\vec{a} \\times \\vec{b}|| \\cdot || \\vec{c} || = ||\\vec{a}|| \\cdot \\underbrace{||\\vec{b}|| \\cdot sin(\\varphi)}_{=b_a \\text{<a href="#skriptum_kapitel_3_2">siehe Skalarprodukt</a>}} \\cdot ||\\vec{c}|| ', span);

thx and br

**Comment by edemaine** [comment]
KaTeX [supports LaTeX's`\href`](https://katex.org/docs/supported.html#html) which will let you make links. It requires [the `trust` setting](https://katex.org/docs/options.html) to be set to something other than the default. For example:

```latex
span = kapitel_3_6_11; katex.render('||\\vec{a} \\times \\vec{b}|| \\cdot || \\vec{c} || = ||\\vec{a}|| \\cdot \\underbrace{||\\vec{b}|| \\cdot sin(\\varphi)}_{=b_a \\text{\\href{#skriptum_kapitel_3_2}{siehe Skalarprodukt}}} \\cdot ||\\vec{c}|| ', span, {trust: true});
```

[Demo](https://katex.org/?data=%7B%22displayMode%22%3Atrue%2C%22leqno%22%3Afalse%2C%22fleqn%22%3Afalse%2C%22throwOnError%22%3Atrue%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22warn%22%2C%22trust%22%3Atrue%2C%22macros%22%3A%7B%22%5C%5Cf%22%3A%22f(%231)%22%7D%2C%22code%22%3A%22%7C%7C%5C%5Cvec%7Ba%7D%20%5C%5Ctimes%20%5C%5Cvec%7Bb%7D%7C%7C%20%5C%5Ccdot%20%7C%7C%20%5C%5Cvec%7Bc%7D%20%7C%7C%20%3D%20%7C%7C%5C%5Cvec%7Ba%7D%7C%7C%20%5C%5Ccdot%20%5C%5Cunderbrace%7B%7C%7C%5C%5Cvec%7Bb%7D%7C%7C%20%5C%5Ccdot%20sin(%5C%5Cvarphi)%7D_%7B%3Db_a%20%5C%5Ctext%7B%5C%5Chref%7B%23skriptum_kapitel_3_2%7D%7Bsiehe%20Skalarprodukt%7D%7D%7D%20%5C%5Ccdot%20%7C%7C%5C%5Cvec%7Bc%7D%7C%7C%22%7D):

![image](https://user-images.githubusercontent.com/2218736/68697838-a65db080-054d-11ea-85d6-254001450001.png)

**Comment by xedex1111** [comment]
big thx!
