### ISSUE TITLE
Support for \noindent

### ISSUE THREAD

**Issue by fabiontop** [KaTeX/KaTeX#2159]
> Before requesting a feature, please search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the solution you'd like:**
Support the \noindent command.

**Link to or name of a (La)TeX package that provides the same feature:**
It's a basic Latex command

**Comment by edemaine** [comment]
@fabiontop KaTeX currently supports only math mode processing (and text mode within math mode, but no vertical mode), so `\noindent` doesn't really make sense.  See e.g. #604.
