### ISSUE TITLE
$symbol match error

### ISSUE THREAD

**Issue by lovebigbird** [KaTeX/KaTeX#2163]
If I write the formula of two $symbol packages in succession, it will be wrong. I guess it conflicts with the matching of double $$symbols。

like this : $\frac{4}{5}$$\frac{4}{5}$

**Comment by kevinbarabash** [comment]
It is configurable using the `delimiters` in the `options` object passed to `renderMathInElement`.  Please see the `delimiters` section in https://katex.org/docs/autorender.html for more details.

**Comment by edemaine** [comment]
Duplicate of #1984 and #1830. There is not an easy fix I know of, other than removing support for `$$...$$`. So something we should fix in auto-render, but we don't need a third issue tracking it.
