### ISSUE TITLE
Parsing `\Huge{x}\small{x}` puts `small` sizing node in body of `Huge` sizing node

### ISSUE THREAD

**Issue by ktraunmueller** [KaTeX/KaTeX#2164]
**Describe the bug:**

It seems there's a bug in the code that parses sizing functions (`defineFunction({type: "sizing", ...` in `sizing.js`).

The test suite (`katex-spec.js`) has a test 
```
describe("A sizing parser", function() {
    const sizeExpression = r`\Huge{x}\small{x}`;
    ...
    it("should produce a sizing node", function() {
        const parse = getParsed(sizeExpression)[0];  // gives unexpected result; see below
        ...
    });
});
```

Running the test and inspecting the body of `parse` gives an unexpected result – the body contains two nodes:
- an `ordgroup` node for the first `x` (which is expected)
- a `sizing` node representing the `\small{x}`  part of the expression (which is unexpected)

See the screenshot of the debugger at this point further down.

**To Reproduce:**

1. Put a breakpoint in the `A sizing parser...should produce a sizing node` test and run the tests in the debugger:

<img width="464" alt="Screenshot 2019-12-03 at 21 28 50" src="https://user-images.githubusercontent.com/650763/70087095-eaefdf80-1613-11ea-9577-8df62b0b71bf.png">

**Expected behavior:**

The body of the first `sizing` node should contain only the `ordgroup` node for the first `x`. The second `sizing` node should not be part of the body of the first `sizing` node.

**Screenshots:**

<img width="1647" alt="Screenshot 2019-12-03 at 21 08 17" src="https://user-images.githubusercontent.com/650763/70086440-b3ccfe80-1612-11ea-82b4-3121fbd8b8b2.png">

**Environment:**
 - KaTeX Version: 0.11.1
 - OS: macOS 10.14
 - VS Code

**Comment by edemaine** [comment]
@ktraunmueller If I'm understanding correctly, that is expected behavior. `\Huge{x}\small{x}` is equivalent to `\Huge x \small x` which is equivalent to `{\Huge x {\small x}}` in LaTeX.  `\Huge` and `\small` are state-changing operators with zero arguments, *not* single-argument macros.

Perhaps you meant `{\Huge x}{\small x}`, which parses as you wanted.

**Comment by ktraunmueller** [comment]
@edemaine Got it, thanks a lot for the explanation.
