### ISSUE TITLE
mhchem for server-side Katex

### ISSUE THREAD

**Issue by offbynull** [KaTeX/KaTeX#2168]
**Is your feature request related to a problem? Please describe.**
As far as I'm aware, there's no way to enable Katex's mhchem implementation when rendering server-side (in NodeJS). Some of us want to use this extension outside of the browser.

**Describe the solution you'd like:**
I'm not sure what the appropriate solution is. It sounds like what needs to happen is...
1. skip __defineMacro() invocations if running outside of a browser.
2. provide a streamlined way of injecting the relevant macros into KatexOptions when invoking renderToString().

```js
const out = katex.renderToString('...', {
    macros: {
        "\\ce": function(context) {
            return chemParse(context.consumeArgs(1)[0], "ce")
          },
        "\\pu": function(context) {
            return chemParse(context.consumeArgs(1)[0], "pu");
          },
        "\\tripledash": "{\\vphantom{-}\\raisebox{2.56mu}{$\\mkern2mu"
          + "\\tiny\\text{-}\\mkern1mu\\text{-}\\mkern1mu\\text{-}\\mkern2mu$}}"
    }
})
```

**Link to or name of a (La)TeX package that provides the same feature:**
N/A

**Describe alternatives you've considered:**
So far all I've tried is forking mhchem.js. 

**Additional context:**
N/A

**Comment by edemaine** [comment]
Admittedly this isn't well-documented, but I figured out how to load katex + mhchem in Node:

```shell
$ npm install katex
$ node
```

```node
> katex = require('katex')
> require('katex/dist/contrib/mhchem.js') // modifies katex module
> katex.__parse("\\ce{CO2 + C -> 2 CO}")
[
  {
    type: 'ordgroup',
    mode: 'math',
    loc: SourceLocation { lexer: [Lexer], start: 0, end: 87 },
    body: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    semisimple: undefined
  }
]
```

Tested on Node 12.13.1, but should work on any version.
