### ISSUE TITLE
PyQt5's QWebEngineView doesn't like KaTeX so I can't use it

### ISSUE THREAD

**Issue by enjoysmath** [KaTeX/KaTeX#2170]
To Reproduce:

Install Python 3.8.0 64-bit.  Set path so 3.8 is first when you do
where python
pip install PyQt5==5.13
pip install PyQtWebEngine

Errors:
`[22056:21456:1210/133403.757:ERROR:mf_helpers.cc(14)] Error in dxva_video_decode_accelerator_win.cc on line 513
[22056:13664:1210/133404.067:ERROR:cache_util_win.cc(19)] Unable to move the cache: 0
[22056:13664:1210/133404.067:ERROR:cache_util.cc(140)] Unable to move cache folder C:\Users\FruitfulApproach\AppData\Local\python\QtWebEngine\Default\GPUCache to C:\Users\FruitfulApproach\AppData\Local\python\QtWebEngine\Default\old_GPUCache_000
[22056:13664:1210/133404.067:ERROR:disk_cache.cc(184)] Unable to create cache
[22056:13664:1210/133404.067:ERROR:shader_disk_cache.cc(622)] Shader Cache Creation failed: -2
[22056:13664:1210/133404.285:ERROR:cache_util_win.cc(19)] Unable to move the cache: 0
[22056:13664:1210/133404.285:ERROR:cache_util.cc(140)] Unable to move cache folder C:\Users\FruitfulApproach\AppData\Local\python\cache\QtWebEngine\Default\Cache to C:\Users\FruitfulApproach\AppData\Local\python\cache\QtWebEngine\Default\old_Cache_000
[22056:13664:1210/133404.285:ERROR:disk_cache.cc(184)] Unable to create cache
js: Uncaught SyntaxError: Invalid or unexpected token`

These are not Python exeptions, they're underlying JS exceptions generated by whatever QWebEngineView uses to render JS pages.

Minimal code:
```
from PyQt5.QtWidgets import (QGraphicsProxyWidget, QMainWindow,
                             QGraphicsView, QGraphicsScene,
                             QGraphicsObject, QGraphicsItem, QWidget,
                             QHBoxLayout, QApplication)
from PyQt5.QtCore import Qt, QUrl
from PyQt5.QtGui import QBrush
from PyQt5.QtWebEngineWidgets import QWebEngineView
import sys

class A(QGraphicsObject):
   def __init__(self, url=None):
      super().__init__()
      self.web_view = QWebEngineView()
      if url is None:
         url = QUrl(url)
         self.web_view.load(url)
      self.proxy = QGraphicsProxyWidget(parent=self)
      self.proxy.setWidget(self.web_view)
      self.web_view.show()
      
   def boundingRect(self):
      return self.childrenBoundingRect()
   
   def paint(self, painter, option, widget):
      pass

if __name__ == '__main__':
   app = QApplication([])
   
   window = QMainWindow()
   window.show()
   view = QGraphicsView()
   scene = QGraphicsScene()
   scene.setBackgroundBrush(QBrush(Qt.gray))
   view.setScene(scene)
   html = '''
   <!DOCTYPE html>
   <!-- KaTeX requires the use of the HTML5 doctype. Without it, KaTeX may not render properly -->
   <html>
       <head>
           <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.10.0-rc.1/dist/katex.min.css" integrity="sha384-D+9gmBxUQogRLqvARvNLmA9hS2x//eK1FhVb9PiU86gmcrBrJAQT8okdJ4LMp2uv" crossorigin="anonymous">
   
           <!-- The loading of KaTeX is deferred to speed up page rendering -->
           <script src="https://cdn.jsdelivr.net/npm/katex@0.10.0-rc.1/dist/katex.min.js" integrity="sha384-483A6DwYfKeDa0Q52fJmxFXkcPCFfnXMoXblOkJ4JcA8zATN6Tm78UNL72AKk+0O" crossorigin="anonymous"></script>
   
           <!-- To automatically render math in text elements, include the auto-render extension: -->
           <script defer src="https://cdn.jsdelivr.net/npm/katex@0.10.0-rc.1/dist/contrib/auto-render.min.js" integrity="sha384-yACMu8JWxKzSp/C1YV86pzGiQ/l1YUfE8oPuahJQxzehAjEt2GiQuy/BIvl9KyeF" crossorigin="anonymous"
           onload="renderMathInElement(document.body);"></script>
       </head>
       <body>
   
           <p id="IdentificatorForElement"></p>
   
           <script>
               katex.render("C", document.getElementById('IdentificatorForElement'), '
                   throwOnError: false
               });
           </script>
       </body>
   </html>
   '''
   #a = A("http://www.google.com")
   a = A()
   a.web_view.setHtml(html)
   scene.addItem(a)
   window.setCentralWidget(view)
   a.web_view.renderProcessTerminated.connect(a.update)   
   sys.exit(app.exec_())
```

Well, my goal is to get a QWebEngineView rendering LaTeX inside of a QGraphicsObject (it's parent item in the QGraphicsScene).  Uncomment `a = A("http://www.google.com")` and comment out the next two lines to demonstrate that QWebEngineView works for a basic webpage like google (which probably includes much JS).  Now running with the original code above, you get all these underlying JS errors.  And no rendered LaTeX shows up. 

Event minus the QGraphicsObject, just calling `web_view.show()` to display the web view, results in these errors and no LaTeX rendered.

**Comment by edemaine** [comment]
I'm not familiar with `QWebEngineView` so can't guess what the problem is here.  I observe [similar error messages in some other (unrelated) issues](https://github.com/sokolovstas/SublimeWebInspector/issues/113).  I doubt this issue is related to KaTeX directly, but it might be a limitation of `QWebEngineView` that you're running into when trying to run KaTeX.

I do wonder whether you'd rather convert the LaTeX into HTML before calling `QWebEngineView` at all, using `katex.renderToString` instead of `katex.render`.  But that would require some other interface to JavaScript, which might not be simpler.

**Comment by kevinbarabash** [comment]
In the code you pasted I see there's a stray single quote at the end of the `katex.render` line:
```
katex.render("C", document.getElementById('IdentificatorForElement'), '
                   throwOnError: false
               });
```
That may be causing the issue.  You may also want to check if your toolchain has an option to provide more info in the stack trace.  `Unable to create cache js: Uncaught SyntaxError: Invalid or unexpected token` isn't much help without know the file and location of the unexpected token.
