### ISSUE TITLE
Server-side rendering guide needs more clarification

### ISSUE THREAD

**Issue by ipelekhan** [KaTeX/KaTeX#2176]
Hi, I have checked docs several times, but still can't figure out next questions: 

1. Do I need to include `fonts` and `katex.js` files if I am doing server side rendering (i.e. `renderToString`)? I am including `katex.min.css` file and it looks fine for simple examples, however not sure if it's enough for complex math stuff.
1. Is it possible to completely inline styles while rendering server side (like [shiki](https://github.com/octref/shiki) does)?

Thanks in advance for the answer.

**Comment by ylemkimon** [comment]
- Fonts should be included on the client side. Therefore, complete inlining is not possible at this time. ([HTML style attribute doesn't support `@font-face`](https://stackoverflow.com/questions/8749225/loading-an-external-font-via-inline-css))
- `katex.css` should also be included on the client side. 
- `katex.js` is not needed on the client side if the rendering is done on the server side.
