### ISSUE TITLE
Horizontal line cannot be displayed on the mobile terminal.

### ISSUE THREAD

**Issue by Sun-ZhenXing** [KaTeX/KaTeX#2179]
It may be that the support of mobile browser is not good, and the Fraction cannot be displayed normally. For example **"\frac{1}{x}"**. But the browser is lastest. Is there a solution?

**Comment by ylemkimon** [comment]
Could you let us know the version of the browser and KaTeX?

**Comment by Sun-ZhenXing** [comment]
The browser is Huawei 10.8.5.4721. Tatex is the latest version 0.11.1
![image](https://user-images.githubusercontent.com/44517244/71776116-c8f8cc80-2fc6-11ea-963b-989b0935ae92.png)
![image](https://user-images.githubusercontent.com/44517244/71776120-d4e48e80-2fc6-11ea-8454-7af8a475e821.png)
This is what it looks like when running on Edge:
![image](https://user-images.githubusercontent.com/44517244/71776129-0e1cfe80-2fc7-11ea-81d0-ecde51f8b943.png)
I am an amateur project player. This is a math calculation website of mine, but I'm sorry, it can only run on my PC at present. I'm going to use Python as a math website.
Can't this product be used for browsers like Huawei or 360?

**Comment by ylemkimon** [comment]
I can't seem to find Huawei Browser 10.8.5.4721. Could you let us know the [user agent string](https://www.google.com/search?q=what+is+my+user+agent)? Also, does [katex.org](katex.org) work on your browser?

**Comment by Sun-ZhenXing** [comment]
![image](https://user-images.githubusercontent.com/44517244/72128850-2f0e9680-33af-11ea-9679-96a2807b57f1.png)
Sorry, katex.org can't run normally on Huawei mobile.
Because Huawei has many users in China, I hope katex can support Huawei browser.
Other problems have been eliminated. If it still doesn't work, I will analyze the source code.
Thank you for your help.

**Comment by Sun-ZhenXing** [comment]
Find bug.
