### ISSUE TITLE
Nested macro definitions

### ISSUE THREAD

**Issue by willisk** [KaTeX/KaTeX#2182]
```
$$
\gdef{\test}#1{ test(#1) }
\gdef{\nest}#1{ nest(\test{#1}) }
\nest{T}
$$
```
Result: error
Expected: nest(test(T))

A lot of my macros use nested macro calls. It isn't too much of an issue, since I can manually evaluate the nested expressions. This would be nice to have automated, as changing one macro means changing all the others again as well.
Here an actual example of where I would want this:

```
$$
\newcommand{\pd}[2]{\frac{\partial #1}{\partial #2}}
\newcommand{\jacobian}[4]{
    \begin{matrix}
        \pd{#1_1}{#2_1} & \cdots & \pd{#1_1}{#2_#4} \\
        \vdots & \ddots & vdots \\
        \pd{#1_#3}{#2_1} & \cdots & \pd{#1_#3}{#2_#4}
    \end{matrix}
}
\jacobian{f}{x}{m}{n}
$$
```

And a small side bug I came across:
```
$$
\gdef{\test}#1{A_{#1}}
$$
```

Throws an error, whereas this works fine (including whitespace):
```
$$
\gdef{\test}#1{A_{ #1}}
$$
```

**Comment by edemaine** [comment]
@willisk Those examples should all work. The issue you're running into seems to be specific to your environment (or you're using an old version of KaTeX).  Here are screenshots of them working fine on [the demo page](https://katex.org/):

![image](https://user-images.githubusercontent.com/2218736/71642250-62964600-2c76-11ea-8a4a-4af32092cff3.png)

![image](https://user-images.githubusercontent.com/2218736/71642271-b4d76700-2c76-11ea-931c-73f1bfcebc45.png)

![image](https://user-images.githubusercontent.com/2218736/71642259-95d8d500-2c76-11ea-9bbb-84aa0455511f.png)

How are you using KaTeX?

**Comment by willisk** [comment]
@edemaine Sorry, I should have tried using the demo page before posting an issue. I think I was using v0.10. Thanks for clearing things up!

**Comment by edemaine** [comment]
Glad it's working now!
