### ISSUE TITLE
\right{...} causes circular structure in error reporting

### ISSUE THREAD

**Issue by edemaine** [KaTeX/KaTeX#2184]
**Describe the bug:**
Testing on `katex.org`, here is a minimal bad example based on #2174:
```latex
\newcommand{\myright}[1]{\right{#1}}
\cos\left(x\myright)
```
Error:
> Converting circular structure to JSON --> starting at object with constructor 't' | property 'settings' -> object with constructor 't' | property 'macros' -> object with constructor 'Object' | ... | property 'loc' -> object with constructor 't' --- property 'lexer' closes the circle

**Expected behavior:**
Unless I'm missing something, `\myright` should behave like `\right`.

**Additional context:**
The following code works fine, so it has to do with macro arguments.
```latex
\newcommand{\myright}{\right}
\cos\left(x\myright)
```
Perhaps #2085 fixes this bug, but I haven't checked. If so, we should add a test.

**Comment by ylemkimon** [comment]
`Converting circular structure to JSON` error is caused when logging the error and the actual error is `Invalid delimiter`. `\right` doesn't accept a braced argument, which is consistent with LaTeX, so `\myright` should be `\right#1`.
