### ISSUE TITLE
does not render properly

### ISSUE THREAD

**Issue by hojas** [KaTeX/KaTeX#2185]
> Before reporting a bug
- [ ] Check [common issues](https://katex.org/docs/issues.html).
- [ ] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [ ] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**

does not render properly

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
p\left(\theta, x\right) = \theta^x \left(1 - \theta\right)^\left(1 - x\right), x \in \left\{0, 1\right\}
```

**Expected behavior:**
A clear and concise description of what you expected to happen. KaTeX's general goal is to render as LaTeX does, so if possible, please include a LaTeX rendering. You can obtain one using [QuickLaTeX](https://www.quicklatex.com/).

MathJax renders properly, but Katex not.

**Screenshots:**

![image](https://user-images.githubusercontent.com/4729039/71714329-6083e100-2e48-11ea-8526-80a8cbff196d.png)

**Environment (please complete the following information):**
 - KaTeX Version: [Can be checked via `katex.version`]
 - Device: [e.g. Desktop, iPhone 8]
 - OS: [e.g. Windows 10, iOS 11]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 72]

**Additional context:**
Add any other context about the problem here. If you're using a library to use KaTeX, please include its name and setup.

**Comment by ylemkimon** [comment]
This behavior is consistent with LaTeX, which only takes `\left` as an argument for the superscript. KaTeX currently doesn't support error recovery, which may add missing `{` (#428).

**Comment by edemaine** [comment]
The correct way to write this expression in LaTeX is as follows (note one set of braces added):
```latex
p\left(\theta, x\right) = \theta^x \left(1 - \theta\right)^{\left(1 - x\right)}, x \in \left\{0, 1\right\}
```
Here's how it renders in LaTeX:
![image](https://user-images.githubusercontent.com/2218736/71738719-7633df00-2e25-11ea-8dba-58b11d421d3a.png)
