### ISSUE TITLE
weird math overflow 

### ISSUE THREAD

**Issue by mohanen** [KaTeX/KaTeX#2190]
Some symbols are visible outside the element 

When overflow set to auto in css
![image](https://user-images.githubusercontent.com/20907037/72683339-88d43680-3afc-11ea-9107-672a9a30eb73.png)

When Scrolled to right the = and hat symbol is visible outside the element while the i and . is not
![image](https://user-images.githubusercontent.com/20907037/72683350-97bae900-3afc-11ea-9c47-43e708e3d9a9.png)

**To Reproduce:**
Set Overflow to auto in css 

**Environment (please complete the following information):**
 - KaTeX Version: 0.11.1
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome, Opera
 - Version: Chrome - Chrome - 79, Opera - 66

Only happening in katex, Mathjax was working fine i switched to katex recently

Any work around ?

**Comment by ronkok** [comment]
@mohanen There isn't enough information here to diagnose the underlying problem. If you give us a link to a page where this occurs, we might be able to look in to it in more detail.

**Comment by kevinbarabash** [comment]
That is weird.  Since the container already has `overflow: scroll` set on it, I'd expect this to clip the contents as well which it's doing for everything except for the hat.  Can you post the expression that you're using?  A link to a test page would be even better.
