### ISSUE TITLE
Incorrect rendering of \ce in Ionic alert

### ISSUE THREAD

**Issue by cumpstey** [KaTeX/KaTeX#2191]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
KaTeX markup is rendered incorrectly in an Ionic 4 alert:
![2020-01-19 20_26_38-ionic-v4-11-katex - StackBlitz](https://user-images.githubusercontent.com/4849733/72687878-21b58280-3afa-11ea-943e-9f36dba97212.png)

This appears to be an issue introduced somewhere between Ionic 4.0.0-beta.7 and 4.11.7 - the former looks fine, while the latter shows the issue in the screenshot.

- [StackBlitz of working 4.0.0-beta.7](https://stackblitz.com/edit/ionic-v4-0-katex)
- [StackBlitz of failing 4.11.7](https://stackblitz.com/edit/ionic-v4-11-katex)

**Environment (please complete the following information):**
 - KaTeX Version: 0.11.1
 - Device, OS, Browser: Same in Windows 10 Firefox & Chrome, and Android Chrome.

**Additional context:**
I realise that this issue was made apparent by a change in Ionic rather than in KaTeX, but I think it's more likely to be caused by an issue in KaTeX - possibly requiring styles to be reset on the `.katex` element or similar. I'm happy to open a ticket at Ionic instead/as well, if someone can figure out what's happening, and can show the need for a change on their side.

**Comment by ronkok** [comment]
@cumpstey In the malfunctioning alert box, all inline styles are missing from every element within the alert wrapper. KaTeX sets vertical alignment via calculated numeric values written in the inline styles. No inline styles, no alignment.

Does Ionic purposely remove inline styles inside the alert box?

**Comment by cumpstey** [comment]
Thank you @ronkok - easy to see once it's pointed out, but I didn't spot it. Clearly not a KaTeX issue then, so I'll close this and open with Ionic.
