### ISSUE TITLE
`\cong` has extra trailing space

### ISSUE THREAD

**Issue by JohnTasto** [KaTeX/KaTeX#2199]
The `\cong` relation, ≅, has some extra trailing space compared with `\cong` in official LaTeX and other similar relations in KaTeX.

```latex
\begin{aligned}
  & x \equiv x \\
  & x \cong x \\
  & x \approxeq x \\
\end{aligned}
```

[Live demo](https://katex.org/?data=%7B%22displayMode%22%3Atrue%2C%22leqno%22%3Afalse%2C%22fleqn%22%3Afalse%2C%22throwOnError%22%3Atrue%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22warn%22%2C%22trust%22%3Afalse%2C%22code%22%3A%22%5C%5Cbegin%7Baligned%7D%5Cn%20%20%26%20x%20%5C%5Cequiv%20x%20%5C%5C%5C%5C%5Cn%20%20%26%20x%20%5C%5Ccong%20x%20%5C%5C%5C%5C%5Cn%20%20%26%20x%20%5C%5Capproxeq%20x%20%5C%5C%5C%5C%5Cn%5C%5Cend%7Baligned%7D%22%7D)

KaTeX rendering:
![cong-katex](https://user-images.githubusercontent.com/5026892/74117265-fdcee500-4b6b-11ea-99e3-ec4f612d79d1.png)

QuickLaTeX rendering:
![cong-quicklatex](https://user-images.githubusercontent.com/5026892/74117287-07584d00-4b6c-11ea-9d20-f99905ae4fdc.png)

 - KaTeX Version: 0.11.1
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 79

**Comment by ronkok** [comment]
I can confirm that @JohnTasto is correct. The issue is inside the font. The font glyph for `≅` in font KaTeX_Main-Regular has an advance width of 1 em whereas `=` and `≡` each have an advance width of 0.778 em.

I don't have font skills. Perhaps @ylemkimon or @kevinbarabash may be able to help.

**Comment by ronkok** [comment]
@JohnTasto It would be helpful if you would open this issue in https://github.com/KaTeX/katex-fonts/issues, since that is where the fix must be done.

**Comment by kevinbarabash** [comment]
This should be relatively easy to fix.  Thanks for the report.

**Comment by fefrei** [comment]
Since I ran into the same issue, I took the liberty to report it [in `katex-fonts`](https://github.com/KaTeX/katex-fonts/issues/77) myself.

Thanks for your awesome work 🚀

**Comment by Yue-Zhengyuan** [comment]
The katex-font repository is archived, but the problem of \cong still persists today. Hope that it is not forgotten...
