### ISSUE TITLE
mhchem problems while using vue-katex

### ISSUE THREAD

**Issue by ntyy233** [KaTeX/KaTeX#2203]
Hello Community,

I am using vue-cli as my develop tool. I was trying to use mhchem extension to enter the chemical formulas for my webapp, like the [README](https://github.com/KaTeX/KaTeX/blob/master/contrib/mhchem/README.md) said: "This extension isn't part of core KaTeX, so the script should be separately included. Place it after the line that calls katex.js." I was trying to include 

> <script src="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/contrib/mhchem.min.js"></script>

 in index.html but failed ( I think the problem is because index.html is alive before the components in vue). I am willing to know how/where to include this extension in my webapp? Thanks for replying.

**Comment by edemaine** [comment]
How are you including base KaTeX? Are you using [vue-katex](https://github.com/lucpotage/vue-katex)? If so, it's probably an issue to raise there. If not, you'll need to tell us how you're including base KaTeX.
