### ISSUE TITLE
 Thai language wrong on mobile

### ISSUE THREAD

**Issue by Permpol** [KaTeX/KaTeX#2204]
I have issue thai language wrong on mobile iphone 6s+ and ipad gen7

https://meta.discourse.org/t/discourse-math-plugin/65770/168?u=bank_live

![image](https://user-images.githubusercontent.com/2218736/75380635-607eeb00-58a5-11ea-8637-65b60cb4861d.png)

**Comment by ronkok** [comment]
Probably characters whose Unicode code points are referencing font glyphs that do not exist.

@Permpol Please paste the problem string into a comment here. Not an image of the string but the string itself. Something that we can copy and paste into a text editor. Then we can experiment a little with the CSS.

Does iOS have something like Android Roboto? That is, a font that supposedly contains every glyph?

**Comment by Permpol** [comment]
In Android it work?  I installed New font on iOS not work

**Comment by kevinbarabash** [comment]
@Permpol please copy/paste the text from the example.  It will help us diagnose the issue.
