### ISSUE TITLE
Math show on Title

### ISSUE THREAD

**Issue by Permpol** [KaTeX/KaTeX#2210]
Now Use command show math on title post. It would be great if mathematical results could be displayed on the topic.

**Comment by kevinbarabash** [comment]
@Permpol could you provide more details or an example of what you're looking for?

**Comment by Permpol** [comment]
> @Permpol could you provide more details or an example of what you're looking for?

I mean this

https://meta.discourse.org/t/discourse-math-plugin/65770/101?u=bank_live

**Comment by kevinbarabash** [comment]
I see.  A change would need to be made in the discourse math plugin not in KaTeX.
