### ISSUE TITLE
equation is not rendering

### ISSUE THREAD

**Issue by fbeleznay** [KaTeX/KaTeX#2211]
I know this is not a bug report, but I could not find any other forum to get help. I need to dynamically change text with inline formulas on a webpage. For some reason the following code does not work (it gives the source code on the screen, not the rendered equation). Can someone please help me fix it?

```
<!DOCTYPE html>
<html lang="en">
<head>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css" integrity="sha384-zB1R0rpPzHqg7Kpt0Aljp8JPLqbXI3bhnPWROx27a9N0Ll6ZP/+DiW/UqRcLbRjq" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js" integrity="sha384-y23I5Q6l+B6vatafAwxRu/0oK/79VlbSz7Q9aiSZUvyWYIYsd+qj+o24G5ZU2zJz" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js" integrity="sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI" crossorigin="anonymous"></script>

  <title>Title</title>
</head>
<body>

<div id="instructionContainer">
Some text comes here.
</div>

<script>
  let katexOpts = {
    // ...options...
  };  
  var text = "some text \\(\\sqrt{x}\\) with formula";

  var xx = document.getElementById("instructionContainer");
  xx.innerHTML=text;
  renderMathInElement(xx, katexOpts);
</script>

</body>
</html>
```
**Screenshot**
![Screenshot at 2020-03-05 13-34-30](https://user-images.githubusercontent.com/56488425/75990466-d8c05e80-5eec-11ea-947b-484a2ed95bb2.png)

**Environment (please complete the following information):**
 - KaTeX Version: link to the KaTeX website
 - Device: Desktop
 - OS: Linux mint
 - Browser: Chrome

**Comment by fbeleznay** [comment]
I am not sure how to remove this issue but I found the mistake I made. I did not add "onload" to the auto-renderer script.

**Comment by ronkok** [comment]
Good show fixing your problem.
