### ISSUE TITLE
Netlify setup

### ISSUE THREAD

**Issue by kevinbarabash** [KaTeX/KaTeX#2212]
Currently the Netlify build uses my team.  I think it'd be better if we had our own separate KaTeX Netlify team.  Also, I was thinking we should apply for Netlify's open source plan: https://www.netlify.com/legal/open-source-policy/.

**Comment by edemaine** [comment]
How should we go about changing to a separate KaTeX Netlify team?

**Comment by edemaine** [comment]
According to https://app.netlify.com/teams/new, you are supposed to request an Open Source plan on an existing Starter account (can't make one for KaTeX); I think this might trigger the creation of a new KaTeX team.

I've gone ahead and submitted the form.

**Comment by edemaine** [comment]
Should we turn off Netlify auto-building? We just hit 90% usage, and risk incurring $7 charge to @kevinbarabash until this gets approved. @ylemkimon

**Comment by ylemkimon** [comment]
@edemaine Good idea. I've disabled the build.

**Comment by edemaine** [comment]
@kevinbarabash Did you ever get a response about this from Netlify?

**Comment by kevinbarabash** [comment]
Sorry I've been away.  I have not contacted netlify.  I do think that as a first step would could create a new team and do whatever needs to be done to transfer our current configuration to the new team.

**Comment by kevinbarabash** [comment]
@edemaine I re-read the thread and since you submitted the form I should probably look in my inbox.

**Comment by kevinbarabash** [comment]
I checked my email and did receive a response from Netlify and we have a new OSS sponsored account.  I've invited the both of you. 🙂

**Comment by kevinbarabash** [comment]
@ylemkimon thanks for stopping the auto-builds. ❤️

**Comment by ylemkimon** [comment]
@kevinbarabash Thank you! Could you [transfer](https://docs.netlify.com/accounts-and-billing/team-management/team-owned-sites/#transfer-sites-between-teams) `katex.org` to the new team?

**Comment by edemaine** [comment]
@kevinbarabash Here are the instructions. I think only you can do the transfer, as owner, but it is easy:
https://docs.netlify.com/accounts-and-billing/team-management/team-owned-sites/

**Comment by kevinbarabash** [comment]
I've transferred the site over and removed you as members of my netlify team.  It should be safe to restart the site now, but I haven't done so yet.
