### ISSUE TITLE
problems to get the new katex content after refreshing, works just after cleaning the browser cache

### ISSUE THREAD

**Issue by xedex1111** [KaTeX/KaTeX#2216]
hi. i have the problem, that i have to clear my browser cache after each kind of change to get the new written katex content. how can i solve that? maybe it is an known problem. for better understanding. i have an extern js file, where the span's for the katex.render text are loaded in. the mainpage has the katex.render functions. any idea for a other solution which i use to see the new written code?

br

**Comment by edemaine** [comment]
@xedex1111 I think we'd need to see a complete example to help you debug. Ctrl-shift-reload doesn't suffice?

**Comment by xedex1111** [comment]
@edemaine hi. sure. 
ext.js file
---------
let something = [
{	Nr: "0", 	index: ['A','B']
	,a_href: "C"
	,inhalt: `
 	  <table>
		<tr>
			<td class="etwas2">Zeige einen Text an
				<span id='etwas_1'>(?)</span>
			</td>
		</tr><tr>
			<td></td>
		</tr>
	</table>
	`
	,jahr:"2020"
},
-----------
index.php
------------
...
<head>
... 
 <script src="ext.js"> </script>
</head>
<body>
...
<table border="0">
	<tbody id="input"></tbody>
</table>
<script>
function outputA(){
  output = document.get......
  ...
  outputB()
}
function outputB() {
  span = etwas_1; katex.render('\\mathbb{N}', span);
}
</script>
</body>

something in that style. br
