### ISSUE TITLE
Display mode doesn't work for MathML output

### ISSUE THREAD

**Issue by yawnoc** [KaTeX/KaTeX#2219]
**Describe the bug:**
Display mode does not work for MathML output (it does for HTML output).

**To Reproduce:**
Render any expression, using the options `{displayMode: true, output: 'mathml'}`.
See [JSFiddle](https://jsfiddle.net/2b497Ls0/).

**Expected behavior:**
Expression renders in display mode, i.e.&nbsp;display-style math centred on its own line.

**Actual behavior:**
Expression appears to render in inline mode.

**Screenshot:**
<img src="https://user-images.githubusercontent.com/48375680/77227660-cfa5e180-6bbc-11ea-9d99-977e65fff34a.png" width="300px">

**Environment:**
 - KaTeX Version: 0.11.1
 - Browser: any browser which supports MathML

**Comment by ronkok** [comment]
@yawnoc Good catch! The `<math>` element needs to have attribute `display="block"`. 

This should be a pretty easy fix. I can probably turn in a PR later today.
