### ISSUE TITLE
\begin{array}{} ... \end leads to TypeError

### ISSUE THREAD

**Issue by jirutka** [KaTeX/KaTeX#2224]
**Describe the bug:**
The following input causes KaTeX to throw `TypeError: o[0] is undefined`, even with option `throwOnError: false`:

```tex
\begin{array}{}
0 \leq x' \leq h\_gauss, \\
0 \leq y' \leq w\_gauss
\end{array}
```

The problem seems to be in `{}` on the first line. When you remove it, KaTeX correctly renders parse error.

**Expected behavior:**
KaTeX should render the input, or render a parse error (when `throwOnError: false`).

**Environment (please complete the following information):**
I encountered this bug with katex 0.11.1 on node 10.16.0 and reproduced in a browser on https://katex.org.

**Comment by edemaine** [comment]
That is invalid LaTeX (I get `Missing # inserted in alignment preamble.`).  Is there some LaTeX package that makes it valid?  The following is valid:

```
\begin{array}{c}
0 \leq x' \leq h\_gauss, \\
0 \leq y' \leq w\_gauss
\end{array}
```

**Comment by jirutka** [comment]
It works on https://latexbase.com/. However, even if it’s invalid syntax, it shouldn’t result in this generic error, moreover when `throwOnError` is disabled.

**Comment by edemaine** [comment]
I tried on latexbase, and there's still an error `Missing # inserted in alignment preamble.`.  latexbase must use `s`croll error mode, which causes it to compile, but only because TeX has decent error recovery, not because there wasn't an error.

**Comment by ylemkimon** [comment]
Closing in favor of #428.
