### ISSUE TITLE
Was using TypeScript considered when building KaTeX?

### ISSUE THREAD

**Issue by leontepe** [KaTeX/KaTeX#2229]
If not, why?

**Comment by kroltan** [comment]
I'm not a contributor, so I cannot authoritatively know why, but looking at the commit history, I see KaTeX development started in 2013. I don't think TypeScript was as prevalent as it is nowadays back in 2013, let alone the associated tooling at the level of quality it is today.

**Comment by ronkok** [comment]
Issue #2110 also contains some discussion regarding TypeScript.

**Comment by leontepe** [comment]
Thanks, @ronkok, I didn't see that issue.
And @kroltan, that makes sense, yeah. Explains why they didn't use TypeScript to begin with. They seem to be thinking about migrating though.
