### ISSUE TITLE
Access internal map

### ISSUE THREAD

**Issue by leontepe** [KaTeX/KaTeX#2230]
I am looking to access an internal map from the MathML tree that represents the input math to the HTML objects as well as the MathML tree itself. I haven't found it in the KaTeX source code yet and I was wondering if it exists (which I suppose?) and how to best extend the KaTeX source (via custom build) to access and use it.

**Comment by ronkok** [comment]
Others have asked for something similar to your request. Issues #376 and #1837 are still open. This looks to me to be a duplicate issue.

**Comment by leontepe** [comment]
Thanks @ronkok, it's sometimes realy hard to find these open issues when you lack the keywords to describe what you are looking for and you think that no one probably ever asked this. Sorry and thanks a lot!
