### ISSUE TITLE
Fraction bars appear very light grey when tailwind css is loaded

### ISSUE THREAD

**Issue by mgreenbe** [KaTeX/KaTeX#2236]
Fraction bars appear very light grey when tailwind css is loaded:

![image](https://user-images.githubusercontent.com/22971503/78721056-0df10f80-78e4-11ea-938f-8d9be74637c5.png)

The issue is present when rendered with chrome, safari, and firefox.

Hard to decide whether to file this with katex or with tailwind. Think it's more likely for latex folks to know css than for css folks to know latex, so decided to file here (first).

Here's a [codepen](https://codepen.io/mgreenbe/pen/xxwKOZR) illustrating the funny rendering. If you comment out the tailwind import line, everything looks normal (checked in chrome, safari, and firefox).

Thanks!

**Comment by mbourne** [comment]
Tailwind has the following CSS:

`*, ::after, ::before {
    box-sizing: border-box;
    border-width: 0;
    border-style: solid;
    border-color: #e2e8f0;
}
`

It's the `border-color` directive that's messing up your fraction (it's not a KaTeX bug).

Add the following at the end of all your other CSS and it should fix it:

`    *, ::after, ::before {
        border-color: #000
 }`

**Comment by ronkok** [comment]
KaTeX uses span borders for several things: fraction lines, rules, `\hline`, `\boxed`, `\sout`, etc. I suppose we could add a CSS rule `.katex { border-color: currentColor }` to try to insulate ourselves from this sort of thing.

**Comment by mgreenbe** [comment]
@mbourne's solution fixes the problem. As far as the extra CSS rule that @ronkok proposes, I'm not qualified to comment.

**Comment by timtody** [comment]
The proposed solutions mess with tailwinds colors. Instead, add 
```
.frac-line {border-color: #000}
```

**Comment by ronkok** [comment]
@timtody The comments in this thread are out-of-date. Current KaTeX CSS applies `.katex * {border-color: currentColor;}`.

If that does not work properly, let us know.
