### ISSUE TITLE
Extra line

### ISSUE THREAD

**Issue by Sun-ZhenXing** [KaTeX/KaTeX#2240]
![image](https://user-images.githubusercontent.com/44517244/79100233-99f9b000-7d98-11ea-95b7-1ca06f65ef96.png)
```
$f{\left(\left[\begin{matrix}1 & 0 & 0\\0 & 1 & 0\\0 & 0 & 1\end{matrix}\right] \right)}$
```
v0.11.1

**Comment by ronkok** [comment]
I'm not sure what you are trying to say. Is this a duplicate of issue #2198? If so, PR #2234 is a pending fix.

**Comment by Sun-ZhenXing** [comment]
Well, that's right. I've got the question. Thank you.
