### ISSUE TITLE
Is There a way to remove .katex-mathml element?

### ISSUE THREAD

**Issue by agungizzulhaq** [KaTeX/KaTeX#2243]
I use autorender with renderMathInElement function. I set the output option to html. So, i think .katex-mathml element will be removed. But it is still in there. Is there a way to remove that element?

**Comment by ronkok** [comment]
It works fine when I try it.

The HTML-only option has been available only since KaTeX version 0.11.0. You might check if you are using an up-to-date version.

If that does not work, then maybe direct us to a link where this occurs. We might be able to find a problem.

**Comment by agungizzulhaq** [comment]
Uh, I use version 0.10.2. It works after I update it to the latest version. Thanks.
