### ISSUE TITLE
Adding class or id properties to <span> tags in formula

### ISSUE THREAD

**Issue by akkadaska** [KaTeX/KaTeX#2244]
I’m not good at English, so I will show you only examples.

When the code is `\frac {a} {b}` , the numerator will be converted to following:
`<span class="mord textstyle uncramped"><span class="mord mathit">a</span></span>` .

I can’t find the way to add my original class or id with commands like ` \frac{\addid{mynumerator_1}{a}} {b}`  which will be converted to following:

`<span class="mord textstyle uncramped" id=”mynumerator_1”><span class="mord mathit">a</span></span>` .

If possible, css or javascript will easily access the certain parts of math formulas and we can build interactive website. For example, when visitors hover over the numerator, it will change the color and some DOM will show up.

Do you know any way? or Are you looking into implementation?

**Comment by ronkok** [comment]
@akkadaska PR #2082 contains the features that you request. It has been merged into master, but it has not yet been released.

@kevinbarabash When might the next release occur?

**Comment by akkadaska** [comment]
Thank you for telling me, and sorry for missing.

I'll follow #2082 .

I'm looking forward to the release.

Thank you!

**Comment by ronkok** [comment]
Closing via PR #2082
