### ISSUE TITLE
KaTeX with MathType

### ISSUE THREAD

**Issue by evelynlearning** [KaTeX/KaTeX#2245]
We are an education institute in India and we are creating a few assignments using KaTeX.
We are using Math-type to create equations as most of our team members comfortable working on Math-type. We would like to convert Math-type equations to KaTeX. Can you please guide us on how to execute this task?

Is it possible to have a KaTeX translator in MathType software? For now, MathType supports variety of TeX and MathML but it is not supporting KaTeX.
Please help with this.

**Comment by ronkok** [comment]
@evelynlearning Multiple products have gone by the name "MathType", so I am not sure which one you use. Could you provide a link?

**Comment by edemaine** [comment]
Assuming you mean [this MathType](http://www.wiris.com/editor/demo/en/developers), it looks like (from the bottom demo) that, yes, MathType can output the (La)TeX text for the formula. KaTeX can render such LaTeX formulas (when they're placed in the appropriate delimiters, like `$...$` or `$$...$$`). Let us know if you need further help with this.

**Comment by gaddemohankumar** [comment]
As you said it is math formulas are rendering in KaTex, but matrices which are in LaTex with $...$ are not rendering in Katex. Please help in this issue.

**Comment by kevinbarabash** [comment]
@gaddemohankumar it sounds like your issue may be KaTeX specific (unrelated to MathType).  If so, can you open a new ticket with the TeX source that's not rendering in KaTeX?
