### ISSUE TITLE
Can KaTeX be hacked to render MathML as input?

### ISSUE THREAD

**Issue by Sukii** [KaTeX/KaTeX#2249]
> Before requesting a feature, please search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like:**

**Link to or name of a (La)TeX package that provides the same feature:**
KaTeX's general goal is to render as LaTeX does.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by edemaine** [comment]
KaTeX definitely only supports LaTeX input currently.  I don't have a good sense of whether MathML as input would be possible or a good idea, but it would definitely be difficult.  And I believe it would be beyond the scope of KaTeX.  Anyone should feel free to re-open if you disagree.

**Comment by kevinbarabash** [comment]
You could generate LaTeX code from XML and then feed it into KaTeX.  It definitely feels like a separate project though.
