### ISSUE TITLE
Problem when rendering \underXXXarrow with fraction

### ISSUE THREAD

**Issue by foretjerome** [KaTeX/KaTeX#2251]
**Describe the bug:**
The rendering of `\underleftarrow{}` and `\underrightarrow{}` when applied to a `\frac{}{}` AND used inside any kind of `\left \right` bracket is misplaced.

**To Reproduce:**
1. Go to https://katex.org/
2. put this code `\left(\underleftarrow{\frac{value}{j}}\right)` in the editor
3. put the same code in https://www.codecogs.com/latex/eqneditor.php
4. See the difference

**Expected behavior:**
![image](https://user-images.githubusercontent.com/33022637/80792705-6f2f9a00-8b95-11ea-8dc1-445d7b023123.png)

got 

![image](https://user-images.githubusercontent.com/33022637/80792721-7eaee300-8b95-11ea-818f-95a3eea7c00d.png)

**Environment (please complete the following information):**
 - KaTeX Version: 0.11.1 
 - Device: Desktop
 - OS: ubuntu 16.04
 - Browser: Chrome, Firefox
 - Version: 73.0.3683.75(chrome), 65.0.1 (firefox)

**Comment by ronkok** [comment]
@foretjerome Thank you for reporting this. I've turned in PR #2252, which fixes the problem.
