### ISSUE TITLE
Square root signs not displaying

### ISSUE THREAD

**Issue by HenrikStaaf** [KaTeX/KaTeX#2260]
![square root](https://user-images.githubusercontent.com/26134734/82921795-16c3a080-9f79-11ea-8df0-ce4c7525fc0e.png)

For some reason, the square root sign is sometimes broken on the top.

**Comment by ronkok** [comment]
@HenrikStaaf What version of KaTeX are you using? You can find out by typing "katex" into the browser console.

**Comment by HenrikStaaf** [comment]
@ronkok  we are on 0.11.1

**Comment by ronkok** [comment]
@HenrikStaaf Can you provide a link to a page where this occurs? I might be able to find the problem if I can look at an instance.
