### ISSUE TITLE
Katex.org can't be accessed with Chrome 85.0.4158.4 dev 64bit.

### ISSUE THREAD

**Issue by SetoKaiba** [KaTeX/KaTeX#2264]
**Describe the bug:**
The website can't be accessed with Chrome 85.0.4158.4 dev 64bit. I confirmed it's not caused by extensions. Because it's still unable to access with Incognito mode. But it's able to accessed with Edge or Firefox. I think it's caused by some updates from Chrome.

**To Reproduce:**
Open the website https://katex.org with Chrome 85.0.4158.4 dev 64bit.

**Expected behavior:**
The website should be able to accessed with it.

**Screenshots:**
![image](https://user-images.githubusercontent.com/159540/83401621-c85e4800-a437-11ea-8a16-a5865a339f5e.png)
![image](https://user-images.githubusercontent.com/159540/83402106-b9c46080-a438-11ea-8f58-4157693aafa5.png)

**Environment (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version:  85.0.4158.4 dev 64bit

**Comment by ronkok** [comment]
I can verify that Chrome 85.0.4158.4 (Windows) will not access https://katex.org/. It also fails to access https://www.netlify.com/.

@kevinbarabash, @ylemkimon Is this something we need to worry about?

**Comment by SetoKaiba** [comment]
It's ok now. Thank you.

**Comment by SetoKaiba** [comment]
I can access it yesterday. But it can't be accessed again today.

**Comment by edemaine** [comment]
I assume this is working again now. Let us know if not!

**Comment by kevinbarabash** [comment]
Sorry for not being around to check on this.  I'm going to assume there was a netlify outage.

**Comment by ylemkimon** [comment]
Sorry for the late update. This was an issue between HTTP/2 GREASE and Netlify. See https://community.netlify.com/t/cannot-access-netlify-sites-with-chrome-85/16059 and https://bugs.chromium.org/p/chromium/issues/detail?id=1094308 for more detail.

**Comment by SetoKaiba** [comment]
Thank you. It's working now.
