### ISSUE TITLE
Dividing lines for /frac not rendered

### ISSUE THREAD

**Issue by yashpalgoyal1304** [KaTeX/KaTeX#2267]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
The dividing lines for \frac lines are not rendered at all.

**(La)TeX code:**

[`\frac` function family](https://katex.org/docs/supported.html#fractions-and-binomials)

Expected behavior (via Vivaldi browser): | Observed behavior (via inbuilt browser):
-- | --
![2020 Jun 05 14-48-12] | ![2020 Jun 05 14-45-38]

[2020 Jun 05 14-48-12]: https://user-images.githubusercontent.com/19423063/83860344-c5679e00-a73c-11ea-826a-d4aef142ba38.png
[2020 Jun 05 14-45-38]: https://user-images.githubusercontent.com/19423063/83860490-f21bb580-a73c-11ea-9974-2bf3c6342c18.png

**Environment (please complete the following information):**
 - KaTeX Version: [Can be checked via `katex.version`]
 - Device: Micromax Q350
 - OS: Android 6.0 (default ROM, i think it's AOSP)
 - Browser: 
Inbuild browser - com.android.browser | version 6.0
Vivaldi 3.0 - com.vivaldi.browser | version 3.0.1885.43

**Additional context:**
https://github.com/gsantner/markor/issues/952#issuecomment-633967426 . Please read the main description first, then the comment at this link The render by inbuilt browser matters as that's exactly what other apps (particularly Markor) show.

**Maybe related:**
https://github.com/KaTeX/KaTeX/issues/1775
https://github.com/KaTeX/KaTeX/issues/824

**Comment by ronkok** [comment]
KaTeX cannot do browser sniffing and work-arounds for every browser that has ever been created. For fraction lines, KaTeX emits a 0.04em span border and it is rendered well on modern browsers. 

If an old browser like Android Browser does not properly display the span border, I don't think we're going to change the KaTeX core code for `\frac`.

But __you__ can change `\frac`!

1. Web site administrators can set a `minRuleThickness` in the KaTeX [rendering options](https://katex.org/docs/options.html).
2. Authors can write a macro for `\frac` and use `\above` to define your own fraction line thickness. Something like: `\global\def\frac#1#2{#1 \above{0.08em} #2}`

**Comment by yashpalgoyal1304** [comment]
thanks for reply ronkok. I understand and agree with you regarding the browser things and KaTeX core code. My main motive was to find a way or workaround for gsantner/markor#952 in the cover of the android browser. But now with the solutions u proposed (thanks a lot for them) i think that fixing the issue is different for the browser/website vs. offline app side.

Can u suggest anything regarding that as well? (and if u can, thanks a lot, and also, i think that issue will be more suitable place for it rather than here)

**Comment by ylemkimon** [comment]
I'm not able to reproduce the problem with the device below:

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy S7 |
| Browser | Mobile_chrome |
| Operating System | Android 6.0 |
| Resolution | 1440 x 2560 px |
| Screen size | 5.1 in - 2.5 x 4.4 in |
| Viewport | 375 * 666 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot** 
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/d3d3ae490b8c688bf05abe3854c14ba48e0834bc/realdroid_Samsung_Galaxy_S7.jpg)

**Comment by ylemkimon** [comment]
From Android 5, it uses Chromium-based WebView, which has moved to an APK so it can be updated seperately to the Android platform. Could you try updating the WebView at https://play.google.com/store/apps/details?id=com.google.android.webview?

**Comment by yashpalgoyal1304** [comment]
That device has incurred an issue and is not in working condition at the moment. When the device got fixed, i will try updating WebView and rechecking. Thanks for the input @ylemkimon

**Comment by ylemkimon** [comment]
Please reopen the issue if the problem persists.
