### ISSUE TITLE
Latex Align Equations

### ISSUE THREAD

**Issue by luischinchillagarcia** [KaTeX/KaTeX#2272]
Currently the docs say there's support for \begin{aligned}, however, doing a simple example as follows fails.

```
<Latex>
  $$
    \begin{aligned}
      V^*(s) &=  \max_a \Big( \underbrace{r(s, a) + \gamma V^*(s')}_{=Q^*(s, a)} \Big)
    \end{aligned}
  $$
</Latex>
```

Is this a bug? I'm using React, but the doing the following is successful.
```
<Latex>
  $$
      V^*(s) &=  \max_a \Big( \underbrace{r(s, a) + \gamma V^*(s')}_{=Q^*(s, a)} \Big)
  $$
</Latex>
```

Furthermore, the docs could use way more examples on inline vs display equations. There is only one surface level example that doesn't really capture a true understanding of the library.

**Comment by edemaine** [comment]
What version of KaTeX are you using? Perhaps it's older than `aligned` support?

**Comment by edemaine** [comment]
Closing for now. Let us know if you need more help tracking this down. `aligned` should definitely work in KaTeX, if you're using a recent version.
