### ISSUE TITLE
bringing equations from ms word document

### ISSUE THREAD

**Issue by MehdiAghighi** [KaTeX/KaTeX#2273]
**Is your feature request related to a problem? Please describe.**
i have about 60 articles written in microsoft office and it has a lot of equations and i wanna post them in a blog that uses sun editor.
the writers are looking for a way to bring word equations directly to editor and not rewriting them.
suneditor uses katex for math equations but i couldn't find a way to bring math equations and copy them

**Comment by edemaine** [comment]
This isn't really the appropriate place for this question, as it's not related to KaTeX.  However, I was looking into this recently.  You might check out the following projects which convert Word to LaTeX:
* https://www.grindeq.com/index.php?p=word2latex&lang=en
* https://pandoc.org/
