### ISSUE TITLE
Macros parameter text with delimiters

### ISSUE THREAD

**Issue by vmx** [KaTeX/KaTeX#2288]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**

If the parameter text in a macro (via `/def`) contains a delimiter, KaTex errors.

**To Reproduce:**
Use the input box on https://katex.org/ and insert

```tex
\def\foo ABC#1{#1}
\foo ABC bar
```

The error is:  `KaTeX parse error: Expected 'EOF', got '#' at position 13: \def\foo ABC#̲1{#1} \foo ABC …`

**Expected behavior:**

It should render as `bar`, the same way as without a delimiter:

```tex
\def\foo #1{#1}
\foo bar
```

**Environment (please complete the following information):**
 - KaTeX Version: https://katex.org/ on 2020-07-09
 - Device: Desktop
 - OS: Debian
 - Browser: Firefox
 - Version: 76.0.1

**Additional context:**

It came up when porting a document from MathJax to KaTex and the definition for a ternary operator looked like this:

```tex
\def\tern#1?#2:#3{#1\ \text{?}\ #2 \ \text{:}\ #3}
```

*Update*: I forgot to add a link to good resource about delimiters in macro parameters: https://www.overleaf.com/learn/latex/How_TeX_macros_actually_work:_Part_4#.3Cparameter_text.3E_and_macro_delimiters

**Comment by edemaine** [comment]
You're right that `\def` doesn't support delimiters, sadly. This will be a substantial undertaking because the existing `MacroParser` doesn't support delimiters, and that will need to be generalized first.  Pull requests are definitely welcome if you're willing to work on this!

I will add a line to [the documentation](https://katex.org/docs/supported.html#macros) to clarify that this isn't supported presently.

**Comment by ylemkimon** [comment]
Actually, #2085 will add support for delimited macros.

**Comment by alvorithm** [comment]
Hi, I am struggling to define a macro with custom delimiters such as

 ```latex
\def\tern#1?#2:#3{#1\ \text{?}\ #2 \ \text{:}\ #3}

as an entry for [the macros object](https://katex.org/docs/options.html). 

My particular use-case is creating macros that accept a list of comma-separated arguments, i.e. `\foo{a,bb,ccc}` as a shorthand for `\foo{a}{bb}{ccc}`. I would be very grateful for an example!

**Comment by edemaine** [comment]
I think the easiest is to run your command (`\gdef\tern#1?#2:#3{#1\ \text{?}\ #2 \ \text{:}\ #3}` say) through `katex.renderToString`, passing in a `macros` object. You could also inspect the resulting `macros` object and use that structure directly, but that relies on the internals of `MacroExpansion`.

**Comment by alvorithm** [comment]
Thank you @edemaine for such a quick answer! Unfortunately, I am using KaTeX embedded in [SiYuan notes](https://github.com/siyuan-note/siyuan/), an Electron-based knowledge management application, and it seems that `\gdef` does not manage / is precluded to install global definitions: any macro I `\gdef`ine in one math environment is not available elsewhere.

Is there any example I can look to for the second approach, i.e. showing how to generate a `MacroExpansion` from a `\gdef` declaration?

**Comment by edemaine** [comment]
@alvorithm If you go to https://katex.org and open a console, you can interact with KaTeX directly. If you enter:

```js
macros={};
katex.renderToString(
    "\\gdef\\tern#1?#2:#3{#1\\ \\text{?}\\ #2 \\ \\text{:}\\ #3}",
    {macros})
```

then you'll get a `macros` object with the necessary information.

The `loc` information in tokens is hard to serialize and optional I believe, so you can remove it like so:

```js
macros['\\tern'].tokens.forEach((token) => { delete token.loc })
```

Then `console.log(JSON.stringify(macros['\\tern'],null,2))` gives this output:

```json
{
  "\\tern": {
    "tokens": [
      {
        "text": "3"
      },
      {
        "text": "#"
      },
      {
        "text": "\\ "
      },
      {
        "text": "}"
      },
      {
        "text": ":"
      },
      {
        "text": "{"
      },
      {
        "text": "\\text"
      },
      {
        "text": "\\ "
      },
      {
        "text": " "
      },
      {
        "text": "2"
      },
      {
        "text": "#"
      },
      {
        "text": "\\ "
      },
      {
        "text": "}"
      },
      {
        "text": "?"
      },
      {
        "text": "{"
      },
      {
        "text": "\\text"
      },
      {
        "text": "\\ "
      },
      {
        "text": "1"
      },
      {
        "text": "#"
      }
    ],
    "numArgs": 3,
    "delimiters": [
      [],
      [
        "?"
      ],
      [
        ":"
      ],
      []
    ]
  }
}
```

This should work as your `macros` object.
