### ISSUE TITLE
\colorbox{color}{string} not working

### ISSUE THREAD

**Issue by irkreja** [KaTeX/KaTeX#2300]
Hi when I tried to render following I got error
```Ne (10) \rArr 1s^2 \space \colorbox{lime}{2s^2 \space 2p^6} ```
The error is:
```KaTeX parse error: Expected '}', got '^' at position 45: …lorbox{lime}{2s^̲2 \space 2p^6}```

Any reason why this occur?

**Comment by ronkok** [comment]
@irkreja Wrap the second argument in `$…$`, like this `{$2s^2 \space 2p^6$}`.

LaTeX expects the second argument to be text. If you write math there, you need the `$…$` delimiters. We're improving the documentation in the next release, due out soon.
