### ISSUE TITLE
\underline do not work in gitbook 

### ISSUE THREAD

**Issue by hanm2019** [KaTeX/KaTeX#2312]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
I install katex in gitbook by add this plugins into book.json and then install it, the version of katex is 1.14
**To Reproduce:**
1. in markdown file, I write 
`$$\underline{add}\;\begin{Bmatrix} \underline{\;} \\\\ \underline{i}mmediate\end{Bmatrix}\begin{Bmatrix} \underline{\;}\\\\ \underline{w}ord \end{Bmatrix}$$`

2. run gitbook serve
3. in the webpage, I can see the Bmatrix, but there is no underline.

**Expected behavior:**
there is some word with underline.

**Screenshots:**
![Screenshot from 2020-07-16 10-58-51](https://user-images.githubusercontent.com/56673361/87621432-62155680-c753-11ea-9bdf-505bdade37a9.png)

**Environment (please complete the following information):**
 - KaTeX Version: [Can be checked via `katex.version`]
 - Device: [ Desktop]
 - OS: [ubuntu18.04]
 - Browser: [Chromimum]

 - Version: []

**Comment by edemaine** [comment]
This is not a KaTeX issue, but rather a Gitbook issue. Perhaps you should raise an issue with them?

Please check again what version of KaTeX you/Gitbook are using. 1.14 is not a KaTeX version: the current release is 0.12.0. Can you try typing `katex.version` into the JavaScript console? (Not sure whether this will work, but worth a try.)

If you go to katex.org and type in your expression, it works fine:
![image](https://user-images.githubusercontent.com/2218736/87687215-78bbad80-c753-11ea-9952-5f4bbba1ef27.png)

The fact that you're getting something to render and not getting an error message suggests to me that maybe Gitbook is sanitizing the output HTML to remove some classes... or maybe an incorrect style file? Anyway, hard to tell without seeing it in action.

**Comment by ylemkimon** [comment]
https://github.com/GitbookIO/plugin-katex seems to use very old version, 0.7.1. There is an issue requesting to update the version at https://github.com/GitbookIO/plugin-katex/issues/22, but it seems unmaintained. You can probably fork the repo and update KaTeX version.
