### ISSUE TITLE
Math operators require braces when used in superscript/subscript

### ISSUE THREAD

**Issue by jason-s** [KaTeX/KaTeX#2319]
On katex.org, enter `T_\max`

Resulting behavior: 

> KaTeX parse error: Got function '\max' with no arguments as subscript at position 3: T_\̲m̲a̲x̲

Expected behavior: This should be identical to `T_{\max}`, which does work fine in KaTeX. The `T_\max` does work in LaTeX and MathJax: http://jbergknoff.github.io/mathjax-sandbox/#JFRfXG1heCQ%3D

Superscripts and subscripts should not require braces.

**Comment by edemaine** [comment]
@ylemkimon Will this be fixed by #2085?

**Comment by ylemkimon** [comment]
This will be fixed by #2085 combined with #2134.

**Comment by ylemkimon** [comment]
Actually, LaTeX adds the missing brace via error recovery:
```
Missing { inserted.
leading text: $x_\max
```

This feature is tracked by #428.
