### ISSUE TITLE
Horizontal line cannot be displayed on the the edge browser

### ISSUE THREAD

**Issue by YinAoXiong** [KaTeX/KaTeX#2325]
**Describe the bug:**
Horizontal line cannot be displayed on the the edge browser

**To Reproduce:**
1. Use the same browser as me
2. Click on https://katex.org/docs/supported.html
3. Scroll down to Fractions and Binomials

**Screenshots:**
![sreenshots](https://user-images.githubusercontent.com/23397945/87935283-6202b700-cac3-11ea-913e-dd529a5a4ed1.png)

**Environment (please complete the following information):**
 - KaTeX Version: 0.12.0
 - Device: Desktop
 - OS: Windows 10
 - Browser: edge dev
 - Version:  85.0.564.8

**Additional context:**
Add any other context about the problem here. If you're using a library to use KaTeX, please include its name and setup.

**Comment by ylemkimon** [comment]
I'm not able to reproduce the issue. Could you check your zoom level? KaTeX works nicely with the default zoom.

**Comment by YinAoXiong** [comment]
> I'm not able to reproduce the issue. Could you check your zoom level? KaTeX works nicely with the default zoom.

I found that the problem only occurred when the external display was used and the default zoom was used. When I zoomed in, the problem disappeared, so this should be a problem of the edge browser's adaptation to high-resolution screens.

**Comment by ylemkimon** [comment]
@YinAoXiong Could you let us know the resolution of your screen?

**Comment by YinAoXiong** [comment]
> @YinAoXiong Could you let us know the resolution of your screen?

The resolution of my external screen is 2k
