### ISSUE TITLE
Line break doesn't work with \left and \right

### ISSUE THREAD

**Issue by visika** [KaTeX/KaTeX#2327]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
Automatic line break does not work on expressions enclosed by `\left[` and `\right]`.
When the same expression is enclosed, e.g., between `\Big[` and `\Big]`, line breaking works as expected.

**To Reproduce:**
1. Go to [the demo](https://katex.org/)
2. Turn `displayMode` off in the settings gear
3. Paste this 
```
(\cosh K)^{N-1}\sum_{\{s_i\}}

\left[
1 + \sum_is_is_{i+1}\tanh K + \sum_{i=1}^{N-1}\sum_{j\ne i}(\tanh K)^2s_is_{i+1}s_js_{j+1}+\dots+(\tanh K)^{N-1}(s_1s_2)(s_2s_3)(s_3s_4)\dots(s_{N-1}s_N)
\right]

=2^N(\cosh K)^{N-1}
```
4. See all the expression is on one line, until the closing `\right]`

**Expected behavior:**
If you replace `\left` and `\right` with any absolute modifier like `\Big` (or blank), the expression fits nicely in its box.

**Screenshots:**
|`\left[`|`[`|
|---|---|
|![image](https://user-images.githubusercontent.com/2254049/87962909-3b8b4e80-cab8-11ea-92d3-fb03e4b9c492.png)|![image](https://user-images.githubusercontent.com/2254049/87962967-4f36b500-cab8-11ea-90d0-15bc30200a3c.png)|

**Environment (please complete the following information):**
 - KaTeX Version: 0.12.0
 - Device: Desktop
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 78.0.2

**Comment by ronkok** [comment]
@visika The same behavior occurs in LaTeX. The following image is from https://www.quicklatex.com/.

![](https://quicklatex.com/cache3/7d/ql_eaf5218bdad8476c32e033c2255c4b7d_l3.png)

LaTeX allows for soft line breaks after binary operators and relational operators, but only when they are outside of any group. The `\left[...\right]` delimiters create a group, so no soft line breaks can occur between them. 

KaTeX emulates LaTeX, so it behaves the same way.

**Comment by visika** [comment]
Thanks for the clarification! I guess this can be closed then.
