### ISSUE TITLE
In minilatex.lamdera.app, KaTeX renders math in Firefox but not Chrome

### ISSUE THREAD

**Issue by jxxcarlson** [KaTeX/KaTeX#2331]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
In https://minilatex.lamdera.app/g/1 KaTeX renders math in Firefox, but not Chrome.

**To Reproduce:**
1. Go to https://minilatex.lamdera.app/g/1 first in Firefox.
2. Scroll down to look at the math.  It is OK
3. Now do the same with Chrome.  The math is not rendered
=

**Expected behavior:**
See above

**Environment (please complete the following information):**
 - KaTeX Version: 0.12.0
 - Device: Desktop
 - OS: MacOS 10.5.5
 - Browser: Firefox 78.0.2, Chrome 83.0.4103.116

**Additional context:**
The error occurs in an app (https://minilatex.lamdera.app) built with Elm does on-the-fly compilation of LaTeX to HTML, with the math-mode stuff rendered by KaTeX.  Elm compiles its code to Javascript and interfaces with KaTeX via a custom element.  Below is the code for that.  Note that it uses `katex.renderToString`

```
exports.init =  async function(app) {

  console.log("I am starting elm-katex: init");
  var katexJs = document.createElement('script')
  katexJs.type = 'text/javascript'
  katexJs.src = "https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js"
  katexJs.onload = initKatex

  document.head.appendChild(katexJs);
  console.log("elm-katex: I have appended katexJs to document.head");

}


function initKatex() {

  console.log("elm-katex: initializing");

  class MathText extends HTMLElement {

     constructor() {
         // Always call super first in constructor
         super();
       }

    connectedCallback() {
      this.attachShadow({mode: "open"});
      this.shadowRoot.innerHTML =
        katex.renderToString(
          this.content,
          { throwOnError: false, output: "mathml", displayMode: this.display }
        );
    }

  }

  customElements.define('math-text', MathText)

}
```

PS. There are some display issues with equation numbers.  That is my problem, not that of KaTeX.  I've had to make some small changes in the MiniLaTeX compiler to make it work with KaTeX. Still a few things left to do.

**Comment by edemaine** [comment]
MathML is only supported well by Firefox, I believe. Did you try turning off the mathml output mode to allow KaTeX to use its default behavior of HTML rendering and MathML backup? (as previously suggested)

**Comment by jxxcarlson** [comment]
Yes, I’ve tried turning that off as suggested both with this version of KaTeX and the previous one (0.11.*). 
Unfortunately, when I do that, the display is messed up in both Chrome and Firefox:
Math elements are repeated.  That is why I have used 

           output: “mathml"

Is there some better way to suppress the double rendering?  Is this a peculiarity of renderToString?


CHROME:




FIREFOX:

**Comment by jxxcarlson** [comment]
Also (PS to reply), when I look closely at the Chrome screenshots, I don’t see rendered math, just doubled source text. Perhaps my custom element code is wrong?

**Comment by edemaine** [comment]
I feel like we're having the same conversation over again. 🙂 The website you sent still doesn't have a `<link>` tag to include the KaTeX CSS. Without that, HTML rendering won't work. Please add it, and turn off `mathml` mode, and I can try to debug.

Also, your screenshots aren't coming through. I don't think Github supports email attachments. You need to use the Github web interface.

**Comment by jxxcarlson** [comment]
Thanks for your patience on this!  I've added `katex.min.css` in the app source code (there is no `index.html` or any other html file in the project, so that took a little head-scratching). By inspecting the web page, I see that it the CSS is there:

<img width="633" alt="Screen Shot 2020-07-23 at 1 49 46 PM" src="https://user-images.githubusercontent.com/679991/88328920-26e8c980-ccf7-11ea-8c7e-c91e7f2bc1dc.png">

I also verified that the CSS was loaded:

<img width="436" alt="Screen Shot 2020-07-23 at 1 31 23 PM" src="https://user-images.githubusercontent.com/679991/88328982-44b62e80-ccf7-11ea-838b-ba317196abc8.png">

Here is some of the resulting rendered text in Chrome:

<img width="518" alt="Screen Shot 2020-07-23 at 3 15 42 PM" src="https://user-images.githubusercontent.com/679991/88329185-8e067e00-ccf7-11ea-8f74-1c04be964acc.png">

And here is the same in Firefox:

<img width="524" alt="Screen Shot 2020-07-23 at 3 17 47 PM" src="https://user-images.githubusercontent.com/679991/88329325-c017e000-ccf7-11ea-97f9-498d33cf54f6.png">

The CSS lives in a node that is a parent of the node where the text is rendered, so it should have access to the CSS.  Nonetheless, it seems that (a) output is doubled, (b) only in FF is one of the twins in a pair is rendered; I guess that is the mathml member of the twins.

**Comment by ylemkimon** [comment]
Shadow DOM is isolated from the outside, so stylesheets loaded outside don't apply.

Try adding
```js
let link = document.createElement('link');
link.setAttribute('rel', 'stylesheet');
link.setAttribute('href', 'https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css');
this.shadowRoot.appendChild(link);
```
and removing `output: "mathml"`.

**Comment by jxxcarlson** [comment]
OK @ylemkimon , will do!

**Comment by jxxcarlson** [comment]
I tried that, with the same results as before.  Here is the current state of the code I am using:

```

exports.init =  async function(app) {

  console.log("I am starting elm-katex: init");
  var katexJs = document.createElement('script')
  katexJs.type = 'text/javascript'
  katexJs.src = "https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js"
  katexJs.onload = initKatex

  document.head.appendChild(katexJs);
  console.log("elm-katex: I have appended katexJs to document.head");

}


function initKatex() {

  console.log("elm-katex: initializing");

  class MathText extends HTMLElement {

     constructor() {
         // Always call super first in constructor
         super();
       }

    connectedCallback() {
      this.attachShadow({mode: "open"});
      let link = document.createElement('link');
      link.setAttribute('rel', 'stylesheet');
      link.setAttribute('href', 'https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css');
      this.shadowRoot.appendChild(link);
      this.shadowRoot.innerHTML =
        katex.renderToString(
          this.content,
          { throwOnError: false, displayMode: this.display }
        );
    }

  }

  customElements.define('math-text', MathText)

}
```

Have I inserted your code correctly?

**Comment by edemaine** [comment]
Setting `innerHTML` will remove the child. You'd need to do those operations in the opposite order, I guess.

**Comment by jxxcarlson** [comment]
Thank all, changing the order did the job:

<img width="535" alt="Screen Shot 2020-07-23 at 3 49 19 PM" src="https://user-images.githubusercontent.com/679991/88332214-31599200-ccfc-11ea-8b79-905e95143035.png">

Thank you so much!

**Comment by jxxcarlson** [comment]
Oops (and sorry for the cross-posting -- trying to get all in order for a conference talk Sunday).  There seems to be one more step needed, as indicated in the mal-formed integral signs below.  I must still be missing something (fonts?)

<img width="528" alt="Screen Shot 2020-07-23 at 4 28 42 PM" src="https://user-images.githubusercontent.com/679991/88337062-0ffca400-cd04-11ea-8fde-9e098ffa5db5.png">

**Comment by edemaine** [comment]
I agree that all the fonts look off. It seems that you just need to add
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css">
```
to the top-level `<head>` as well, as the CSS also defines the font families.

**Comment by jxxcarlson** [comment]
Yes indeed!!  Thanks^{10}

<img width="538" alt="Screen Shot 2020-07-23 at 5 27 05 PM" src="https://user-images.githubusercontent.com/679991/88340425-d169e800-cd09-11ea-8f42-bc3d2e2d7ca2.png">
