### ISSUE TITLE
It looks like the maximum expansions counter is not reset between macros.

### ISSUE THREAD

**Issue by delbaredouard** [KaTeX/KaTeX#2333]
Hi. It looks like the maximum expansions counter is not reset between macros.

Please try the following code (uncomment to see what I mean):

```
$$
\def\0{}\def\1{}\def\2{}\def\3{}\def\4{}
\def\5{}\def\6{}\def\7{}\def\8{}\def\9{}
\newcommand\if[4]{\@ifnextchar#1{
    \@ifnextchar#1{#4}{#4\ \n{#2}{#4}}\1
}{}#3}
\newcommand\n[2]{
    \if\9\8#1#2 \if\8\7#1#2 \if\7\6#1#2
    \if\6\5#1#2 \if\5\4#1#2 \if\4\3#1#2
    \if\3\2#1#2 \if\2\1#1#2 \if\1\0#1#2
}
\begin{array}{c}
    \sf \n{\9}{I} \\
    \sf \n{\9}{I} \\
    \sf \n{\9}{I} \\
%    \sf \n{\6}{I} \\ % "too many expansions" :-S
\end{array}
$$
```

I'm using Katex through StackEdit 5.14.5, so I guess the Katex version is 0.10.2:

> https://github.com/benweet/stackedit/blob/v5.14.0/package.json#L41

I'm sorry I can't describe things better.

Not sure that it's a bug though...

**Comment by edemaine** [comment]
This is the intended behavior. The goal is to prevent code from sucking up a bunch of CPU and thereby bringing down the page. The expansion limit is like a time limit on an expression. You can always disable it, if you trust your LaTeX input.
