### ISSUE TITLE
mathdefault versus mathnormal classes

### ISSUE THREAD

**Issue by mgreenbe** [KaTeX/KaTeX#2347]
I'm working with `remark-math` and `rehype-katex`, to render math in markdown files. I'm posting here because it's all katex under the hood generating the html. (Please tell me if this isn't the appropriate venue.)

If I use`remark-math` and `rehype-katex` to render the simple markdown string `$x$`, I get 

`... <span class="mord mathdefault">x</span> ...`

and it renders, unslanted, thusly:

![image](https://user-images.githubusercontent.com/22971503/88854890-42e4e300-d1af-11ea-8a22-da1545a9e2f6.png)

If I render it "by hand" with `katex.renderToString`, I get

`... <span class="mord mathnormal">x</span> ...`

Note that the `mathdefault` class has been swapped out for `mathnormal`. This renders correctly:

![image](https://user-images.githubusercontent.com/22971503/88855129-a242f300-d1af-11ea-8ac3-f376dd1e1c1a.png)

What's going on here? Has there been some change recently involving these two css classes?

I have version 0.12.0 installed, by the way.

**Comment by edemaine** [comment]
Yes, the name changed in the latest release. This suggests that `remark-math`/`rehype-katex` are using a different version of KaTeX than the one you have "installed", i.e., you're using two versions of KaTeX simultaneously. You should probably use only one.

**Comment by mgreenbe** [comment]
Right, `rehype-katex` is on 0.11.0. I'll just close and this and stroll on over to that repo. Thanks!!

**Comment by hrldcpr** [comment]
Thanks for posting this, was just having the same issue.

I was searching for "not italic" so I'll drop that term here while I'm at it
