### ISSUE TITLE
Rename the default branch name from `master` to `main`

### ISSUE THREAD

**Issue by ylemkimon** [KaTeX/KaTeX#2350]
https://github.com/github/renaming

**Comment by edemaine** [comment]
Thanks for the pointer on this! Nice to see Github making a general move. Sounds like it might be easiest to wait till their update "by end of year", but also happy to move sooner if anyone desires.

**Comment by edemaine** [comment]
I just looked at the webpage again, and it looks like renaming a branch is far easier now.

> Renaming a branch will:
>
> * Re-target any open pull requests
> * Update any draft releases based on the branch
> * Move any branch protection rules that explicitly reference the old name
> * Update the branch used to build GitHub Pages, if applicable
> * Show a notice to repository contributors, maintainers, and admins on the repository homepage with instructions to update local copies of the repository
> * Show a notice to contributors who git push to the old branch
> * Redirect web requests for the old branch name to the new branch name
> * Return a "Moved Permanently" response in API requests for the old branch name

Any objections to moving from `master` to `main`?  It looks like all existing PRs are moved over.  Probably has the most significant (but still minor) impact on the developers, who need to remember to use `git checkout main` now.

Oh, and most of the [workflows](https://github.com/KaTeX/KaTeX/tree/master/.github/workflows) need to change.
