### ISSUE TITLE
Enable \tag within AMS environments

### ISSUE THREAD

**Issue by ronkok** [KaTeX/KaTeX#2379]
The following AMS environments allow `\tag`(s) to be placed inside the environment, one tag for each line.

* {align}
* {align*}
* {alignat}
* {alignat*}
* {equation}
* {equation*}
* {gather}
* {gather*}

It would be good if KaTeX could enable the same thing.

**Comment by edemaine** [comment]
@marekyggdrasil I believe LaTeX would give the same error. You can't use multiple `\tag` statements in a single `equation` environment. Try `align` or `align*` instead. Also, please open a new issue or discussion in the future.

**Comment by marekyggdrasil** [comment]
@edemaine well noted, I tried and indeed both `align` and `align*` work fine. Thank you for the comment!
