### ISSUE TITLE
Katex extension"math/tex"

### ISSUE THREAD

**Issue by bjeevana94** [KaTeX/KaTeX#2382]
According to the Katex website, It says "math/tex Custom Script Type: Automatically displays LaTeX math inside script tags with type=math/tex".

This feature works great when I write `<script type="math/tex">x+\sqrt{1-x^2}</script>` <br/>
but If I try to use `<script type="math/tex">
\documentclass{article}
\usepackage{tikz}
\begin{document}
\thispagestyle{empty}
\begin{tikzpicture}
    \draw (0,0) circle (1in);
  \end{tikzpicture}
\end{document}</script>` <br/>

It gives me the following error `"angular.js:11655 ParseError: KaTeX parse error: Undefined control sequence: \documentclass at position 2: 
\̲d̲o̲c̲u̲m̲e̲n̲t̲c̲l̲a̲s̲s̲{article}"`

I would really appreciate it. If there is any solution to this issue.

Thanks in advance

**Comment by edemaine** [comment]
KaTeX processes LaTeX math, not entire LaTeX documents.  (I don't think anything does the latter, other than LaTeX itself.)  Also no support for Tikz (see #219).
