### ISSUE TITLE
Using Katex with kahoot-clone-nodejs - MongoDB String?!?

### ISSUE THREAD

**Issue by Paule2020** [KaTeX/KaTeX#2395]
Hello,

this is not really a feature-request, but however I would like to give it a try.

I'm using kahoot-clone-nodsjs (https://github.com/ethanbrimhall/kahoot-clone-nodejs) and I wonder if it's possible to render latex-code with KaTeX?

All questions and answers are stored in a MongoDB, domain String.
I installed KaTeX and entering "katex.render("c = \\pm\\sqrt{a^2 + b^2}", element, {
    throwOnError: false
});" in a question/answer field was wrong... Nothing is rendered...

Any ideas where I must but the render-statement?

**Comment by kevinbarabash** [comment]
I don't know how kahoot-clone-nodejs renders it's content but
```
katex.render("c = \pm\sqrt{a^2 + b^2}", element, {
throwOnError: false
});
```
is JavaScript and it's unlikely that the project you linked to is going to execute strings stored in the database as JavaScript.  I would suggest opening a ticket with kahoot-clone-nodejs' issue tracker since they'll have a better idea of how to libraries to render different content types into their project.

**Comment by Paule2020** [comment]
Hi,
I already opend a ticket but I'm not sure if the project is still alive...

However, I managed to render tex-code, but unfortunately not in the right way as it is display "twice", see screenshot.
In the KaTeX API I read that htmlandmathml is default and so an tried to get only the hmtl-string as in var-html, however, nothing changed.
![Latex](https://user-images.githubusercontent.com/62879618/89707434-23e40f00-d96e-11ea-9b93-cb51b067387a.JPG)

I know that this might not be the right place to ask but I would be grateful for any hints and solutions.

**Comment by ylemkimon** [comment]
@Paule2020 You should also include the stylesheet:
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css" integrity="sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X" crossorigin="anonymous">
```

**Comment by Paule2020** [comment]
thanks! it works!
