### ISSUE TITLE
Support \phase function

### ISSUE THREAD

**Issue by Atlas-K** [KaTeX/KaTeX#2397]
> Before requesting a feature, please search for [existing issues](https://github.com/KaTeX/KaTeX/issues).
By a quick search the only issue that mention "phase" or "steinmetz" is: https://github.com/KaTeX/KaTeX/pull/1827#issuecomment-452976494

**Is your feature request related to a problem? Please describe.**
I wish KaTeX support the "\phase" function or something that does the same job.

**Describe the solution you'd like:**
![](https://i.ibb.co/72QGCSf/phase.png)
example image from: https://tex.stackexchange.com/questions/185079/angle-notation-for-complex-numbers-in-polar-form 

**Link to or name of a (La)TeX package that provides the same feature:**
The "\phase" function is supported by the "steinmetz" package.

**Describe alternatives you've considered:**
I tried to combine other "\angle" and "\underline" but couldn't get the bottom line to match . So, I compromised by giving up the underline "\phase" gives, and used the "\angle" function.

Some more info about steinmetz package.
https://mirror.yongbok.net/ctan/macros/latex/contrib/steinmetz/steinmetz.pdf

**Comment by ronkok** [comment]
@Atlas-K Thank you for raising this issue. I've turned in PR #2406, which will resolve it.
