### ISSUE TITLE
Typo in macro definition

### ISSUE THREAD

**Issue by jxir** [KaTeX/KaTeX#2458]
PR #2429 added support for AMS log-like symbols.
There is a typo in one of the macro definitions:
```
defineMacro("\\injlim", "\\DOTSB\\operatorname*{int\\,lim}");
```
The name should start with `inj`, not `int`.
The corresponding test contains the same typo.

**Comment by ronkok** [comment]
@jxir Thank you for raising this issue. I'll turn in a PR to fix it.
