### ISSUE TITLE
Dependabot workflow

### ISSUE THREAD

**Issue by edemaine** [KaTeX/KaTeX#2471]
I wonder whether we could improve the Dependabot workflow.  This is maybe a little gripe-y, but I get a lot of email messages about every Dependabot update.  Here's a recent example for #2469, where I got 12 messages (maybe above average):
1. dependabot opens pull request
2. github-actions pushes `Dependabot autofix [skip netlify]`
3. dependabot pushes another bump commit? (I guess a version change from Friday to Saturday)
4. github-actions pushes `Dependabot autofix [skip netlify]` again
5. github-actions pushes `Dependabot autofix [skip netlify]` again
6. github-actions pushes `Dependabot autofix [skip netlify]` again (why?)
7. @ylemkimon closes the PR
8. dependabot responses with "OK, I won't notify you again about this release"
9. @ylemkimon reopens the PR (what does this do?)
10. codecov reports on coverage (perhaps we should disable this for dependabot PRs, though it's the least of my worries at this point)
11. @ylemkimon approves with `@dependabot merge` -- this one is important and concise
12. dependabot merges

I feel like we could improve on this, but I also don't know the specifies of how things are working here:
* Why do we need github-actions to skip netlify?
* Why is the close/reopen cycle necessary?

Ideally we could reduce to only messages 1, 11, 12 (and maybe message 3 in this case).

**Comment by ylemkimon** [comment]
Sorry for the notification overload. Currently, since the commit by GitHub Actions doesn't trigger a new workflow run, PRs have to be closed and reopened in order to run the tests. This will be fixed by #2438.

**Comment by ylemkimon** [comment]
For notifications triggered by commits pushed by `github-actions[bot]`, I can't seem to find a way to suppress them from the workflow side. It'd be possible to filter emails by the sender name or `X-GitHub-Sender` header of `github-actions[bot]` or the body containing `Dependabot autofix`.

**Comment by ylemkimon** [comment]
I'll hold off Dependabot PRs until #2438.

**Comment by ylemkimon** [comment]
Another way seems to be to move to Renovate. It supports Yarn 2 out of the box and supports grouping dependencies, which will reduce PRs.

**Comment by ylemkimon** [comment]
Sorry again for the notification overload. I didn't expect Renovate to create all PRs at once. It seems the hourly limit doesn't apply to our current configuration.
