### ISSUE TITLE
mhchem.js will not run if katex.js is set to "defer"

### ISSUE THREAD

**Issue by mhchem** [KaTeX/KaTeX#2482]
JS Bin with .min.js version: https://jsbin.com/runowevafi/edit?html,output
JS Bin with .js version: https://jsbin.com/bagafidifi/1/edit?html,output

Both show the same error: Cannot read property '__defineMacro' of undefined

(After the change, you will need to fix the integrity hash at <https://github.com/KaTeX/KaTeX/blob/master/contrib/mhchem/README.md>. While you are at it, please add the missing `crossorigin="anonymous"`.)

**Comment by ronkok** [comment]
It runs if I delete "defer" from the script tag for `katex.min.js`. So no modification of code is necessary. All that is needed is an explanation on the [README page](https://github.com/KaTeX/KaTeX/tree/master/contrib/mhchem) for the mhchem extension. 

I'll work up a PR tomorrow.
