### ISSUE TITLE
Avoid unnecessary netlify builds

### ISSUE THREAD

**Issue by kevinbarabash** [KaTeX/KaTeX#2483]
I got an email from netlify saying we'll "need an allowance increase soon".  I think we'll still be under this billing cycle but it would be nice to avoid unnecessary netlify builds if possible, e.g. dependabot builds.

**Comment by edemaine** [comment]
Yeah, I was surprised to see that the open-source plan (and pro plan) "only" have 1000 free minutes per month.  Still better than the 300 free minutes we had on the free plan, but it seems like we optimize our use of Netlify.  (I thought depandabot builds were already being excluded? Perhaps not correctly?)

**Comment by kevinbarabash** [comment]
I had a look at one of the dependabot PRs and one of the commits has `[skip netlify]` in the commit message, but the first commit doesn't.  It's possible that dependabot isn't the culprit.  I should look at netlify's UI to see if there's some low-hanging fruit still. 🤞

**Comment by kevinbarabash** [comment]
I had a look and most of the builds are dependabot builds.  I think we'll need to give https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds a try.  I believe our site was created before October 3rd, 2019 so we'll need to re-link the repository for this to work according to the docs.

**Comment by ylemkimon** [comment]
> Another way seems to be to move to Renovate. It supports Yarn 2 out of the box and supports grouping dependencies, which will reduce PRs.

**Comment by ylemkimon** [comment]
@kevinbarabash I've requested to install Renovate on the repo. It will not immediately enable Renovate, but open [an onboarding PR](https://docs.renovatebot.com/configure-renovate/).

**Comment by kevinbarabash** [comment]
That sounds awesome!

**Comment by kevinbarabash** [comment]
@ylemkimon I've installed the app.  I set up an account with them but there doesn't seem to be a way to share access to the account with other people.

**Comment by kevinbarabash** [comment]
The bot created #2493.

**Comment by ylemkimon** [comment]
Netlify still seems to run even the commit message has `[skip netlify]`. I'll open a issue at Netlify.

**Comment by ylemkimon** [comment]
Apparently, `[skip netlify]` only works if it's in the PR title (#2520).
