### ISSUE TITLE
bmatrix*/pmatrix* column alignment

### ISSUE THREAD

**Issue by cirosantilli** [KaTeX/KaTeX#2484]
> Before requesting a feature, please search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the solution you'd like:**

https://tex.stackexchange.com/questions/45001/how-do-i-left-align-entries-in-a-matrix-with-beginmatrix/156928#156928

Notably, minus signs make numbers misalign which is ugly.

**Link to or name of a (La)TeX package that provides the same feature:**
KaTeX's general goal is to render as LaTeX does.

https://www.ctan.org/pkg/mathtools?lang=en

**Describe alternatives you've considered:**

```
\begin{pmatrix*}[r]
  -1 & 3 \\
  2 & -4
\end{pmatrix*}
```

`bmatrix*`/`pmatrix*` environments are not defined. KaTeX v0.11.1.

**Comment by ronkok** [comment]
@cirosantilli That's a good idea. I've turned in a PR to support these packages.

**Comment by ronkok** [comment]
Closed per PR #2488.

**Comment by VergeDX** [comment]
Notion note still not support this feature : (
that's quite annoying...
