### ISSUE TITLE
render bug?

### ISSUE THREAD

**Issue by risehide** [KaTeX/KaTeX#2489]
> Before reporting a bug
- [1] Check [common issues](https://katex.org/docs/issues.html).
- [1] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [1] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
Mathjax can render this formula normally, but Katex can't.

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
\begin{matrix}&7&1&0\\-&3&7&9\\\hline&3&3&1\\\end{matrix}
```

**Expected behavior:**
render it as MathJax.

**Screenshots:**
sry.

**Environment (please complete the following information):**
 - KaTeX Version: 0.12
 - Device: all
 - OS: all
 - Browser: chrome
 - Version: all

**Additional context:**
KaTeX auto-render: Failed to parse `\begin{matrix}&&&7&1&0\-&&&3&7&9\\hline&\\end{matrix}` with  ParseError: KaTeX parse error: Undefined control sequence: \- at position 23: …matrix}&&&7&1&0\̲-̲&&&3&7&9\\hline….

**Comment by ylemkimon** [comment]
It seems backslashes are not properly escaped, try:
```js
"\\begin{matrix}&7&1&0\\\\-&3&7&9\\\\\\hline&3&3&1\\\\\\end{matrix}"
```
or
```js
`\begin{matrix}&7&1&0\\-&3&7&9\\\hline&3&3&1\\\end{matrix}`
```

**Comment by risehide** [comment]
"auto-render"  render it fail
"katex.renderToString()"  render it success
