### ISSUE TITLE
After colon, dot and comma a whitespace is added.

### ISSUE THREAD

**Issue by q2apro** [KaTeX/KaTeX#2514]
**Describe the bug:**

Katex renders a division colon `:`, a dot `·` and a comma `,` by adding a space after the sign:
![image](https://user-images.githubusercontent.com/6764548/93216336-47ba2200-f770-11ea-9f4c-4462571a2ca6.png)

`= \frac{24\color{blue}{:6}}{30\color{blue}{:6}}`

Expected was:
![image](https://user-images.githubusercontent.com/6764548/93216407-5c96b580-f770-11ea-870c-3597c5ba5778.png)

This can only be achieved by using `{:}` instead of `:`. But we cannot start to edit 100,000s of posts of our users that have used `:` and comma (German decimal!) in their latex. 

Same situation is when using `·` instead of `{·}`:
![image](https://user-images.githubusercontent.com/6764548/93216695-b6977b00-f770-11ea-96cb-1eb5870a38ab.png)

Same for comma:
![image](https://user-images.githubusercontent.com/6764548/93218731-37577680-f773-11ea-9817-5e0669fb571a.png)

Q: How can we set up Katex to render accordingly so that no whitespace is added?

<br>

**To Reproduce:**

1. Go to https://katex.org/

2. Enter latex: 

```
\frac{12}{100} = 0,12
\\
\frac{12}{100} = 0{,}12
```

3. See different output:

![image](https://user-images.githubusercontent.com/6764548/93226550-1fd0bb80-f77c-11ea-8c94-c017b4364ef5.png)

**Environment (please complete the following information):**
 - KaTeX Version: 0.12.0
 - Device: Deskto
 - OS: Windows 10
 - Browser: Chrome
 - Version: 85.0.4

**Comment by edemaine** [comment]
This is not a bug.  It is how LaTeX works, so KaTeX reproduces that behavior.

If you want `:` to act like `{:}`, you can pass in a settings object like this:
```js
{
  macros: {":": "{\\char`:}"}
}
```

https://katex.org/docs/autorender.html explains how to pass options into autorender.

**Comment by ylemkimon** [comment]
This seems to be a bug, `:` at the start of `\color{}` should be `mathord`, where the spacing should not be inserted.

**Comment by q2apro** [comment]
Thanks. I could fix with the autorender by this code:

```
renderMathInElement(document.body, {
    delimiters: [
        {left: "$$", right: "$$", display: true},
        {left: "\\(", right: "\\)", display: false},
    ],
    macros: {
        ":": "{\\char`:}",
        ",": "{\\char`,}",
        "·": "{\\char`·}",
    },
    fleqn: true
});
console.log('Katex rendered');
```

**Comment by edemaine** [comment]
> This seems to be a bug, `:` at the start of `\color{}` should be `mathord`, where the spacing should not be inserted.

I believe it's working correctly. Notice that it's `\color`, not `\textcolor`, but there are braces around `{:6}`, so there's a space after but not before the colon.

**Comment by ylemkimon2** [comment]
QuickLaTeX seems to show no space with `\frac{24\color{blue}{:6}}{30\color{blue}{:6}}`:
![image](https://user-images.githubusercontent.com/71343000/93242682-22560400-f7c2-11ea-8a5b-9d6829b13741.png)

**Comment by ylemkimon** [comment]
(Wrong account) QuickLaTeX seems to show no space with `\frac{24\color{blue}{:6}}{30\color{blue}{:6}}`:
![image](https://user-images.githubusercontent.com/71343000/93242682-22560400-f7c2-11ea-8a5b-9d6829b13741.png)

**Comment by edemaine** [comment]
Hmm, we must be running it differently?  Here's what I got with the same input (after adding `\usepackage{color}`):

![image](https://user-images.githubusercontent.com/2218736/93246476-d91e9980-f75a-11ea-8761-e386372c1c80.png)

I just confirmed on my local PDFLaTeX installation:

![image](https://user-images.githubusercontent.com/2218736/93246606-053a1a80-f75b-11ea-997f-e4806d4adad9.png)
