### ISSUE TITLE
I would be nice if kate have support for overarc and intclockwise operator

### ISSUE THREAD

**Issue by michelmar** [KaTeX/KaTeX#2542]
![image](https://user-images.githubusercontent.com/60835138/93949951-6ee89480-fd18-11ea-8b82-4b272cb13bea.png)

![image](https://user-images.githubusercontent.com/60835138/93950006-9fc8c980-fd18-11ea-88dc-564f01ff92f1.png)

**Comment by ylemkimon** [comment]
We're tracking `\wideparen` and `\ointclockwise` support in #560 and #2059, respectively.
