### ISSUE TITLE
Doc: Which font file to include?

### ISSUE THREAD

**Issue by qlcom** [KaTeX/KaTeX#2554]
there are a few different font files. in `woff2` format there are 

```
KaTeX_AMS-Regular.woff2
KaTeX_Caligraphic-Bold.woff2
KaTeX_Caligraphic-Regular.woff2
KaTeX_Fraktur-Bold.woff2
KaTeX_Fraktur-Regular.woff2
KaTeX_Main-BoldItalic.woff2
KaTeX_Main-Bold.woff2
KaTeX_Main-Italic.woff2
KaTeX_Main-Regular.woff2
KaTeX_Math-BoldItalic.woff2
KaTeX_Math-Italic.woff2
KaTeX_SansSerif-Bold.woff2
KaTeX_SansSerif-Italic.woff2
KaTeX_SansSerif-Regular.woff2
KaTeX_Script-Regular.woff2
KaTeX_Size1-Regular.woff2
KaTeX_Size2-Regular.woff2
KaTeX_Size3-Regular.woff2
KaTeX_Size4-Regular.woff2
KaTeX_Typewriter-Regular.woff2
```
A description about those font files will help to know what they are for or what the contain.

**Comment by qlcom** [comment]
looks like `katex.min.css` includes all of them.

**Comment by edemaine** [comment]
Yes, they are all necessary in general. Each serves a corresponding font in LaTeX. For example, `\mathcal` requires the Caligraphic fonts. Do you need a specific breakdown? If you only want to support specific TeX inputs, it'd probably make sense to render them and see which fonts end up being referenced. If you want to support general TeX inputs, you need them all.

**Comment by qlcom** [comment]
> Do you need a specific breakdown?

That will be helpful.

> If you only want to support specific TeX inputs, it'd probably make sense to render them and see which fonts end up being referenced.

How can i do that?

**Comment by kevinbarabash** [comment]
@ghost I believe that the browser will only load the fonts it uses.  If you create a test page that renders a few expressions using KaTeX, open up the browser's developer tools and look at the network tab.  It should show you which files it requested when loading the page.
