### ISSUE TITLE
Safari screenshotter

### ISSUE THREAD

**Issue by ronkok** [KaTeX/KaTeX#2561]
The Safari screenshotter is broken. I have three PRs that currently are shown as having errors purely due to Safari screenshotter disfunction. Even when the Safari screenshotter works, the process is clumsy and tedious.

I think we should get rid of it.

**Comment by ylemkimon** [comment]
If you create a branch in the main repo, i.e., push to `KaTeX/KaTeX`, the screenshotter will run without the need to add the label. I'll work on a PR to allow running screenshotter on PRs from a list of users.

**Comment by ylemkimon** [comment]
#2644 will eliminate the need for manual approval (`test screenshots` label).
