### ISSUE TITLE
Double superscript at position 6: f^{*}'

### ISSUE THREAD

**Issue by q2apro** [KaTeX/KaTeX#2612]
**Describe and reproduce:**

1. Use this Latex: `f^{*}'`
2. See error message: 

> KaTeX parse error: Double superscript at position 6: f^{*}'̲

**Expected behavior:**
Clear rendering since there is not double superscript.

**Screenshots:**

![image](https://user-images.githubusercontent.com/6764548/97256594-1bd49680-181c-11eb-905e-edaf5cd906c4.png)

**Environment (please complete the following information):**
 - KaTeX Version: 0.12.0
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86

**Comment by mbourne** [comment]
In the meantime, this may solve it for you:

![image](https://user-images.githubusercontent.com/7541940/97300088-ed44d300-1890-11eb-8d6d-c4b4abc38a7e.png)

**Comment by q2apro** [comment]
Thanks a lot. ❤

**Comment by edemaine** [comment]
In (La)TeX, `'` is treated as a superscript. For technical reasons, `f'^*` works fine but `f^*'` generates the double subscript error. This is how it is in (La)TeX, so this is how it is in KaTeX. In other words, KaTeX is correctly reproducing (La)TeX behavior.

In addition to @mbourne's workaround, you can use `f^{* \prime}`.  `'` is equivalent to `^{\prime}` which maybe helps explain why it's viewed as a superscript.
