### ISSUE TITLE
Unicode Character Escapes

### ISSUE THREAD

**Issue by stefnotch** [KaTeX/KaTeX#2619]
**Is your feature request related to a problem? Please describe.**
It'd be great if KaTeX supported entering Unicode escapes.

**Describe the solution you'd like:**
`\char"hexcode` or `^^hex` or some other option
https://tex.stackexchange.com/a/545535

**Link to or name of a (La)TeX package that provides the same feature:**
KaTeX's general goal is to render as LaTeX does.

**Describe alternatives you've considered:**
Insert an unescaped Unicode character into the document

**Additional context:**
I was looking for a robust way of inserting arbitrary text into LaTeX. Unicode escaping seems to be one of them.

**Comment by ronkok** [comment]
KaTeX already has the `\char` function. For example, if you write `\char"263a` in the [KaTeX demo](https://katex.org/), it will render as a smiley face.

We do not have that command listed yet in the [support table](https://katex.org/docs/support_table.html). We'll fix that. And maybe also add it to the [letters](https://katex.org/docs/supported.html#letters-and-unicode) section of the support page.

**Comment by ronkok** [comment]
Closed per PR #2620.
