### ISSUE TITLE
Equation not getting converted in katex but mathjax can 

### ISSUE THREAD

**Issue by nisha2107** [KaTeX/KaTeX#2676]
**Describe the bug:**
The following equation is rendered correctly when added in latex component inside editor, but it is not displayed correctly in html. 
Also when i edit this equation in editor the equation is blank with JS error.

i have recorded my screen to show how it is displaying in katex, and screenshot of JS error when Editing.
http://recordit.co/tyUEWEa0ay
![image](https://user-images.githubusercontent.com/17924176/101734357-1b0d7080-3afb-11eb-88c9-9ed1a50b2c8e.png)

**(La)TeX code:**
This below latex is taken from https://katex.org/#demo

The code of (La)TeX you tried to render:
```% \f is defined as #1f(#2) using the macro
\f\relax{x} = \int_{-\infty}^\infty
    \f\hat\xi\,e^{2 \pi i \xi x}
    \,d\xi

```

**Expected behavior:**
this screenshot is using mathjax
![image](https://user-images.githubusercontent.com/17924176/101732926-f0bab380-3af8-11eb-9233-04c8412c4fd4.png)

**Screenshots:**
This below screenshot is result in katex
![image](https://user-images.githubusercontent.com/17924176/101733052-29f32380-3af9-11eb-81b3-16a27054e439.png)

**Environment (please complete the following information):**
 - KaTeX Version: 0.12.0
![image](https://user-images.githubusercontent.com/17924176/101733228-7a6a8100-3af9-11eb-9f0b-8813b51c9bec.png)
 - Device: [ Desktop]
 - OS: [ Windows 10]
 - Browser: [Chrome, Safari]
 - Version: [e.g.  Chrome(87.0), Firefox(78.5)]

**Comment by ronkok** [comment]
CKEditor does not use KaTeX to render math, it uses something called [MathType](http://www.wiris.com/en/mathtype) from Wiris. If you have an issue with something in their math editor, you should raise the issue with CKEditor or Wiris, not with KaTeX.

KaTeX, MathJax, and MathType all emulate LaTeX. For all three, the emulation is incomplete. KaTeX supports some parts that MathJax does not, and vice versa. In your example, it appears that something in a KaTeX expression is not supported by MathType. That is not a KaTeX bug.

More generally, the KaTeX documentation tells you what KaTeX supports. That does not tell you anything about what is supported elsewhere.

And again, if you have an issue with CKEditor, bring it up with them. Leave KaTeX out of it.

**Comment by nisha2107** [comment]
@ronkok 
Though I have already found what what the issue is, let me address few things.
This is not ck-editor issue bcoz when I add equation in ck-editor it is fine but katex is not converting equation in HTML page, which I suppose should be a katex issue.

If you have visited to the website link that I have shared with you, there are macros defined which actually caused the problem. 

Thanks

**Comment by ronkok** [comment]
>  I have already found what what the issue is

Then I'm closing this issue.
