### ISSUE TITLE
incorrect rendering of very large delimiters

### ISSUE THREAD

**Issue by pzinn** [KaTeX/KaTeX#2697]
I have this vague feeling that I've already reported this. if so, apologies but I couldn't find among the issues.
```
\left\{\{\raisebox{-30cm}{}\right\}
```
will produce this (note the gap)
![katex](https://user-images.githubusercontent.com/4632711/102870132-b524cf80-4490-11eb-87f8-da9a1965293a.png)

**Comment by ronkok** [comment]
@pzinn Thank you for raising this issue. I don't believe you have reported this before.

We've had previous trouble with tall delimiters. I'll look into this problem, too.
