### ISSUE TITLE
katex package for LaTeX

### ISSUE THREAD

**Issue by gagern** [KaTeX/KaTeX#272]
In #268 I've made a stab at investigating the differences between LaTeX and KaTeX. Many of these differences should probably considered bugs, but some are intentional. Examples include the possibiluty of using sizing commands in math mode, the additional color commands, and of course the KaTeX package.

Should we create a package called `katex.sty` for LaTeX, which contains all these deviations? The goal would be allowing the same set of formulas to render as similar as possible in both environments.

**Comment by kevinb7** [comment]
Our implementation of ```\color``` is pretty close to ```\textcolor``` from the "color" package.  That package also define ```\color```, but it behaves differently with everything after the command (until end-of-group) becoming that color.  I'm not sure how much work it would be to support sizing commands in math mode in LaTeX.  

In general though, I don't think this is a priority for Khan Academy.  I do however think we should try to move our ```\color``` implementation closer to what the "color" package is doing and add ```\textcolor```.

**Comment by edemaine** [comment]
I implemented `\color` and `\textcolor` as in the color package: #619.  Are there other differences?

**Comment by kevinbarabash** [comment]
If we create an .sty file it would be cool if we could use it in test.tex.  Maybe by exporting an appropriate value for the `TEXINPUTS` environment variable.

**Comment by edemaine** [comment]
Merging this into #793.
