### ISSUE TITLE
Support \dddot from AMSTeX

### ISSUE THREAD

**Issue by stefanspringer1** [KaTeX/KaTeX#2744]
\dddot from AMSTeX = three dots above should be supported. (KaTeX should support AMSTeX as far as possible, I think.)

**Comment by q2apro** [comment]
Is there any workaround how to do \dddot even with Katex?

**Comment by edemaine** [comment]
`\stackrel{\cdot\cdot\cdot}{x}` is not a terrible reproduction.
You can define this as a macro via `{macros: {"\\dddot": "\\stackrel{\\cdot\\cdot\\cdot}{#1}"}}`.

![image](https://github.com/KaTeX/KaTeX/assets/2218736/8325fcee-fefb-44af-b6be-a9823c9cabc2)

Maybe a better version is `\stackrel{\raisebox{-0.2ex}{$\scriptsize\cdot\cdot\cdot$}}{x}`.
Macro version: `{macros: {"\\dddot": "\\stackrel{\\raisebox{-0.2ex}{$\\scriptsize\\cdot\\cdot\\cdot}}{#1}"}}`

![image](https://github.com/KaTeX/KaTeX/assets/2218736/41431361-ad5e-446a-ba07-707d79288769)

**Comment by edemaine** [comment]
Reading AMSTeX's definition of `\dddot`:
```latex
\def\dddot#1{{\mathop{#1}\limits^{\vbox to-1.4\ex@{\kern-\tw@\ex@
 \hbox{\normalfont ...}\vss}}}}
```
a maybe closer reproduction in KaTeX is `\mathop{x}\limits^{\hbox{...}}`
Or `{macros: {"\\dddot": "\\mathop{#1}\\limits^{\\hbox{...}}"}}`

But KaTeX seems to do the italic correction incorrectly, so this doesn't look great with e.g. `A`. Possibly related to #1821.

**Comment by edemaine** [comment]
One more version that fixes the vertical alignment (but still has the italic correction issue):

`{\overset{\raisebox{-0.1ex}{\normalsize ...}}{x}}"`
`{macros: {"\\dddot": "{\\overset{\\raisebox{-0.1ex}{\\normalsize ...}}{#1}}"}}`

![image](https://github.com/KaTeX/KaTeX/assets/2218736/91f1ed89-d2b0-4159-bd08-cf92f9acd748)

Pretty close to LaTeX's rendering:

![ql_1a7a1e0280b1d7ff4b6d093366e52dec_l3](https://github.com/KaTeX/KaTeX/assets/2218736/a84773a3-8c7a-4121-8f8f-6f10657bee1d)

This seems close enough that I'll work it into a PR.
