### ISSUE TITLE
Mathmode inside \tag can not be achieved

### ISSUE THREAD

**Issue by step135** [KaTeX/KaTeX#2756]
```
$$
p+q=r   \tag{$\dagger$}
$$
```
This will fail.

**Comment by ronkok** [comment]
It works in the KaTeX [demo page](https://katex.org/?data=%7B%22displayMode%22%3Atrue%2C%22leqno%22%3Afalse%2C%22fleqn%22%3Afalse%2C%22throwOnError%22%3Atrue%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22warn%22%2C%22output%22%3A%22htmlAndMathml%22%2C%22trust%22%3Afalse%2C%22macros%22%3A%7B%22%5C%5Cf%22%3A%22%231f(%232)%22%7D%2C%22code%22%3A%22p%2Bq%3Dr%20%20%20%5C%5Ctag%7B%24%5C%5Cdagger%24%7D%22%7D).
