### ISSUE TITLE
\hline not working at end of line

### ISSUE THREAD

**Issue by MisterAI** [KaTeX/KaTeX#2761]
Maybe my understanding of `\hline` is incorrect but if I use the following code (at https://katex.org/):
```
\begin{array}{|c|}
\hline a\\
b\hline\\
\end{array}
```
I get the following error: 
> KaTeX parse error: \hline valid only within array environment

What I would expect to get there is an _a_ over a _b_ with a frame around it. Is my use of `\hline` incorrect or is this an error in KaTeX?

**Comment by edemaine** [comment]
I believe `\hline` can only appear at the beginning or immediately after a `\\`. The correct form of the above would be:
```latex
\begin{array}{|c|}
\hline a\\
b\\ \hline
\end{array}
```

This works in KaTeX. If you find that LaTeX disagrees with KaTeX, please open a bug report, but I think they match in this respect (though the error message could clearly be more useful).

**Comment by MisterAI** [comment]
Thanks for this hint. It works and seems to be concordant to LaTeX
