### ISSUE TITLE
Unnecessary space when typing \cdots between parenthesis

### ISSUE THREAD

**Issue by Gareth618** [KaTeX/KaTeX#2773]
Hi, I've noticed that if you write `(\cdots)`, KaTeX generates a little annoying space between `\cdots` and `)`. This is available also for the other kind of parenthesis (`)`, `]`, `\}`, `\rangle`), but the issue disappeares when `\cdots` is replaced by `\ldots`.

[https://imgur.com/a/O31k1D5](https://imgur.com/a/O31k1D5)

I hope you can solve this bug :)

**Comment by ronkok** [comment]
The same space appears in LaTeX. I doubt that we will depart from LaTeX behavior in this instance.

You can suppress the operator spacing by wrapping `\cdots`  in a pair of braces, as in`f({\cdots})`
