### ISSUE TITLE
rander error in jodit

### ISSUE THREAD

**Issue by sid-ihycq** [KaTeX/KaTeX#2775]
i use katex(lastest version) in [jodit](https://github.com/xdan/jodit) with [angular-jodit](https://github.com/jodit/jodit-angular).
when i insert a new formula through:
 ```
editor.s.insertHTML(katex.renderToString('c` = \\pm\\sqrt{a^2 + b^2}'));
```
but in my project the 1st second it's ok and suddenly it's misplace at all. 

![image](https://user-images.githubusercontent.com/34854879/107014768-04238b80-67d7-11eb-94e4-c9dfa1c7b2dd.png)

track the events can find that it was triggered twice,  1st time it renderes the generated html, and at the 2nd time,  the content was changed to bellow:
```
<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>c</mi><mo>=</mo><mo>±</mo><msqrt><mrow><msup><mi>a</mi><mn>2</mn></msup><mo>+</mo><msup><mi>b</mi><mn>2</mn></msup></mrow></msqrt></mrow><annotation encoding="application/x-tex">c = \pm\sqrt{a^2 + b^2}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="mord mathnormal">c</span><span class="mrel">=</span></span><span class="base"><span class="mord">±</span><span class="mord sqrt"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.913389em;"><span class="svg-align" style="top:-3em;"><span class="mord" style="padding-left:0.833em;"><span class="mord"><span class="mord mathnormal">a</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.740108em;"><span style="top:-2.9890000000000003em;margin-right:0.05em;"><span class="sizing reset-size6 size3 mtight"><span class="mord mtight">2</span></span></span></span></span></span></span></span><span class="mbin">+</span><span class="mord"><span class="mord mathnormal">b</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.740108em;"><span style="top:-2.9890000000000003em;margin-right:0.05em;"><span class="sizing reset-size6 size3 mtight"><span class="mord mtight">2</span></span></span></span></span></span></span></span></span></span><span style="top:-2.873389em;"><span class="hide-tail" style="min-width:0.853em;height:1.08em;"><svg width="400em" height="1.08em" viewBox="0 0 400000 1080" preserveAspectRatio="xMinYMin slice"><path d="M95,702
c-2.7,0,-7.17,-2.7,-13.5,-8c-5.8,-5.3,-9.5,-10,-9.5,-14
c0,-2,0.3,-3.3,1,-4c1.3,-2.7,23.83,-20.7,67.5,-54
c44.2,-33.3,65.8,-50.3,66.5,-51c1.3,-1.3,3,-2,5,-2c4.7,0,8.7,3.3,12,10
s173,378,173,378c0.7,0,35.3,-71,104,-213c68.7,-142,137.5,-285,206.5,-429
c69,-144,104.5,-217.7,106.5,-221
l0 -0
c5.3,-9.3,12,-14,20,-14
H400000v40H845.2724
s-225.272,467,-225.272,467s-235,486,-235,486c-2.7,4.7,-9,7,-19,7
c-6,0,-10,-1,-12,-3s-194,-422,-194,-422s-65,47,-65,47z
M834 80h400000v40h-400000z"></path></svg></span></span></span></span><span class="vlist-r"><span class="vlist" style="height:0.12661100000000003em;"></span></span></span></span></span></span></span>

```

hope for good news! tks!

**Comment by ronkok** [comment]
I suspect some sort of CSS collision. If you will give us a link to a page or perhaps a [JSFiddle](https://jsfiddle.net/), we could take a look and perhaps help.

**Comment by sid-ihycq** [comment]
i create a simple demo on [JSFiddle](https://jsfiddle.net/f3sktbpw/), click the button '┇‘ then can see a sub button insertFormula.
![image](https://user-images.githubusercontent.com/34854879/107106221-6cb94980-6865-11eb-9c87-a938558f5502.png)

please check it, tks!

**Comment by ronkok** [comment]
@sid-ihycq Thank you for the JSFiddle. You are correct in saying that the math is rendered twice, first correctly, then incorrectly. 

KaTeX vertical alignment uses an invisible strut that consists of an empty span element with a defined height. In the square root radical of your example, that nested element is : `<span class="pstrut" style="height: 3.2em;"></span>`. 

Jodit is deleting that `pstrut` span. Without the strut, the radical is aligned too high. Struts like this one are used to set vertical alignment of every KaTeX fraction, exponent, subscript, and accent. Without the struts, they will be rendered incorrectly. 

I don't think there is much that this library can to do when another program reaches in and deletes spans inside the KaTeX HTML.

**Comment by sid-ihycq** [comment]
i have resolved this finally!
At first, use option below can avoid jodit's removal. 
`cleanHTML: {
        removeEmptyElements: false,
},` 
Then, when insert a katex formula html code, add attr contenteditable="false" to the root(<span class="katex'>) .
