### ISSUE TITLE
How does $..$ work in this example

### ISSUE THREAD

**Issue by nszbf** [KaTeX/KaTeX#2805]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
This seems to be a simple question, but for me, I looked up a lot of documents and issues and found no answer, sry&thk 😭

**To Reproduce:**
1. Go to  example   [https://codesandbox.io/s/katex-hilsi?file=/index.html](https://codesandbox.io/s/katex-hilsi?file=/index.html)
2. On lines 40 and 43

or:

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css">
	<style>
		.katex .katex-mathml{
			position: relative;
			display: block;
			width:auto;
			height:auto;
			margin-bottom:10px;
			clip: inherit;
		}
	</style>
</head>
<body>
	<div id="a"></div>
	<script src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js"></script>
	<script>
		renderMathInElement(document.body, {
			delimiters: [
				{left: '$', right: '$', display: false},
				{left: '$$', right: '$$', display: true},
				{left: '\\(', right: '\\)', display: false},
				{left: '\\[', right: '\\]', display: true}
			]
		})
		// 没有 $ 是好的
		// 问: 加上 $ 的配置该怎么写
		// Q: how to add the $configuration

		// const str = "\\sqrt{a} - \\sqrt{b}"
		const str = "$\\sqrt{a} - \\sqrt{b}$"
		const opts = {
			displayMode: true,
			throwOnError: true,
			output: 'htmlAndMathml'
		}
		katex.render(str, document.querySelector('#a'), opts)

		const ret = katex.renderToString(str, opts)
		console.log(ret)
	</script>
</body>
</html>
```

**Expected behavior:**
its work

**Screenshots:**

![image](https://user-images.githubusercontent.com/16892834/108702996-f85cf680-7544-11eb-9061-86f6ad28d489.png)

**Environment (please complete the following information):**
 - KaTeX Version: 0.12.0
 - Device: Desktop
 - OS: MacOs
 - Browser: Chrome
 - Version: 88

**Comment by nszbf** [comment]
```javascript
const opts = {
	displayMode: true,
	throwOnError: true,
	output: 'htmlAndMathml',
	macros: {
		"$": ""
	}
}
```
It can be done with macros, but is this a good solution?

**Comment by mattford** [comment]
What happens if you put the $ and $$ delimiters the other way round?

```
renderMathInElement(document.body, {
    delimiters: [
        {left: '$$', right: '$$', display: true},
	{left: '$', right: '$', display: false},
	{left: '\\(', right: '\\)', display: false},
	{left: '\\[', right: '\\]', display: true}
     ]
})
```

**Comment by nszbf** [comment]
@mattford  It doesn't work，You can try it in this demo [https://codesandbox.io/s/katex-hilsi?file=/index.html](https://codesandbox.io/s/katex-hilsi?file=/index.html)

**Comment by edemaine** [comment]
You can't (yet) pass the `$` wrappers to `katex.render` or `katex.renderToString`. Instead you should pass the option `displayMode: false` to indicate that type of rendering.

**Comment by ssssshql** [comment]
请问这个问题解决了吗，我困惑了一晚上。不管怎么设置都是显示数学模式下不能使用$

**Comment by ssssshql** [comment]
> 请问这个问题解决了吗，我困惑了一晚上。不管怎么设置都是显示数学模式下不能使用$

已经解决了，需要使用renderMathInElement配置delimiters才行
