### ISSUE TITLE
Katex + Remark.js: Equation with curly brackets in super- and subscript don't render correctly

### ISSUE THREAD

**Issue by ConstantinGahr** [KaTeX/KaTeX#2842]
Formulas with super- and subscripts, where both contain curly brackets don't render correctly:
- renders correctly: `\\[u^{j+1}_{n+1} \\]`
- renders correctly: `\\[u^{j+1}_{n+1} - u^{j+1}_n\\]`
- doesn't renders correctly: `\\[u^{j+1}_{n+1} - u^{j+1}_{n}\\]`
- doesn't renders correctly: `\\[u^{j+1}_{n+1} - u^{j+1}_{n-1}\\]`

I'm using Katex 0.13.0 together with remark.js.

Here is a minimum (not) working example:
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Title</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <style type="text/css">
            /* Slideshow styles */
        </style>
    </head>
    <body>
        <textarea id="source">

# Test

- renders correctly:
\\[u^{j+1}_{n+1} \\]

- renders correctly:
\\[u^{j+1}_{n+1} - u^{j+1}_n\\]

- doesn't renders correctly:
\\[u^{j+1}_{n+1} - u^{j+1}_{n}\\]

- doesn't renders correctly:
\\[u^{j+1}_{n+1} - u^{j+1}_{n-1}\\]

    </textarea
        >
        <script src="https://gnab.github.io/remark/downloads/remark-latest.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.0/katex.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.0/contrib/auto-render.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.13.0/katex.min.css" />
        <script type="text/javascript">
            var options = {};
            var renderMath = function () {
                renderMathInElement(document.body);
            };
            var slideshow = remark.create(options, renderMath);
        </script>
    </body>
</html>

```

**Comment by edemaine** [comment]
This probably has to do with how Remark is processing `_`s to do italics. If it's a bug, it's with Remark, and you should post there. But more likely it has to do with running KaTeX on the result of Remark's output, instead of using a KaTeX plugin for Remark that processes both at once (if such a plugin exists).  You can test my theory by escaping the `_`s as `\_`.

**Comment by ConstantinGahr** [comment]
You are correct, escaping the underscores fixes the problem. Thank you!

You wrote that there is a Katex Plugin for Remark. Can you give me a hint where I can find this plugin?

**Comment by edemaine** [comment]
I don't know anything beyond a Google search for 'remark katex':
* https://github.com/remarkjs/remark-math
* https://www.gatsbyjs.com/plugins/gatsby-remark-katex/
