### ISSUE TITLE
rendering not as expected

### ISSUE THREAD

**Issue by HerbertHe** [KaTeX/KaTeX#2855]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**

Tex content:

```latex
\widetilde{E}_1 = A_1e^{kd_1 - \varphi_{01}} = A_1e^{i\theta_1}
```

But it rendered as followed:

![image](https://user-images.githubusercontent.com/30955264/112083921-cab39f00-8b3c-11eb-9819-425a063ab1a0.png)

This part seems not correct

![image](https://user-images.githubusercontent.com/30955264/112084281-634a1f00-8b3d-11eb-9407-f58672be25d5.png)

DOM as followed:

![image](https://user-images.githubusercontent.com/30955264/112084237-4d3c5e80-8b3d-11eb-8883-92e430bb8c53.png)

> It seems that the bug caused by font family???

**To Reproduce:**

Just as above.

**Expected behavior:**

The font height of Greek letter is equal to the Latin, or would cause misunderstanding!

**Screenshots:**

Just as above.

**Environment (please complete the following information):**
 - KaTeX Version: Latest
 - Device: Desktop
 - OS: Win10
 - Browser: Edge chromium
 - Version: Latest

**Additional context:**
Add any other context about the problem here. If you're using a library to use KaTeX, please include its name and setup.

**Comment by edemaine** [comment]
Here's how your example renders in actual LaTeX:

![image](https://user-images.githubusercontent.com/2218736/113490751-3b8e7b80-949a-11eb-912c-cc60c7795bbc.png)

If I zoom into the KaTeX demo (in Chrome, but I think Edge should be the same), it looks about the same:

![image](https://user-images.githubusercontent.com/2218736/113490776-6678cf80-949a-11eb-939e-c5b82a2ed321.png)

So I think the rendering defect you're seeing is just from a low zoom level, and this isn't a bug.  Unless I'm missing something?

**Comment by HerbertHe** [comment]
I don't know why it displays well now. In the above, the screenshots show that the height of Latin letters are equal to the number before. And it could cause misunderstanding that looks like subscript. 

Thanks for your reply.

**Comment by edemaine** [comment]
Ah, it seems to be a minimum font size issue with browsers. See #2878.
