### ISSUE TITLE
readme in 0.13.1 tarball has info for 0.13.0 in starter template section

### ISSUE THREAD

**Issue by qtfkwk** [KaTeX/KaTeX#2904]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
README.md in the 0.13.1 tarball released today has the info (versions and sha384's) for 0.13.0.

**To Reproduce:**
1. Download https://github.com/KaTeX/KaTeX/releases/download/v0.13.1/katex.tar.gz
2. Extract it
3. Open README.md
4. See the old info in the Starter template section

**Expected behavior:**
README.md should be updated (as it is currently is in master branch at https://github.com/KaTeX/KaTeX/blob/master/README.md) prior to releasing.

**Screenshots:**
N/A

**Environment (please complete the following information):**
 - KaTeX Version: 0.13.1
 - Device: any
 - OS: any
 - Browser: any
 - Version: N/A

**Additional context:**
N/A

**Comment by ylemkimon** [comment]
Thank you for reporting this!

**Comment by qtfkwk** [comment]
Confirm fixed... thanks!
