### ISSUE TITLE
Docu site: broken links on 404 page

### ISSUE THREAD

**Issue by deining** [KaTeX/KaTeX#2907]
On the docu site, try to call a non existing page, like

https://katex.org/docs/foo

The 404 error page shows up:

![image](https://user-images.githubusercontent.com/18169566/113728772-a936e380-96f6-11eb-9292-d97bc3e7b88d.png)

The two links `Installation` and `Documentation` are broken and should be fixed.

**Comment by ylemkimon** [comment]
They should be absolute paths. Thank you!
