### ISSUE TITLE
docs (copy-tex): outdated info on clipboard support in Edge browser

### ISSUE THREAD

**Issue by deining** [KaTeX/KaTeX#2912]
**Documentation, copy tex**

https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex#known-issues

This paragraph `Known issues` states:

`Microsoft Edge does not seem to support text and HTML content in a single clipboard.`

This information is outdated:

* The link in this paragraph  given as reference is a **broken link**.
* The correct [link](https://developer.microsoft.com/en-us/microsoft-edge/status/clipboardapi/) states that clipboard api actually **is** supported by Microsoft Edge.

One should verify clipboard support in Edge and correct/remove the incorrect text passage afterwards.

**Comment by edemaine** [comment]
I tested this out and indeed copy/paste in Edge works the same as Chrome (perhaps not surprising given the move to Chromium). PR #2917 removes this paragraph.
