### ISSUE TITLE
docs: search functionality partly broken 

### ISSUE THREAD

**Issue by deining** [KaTeX/KaTeX#2913]
**Documentation:**

https://katex.org/docs/api.html

Type an arbitrary search phrase into the search input field, e.g. `auto-render`.

A list with 5 occurrences of àuto-render` is presented. Click on the link given in the first row. This forwards you to a non existing page:

https://katex.org/docs/0.10.1/autorender.html#docsNav

**Comment by ylemkimon** [comment]
Thank you for the report! We're using an external search engine, Algolia DocSearch, and since we removed versioned docs, it seems it couldn't index our documentation. I've sent a pull request at https://github.com/algolia/docsearch-configs/pull/3932.

**Comment by ylemkimon** [comment]
The issue should be resolved now. Thanks again.
