### ISSUE TITLE
\binom parentheses too big in \scriptscriptstyle

### ISSUE THREAD

**Issue by Artoria2e5** [KaTeX/KaTeX#2973]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
The `\binom` in ` \sum_{\vec a\in \mathbb{N}^{\binom {d}{2}}}` is way too tall.

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
\displaystyle \sum_{\vec a\in \mathbb{N}^{\binom {d}{2}}}
```

The snippet is minimized from https://en.wikipedia.org/wiki/Solid_angle#Solid_angles_in_arbitrary_dimensions. (Okay it can actually get smaller.)

**Expected behavior:**
![quicklatex](https://quicklatex.com/cache3/1b/ql_34badb85bd82c88f551d3e360540fa1b_l3.png)

(Oops, GitHub made it transparent! Switch to day mode please. Or just open image in new tab.)

**Screenshots:**
<img width="130" alt="Screen Shot 2021-05-01 at 18 22 29" src="https://user-images.githubusercontent.com/6459309/116779663-32e59100-aaaa-11eb-8085-19a153617c17.png">

**Environment (please complete the following information):**
 - KaTeX Version: "0.13.3"
 - Device: Desktop
 - OS: macOS 11
 - Browser: Cr 
 - Version: 90.0.4430.93

**Comment by edemaine** [comment]
I'm guessing this is an issue with the paren sizing in `\binom` (internally, `genfrac`) when in `\scriptscriptstyle`.  @ronkok, do you have any ideas?
