### ISSUE TITLE
Too strict about accents in math mode

### ISSUE THREAD

**Issue by Artoria2e5** [KaTeX/KaTeX#2983]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
Does not admit `\mathrm{\AA}` even in non-strict. It's a bad idea, but current LaTeX takes it fine.

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
\mathrm{\AA}
```

**Expected behavior:**
Should get the Å sign with warnings. LaTeX on overleaf will complain a bit, tell me about how it's hoping that replacing `\accent` with `\mathaccent` will work out, but it does work out.

**Screenshots:**
```
KaTeX parse error: Can't use function '\r' in math mode at position 1: \̲r̲ ̲A
```

**Environment (please complete the following information):**
 - KaTeX Version: 0.13.5
 - Device: Desktop
 - OS: Windows 10
 - Browser: Cr
 - Version: 90

**Additional context:**
Part of #2876. Not something I would normally write, since Unicode feels better and `\text` is a thing.

The parse error is honestly a bit hard to get, since it's complaining about the result of macro expansion.

**Comment by edemaine** [comment]
It's true that LaTeX only generates a warning:
```
LaTeX Warning: Command \r invalid in math mode on input line 5.
```
We should probably use `strict` for this (and for #2876 you probably want to use `{strict: false}`).
