### ISSUE TITLE
Wide indices of integrals with "\limits" overlap

### ISSUE THREAD

**Issue by stefanspringer1** [KaTeX/KaTeX#2986]
In the following example the content of the indices overlap:

```latex
\int\limits^x_{y + 4 - a} \int\limits^x_{y + 4 - a}
```

This should not happen. There even should some spacing between the indices from different integral signs.

Screenshot:

<img width="110" alt="Bildschirmfoto 2021-05-05 um 16 10 32" src="https://user-images.githubusercontent.com/5261689/117154781-7a2a9500-adbc-11eb-9d13-c8479e2c45c3.png">

 - KaTeX Version: on https://katex.org May 5th 2021
 - Platform: Safari 14.1 on macOS 11.3 on Apple Silicon, but also seen on Windows. Seems to be a general issue.

Note that this does not happen with sums.

**Comment by edemaine** [comment]
Indeed. For comparison, here's how that text renders on QuickLaTeX:

![image](https://user-images.githubusercontent.com/2218736/117156904-243df900-ad8c-11eb-812c-14c05afffe4e.png)

**Comment by ronkok** [comment]
> Note that this does not happen with sums.

The integration symbol has a italic slant. So KaTeX nudges the lower limit to the left a little bit via a CSS negative margin. We probably need to correct for that by applying a positive margin to the overall integrand group. I'll look into it.
