### ISSUE TITLE
Safari screenshotter often breaks

### ISSUE THREAD

**Issue by edemaine** [KaTeX/KaTeX#3012]
Most PRs (and when I merge to master branch) requires clicking "re-run tests" 2-3 times to get the Safari screenshotter tests to work.

It seems to fail on the `Includegraphics` test most often, perhaps because of the web fetch it needs to do. Perhaps we should remove that test, ~~or make the URL it loads a local file on the tester~~? Oops, it's already a local file. I'm not sure why Safari fails at this -- perhaps a race condition?

**Comment by ylemkimon** [comment]
I think we should disable `Includegraphics` test on Safari.

**Comment by edemaine** [comment]
Ah, that would be a simpler solution. 🙂 Screenshotter already has an `-x`/`--exclude` option, so this should be easy to do.
