### ISSUE TITLE
Need "delimeter" option in "katex.renderToString()" method

### ISSUE THREAD

**Issue by rishadbaniya** [KaTeX/KaTeX#3014]
It seems that the option for delimeter is not available in ``` katex.renderToString()``` method but is available for ```katex.renderMahInElement()```

I want this to work
```
    let katexHTML = katex.renderToString(String.raw`$\text{hello}$ $\frac{1}{2}$ `, {
          delimiters: [
              {left: '$$', right: '$$', display: true},
              {left: '$', right: '$', display: false},
              {left: '\\(', right: '\\)', display: false},
              {left: '\\[', right: '\\]', display: true}
          ],
          throwOnError : false
        });
```
**But idk why it doesnt work when i pass that the html into a div in react as**
```
  <div dangerouslySetInnerHTML={{ __html: katexHTML }}></div>
```

**Comment by edemaine** [comment]
`renderToString` is just for a single math expression.  Unfortunately, there isn't an interface in auto-render for rendering to string.  Probably we should have one, and maybe a good time to revisit it.  This is equivalent to #604 though, so moving discussion there.
