### ISSUE TITLE
bmatrix with spaces

### ISSUE THREAD

**Issue by nschloe** [KaTeX/KaTeX#3031]
I found an weird bug with [Purple Pi](https://github.com/nschloe/purple-pi?activate). Try
```markdown
$$
A = \begin{bmatrix}
   a & b \\\\
   c & d(INSERTSPACEHERE)
\end{bmatrix}
$$
```
When inserting two or more spaces at `(INSERTSPACEHERE)`, it won't render as math. I'm not sure if it's KaTeX or not, so I'd be glad if you could try it out elsewhere.

\\[
a + b = c
\\]

No spaces:
$$A = \begin{bmatrix}   a & b \\\\   c & d\end{bmatrix}$$
One space:
$$
A = \begin{bmatrix}
   a & b \\\\
   c & d 
\end{bmatrix}
$$
Two spaces:
$$
A = \begin{bmatrix}
   a & b \\\\
   c & d  
\end{bmatrix}
$$

**Comment by nschloe** [comment]
Nothing renders now, investigating.

**Comment by nschloe** [comment]
Closing, I'll reopen once I can reliably reproduce it.

**Comment by edemaine** [comment]
Definitely seems like a Purple Pi issue.  The examples with spaces work fine on katex.org.
