### ISSUE TITLE
Support for \setcounter

### ISSUE THREAD

**Issue by davidneira92** [KaTeX/KaTeX#3048]
Hello everyone, I would like to request support for `\setcounter`, specifically `\setcounter{equation}`. It would be nice to have the possibility of renumbering equations inside the `align` environment. In my particular case, I need to keep track of the equation counter across different KaTeX blocks, instead of having it reset to zero on each block.

**Comment by edemaine** [comment]
I believe your request for `\setcounter{equation}` is roughly #2380.

Currently, we use CSS-based counters, so you should be able to manually control the counter via a CSS rule like
```css
body { counter-reset: katexEqnNo mmlEqnNo }
```
(or you can use a smaller level than `body`)

If you're getting the counter resetting to zero between KaTeX calls, that sounds like a bug &mdash; I think we may need to add this rule to KaTeX's CSS.
