### ISSUE TITLE
Invalid box-sizing property in .katex .angl css class

### ISSUE THREAD

**Issue by klittlepage** [KaTeX/KaTeX#3052]
**Describe the bug:**

As seen [here](https://github.com/KaTeX/KaTeX/blob/2f62c0d8ee8135f4d5b7fe727add6ad25d5c86a0/src/katex.less#L596) the `.angl` class contains a non-existent property value for `border-box`. Judging from the context it should be `content-box`. I'm happy to open a PR if anyone can confirm that it should indeed be `content-box` and not `border-box`.

```
.angl {
    // from package actuarialangle, which is always used in a subscript.
    box-sizing: border-content;       // NON-EXISTENT css property
    border-top: 0.049em solid;        // defaultRuleThickness in scriptstyle
    border-right: 0.049em solid;      // ditto
    margin-right: 0.03889em;          // 1 mu
}
```

**To Reproduce:**
NA

**Expected behavior:**
Stylesheets to include [W3C valid properties](https://drafts.csswg.org/css-ui-3/#propdef-box-sizing): `content-box | border-box`.

**Comment by ronkok** [comment]
@klittlepage You are correct. I meant that property to be `border-box`. Good catch.

**Comment by klittlepage** [comment]
@ronkok I [opened a PR](https://github.com/KaTeX/KaTeX/pull/3053) to fix this issue and updated the screenshot test for Chrome and Safari following the procedures [here](https://github.com/KaTeX/KaTeX/pull/3053). I'm unable to get the build artifacts for Safari seeing as the build fails and there doesn't appear to be a means for running it locally sans a BrowserStack API key. Do you know a path forward?
