### ISSUE TITLE
\bar doesn't always have correct italic correction

### ISSUE THREAD

**Issue by edemaine** [KaTeX/KaTeX#3082]
**Describe the bug:**
Stacking accents such as `\bar{\bar{...}}` does not do the proper italic correction on the outer accent. This was originally reported [on StackOverflow](https://stackoverflow.com/questions/60324630/how-can-i-make-double-bars-align-vertically-over-a-variable-in-katex-they-are-o).

**To Reproduce:**
1. Go to https://katex.org
2. Enter `\bar{\bar{X}}`

**Expected behavior:**
LaTeX produces the following:
![image](https://user-images.githubusercontent.com/2218736/122131172-c549b600-ce06-11eb-90f4-cf1aebfa83a1.png)

**Screenshots:**
KaTeX produces the following:
![image](https://user-images.githubusercontent.com/2218736/122131241-e14d5780-ce06-11eb-8d6a-8e50b7b659b8.png)

**Environment (please complete the following information):**
 - KaTeX Version: 0.13.11
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91

**Additional context:**
A workaround is to use `\overline`. `\overline{\overline{X}}` renders as
![image](https://user-images.githubusercontent.com/2218736/122131520-4608b200-ce07-11eb-8339-23f9a9851fc4.png)

**Comment by ronkok** [comment]
I suspect the root cause is the same here as #1821.

**Comment by edemaine** [comment]
Oops, indeed. I totally forgot about that issue, despite having commented there. 🙂 I'll merge this into #1821 then.
