### ISSUE TITLE
Switch from Less to SCSS?

### ISSUE THREAD

**Issue by edemaine** [KaTeX/KaTeX#3116]
SCSS seems to be far more popular than Less these days (in the same way that TypeScript is generally favored over Flow now, see #2110). For example, Bootstrap migrated from Less to SCSS between versions 3 and 4.

Distributing SCSS style files (ideally also a version in `dist` so that the fonts path is correct relatively, but could also be overridable) would make it easier to include KaTeX in e.g. Webpack configurations that are already configured for SCSS. See #547 and #3115.

I don't think we use (m)any features where Less and SCSS differ, so the transition should be fairly easy, if we agree it's a good idea.

**Comment by grigoriy-reshetniak** [comment]
@edemaine have you considered migration to plain CSS? There's not so many styles in KaTeX and some features like nesting and variables are supported by CSS.

**Comment by edemaine** [comment]
I don't think we could implement the toggling features in [fonts.less](https://github.com/KaTeX/KaTeX/blob/main/src/fonts.less) without a preprocessor.

That said, we could use CSS variables where possible so that our built `.css` files are still overridable to some extent.

Can CSS variables be used to specify `font-folder`? I'm guessing not...
