### ISSUE TITLE
Not all colors defined in macros.js working

### ISSUE THREAD

**Issue by udaypandey** [KaTeX/KaTeX#3119]
> Before reporting a bug
- [X] Check [common issues](https://katex.org/docs/issues.html).
- [X] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [X] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**

In `macros.js`, quite a few colors are defined but when I try using them on katex.org demo, only few of them are being rendered in the right color and rest are only being render in default black.

**To Reproduce:**
1. Go to 'https://katex.org'

2. Type in the following

```
\textcolor{blue}{ 42 } \\
\textcolor{red}{ 42 }   \\
\textcolor{redA}{ 42 } \\
\textcolor{greenA}{ 42 }
```
3. The first 2 lines are rendered in the right color but the last two are rendered in default black. No error is thrown for missing color name.

**Expected behavior:**

All colors defined in macros.js should work.

**Screenshots:**

<img width="803" alt="Screenshot 2021-07-14 at 21 08 51" src="https://user-images.githubusercontent.com/27879/125686194-fb152a08-1de3-4c74-9ae3-d51d767909d8.png">

**Comment by edemaine** [comment]
`\redA` is a macro; `redA` is not a color. The correct usage is `\redA{42}`.

However, the plan is to remove all of these macro definitions (see #28) so you shouldn't be using these.
