### ISSUE TITLE
html attributes raises error when followed by some functions: Unexpected end of input in a macro argument

### ISSUE THREAD

**Issue by summersz** [KaTeX/KaTeX#3128]
The following error is received when calling certain functions, e.g. \frac, immediately after a html attribute:

`KaTeX parse error: Unexpected end of input in a macro argument, expected '}' at position....`

Error occurs with:

`\htmlId{id}\frac{a}{b}`

but not with:

`\htmlId{id}\sigma`

![image](https://user-images.githubusercontent.com/7293216/126627495-6394f0f8-1003-4c46-9216-22f8cd50f1e9.png)

This error does not occur when using KaTeX version 0.12.

**Comment by edemaine** [comment]
@summersz This is a consequence of a change in how macro arguments get parsed; see #2490 (linked from [the changelog](https://github.com/KaTeX/KaTeX/blob/master/CHANGELOG.md#v0130)). You now need to wrap the second argument, like so:
```latex
\htmlId{id}{\frac{a}{b}}
```

This change was made to better match how TeX actually parses arguments. I just confirmed that e.g. `\textcolor{red}\frac{a}{b}` does not work in LaTeX, even though `\sqrt\frac{a}{b}` does.
