### ISSUE TITLE
A tool to convert LaTeX to Katex! 

### ISSUE THREAD

**Issue by ahmedfarrag17** [KaTeX/KaTeX#3137]
I've noticed that not all commands of LaTeX for maths formulas especially, are compatible with Katex.

So is there a tool/software that can convert LaTeX formulas into Katex (when it's possible), so I can copy Katex math formula and past it in apps that only rely on Katex as input for LaTeX formulas?

On the main page (https://katex.org/) the LaTeX expressions that I put are rendered correctly with Katex, but I need their full syntax.

Thank you!

**Comment by edemaine** [comment]
@ahmedfarrag17 If the formula works on the katex.org demo page, then it's supported by KaTeX. If it's not working on a different site, probably it's using an old version of KaTeX, or it's not passing the right thing into KaTeX. (You originally included an example with `\begin{equation}` which didn't use to be supported by KaTeX, so some parsers won't recognize it. You could try wrapping it in `$$`s.)

I don't think there's much of LaTeX math mode that could be converted to KaTeX, other than what's already supported by KaTeX (see [the support table](https://katex.org/docs/support_table.html) and [supported functions](https://katex.org/docs/supported.html)). If you want to request support for a specific feature, please open a new issue specific to that.

**Comment by deadhitter1** [comment]
I'm trying to get KaTeX to LaTeX. It renders correctly on StackEdit.io, but throws an error in the demo. 
For example, the demo doesn't like /hypertarget.
No converter exists, meaning I have to rewrite everything by hand in LaTeX.
