### ISSUE TITLE
What is the recommended way to globally define macros?  (also, that take arguments)

### ISSUE THREAD

**Issue by hrbigelow** [KaTeX/KaTeX#3165]
> Before requesting a feature, please search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

I was reading through [https://github.com/KaTeX/KaTeX/issues/2070](https://github.com/KaTeX/KaTeX/issues/2070) and have successfully used the technique mentioned there to define global macros that take arguments:

```javascript
    let macros = {
      '\\B': '\\boldsymbol{#1}',
      '\\proj': '#1_{\\small \\parallel #2}'
    };
    document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          macros: macros,
          
          // customised options
          // • auto-render specific keys, e.g.:
...
```

Since the post is a few years old, I wonderedi f there some HOWTO or update that I should also read.

Thanks very much!

**Comment by edemaine** [comment]
Thanks for checking in.  That is still the recommended method.
