### ISSUE TITLE
Inconsistent treatment of "&" character in macro arguments

### ISSUE THREAD

**Issue by mattvague** [KaTeX/KaTeX#3185]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
Custom macros defined with `\newcommand`, e.g. `\newcommand{\testMacro}[1]{#1}` seem to work fine when passed `&` characters as arguments, but macros defined as functions and even builtin macros throw an `Expected 'EOF', got '&' at position` error.

**To Reproduce:**

This example works: 
```
\newcommand{\testMacro}[1]{#1}

\begin{aligned}
  a + b &= c² \\
  \testMacro{
    &= d + e
  }
\end{aligned}
```

But this example throws the error `Expected 'EOF', got '&' at position`:

```
\begin{aligned}
  a + b &= c² \\
  \htmlData{test=test}{
    &= d + e
  }
\end{aligned}
```

I experimented a bit and it seems to be limited to macros with function definitions instead of string definitions), but not totally sure about that.

**Expected behavior:**
I'm actually not sure what should happen (if it should be allowed in both cases or an error in both cases), but I think it should probably be consistent no?

**Comment by edemaine** [comment]
I believe the issue is just whether the contents are getting wrapped in a rendering element.  `\htmlData` needs to wrap everything in a `<span>`.  `\mathbf{&= d + e}` similarly fails, because it needs to wrap in a bold environment.  Even `{&= d + e}` fails, because it's wrapped in a group.  I believe this exactly matches how LaTeX works, but if you find a counterexample, let us know.

**Comment by mattvague** [comment]
>I believe the issue is just whether the contents are getting wrapped in a rendering element. \htmlData needs to wrap everything in a <span>. \mathbf{&= d + e} similarly fails, because it needs to wrap in a bold environment. Even {&= d + e} fails, because it's wrapped in a group. I believe this exactly matches how LaTeX works, but if you find a counterexample, let us know.

Hmm ok, that makes sense. Sorry to bug ya then!
