### ISSUE TITLE
U+2212 (minus, `−`) used in input renders with too little space

### ISSUE THREAD

**Issue by rriegs** [KaTeX/KaTeX#3225]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
KaTeX and LaTeX math-mode with unicode-math both accept U+2212 (minus, `−`) in place of the more typical U+002D (hyphen-minus, `-`), rendering both as U+2212 in the output. KaTeX, however, appears to give the symbol `\mathord` spacing (i.e., no space between it and neighboring symbols) rather than the appropriate `\mathop` spacing, as is obtained with unicode-math or when inputting U+002D instead.

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
a − b
```

**Expected behavior:**
The output should have space between the operator and operands, or roughly *a* − *b* instead of *a*−*b*. See, for example, [texrender (MathJax)](http://www.texrendr.com/?eqn=a%20%E2%88%92%20b) and [KaTeX with U+002D](https://katex.org/?data={%22code%22%3A%22a%20-%20b%22}) versus [KaTeX with U+2212](https://katex.org/?data={%22code%22%3A%22a%20%E2%88%92%20b%22}).

**Environment (please complete the following information):**
 - KaTeX Version: 0.13.17 (presumably; whatever https://katex.org/#demo is using)
 - Device: Laptop
 - OS: Ubuntu 20.04.3 LTS
 - Browser: Firefox
 - Version: 91.0.2

**Comment by edemaine** [comment]
@rriegs Thanks for the report. There turns out to be an easy fix for this, which I've put together as PR #3227.
