### ISSUE TITLE
parseTree to latex expression

### ISSUE THREAD

**Issue by mkuehn94** [KaTeX/KaTeX#3380]
**Is your feature request related to a problem? Please describe.**
My goal is to parse a latex equation using the katex parser into a parseTree and convert that parseTree back into a latex expression, to normalize latex equations. for example \frac {1}{2} results in the same parseTree as \frac 1 2. Is there any way to do this?

**Describe the solution you'd like:**
a function that generates latex expressions from a parseTree

**Link to or name of a (La)TeX package that provides the same feature:**
-

**Comment by edemaine** [comment]
`katex.__parse` will do this, but the tree format is unspecified and subject to change. It does satisfy that `\frac 1 2` and `\frac{1}{2}` parse the same though.
