### ISSUE TITLE
Invalid markup error for \braket inside \frac element

### ISSUE THREAD

**Issue by pranabdas** [KaTeX/KaTeX#3500]
**Describe the bug:**
Invalid markup error for `\braket` inside `\frac` element in Firefox. Consider following equation:

$$
\frac{1}{\braket{\Phi|\Phi}}
$$

This throws `Invalid markup: Incorrect number of children for <mfrac/> tag.` in the browser console, nonetheless the equation is correctly displayed.

I am using KaTeX v0.13.24, Node 16.13.2, Mozilla Firefox 95.0.2 (64bit) on Windows 10.

**To Reproduce:**
1. Go to [katex.org](https://katex.org) using Firefox on Windows
2. Open browser console
3. Paste `\frac{1}{\braket{\Phi|\Phi}}` in the demo box

**Environment (please complete the following information):**
 - KaTeX Version: 0.13.24 and also on katex.org
 - Device: Desktop
 - OS: Windows 10
 - Browser: Firefox
 - Version: 95.0.2

**Additional context:**
The error does not appear on Safari on macOS, or Edge on Windows 10.

**Comment by ronkok** [comment]
Thank you for raising this issue. I've found the bug and it is in the MathML part of KaTeX. That's why the HTML can still render properly.

I'll turn in a PR to fix it.
