### ISSUE TITLE
fonts for accents don't match base font

### ISSUE THREAD

**Issue by kevinbarabash** [KaTeX/KaTeX#353]
See https://github.com/Khan/KaTeX/pull/349 for details.

**Comment by kevinb7** [comment]
Reported by @gagern.

**Comment by gagern** [comment]
Let's include some texcmp images. TeX in green, KaTeX in red, as usual.

* MathIt: ![mathit](https://cloud.githubusercontent.com/assets/190759/9790460/71906880-57d6-11e5-981a-59d1d8ab597a.png)
* MathTt: ![mathtt](https://cloud.githubusercontent.com/assets/190759/9790464/71a7d600-57d6-11e5-8e08-2860addf71f0.png)
* MathBf: ![mathbf](https://cloud.githubusercontent.com/assets/190759/9790457/718a2e7a-57d6-11e5-8eb4-cd67ea0781e8.png)

**Comment by kevinb7** [comment]
Thanks for adding some images.

**Comment by kevinbarabash** [comment]
I did some investigating and here and the root cause of this issue is that we're using the non-combining version of these glyphs but the sans-serif and typewriter fonts only contain the combining version.  As a result we weren't locating the correct glyph.  I tried using the combing version instead but the glyph shifted to the left by 0.5em.  This works fine if you only have a single glyph you're accenting, but this is not always the case in TeX.

So, in order to solve this we'll have to update the fonts to include a non-combining version of this glyph that isn't shifted to the left.  I left some comments in https://github.com/Khan/KaTeX/issues/237 on how to update fonts.

**Comment by kevinbarabash** [comment]
The accent glyphs in the fonts no longer have a horizontal shift.  This change was made in https://github.com/KaTeX/katex-fonts/pull/5 and https://github.com/Khan/KaTeX/pull/1094.  This is still an issue, but could probably be fixed now.

**Comment by kevinbarabash** [comment]
I'm moving this out fo the Version 1.0 milestone.  We should fix it, but it doesn't seem particularly pressing.

**Comment by kevinbarabash** [comment]
I guess it's back in the 1.0 milestone again. 🙂
