### ISSUE TITLE
Distribute typescript definitions

### ISSUE THREAD

**Issue by tobiasdiez** [KaTeX/KaTeX#3531]
**Is your feature request related to a problem? Please describe.**
When using `katex` in typescript, one has to use the `@types/katex` package to get some type interference. However, these type definitions are quite minimal.

**Describe the solution you'd like:**
Provide full typescript definitions automatically.

**Describe alternatives you've considered:**
Using `@types/katex`.

**Additional context:**
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by jameshfisher** [comment]
[The @types/katex type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/katex) seem completely broken. Katex as of v0.15 seems to have only a default export, so I have to `import katex from 'katex'`. But the type definitions demand that I `import * as katex from 'katex'`, which is completely different.

**Comment by jameshfisher** [comment]
Note that those definitions seemed to work with Katex v0.13, but have been broken somewhere between v0.13 and v0.15.

**Comment by jameshfisher** [comment]
It appears this was a breaking change in v0.14: https://github.com/KaTeX/KaTeX/blob/main/CHANGELOG.md

**Comment by Mister-Hope** [comment]
I am not sure who is maintaining type files, but due to https://github.com/microsoft/TypeScript/issues/50690, types are broken with esm. The solution may need to move the types inside to this repo.

**Comment by edemaine** [comment]
Is someone on this thread willing to put together a PR to add a `.d.ts` file to this repository? It would be greatly appreciated!

**Comment by StefaniOSApps** [comment]
same issue

**Comment by nidrissi** [comment]
@edemaine I'm not sure what's going on, but the typescript definitions don't actually get distributed with the package.

```bash
~/tmp $ npm i katex

added 2 packages in 476ms
~/tmp $ cat package.json
{
  "dependencies": {
    "katex": "^0.16.17"
  }
}
~/tmp $ find node_modules/katex/ -name '*.ts'
# <no output>
~/tmp $
```

**Comment by edemaine** [comment]
@nidrissi Thanks for the report! I see the issue, and #4008 should fix it shortly.
