### ISSUE TITLE
incorrect spacing around dotless i (and j)

### ISSUE THREAD

**Issue by kevinbarabash** [KaTeX/KaTeX#354]
See https://github.com/Khan/KaTeX/pull/349 for details.

**Comment by kevinb7** [comment]
Reported by @gagern.

**Comment by gagern** [comment]
A texcmp comparison, with TeX in green and KaTeX in red:
![mathdefaultfonts](https://cloud.githubusercontent.com/assets/190759/9790459/718cd134-57d6-11e5-8766-54b5cff155f6.png)

Right now I can think of three possibilities: either the glyph is positioned differently in the font, or the typesetting mechanics do some italic correction or some such differently, or TeX adds some explicit spacing in a different way.

**Comment by kevinbarabash** [comment]
For some reason we add extra `margin-right` on the preceding character.

**Comment by kevinbarabash** [comment]
Moving this to the backlog.
