### ISSUE TITLE
globalGroup documentation

### ISSUE THREAD

**Issue by nschloe** [KaTeX/KaTeX#3547]
I have two math blocks that I'd like to render
```latex
\newcommand\dfn{:=}
\newcommand\conj[1]{\overline{#1}}

a \dfn \conj{b}
```
and
```latex
a \dfn \conj{b}
```
The second block uses `\newcommand` definitions from the first.

I'm looping over the blocks via
```js
katex.render(content, node, {
  displayMode: true,
  throwOnError: false,
  trust: true,
  globalGroup: true,
});
```
I'd been under the impression that `globalGroup: true` makes sure the `\newcommand`s are global. However, from the above I'm getting

![screenshot](https://user-images.githubusercontent.com/181628/152994991-a01e2e67-037c-4725-b77c-423c2c8084f5.png)

This is with KaTeX v0.15.2 on Chrome 98.0.4758.80.

Am I missing something?

**Comment by nschloe** [comment]
[In the docs](https://katex.org/docs/options.html) one finds:

> globalGroup: boolean (default: false). Place KaTeX code in the global group. As a consequence, \def and \newcommand persist in macros across render calls. In LaTeX, constructs such as \begin{equation} and $$ create a local group and prevent definitions from becoming visible outside of those blocks.
>
> For example: 
> ```js
> katex.render("c = \\pm\\sqrt{a^2 + b^2}\\in\\RR", element, {
>   displayMode: true,
>    macros: {
>    "\\RR": "\\mathbb{R}"
>   }
> });
> ```

It's weird that the example doesn't actually include `\def` or `\newcommand`. I'm unsure now how this is supposed to work at all.

**Comment by nschloe** [comment]
Alright, I got to the bottom of it. Apparently, when specifying `globalGroup: true`, the `newcommand`s get added to the value of `macros`. If `macros` is not given, i.e., a fixed default is used,
```js
katex.render(content, node, {
  globalGroup: true,
});
```
or if a fixed standard set is used every time (that was the case with me)
```js
katex.render(content, node, {
  globalGroup: true,
  macro: {...},
});
```
it of course never carries over.

Better documentation of this would have helped me. Perhaps I can contribute it. Where?

**Comment by edemaine** [comment]
Oops, I didn't read your original post closely enough; I should have seen that. Glad you found it though!

I agree that it'd be good if we/you can improve the documentation. I was going to suggest that [the `globalGroup` documentation](https://katex.org/docs/options.html) should specifically (re)mention `macros`, but I see that it already does:

> `globalGroup: boolean` (default: `false`). Place KaTeX code in the global group. As a consequence, `\def` and `\newcommand` persist in `macros` across render calls. 

But perhaps that brief mention of `macros` could be elaborated at least slightly to mention "the option `macros`", and maybe more to say "if you use this, you should also pass in an object `macros`". Could also mention/clarify that `katex` itself doesn't keep global macros; you need to use `macros` to do so.

To edit this in a PR, you can just edit the file [docs/api.md](https://github.com/KaTeX/KaTeX/blob/main/docs/api.md).

**Comment by edemaine** [comment]
> It's weird that the example doesn't actually include `\def` or `\newcommand`. I'm unsure now how this is supposed to work at all.

The example is outside the bullet; it's meant to be an example of how to use `katex.render` in general. I think it would make sense to replace it with an example that actually creates a shared `macros` object, e.g.:

```js
const macros = {};
katex.renderToString(..., {macros});
katex.render(..., element2, {macros});
```

And maybe include a `\gdef` (or `\def` and `globalGroup`) in the first example.

**Comment by nschloe** [comment]
> The example is outside the bullet;

I thought that was by mistake. Anyway, a more complex example would have definitely been helpful for me.
