### ISSUE TITLE
renderMathInElement does not seem to treat code in multilines ?!

### ISSUE THREAD

**Issue by Hamarkhis** [KaTeX/KaTeX#3569]
Hello, 

I am struggling to make this simple code working on Katex, but it seems to be ignored

```
$\begin{aligned}
I_0 &= \int_{-1}^{1} (t^2-1)^0\,\mathrm{d}t \\
&= \int_{-1}^{1} \mathrm{d}t\\
&=2.
\end{aligned}$
```

However, putting it in a single line like this
`$\begin{aligned}I_0 &= \int_{-1}^{1} (t^2-1)^0\,\mathrm{d}t \\ &= \int_{-1}^{1} \mathrm{d}t\\ &=2. \end{aligned}$`
 this is working but it's unreadable code.

You can see the issue in the following sample page on a fresh wordpress site.
[https://debugggg.fr/katex20220223issue/sample-testing-page/](https://debugggg.fr/katex20220223issue/sample-testing-page/)

I am using this js file `katex_static_script.js` with this content:
```
document.addEventListener("DOMContentLoaded", function() {
	renderMathInElement(document.body, {
		throwOnError : true,
		//strict       : false,
		delimiters: [
			{left: '$', right: '$', display: false},
		],
	});
});
```

I am pretty sure there is a workaround for this, but I suspect that `renderMathInElement` can do this, I don't know how from now.
Thanks for your feedback.

**Comment by Hamarkhis** [comment]
The `preProcess` option do not seem to capture the following code.

```
$\begin{aligned}
I_0 &= \int_{-1}^{1} (t^2-1)^0\,\mathrm{d}t \\
&= \int_{-1}^{1} \mathrm{d}t\\
&=2.
\end{aligned}$
```

So I made a hybrid solution using the PHP, when I am changing `$\begin{aligned}` to a `<span class="some_katex_eq">` element and rendering that class using `katex.render` with some JS.

It wasn't the thing I wanted to do. I'm pretty sure I don't see a better solution.

**Comment by ronkok** [comment]
@Hamarkhis Thank you for including a link to an example. I took a look at that page's source code. 

In the problematic part, the lines are separated by HTML `<br>` elements.  `renderMathInElement` is looking for a newline or a space at that position. `<br>` is not valid LaTeX.

**Comment by Hamarkhis** [comment]
Ok I understand this, thanks.
But the problem is that `renderMathInElement` does not capture the `<br>`, so it seems to be impossible to discard it using `preProcess`. It would have been nice.

**Comment by edemaine** [comment]
I agree that this isn't possible with `preProcess`, because it only deals with text elements. You can create your own preprocessing of HTML elements and call `renderMathInElement` afterward.  I don't see an easy way to support this by KaTeX itself, as it's specific to your setup.
