### ISSUE TITLE
Prime symbol ' is not good

### ISSUE THREAD

**Issue by Hamarkhis** [KaTeX/KaTeX#3575]
Reading [the docs](https://katex.org/docs/supported.html), I see that both `y'` and `y^{\prime}` should be supported.

Unfortunately, using `y'+2y = 3x^3+x` the prime is not very nice, [see it](https://snipboard.io/zoREML.jpg).

Using  `y^{\prime}+2y = 3x^3+x` the prime is supported like expected, [see it](https://snipboard.io/Ns6KJY.jpg).

Please tell me what I have to do to set up things nicely, I think I am missing something elsewhere.

**Comment by edemaine** [comment]
It works fine on [the demo page](https://katex.org/?data=%7B%22displayMode%22%3Atrue%2C%22leqno%22%3Afalse%2C%22fleqn%22%3Afalse%2C%22throwOnError%22%3Atrue%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22warn%22%2C%22output%22%3A%22htmlAndMathml%22%2C%22trust%22%3Afalse%2C%22macros%22%3A%7B%22%5C%5Cf%22%3A%22%231f(%232)%22%7D%2C%22code%22%3A%22y'%2B2y%20%3D%203x%5E3%2Bx%22%7D):

![image](https://user-images.githubusercontent.com/2218736/156804028-94933161-7059-44f1-8671-3f0bbf0a9ae8.png)

So probably something to do with your setup. Are there any console messages? Do you have the correct DOCTYPE header?

**Comment by Hamarkhis** [comment]
Hello, I isolated the problem from a fresh wordpress site. 
The issue is still there. [See this page](https://debugggg.fr/20220305testingprimefromvoid/test/).

No console messages.
The page content is only `$y'=y$`.

Katex is launched from this script:
```
document.addEventListener("DOMContentLoaded", function() {
	const katex_options_when_dollar_rendering = {
		throwOnError : true,
		strict       : false,
		delimiters: [
			{left: '$', right: '$', display: false},
		],
	};
	renderMathInElement(document.body, katex_options_when_dollar_rendering);
});
```
I don't know what happens.

**Comment by mbourne** [comment]
Sounds like Wordpress's Smart Quotes are enabled (which they are by default).

This post tells you how to disable them: https://www.ironpaper.com/webintel/articles/fix-wordpress-quotes-by-displaying-straight-quotation-marks

**Comment by Hamarkhis** [comment]
Thanks for your feedback.
Added the corresponding filters in WordPress `remove_filter('the_content', 'wptexturize');` and `remove_filter('the_title', 'wptexturize');` but that does not change anything.

When using MathJax I don't have this problem. So I still believe this is a KaTeX issue.

**Comment by Hamarkhis** [comment]
More exactly, the prime issue does not appear in pure KaTeX.
Il only appears when using renderMathInElement.

**Comment by Hamarkhis** [comment]
Fixed.
Using renderMathInElement, we can preprocess special WordPress characters to reassign them to the specified chars.
It's quite surprising we don't need to do this in pure KaTeX whereas we have to in renderMathInElement. I'm pretty sure there exist a specific tag to tell WordPress to bypass the automatic treatment of some quotes.

**Comment by edemaine** [comment]
Glad you fixed the problem. You might also check out the second common issue in https://katex.org/docs/issues.html

**Comment by Hamarkhis** [comment]
Very nice.
An issue still persists for double closing quotes which should be replaced with `''`.

I defined this:
`const ClosedQuotesTwo = String.fromCharCode(160)+"»";`

And added in my macros:
`ClosedQuotesTwo : "''"`

but that does not work. 

I don't know exactly how renderMathInElement works with macros, whereas it's fine using a callback in the PreProcess.

**Comment by edemaine** [comment]
Did you try the following macro?
```js
"”": "''"
```

**Comment by Hamarkhis** [comment]
Thanks for coming back.

I tried, yes, but the non-breaking space character (160 code) is still there before the double quote and there is a space between `f` and the second derivative symbol.
I tried to copy it/paste it before the double quote. No effet.
So I tried to add it with `String.fromCharCode(160)` but it's not detected in the macro. Strange.

**Comment by Hamarkhis** [comment]
I tried this, but still no effect.
```
const ClosedQuotesTwo = String.fromCharCode(160)+String.fromCharCode(187);
	const my_macros = { ClosedQuotesTwo : "''" };
	const katex_options_when_dollar_rendering = {
		throwOnError : true,
		strict       : false,
		delimiters: [
			{left: '$', right: '$', display: false},
		],
		macros : my_macros,
	};
	renderMathInElement(document.body, katex_options_when_dollar_rendering);
```

**Comment by edemaine** [comment]
Macros only work for single characters (or `\commands`), so you'd need to define them individually. Of course you can do more work in `preprocess`.

**Comment by Hamarkhis** [comment]
Ok that's the point why it worked on PreProcess callback but not using macros.
Thanks for that.
