### ISSUE TITLE
empty chemical formula crashes (mhchem)

### ISSUE THREAD

**Issue by Entkenntnis** [KaTeX/KaTeX#3626]
**Describe the bug:**
Entering an empty mhchem formula is crashing katex.

**To Reproduce:**
1. Visit demo
2. enter `\ce{}`
3. crash

Link: https://katex.org/?data=%7B%22displayMode%22%3Atrue%2C%22leqno%22%3Afalse%2C%22fleqn%22%3Afalse%2C%22throwOnError%22%3Atrue%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22warn%22%2C%22output%22%3A%22htmlAndMathml%22%2C%22trust%22%3Afalse%2C%22macros%22%3A%7B%22%5C%5Cf%22%3A%22%231f(%232)%22%7D%2C%22code%22%3A%22%5C%5Cce%7B%7D%22%7D

**Expected behavior:**
Empty formula without crash

**Screenshots:**
![grafik](https://user-images.githubusercontent.com/13507950/165049808-0b0a5eb8-a5ba-4e5c-8662-d580411c3c3c.png)

**Environment (please complete the following information):**
 - KaTeX Version: latest
 - Device: desktop
 - OS: linux
 - Browser: firefox
 - Version: latest

**Additional context:**
using mhchem extension

**Comment by ronkok** [comment]
@Entkenntnis Thank you for raising this issue. I'll work up a P.R. tomorrow. It should be a pretty easy fix.
