### ISSUE TITLE
The Online documents doesn't work normally. 

### ISSUE THREAD

**Issue by Azou1** [KaTeX/KaTeX#3640]
https://katex.org/docs/supported.html
The examples can't be displayed normally on this web.
like this picture
![1653468021(1)](https://user-images.githubusercontent.com/92700277/170220499-3e347efe-910d-492f-ac24-8aa6ebb4a907.jpg)

**Comment by edemaine** [comment]
It looks fine to me:

![image](https://user-images.githubusercontent.com/2218736/172025353-2fdcf736-c572-4310-9ee6-a6f1d7027cc4.png)

Just guessing, it looks like your browser failed to load the CSS, perhaps because of a plugin.

**Comment by Azou1** [comment]
Thank you!
