### ISSUE TITLE
Undefined control sequence: \cdotp when including middle dot in text mode

### ISSUE THREAD

**Issue by bluebear94** [KaTeX/KaTeX#3641]
When U+00B7 MIDDLE DOT is included in text mode, KaTeX complains about `\cdotp` being undefined.

**(La)TeX code:**
```latex
a = \text{c·}
```

**Expected behavior:**
The equation should render as ‘*a* = c·’, as in this screenshot (from QuickLaTeX):

![image](https://user-images.githubusercontent.com/2975203/171068387-7e30d5b8-55a2-4377-8043-711d1ff5feb8.png)

**Environment:**
 - KaTeX Version: 0.15.6 (both in the demo and with a locally installed copy)
 - Device: Desktop
 - OS: Linux
 - Browser: Firefox
 - Version: 100.0.2

**Comment by edemaine** [comment]
Actually, `\cdotp` is invalid in text mode.  If you try to use it, LaTeX gives this error message:

```
! Missing $ inserted.
<inserted text>
                $
l.3 \cdotp
```

QuickLaTeX doesn't render errors like this.

So I believe this is expected behavior.

**Comment by bluebear94** [comment]
Then the middle dot character itself shouldn’t be expanding to `\cdotp` in text mode.

**Comment by LanderlYoung** [comment]
This still can be reproduced, seems to be a BUG? @edemaine 

` \text{eV·nm} `

<img width="839" height="299" alt="Image" src="https://github.com/user-attachments/assets/672d79dd-e635-401a-a641-46b275b43cf4" />

**Comment by edemaine** [comment]
Like I said above, that's the same behavior as LaTeX, so it is not a bug. You should exit text mode to render that character. For example:

```tex
\text{eV} · \text{nm}
```

**Comment by justnewbee** [comment]
I was troubled by this bug for a while now. Since it might possibly not be fixed, I made a workaround, processing the input before it is parsed by KaTeX.

Here's the remedy if you are troubled as well:

```ts
function workaroundLatexTextModeCdotpBug(input: string): string {
  return input.replace(/\\text\{([^}]*)}/g, (match, content: string): string => {
    if (!content.includes('·')) {
      return match;
    }
    
    return content.split('·').map(part => `\\text{${part}}`).join('·');
  });
}
```

It has a side effect though, if you are doing it in Markdown, the plain text might be affected by accident as well. I think this side effect is acceptable.

**Comment by edemaine** [comment]
I seemed to have made a mistake here. While `\cdotp` does not render in text mode in LaTeX, the Unicode character seems to (at least within `\text`). So this is in fact a bug.
