### ISSUE TITLE
Lines rendered by `vmatrix` environment are misaligned

### ISSUE THREAD

**Issue by chrisjpurdy** [KaTeX/KaTeX#3650]
The vertical lines rendered by the `vmatrix` environment are segmented into 3 parts, with the middle segment bolder and misaligned from the others. The issue seems more obvious with larger matrices. These lines should be uniform if possible.

**(La)TeX code:**
```latex
\begin{vmatrix}
   0 & -1 & 1 \\
   -1 & 0 & 1 \\
   -1 & 0 & -1
\end{vmatrix}
```

**Environment**
 - KaTeX Version: 0.16.0 (version on `katex.org`)
 - Device: Desktop
 - OS: Windows 10
 - Browser: Firefox, Edge, Chrome
 - Version: 101, 102, 101 

Turning off [Microsoft ClearType](https://docs.microsoft.com/en-us/typography/cleartype/) doesn't make a noticeable difference.

**Example on Chrome:**
![image](https://user-images.githubusercontent.com/33040507/172595836-cd7a21fa-c5bf-4636-9787-64e8dd7a8fce.png)

**Comment by edemaine** [comment]
FWIW, I can't reproduce this on Chrome on Windows 10. I think it depends on your monitor resolution/DPI and zoom level (though I couldn't reproduce at any zoom level). I'm on a 4K display and get this at 100%:

![image](https://user-images.githubusercontent.com/2218736/172636279-35b6de84-eb49-46cc-8a69-0c8ebd43109a.png)

**Comment by mangerlahn** [comment]
Can be closed?
