### ISSUE TITLE
Does not work on google chrome with API call

### ISSUE THREAD

**Issue by JeromeCGithub** [KaTeX/KaTeX#3655]
When using a simple js file with which import katex and katex.render("MATH EXPRESSION like \\frac{2}{3}") work correctly on firefox, but in chrome it display \frac{2}{3}.

**Comment by JeromeCGithub** [comment]
`import katex from 'katex';
const elem = document.getElementById("equationLatex");
katex.render("\\frace{2}{3}", elem)`

**Comment by JacobBeaudry** [comment]
If the above code is a copy-paste, then the issue may be the typo: `\frace` Vs. `\frac`?

**Comment by edemaine** [comment]
We'd need an actual reproduction (e.g. CodePen or repo) to help you debug. KaTeX is used on Chrome all the time, so there's likely a bug in the way you're using it, as @JacobBeaudry suggests. Please also check the console log to see if there are any error messages.

**Comment by JeromeCGithub** [comment]
![Capture d’écran, le 2022-06-11 à 13 44 45](https://user-images.githubusercontent.com/38048350/173199020-b21253b2-56fd-4b47-b47c-db6108f2982f.png)

this is the result with this code (copy and past) : 
`const elem = document.getElementById("equationLatex");
katex.render("1000 \\, ln \\alpha = " + equation[3] + "\\frac{10^6}{T^2} + " + equation[4]+ "\\frac{10^3}{T} + " + equation[5], elem, {throwOnError: false});`

**Comment by edemaine** [comment]
Like I said, we'd need a full reproduction. Your code sample doesn't define `equation`, so that causes an error. I just tried the following on https://katex.org:

```js
const elem = document.getElementById("demo-output");
katex.render("1000 \\, ln \\alpha = \\frac{10^6}{T^2} + \\frac{10^3}{T} + ", elem, {throwOnError: false});
```

and it worked fine:

![image](https://user-images.githubusercontent.com/2218736/173199169-4861ea02-f934-411d-9275-204f07cbf0a3.png)

**Comment by JeromeCGithub** [comment]
Effectively if i do a new project with only katex it work on google chrome. I guess it is a side effect of something in my current code. Firefox print correctly a <math> with <sementic> inside, and it print everything correctly. But Google chrome got a <annotation> in his <semantic>. And this is the <annotation> that is display, with the raw math formul.

I use mathjax and plotly for something else in the same code. Can it create an error like that ?
