### ISSUE TITLE
Blocking translation of formulas

### ISSUE THREAD

**Issue by Laciniata** [KaTeX/KaTeX#3679]
Some symbols in KaTex formulas are translated when using web translation features, such as Google Translate, which is built into Chrome.

For KaTex, is it possible to provide a solution similar to [the one mentioned in this MathJax issue](https://github.com/mathjax/MathJax/issues/2115#issuecomment-458328112)?

**Comment by edemaine** [comment]
Similar to that MathJax suggestion, you could do this:

```js
document.querySelectorAll('.katex').forEach((node) => node.classList.add('notranslate'));
```

**Comment by Laciniata** [comment]
> Similar to that MathJax suggestion, you could do this:
> 
> ```js
> document.querySelectorAll('.katex').forEach((node) => node.classList.add('notranslate'));
> ```

It works well, thanks!
