### ISSUE TITLE
Does katex support symbol `->` in this picture?

### ISSUE THREAD

**Issue by dongrixinyu** [KaTeX/KaTeX#3707]
> Before reporting a bug

- I am curious that does katex support symble `->` in this picture below? How to type it in katex?

![image](https://user-images.githubusercontent.com/27001062/189102873-1af0b2a7-3d4a-4c42-845d-2b3e225138d6.png)

- I wrote the this symbol like `->` above via word-math

**Comment by edemaine** [comment]
Try `\to` or `\rightarrow` or `→`

**Comment by dongrixinyu** [comment]
thankyou
