### ISSUE TITLE
Security contact for reporting vulnerabilities?

### ISSUE THREAD

**Issue by jupenur** [KaTeX/KaTeX#3709]
We've found a security issue in KaTeX and attempted to report it through the Khan Academy HackerOne program as instructed in the project's [security policy](https://github.com/KaTeX/KaTeX/security/policy). Their response was this:

>  Unfortunately, I have to close this as Informative since we (Khan Academy) don't have much ownership over KaTeX these days and we can't directly address this issue. Your best bet will be to report it in Github issues over on the KaTeX project.

So, asking here instead: what's the appropriate channel to report security issues? And could you please update the security policy and docs accordingly?

**Comment by ylemkimon** [comment]
Please mail to `y@ylem.kim`. Thank you!

**Comment by ylemkimon** [comment]
I'll create a GitHub security advisory and invite you. Please wait a moment.

**Comment by ylemkimon** [comment]
Please report the issue in https://github.com/KaTeX/KaTeX/security/advisories/GHSA-cvr6-37gx-v8wc.

**Comment by jupenur** [comment]
Thanks @ylemkimon! I'll leave this issue open so you can use it to track updating the security policy. But if you'd rather create a separate ticket for that, feel free to close this one.

**Comment by edemaine** [comment]
@ylemkimon Could you give me (and maybe all maintainers) access to the advisory? Also I wonder if there's a way to use GitHub security advisories for reporting in the future?

Thanks @jupenur for the heads up on both!
