### ISSUE TITLE
`\hline` not working after `\cr`

### ISSUE THREAD

**Issue by psymonmarkrine** [KaTeX/KaTeX#3734]
* `\\` is OK
```katex
\begin{array}{}
  a & b \\ \hline
  c & d
\end{array}
```
![hline_true](https://user-images.githubusercontent.com/47858465/194350791-1cacaaaa-d353-4b79-8461-fba2bf3221f0.png)

* `\newline` makes a parsing error
```katex
\begin{array}{}
  a & b \newline \hline
  c & d
\end{array}
```
![hline_false](https://user-images.githubusercontent.com/47858465/194350854-a43a1eb4-645d-474a-bc3c-1dce3a4655cc.png)

https://katex.org/#demo

**Comment by ronkok** [comment]
`\newline \hline` does not work in LaTeX, either.

Since KaTeX emulates LaTeX, this really doesn't qualify as a bug. I'm not sure why `\newline` works at all. It doesn't work in LaTeX.

**Comment by psymonmarkrine** [comment]
I had mistakenly thought that `\newline` could be substituted for `\\` until now.
Thank you for correcting my mistake.

Moreover, may I confirm one more thing?
I checked with Overleaf and indeed `\newline` does not work in an array environment.
However, `\cr \hline` work in LaTeX.

![overleaf_cr_hline](https://user-images.githubusercontent.com/47858465/194556627-0076ee3a-5603-4e61-b782-0ad801183a6f.png)

`\cr \hline` does not work in KaTeX.

![katex_cr_hline](https://user-images.githubusercontent.com/47858465/194556776-b91548d1-6519-44b3-8639-698e76e67e77.png)

Does this qualify as a bug?

**Comment by ronkok** [comment]
Yep, that's a bug. I'll look into it. It may be a few days before I get there.
