### ISSUE TITLE
Equivalent of `\let` via `macros` options

### ISSUE THREAD

**Issue by edemaine** [KaTeX/KaTeX#3737]
**Describe the bug:**
It's certainly not convenient to do the equivalent of `\let\Oldint=\int` via a user-constructued `macros` option. In fact, it may not be possible.

**To Reproduce:**
Steps to reproduce the behavior, in Node or browser console:
1. `macros = {};`
2. `katex.renderToString("\\let\\Oldint=\\int\\def\\int{\\Oldint\\limits}", {macros, globalGroup: true});`
3. `Object.values(macros).forEach((val) => val.tokens.forEach((token) => delete token.loc))` — remove `loc` pointers which prevent serialization
4. `console.log(JSON.stringify(macros))`
    &rarr; `{"\\Oldint":{"tokens":[{"text":"\\int","noexpand":true}],"numArgs":0,"unexpandable":false},"\\int":{"tokens":[{"text":"\\limits"},{"text":"\\Oldint"}],"numArgs":0,"delimiters":[[]]}}`
5. `katex.renderToString("\\int", {macros})` works fine
6. But `katex.renderToString("\\int", {macros: {"\\Oldint":{"tokens":[{"text":"\\int","noexpand":true}],"numArgs":0,"unexpandable":false},"\\int":{"tokens":[{"text":"\\limits"},{"text":"\\Oldint"}],"numArgs":0,"delimiters":[[]]}}})` causes an infinite loop (!).

**Expected behavior:**
Manually constructing the `macros` object in the same shape [as produced by `\let`](https://github.com/KaTeX/KaTeX/blob/c5ac4c769588761fb68d89890998234e83fc1c1a/src/functions/def.js#L37) should simulate the behavior of `\let`.

We might also want to document this shape, or otherwise make it easier to request `\let` behavior for built-in commands.

Also, an infinite loop should not be possible, even with invalid `macros` input. I would expect `maxExpand` to hit a limit here if nothing else.

**Screenshots:**

**Environment (please complete the following information):**
 - KaTeX Version: 0.16.2
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome or Node
 - Version: 106.0.5249.119 or v18.7.0

**Additional context:**
From #3736

**Comment by MrOddlyFormal** [comment]
Is this fixed? 
I tried the snippet in the KaTeX demo on the website, but didn't work.

**Comment by edemaine** [comment]
No, it's not fixed yet in release. #3738 fixes it, but it's currently under review. Thanks for the reminder to respond to the review though. 🙂

**Comment by MrOddlyFormal** [comment]
@edemaine happy to help :wink:

**Comment by pedrolimasi** [comment]
@MrOddlyFormal in case you're trying to use `\let` to redefine `\int` to `\int\limits` (like I originally posted), few months ago I stumbled on a workaround:

There's an undocumented `\intop` that produces the same behavior as `\int\limits`. It seems to have been inspired by the `esint` package. If you have access to the `macros` object, all you have to do is to map `\int` to `\intop`.
