### ISSUE TITLE
Wrong function in docs

### ISSUE THREAD

**Issue by Masynchin** [KaTeX/KaTeX#3753]
In [Accents](https://katex.org/docs/supported.html#accents) table `\bar{y}` rendered not as `y` with bar, but as `ay`.

<img width="712" alt="Screenshot with this bug" src="https://user-images.githubusercontent.com/47028153/204279766-449c79a6-b9ea-47b7-8031-163d95078766.png">

*In the left bottom corner*.

**Comment by edemaine** [comment]
Sorry for missing this earlier. It's fixed now.
