### ISSUE TITLE
expose defineFunction

### ISSUE THREAD

**Issue by arrocke** [KaTeX/KaTeX#3756]
**Is your feature request related to a problem? Please describe.**
We would like to be able to add a custom command with a custom render. I don't see a way right now to add a custom render function to convert a command to HTML.

**Describe the solution you'd like:**
It would be great if we could call defineFunction and provide our our own html render function.

**Describe alternatives you've considered:**
defineSymbol and defineMacro won't work in this case because we want to render custom html. We've considered adding a new symbol and then replacing that symbol with custom html after it renders, but there is no way to determine function arguments.

**Additional context:**
We want to create a drag and drop question interface with complex expressions. We want to add a custom command called `\drop{id}`. Having a custom function that we could define ourselves would allow us to render an html drop target within the LaTeX render.

**Comment by ronkok** [comment]
This might require a refactoring of `defineFunction.js` and/or `functions.js`. At the moment, `functions.js` works via side effects, which seems like an awkward thing to expose.

**Comment by edemaine** [comment]
I believe defineMacro and defineSymbol, already exposed, have the same behavior.

**Comment by ronkok** [comment]
Yeah, the thought on how to wrap it came to me about 30 minutes after I wrote that comment.
