### ISSUE TITLE
Mhchem extension appears to not be working from 0.16

### ISSUE THREAD

**Issue by WilliamABradley** [KaTeX/KaTeX#3758]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] ~~Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.~~ (N/A)
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
A clear and concise description of what the bug is. If your installation is available on the web or you can provide a minimal repo or CodePen that reproduces the bug, please add the link to it.

Importing mhchem first works in katex 0.15.6, the same logic does not work from 0.16.0.

**To Reproduce:**

```ts
// Adds mhchem extensions to katex, must be imported first
import 'katex/contrib/mhchem';
import 'katex/contrib/auto-render';
```

**Expected behavior:**

Mhchem extensions load

**Screenshots:**

These UI is using Katex via remark + rehype-katex.

0.15.6:
![image](https://user-images.githubusercontent.com/6026537/207204111-c1fd4ff2-9cb2-45b1-b2b4-b29faabb8335.png)

0.16.4:
![image](https://user-images.githubusercontent.com/6026537/207204276-57f260d7-02ea-4ceb-83af-33aefab2f971.png)

**Environment (please complete the following information):**
 - KaTeX Version: [0.16.0, 0.16.4]
 - Device: Desktop
 - OS: Windows 11
 - Browser: MS Edge
 - Version: 108.0.1462.46

**Additional context:**
Add any other context about the problem here. If you're using a library to use KaTeX, please include its name and setup.

**Comment by edemaine** [comment]
Could you maybe include a repo that reproduces this error?

mhchem seems to work fine on [the demo site](https://katex.org/):

![image](https://user-images.githubusercontent.com/2218736/207432170-b1bcc7bc-da81-423f-af99-c9d0ebccfc52.png)

So it may be something specific to your usage (perhaps remark/rehype-katex?).
