### ISSUE TITLE
Tensor notation - Lorentz indices alignment

### ISSUE THREAD

**Issue by Pedrexus** [KaTeX/KaTeX#3763]
I'm always frustrated when I have to write tensors and Lorentz indices alignment doesn't seem possible with katex

**Describe the solution you'd like:**
Is there a way to enable Lorentz indices alignment?

\tensor{g}_\mu^\nu

**Link to or name of a (La)TeX package that provides the same feature:**
https://ctan.org/tex-archive/macros/latex/contrib/tensor

**Describe alternatives you've considered:**
Use something else besides katex

**Additional context:**
This would be helpful for tensor analysis, general relativity and many other areas, I think. Please tell me if there is already a way to perform this, but I could not find, unfortunately.

**Comment by edemaine** [comment]
For a workaround, are you looking for `{g_\mu}^\nu` or `g_\mu{}^\nu`?

![image](https://user-images.githubusercontent.com/2218736/209577734-455cc2e5-8095-47dc-8a76-0ba87f5b3bd5.png)

I don't think `\tensor` would be *too* difficult to implement (pull requests certainly welcome!), but it can be simulated by adding `{}`s in appropriate locations I believe. For example, `{}^a{}_b{}^c{}_d M {}^a{}_b{}^c{}_d` seems to be the equivalent of `\tensor[^a_b^c_d]{M}{^a_b^c_d}`.

**Comment by Pedrexus** [comment]
Yes! I believe this would be enough (for me at least). Maybe this info could be added to the website docs BTW.

Thank you very much for your help! Closing issue!

**Comment by GaugeAndGravity** [comment]
> For a workaround, are you looking for `{g_\mu}^\nu` or `g_\mu{}^\nu`?
> 
> ![image](https://user-images.githubusercontent.com/2218736/209577734-455cc2e5-8095-47dc-8a76-0ba87f5b3bd5.png)
> 
> I don't think `\tensor` would be _too_ difficult to implement (pull requests certainly welcome!), but it can be simulated by adding `{}`s in appropriate locations I believe. For example, `{}^a{}_b{}^c{}_d M {}^a{}_b{}^c{}_d` seems to be the equivalent of `\tensor[^a_b^c_d]{M}{^a_b^c_d}`. Unless I'm missing something about vertical alignment.

Actually, they won't be equivalent, at least in LaTeX. See this simple test:
```latex
\documentclass{standalone}

\usepackage{tensor}
\usepackage{color}

\begin{document}
    \rlap{\color{red}$\tensor{h}{^a_b} \tensor{\eta}{^b_c} \tensor{\xi}{^c_f}$}\color{blue}$h^{a}{}_b \eta^b{}_c \xi^c{}_f$
\end{document}
```
The output:
<img width="1437" alt="image" src="https://github.com/KaTeX/KaTeX/assets/38576654/2a96478b-6b7f-489a-a941-7e560258add5">
I don't know if `\tensor`'s behavior is more "correct", but you can see it puts subscripts on the same height, while naive subscripts "b" and "c" won't line up.

I research in gravity, so I write tensors a lot. Is there any document on how to add new commands to KaTeX? I'd like to try it.
