### ISSUE TITLE
"Font metrics not found for font" error

### ISSUE THREAD

**Issue by pzinn** [KaTeX/KaTeX#3776]
Try typesetting the randomly chosen unicode symbol 𝕭 (this can be tested e.g. in https://katex.org/)
KaTeX will produce an error:
```
Font metrics not found for font: .
```
This is a bit brutal. Maybe KaTeX could handle this more gracefully?

**Comment by ronkok** [comment]
I think we can do better than just an improved error message. See PR #3777.

**Comment by pzinn** [comment]
thanks! looking good

**Comment by pzinn** [comment]
would be good if #3777 got approved and merged, just saying...
