### ISSUE TITLE
Issue with the infinity symbol under actuarial angle

### ISSUE THREAD

**Issue by fypc** [KaTeX/KaTeX#3792]
**Describe the bug:**
The infinity symbol under the actuarial angle notation cannot be rendered:

```
a_{\angl n}           # correctly rendered
\infty                # correctly rendered
a_{\angl \infty}.     # ERROR
```

**Comment by edemaine** [comment]
This is because `\angl` enters text mode, and `\infty` is only defined in math mode.  You probably want `\angl{$\infty$}`

**Comment by fypc** [comment]
Thank you so much for your answer Erik!
