### ISSUE TITLE
inline mode, "\lim_{n \to \infty}" renders incorrectly

### ISSUE THREAD

**Issue by paladin-fish** [KaTeX/KaTeX#3802]
![image](https://user-images.githubusercontent.com/65432914/230256268-fd5e811b-a5de-491c-9289-9ac51725c829.png)

**Comment by edemaine** [comment]
That looks correct to me. Were you expecting `\displaystyle`?

![image](https://user-images.githubusercontent.com/2218736/230502244-539d339b-7706-4b64-a3f7-51fcf2c7e388.png)
