### ISSUE TITLE
Formula fails to render with: Expected node of symbol group type, but got node of type cr

### ISSUE THREAD

**Issue by roman-mibex-2** [KaTeX/KaTeX#3806]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
The formula crashes Katex with an 'Expected node of symbol group type, but got node of type cr' error.
It can be reproduced in the online editor https://katex.org/

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
\left\{
    \begin{array}\\
        w=\alpha t,\,\theta=\frac{\alpha t^2}{2} - A & 0\le t\le t_1 \\
        w=w_1=\alpha t_1,\,\theta=\alpha t_1\left( t - \frac{1}{4F}\right) & t_1\le t\le t_2 \\
        w=\alpha \left(\frac{1}{2F}-t\right),\theta= -\frac{\alpha}{2}\left(t-\frac{1}{2F}\right)^2 + A & t_2\le t \le \frac{T}{2}
    \end{array}
\right
```

**Expected behavior:**
Rendering of the array formula. See output from https://www.quicklatex.com in the screenshot.
Or alternatively, and error on what is wrong with the formula.

**Screenshots:**
![image](https://user-images.githubusercontent.com/123380887/231403283-035f3b59-3c65-4833-85f9-328db081a713.png)

**Environment (please complete the following information):**
 - KaTeX Version:0.16.4
 - Device: Desktop
 - OS: Linux
 - Browser: Firefox / Chromium
 - Version: 111.0.1  / 112.0.5615.49

**Comment by edemaine** [comment]
`\begin{array}` takes a required argument in LaTeX, specifying column alignments. In this example, something like `\begin{array}{rl}` might be what you're looking for.
