### ISSUE TITLE
No Support For Proper Oxidation State Formatting

### ISSUE THREAD

**Issue by micahchaya** [KaTeX/KaTeX#3807]
KaTex's [chemistry documentation page](https://mhchem.github.io/MathJax-mhchem/) has a section on formatting oxidation states that can be visited to verify the issue.
<img src="https://user-images.githubusercontent.com/115888064/231831213-36636c4f-cc46-41f1-8241-23203356d00f.png" width = "300" />
Unfortunately, this formatting is incorrect. Oxidation states are supposed to be written overtop of elements, while ionization is supposed to be written as an exponent.
<img width="300" alt="bug" src="https://user-images.githubusercontent.com/115888064/231832699-c90b1ba5-0441-4d52-a46b-80a5099046ff.png">

**Comment by edemaine** [comment]
This should be reported in the [mhchem repo](https://github.com/mhchem).
