### ISSUE TITLE
long vertical bar not rendering as a straight line

### ISSUE THREAD

**Issue by GiacomoDandria** [KaTeX/KaTeX#3809]
**Describe the bug:**
I'm trying to display long vertical straight left/right bars as I do in Latex, but in Katex the rendered output is not a straight line (see images below). Is there a way to display it properly or is it a bug?

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
\left | \frac{ \dfrac{A \cdot \alpha}{B} }{ \dfrac{C \cdot \Omega}{D} } \right |
```

**Expected behavior:**
See Latex image below.

**Screenshots:**
Katex:
![image](https://user-images.githubusercontent.com/73328482/232469743-7351f85c-4821-4a16-b231-e57619fd85d7.png)

Latex:
![image](https://user-images.githubusercontent.com/73328482/232470242-4ec49962-cc30-45d6-9154-79fe917c90df.png)

**Environment:**
 - KaTeX Version: 0.16.4
 - Device: Desktop, Samsung S22, iPhone 14
 - OS: Windows 11, Android 13, iOS 15, macOS 13
 - Browser: Chrome, Safari, Firefox, Edge, Brave
 - Version: 111

**Comment by ronkok** [comment]
Before PR #3686, we had the problem that you describe. But in current KaTeX, that vertical bar is a single path in a SVG image. I don't know any way to make it straighter. And it renders fine on the KaTeX demo page.

You might check if the version you are using is really 0.16.4.
