### ISSUE TITLE
'\begin{align*}ab&=\frac{600\times16}{2}\\ab&=400\\a&=20.46\\b&=15.66end{align*}' render error

### ISSUE THREAD

**Issue by AHRL** [KaTeX/KaTeX#3818]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
This example renders incorrectly in my project, but renders correctly on the official website.
what is wrong?
Please help me. Thanks.

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/katex.min.css"
  integrity="sha384-3UiQGuEI4TTMaFmGIZumfRPtfKQ3trwQE2JgosJxCnGmQpL/lJdjpcHkaaFwHlcI"
  crossorigin="anonymous"
/>
<script
  defer
  src="https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/katex.min.js"
  integrity="sha384-G0zcxDFp5LWZtDuRMnBkk3EphCK1lhEf4UEyEM693ka574TZGwo4IWwS6QLzM/2t"
  crossorigin="anonymous"
></script>
<script
  defer
  src="https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/contrib/auto-render.min.js"
  integrity="sha384-+VBxd3r6XgURycqtZ117nYw44OOcIax56Z4dCRWbxyPt0Koah1uHoK0o4+/RRE05"
  crossorigin="anonymous"
  onload="renderMathInElement(document.body);"
></script>

katex.render('\begin{align*}ab&=\frac{600\times16}{2}\\ab&=400\\a&=20.46\\b&=15.66end{align*}', document.querySelector('#katex'), {
      throwOnError: false,
    })
```

**Expected behavior:**
<img width="822" alt="image" src="https://github.com/KaTeX/KaTeX/assets/31957724/107b47b5-6b13-49b9-a092-6d09d828b1c8">

**Comment by AHRL** [comment]
<img width="871" alt="image" src="https://github.com/KaTeX/KaTeX/assets/31957724/e9546a89-0709-4a92-ad21-63c9dd672378">

**Comment by edemaine** [comment]
It looks like your `\b` is getting processed. Did you try doubling your backslashes, e.g. `\\begin`? This is necessary if you're putting your LaTeX code in a JavaScript string, for example.

If that's not it, you'll need to tell us more about your project, as it's clearly specific to that.

**Comment by AHRL** [comment]
@edemaine Why can I output this example directly on the official website? Can you tell me how to deal with it?

**Comment by edemaine** [comment]
When you put LaTeX code inside a JavaScript string (via `'...'` or `"..."`), you need to double the backslashes, so that you end up with single backslashes in the actual string contents. See, for example, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#escape_sequences
When inputting content in a textarea such as on katex.org, you don't get this issue. 

Hope this helps!

**Comment by AHRL** [comment]
Thanks！I will try it.    : )
