### ISSUE TITLE
Unicode character issue caused Uncaught SyntaxError: Invalid regular expression when importing katex.mjs

### ISSUE THREAD

**Issue by wenion** [KaTeX/KaTeX#3831]
**Describe the bug:**
I imported katex to build frontend app, sometimes the console would report 
```shell
Uncaught SyntaxError: Invalid regular expression: /[Ì€-Í¯]+$/: Range out of order in character class
```
I have located the issues which happened in line 14874(katex/dist/katex.mjs), the code shows as follows,
```javascript
var combiningDiacriticalMarkString = "[\u0300-\u036f]";
var combiningDiacriticalMarksEndRegex = new RegExp(combiningDiacriticalMarkString + "+$");
```
when I rewrote it as 
```javascript
var combiningDiacriticalMarkString = "[\\u0300-\\u036f]";
```
the issue was fix.

**Environment (please complete the following information):**
 - KaTeX Version: [0.16.7]
 - Browser: [Chrome]

**Comment by KiranMohan** [comment]
Any plans to fix this?

**Comment by edemaine** [comment]
1. This sounds like an encoding issue. You must be serving `katex.js` with the incorrect encoding (should be UTF8 I imagine).
2. `src/Lexer.js` seems to be filled with `\u` Unicode escapes in the regex, not just this one line. It might be a good idea to change it for these regexes, but given our use of Unicode characters throughout the codebase (I count over 500 uses), I think it would fix only some of the code.
3. `katex.min.js` seems to have no Unicode characters whatsoever, thanks to our minified. So I'd suggest using that to fix this issue.

**Comment by KiranMohan** [comment]
Thank you @edemaine. It did turn out to be an encoding issue. For some reason, the webpack compiled react javascript file was in ascii text. 

(apologies for the late reply).
