### ISSUE TITLE
How to render CHARISSIL Font in Katex Output instead of default Katex fonts ?

### ISSUE THREAD

**Issue by drajakullayappa** [KaTeX/KaTeX#3836]
I am trying to render Charisil font in the Katex output. When I change Katex CSS to use Charissil font instead of Katex default fonts, I am getting below issues,

1. Content loss for some special characters like Wide tilde, hat symbols.
2. Accent characters are not properly aligned.

I am wondering how to use custom fonts in Katex without content loss/alignment issues.

**Comment by edemaine** [comment]
This is tracked in #123. Unfortunately it's quite difficult to do with current KaTeX, though of course it's theoretically possible. You'd need to compute font metrics for your custom fonts (possibly via our infrastructure, but currently not at all easy to do), and possibly switch to KaTeX fallbacks perhaps for missing characters. It'd be a great extension if someone wants to pick it up!
