### ISSUE TITLE
\tag not support 

### ISSUE THREAD

**Issue by kylincodelab** [KaTeX/KaTeX#3861]
> Before reporting a bug

**Describe the bug:**
I have readed the issuse 

https://github.com/KaTeX/KaTeX/issues/899

and try the lastest version, but it not work now.
```
$$\begin{aligned}
    \left(\frac{a}{b}\right)^m&=\underbrace{\left(\frac{a}{b}\right)\cdot \left(\frac{a}{b}\right)\cdots \left(\frac{a}{b}\right)}_{\text{$m$个}}
 \tag{乘方的意义}\\
&=\frac{\overbrace{a\cdot a\cdots a}^{\text{$m$个}}}{\underbrace{b\cdot b\cdots b}_{\text{$m$个}}} \tag{分数乘法法则}\\
&= \frac{a^m}{b^m}\tag{乘方的意义}\\
\end{aligned}$$
```

**To Reproduce:**

**Expected behavior:**
expect \tag work.

![图片](https://github.com/KaTeX/KaTeX/assets/20011546/8f531d76-1e87-4ab9-8512-cf235be240fe)

**Screenshots:**

![图片](https://github.com/KaTeX/KaTeX/assets/20011546/8f531d76-1e87-4ab9-8512-cf235be240fe)

**Comment by edemaine** [comment]
Like LaTeX, you need to use `\begin{align} ... \end{align}` to have multiple tags in a single formula. For example:

```latex
\begin{align}
    \left(\frac{a}{b}\right)^m&=\underbrace{\left(\frac{a}{b}\right)\cdot \left(\frac{a}{b}\right)\cdots \left(\frac{a}{b}\right)}_{\text{$m$个}}
 \tag{乘方的意义}\\
&=\frac{\overbrace{a\cdot a\cdots a}^{\text{$m$个}}}{\underbrace{b\cdot b\cdots b}_{\text{$m$个}}} \tag{分数乘法法则}\\
&= \frac{a^m}{b^m}\tag{乘方的意义}\\
\end{align}
```

![image](https://github.com/KaTeX/KaTeX/assets/2218736/5b9173d2-4124-4897-873f-dce497f8e529)

**Comment by kylincodelab** [comment]
KaTeX parse error: Multiple \tag

**Comment by kylincodelab** [comment]
![图片](https://github.com/KaTeX/KaTeX/assets/20011546/20465066-dd52-48e5-bc6c-f74c64ebed45)

**Comment by edemaine** [comment]
What version of KaTeX are you using?

**Comment by kylincodelab** [comment]
0.16.8







&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "KaTeX/KaTeX"                                                                                    ***@***.***&gt;;
Date:&nbsp;Mon, Sep 25, 2023 10:09 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [KaTeX/KaTeX] \tag not support  (Issue #3861)





 
What version of KaTeX are you using?
