### ISSUE TITLE
Unable to render braces `{}` in 'Support Table' page

### ISSUE THREAD

**Issue by untitledunrevised** [KaTeX/KaTeX#3870]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
Braces $\\{\\}$ are not rendered in the table.

**To Reproduce:**
1. Go to '[Support Table](https://katex.org/docs/support_table)'
2. Click on '[Symbols](https://katex.org/docs/support_table#symbols)'
3. Scroll down to `\{` and `\}`

**Expected behavior:**
Render $\\{$ and $\\}$.

**Screenshots:**
![image](https://github.com/KaTeX/KaTeX/assets/28651011/cb6771d5-82da-4668-8a0a-7f7cdf051449)

**Environment (please complete the following information):**
 - KaTeX Version: 0.16.9
 - Device: Desktop
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 117.0.2045.43

**Additional context:**

**Comment by rahul1995** [comment]
Can someone assign this to me?

**Comment by rahul1995** [comment]
Raised PR #3872 to close this. Please review.
