### ISSUE TITLE
[feature request] array alignment: `\begin{array}{*{3}c}`

### ISSUE THREAD

**Issue by nschloe** [KaTeX/KaTeX#3891]
In `array`s, the alignment spec

```latex
\begin{array}{*{3}c}
a & b & c
\end{array}
```

is equivalent with `ccc`. Would be nice the have this automatically handled in KaTeX.

**Comment by edemaine** [comment]
Agreed; this is a rather old issue, #269, and in fact there's a pending PR #3583 potentially solving it, which I should review.
