### ISSUE TITLE
Limit with blanks space below

### ISSUE THREAD

**Issue by Guseyn** [KaTeX/KaTeX#3919]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
Limit symbol displays a blank space below lim

**To Reproduce:**
```
f'(x) = \frac{df}{dx} = \lim\limits_{\Delta\to0}\frac{f(x + \Delta) - f(x)}{\Delta}
```

**Expected behavior:**
limit without any blank space below

**Screenshots:**
<img width="572" alt="Screenshot 2024-01-12 at 8 06 49 PM" src="https://github.com/KaTeX/KaTeX/assets/7002896/bc30285f-461f-46f8-8931-2f5dd539fe4b">
<img width="204" alt="Screenshot 2024-01-12 at 8 07 12 PM" src="https://github.com/KaTeX/KaTeX/assets/7002896/57550bbb-fb58-4e25-92ae-13e7b478b9bb">

**Environment (please complete the following information):**
 - KaTeX Version:`^0.11.1` - comes from showdown katex plugin
 - Device: [e.g. Desktop]
 - OS: [MacOs]
 - Browser: [e.g. Chrome]
 - Version: [latest]

**Comment by Guseyn** [comment]
In Firefox it works well:
<img width="754" alt="Screenshot 2024-01-12 at 8 27 51 PM" src="https://github.com/KaTeX/KaTeX/assets/7002896/2ec89cad-1a65-4837-b6b0-429a4e78c0cb">

**Comment by edemaine** [comment]
It definitely works on the demo site (also in Chrome):

![image](https://github.com/KaTeX/KaTeX/assets/2218736/a931fdce-f14e-4e7a-b21d-d338cfadb0be)

Perhaps you're using KaTeX in a context where you've overridden some of its CSS rules. If so, please provide more information.

**Comment by Guseyn** [comment]
Yes, it was conflicting class with name `base`.
