### ISSUE TITLE
Line breaks inside \fbox

### ISSUE THREAD

**Issue by rsp4jack** [KaTeX/KaTeX#3922]
**Is your feature request related to a problem? Please describe.**
```latex
$$
\fbox{$foo\newline bar$}
$$
```

$$
\fbox{$foo\newline bar$}
$$

`\newline` does not work.

**Describe the solution you'd like:**
Make it work.

**Comment by edemaine** [comment]
This is how it renders in LaTeX as well: (via QuickLaTeX.com)

![image](https://github.com/KaTeX/KaTeX/assets/2218736/b6741c09-a2f5-4a40-aead-0a2b1f31608e)

So I don't think it's a bug (as KaTeX aims to be compatible with LaTeX).

To gain `\newline`/`\\` ability, you need to wrap in an array environment. For example:

```latex
\fbox{$\begin{array}{l}foo\\bar\end{array}$}
```

![image](https://github.com/KaTeX/KaTeX/assets/2218736/9b66a2a9-a572-4a5a-9ed6-f6ff4a60a7b2)
