### ISSUE TITLE
No character metrics for '³' in style 'Main-Regular' and mode 'text'

### ISSUE THREAD

**Issue by mtrevisan** [KaTeX/KaTeX#3927]
An error is raised in the console (but the character appears to be displayed correctly).

KaTeX code:
```latex
$0.57 \text{ g/cm³}$
```

The generated html code is
```html
<span>
<span class="katex">
<span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>0.57</mn><mtext>&nbsp;g/cm³</mtext></mrow><annotation encoding="application/x-tex">0.57 \text{ g/cm³}</annotation></semantics></math></span>
<span class="katex-html" aria-hidden="true">
<span class="base">
<span class="strut" style="height: 1em; vertical-align: -0.25em;"></span>
<span class="mord">0.57</span>
<span class="mord text">
<span class="mord">&nbsp;g/cm³</span></span></span></span></span></span>
```

**Comment by edemaine** [comment]
`³` is not within the supported Unicode characters of KaTeX's *text mode*, but it should work fine in math mode. So you could write your example like so:

```tex
$0.57 \text{ g/cm$³$}$
```

or

```tex
$0.57 \text{ g/cm}³$
```

or


```tex
$0.57 \text{ g}/\text{cm}³$
```

Here's what the last one looks like in our [demo site](https://katex.org):

![image](https://github.com/KaTeX/KaTeX/assets/2218736/b918ef65-278b-496b-9c5e-f2691aa7a42c)

**Comment by mtrevisan** [comment]
Thank you. I opted for $0.57 \text{ g/cm}^3$
