### ISSUE TITLE
overrightarrow not surport when used in esm，but surported in umd 

### ISSUE THREAD

**Issue by xiaoji201509** [KaTeX/KaTeX#3953]
var katex = require('katex');
var katexInline = function(latex){
        options.displayMode = false;
        try{
            return katex.renderToString(latex, options);
        }
        catch(error){
            if(options.throwOnError){ console.log(error); }
            return latex;
        }
    };

**Comment by xiaoji201509** [comment]
it is bug in this library which is named “markdown-it-katex” ,this library Lock the version of "katex",so cute ,just only when it update ,"katex" can be updated

**Comment by edemaine** [comment]
Ah, so perhaps you should open an issue on markdown-it-katex, not this repository.
