### ISSUE TITLE
No space between formula and text

### ISSUE THREAD

**Issue by myselflohith** [KaTeX/KaTeX#3966]
![Screenshot (101)](https://github.com/KaTeX/KaTeX/assets/117293995/3355a54b-8735-4bba-ad00-1906840738fb)

There is no space between text and formula while pasting Unicode math

**Comment by edemaine** [comment]
KaTeX renders LaTeX math mode.  It sounds like you want LaTeX text mode.  You can enter text mode via `\text{...}`.  For example:

```latex
\text{The sum to $n$ terms of the series, }1+\left(1+\frac{1}{2}+\frac{1}{2^2}\right)+\left(1+\frac{1}{2}+\frac{1}{2^2}+\frac{1}{2^3}+\frac{1}{2^4}\right)
```

![image](https://github.com/KaTeX/KaTeX/assets/2218736/95b7006d-2e39-4acc-b1d1-881d70daf112)

**Comment by myselflohith** [comment]
This is the Unicode generated by Microsoft Office, I can't add \text to text only. Is there any other way to separate the formula and text in Katex while rendering?

The sum to n terms of the series, 1 + \left(1+\frac{1}{2}+\frac{1}{2^2}\right)+ 
\left(1+\frac{1}{2}+\frac{1}{2^2}+\frac{1}{2^3}+\frac{1}{2^4}\right)+ …… is

**Comment by mbourne** [comment]
Two ways to think about this:

(1) Math is math (and get KaTeX to process it), and text is text (just let the browser display your text (in your default page font).

So for your example, you'd have (assuming you're using $ as your delimiter):

The sum to `$n$` terms of the series, `$1 + \left(1+\frac{1}{2}+\frac{1}{2^2}\right)+
\left(1+\frac{1}{2}+\frac{1}{2^2}+\frac{1}{2^3}+\frac{1}{2^4}\right)+ ...$` is 

(2) If you want the whole thing to look like a LaTeX PDF (kind of) with all text looking like the example @edemaine gave above, but it's too troublesome to manipulate Word's output, you could use the same code I gave in (1), but style the ordinary HTML text on your page using KaTeX fonts via the use of `class="katex"`.

It would be something like this:

`<p><span class="katex">The sum to </span> $n$ <span class="katex">terms of the series, </span> $1 + \left(1+\frac{1}{2}+\frac{1}{2^2}\right)+
\left(1+\frac{1}{2}+\frac{1}{2^2}+\frac{1}{2^3}+\frac{1}{2^4}\right)+ ...$ <span class="katex">is ...</span>`

The output is something like (for a different example than yours):

![image](https://github.com/user-attachments/assets/9f216dcb-fec4-441f-8990-e625b7215b76)

I'd suggest approach (1). It's easier.

Regards
Murray

**Comment by myselflohith** [comment]
Thank you, @mbourne , for your suggestion. However, my database has over 100,000 lines, which include both text and Unicode characters. It is not possible to separate them for each line. Can you please share the code as well?

<p>The sum to n terms of the series, 1 + \left(1+\frac{1}{2}+\frac{1}{2^2}\right)+
\left(1+\frac{1}{2}+\frac{1}{2^2}+\frac{1}{2^3}+\frac{1}{2^4}\right)+ …… is</p>

**Comment by mbourne** [comment]
I gather your output from Word has no `<span>` tags around the math. Is this correct? Or have you saved as text only, thus losing any markup?

If so, and if Word doesn't give you an option to do so, then you may have success doing the following.

In the original Word document, do "Save as..." and choose HTML. It will probably save the math as images and if you're lucky, the math content will be included as the alt tag, or in a data tag on the img.

Then it's possible to separate out the plain text and the math (using JavaScript at run time, or better, preprocessing it with PHP or similar), then get KaTeX to process the math.

I haven't used Micro$oft products in years, so not sure what options are actually available to you.

Regards
