### ISSUE TITLE
Certain expressions display incorrectly when overflowing container with `overflow: hidden` and `text-overflow: ellipsis`

### ISSUE THREAD

**Issue by jsspiegel** [KaTeX/KaTeX#3968]
> Before reporting a bug
- [X] Check [common issues](https://katex.org/docs/issues.html).
- [x] ~Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.~ Not applicable, involves custom CSS.
- [X] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
When rendering certain expressions that overflow an element with CSS styles `overflow: hidden` and `text-overflow: ellipsis`, the expressions do not display properly. In the linked example, the expression that should be displayed (and cut off at some point due to the overflow) is `(10^n)^m = 10^{n \\bullet m}.`, but what ends up getting displayed is roughly `{}^n \space {}^m`.

I was able to work around this issue in my case by adding an `\\allowbreak` between the `(10^n)^m` and the `=`, but I still believe that that should not be necessary and that this behavior is a bug that should be fixed.

[CodePen demonstrating both the issue and the workaround.](https://codepen.io/jspiegel/pen/eYwNOgy)

**To Reproduce:**
See CodePen above.

**Expected behavior:**
It's not immediately obvious what the expected behavior should be, but I think that either cutting off before the beginning of the expression or cutting off between the `(10^n)^m` and the `=` would be acceptable.

**Screenshots:**
Bug:
<img width="510" alt="Screenshot 2024-07-11 at 2 27 00 PM" src="https://github.com/KaTeX/KaTeX/assets/12619580/a56108a1-29bd-479b-b831-202f76b1d9ca">

With workaround:
<img width="510" alt="Screenshot 2024-07-11 at 2 27 06 PM" src="https://github.com/KaTeX/KaTeX/assets/12619580/7a2b0053-55bc-4860-823c-6c30e064a4db">

**Environment (please complete the following information):**
 - KaTeX Version: 0.16.11
 - Device: Desktop
 - OS: macOS 13
 - Browser: Chrome
 - Version: 124

**Additional context:**
I was also able to reproduce this issue on Safari 17.5. I was unable to reproduce this issue on Firefox 128.

**Comment by edemaine** [comment]
[text-overflow](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow) is implemented by the browser, and we can't control it. I also believe it is very limited with what it can control. For example, MDN writes:

> The `text-overflow` property only affects content that is overflowing a block container element in its inline progression direction (not text overflowing at the bottom of a box, for example).

KaTeX doesn't render as simple inline text; it uses a trick called `vlist` to stack blocks, most obviously when it comes to fractions, but for any vertical offset including superscripts. So I don't think we can (easily) fix this, barring a complete overhaul to the `vlist` hack. ☹️

**Comment by jsspiegel** [comment]
@edemaine No worries, thank you for the explanation - I appreciate you taking the time to consider this!
