### ISSUE TITLE
Katex throws parsing error despite "throwOnError" to be false

### ISSUE THREAD

**Issue by kenjinp** [KaTeX/KaTeX#3973]
### **Describe the bug:**
Katex throws an error on parsing despite "throwOnError" to be false on the following value. This explodes `rehype-katex`, an upstream consumer. 

### Error: 
```
Error: Expected node of type textord, but got node of type color
```

### Naughty Value
```javascript
const naughtyValue =
  "\\begin{\\align}\n\\begin{pmatrix} y_1 \\\\ \\vdots \\\\ y_n \\end{pmatrix} = \\begin{pmatrix} 1 \\end{pmatrix}\n\\end{align}";

```

### **To Reproduce:**
1. Check out my small demo [on codesandbox where the bug can be easily reproduced](https://codesandbox.io/p/sandbox/test-katex-bug-rhmstw?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm03ztyt600063b6i3l42j8bb%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm03ztyt600023b6iracrk58s%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm03ztyt600033b6iyig8e5ke%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm03ztyt600053b6ihcbmwfxl%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm03ztyt600023b6iracrk58s%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm03ztyt500013b6i1d3ol1y8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%257D%255D%252C%2522id%2522%253A%2522cm03ztyt600023b6iracrk58s%2522%252C%2522activeTabId%2522%253A%2522cm03ztyt500013b6i1d3ol1y8%2522%257D%252C%2522cm03ztyt600053b6ihcbmwfxl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm03ztyt600043b6iy43w1u56%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522cm03ztyt600053b6ihcbmwfxl%2522%252C%2522activeTabId%2522%253A%2522cm03ztyt600043b6iy43w1u56%2522%257D%252C%2522cm03ztyt600033b6iyig8e5ke%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm03ztyt600033b6iyig8e5ke%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### **Expected behavior:**
I expect the `Katex` not to throw an error in this instance

**Environment (please complete the following information):**
 - KaTeX Version: 0.16.11 (latest)
 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Version: 127

**Comment by kenjinp** [comment]
similar to this issue, I think https://github.com/KaTeX/KaTeX/issues/3942

**Comment by chyi13** [comment]
+1

**Comment by edemaine** [comment]
Closing this in favor of #3942

Note that `throwOnError` does not catch all parse errors (despite its name). It only catches unsupported commands. You should always catch errors via `try` when using KaTeX.
