### ISSUE TITLE
KaTeX treats `*` in user defined macros as an option

### ISSUE THREAD

**Issue by magic0whi** [KaTeX/KaTeX#3975]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
The KaTeX wrongly interpret the symbol `*` in a macro invoke as its first option. 

**To Reproduce:**
1. Define macros in JS:
   ```javascript
   const macros = { "\\abs": "\\@ifstar{\\left\\lvert#1\\right\\rvert}{\\lvert#1\\rvert}" };
   var output = katex.renderToString(blk.body, { macros });
   ```
   Or in document:
   ```latex
   \newcommand{\abs}[1]{\@ifstar{\left\lvert#1\right\rvert}{\lvert#1\rvert}}
   ```
2. Run and render this.
   ```latex
   \begin{aligned}
     \verb!\abs{x}!\text{: }\abs{x}\\
     \verb!\abs*{x}!\text{: }\abs*{x}
   \end{aligned}
   ```

**Expected behavior:**
It should use contents in brackets, in this case it will be `\left\lvert x\right\rvert`.

**Screenshots:**
![image](https://github.com/user-attachments/assets/e15c2dba-1b75-42ca-8ca1-16b4800d8fbc)

**Environment (please complete the following information):**
 - KaTeX Version: katex@0.16.11
 - Device: YogaAir 14s
 - OS: Arch Linux x86_64
 - Browser: Firefox
 - Version: 129.0.1-2

**Additional context:**
Using [Honkit](https://honkit.netlify.app/) with [honkit-plugin-katex](https://github.com/magic0whi/notebook/tree/main/honkit-plugin-katex)

**Comment by edemaine** [comment]
I believe that is how `\@ifstar` works in LaTeX. If you specify a macro as having one argument (via `\newcommand...[1]` say), it's too late - you've already consumed the star (which is just another character like 'a' ) as an argument. You need to make a zero-argument function, use `\@ifstar` to detect a star, and then call one of two different versions of your macro which can correctly consume the star and/or argument. (`\def` is usually a nice way to consume the star.)

**Comment by edemaine** [comment]
Here's an example of your desired functionality working with these macros:

```js
macros: {
    "\\abs": "\\@ifstar\\abs@star\\abs@",
    "\\abs@star": "\\left\\lvert#1\\right\\rvert",
    "\\abs@": "\\lvert#1\\rvert"
}
```

![image](https://github.com/user-attachments/assets/301ae426-dfd2-4bc3-8b1f-4a3256a259be)

The key is that `\abs` doesn't use `#1` so it doesn't consume the first argument, leaving it to be consumed by `\@ifstar`.

Hope this helps!
