### ISSUE TITLE
tag function not work

### ISSUE THREAD

**Issue by wuxue107** [KaTeX/KaTeX#3985]
> Before reporting a bug

**Describe the bug:**

```
$$
x = a_0+\cfrac{1^2}{a_1+\cfrac{2^2}{a_2+\cfrac{3^2}{a_3+\cfrac{4^2}{a_4+\cdots}}}} \tag{\cfrac}
$$
```
![image](https://github.com/user-attachments/assets/42767b1a-45ba-4c8e-980d-bba5b80925b6)

 not work In KaTex

**Comment by ronkok** [comment]
It doesn't work in LaTeX, either.  Try `\tag{\textbackslash cfrac}`.
