### ISSUE TITLE
Feature Suggestion: default display math environment

### ISSUE THREAD

**Issue by aterenin** [KaTeX/KaTeX#3987]
**Is your feature request related to a problem? Please describe.**

In LaTeX, many people use the `align` or `align*` environment as their default equation environment, since this automatically supports alignment via `&` and multi-line equations via `\\` without any large downsides if none of these characters are present.

Right now, I use KaTeX as a math scratch-work tool in VS Code. I recently created a snippet for
```
$$
\begin{align}

\end{align}
$$
```
so that all my display-style equations are numbered, and support alignment character if need be. This results in a more-verbose file than I believe is ideal.

**Describe the solution you'd like:**

I propose to add an option called `displayMathEnvironment` which would have six options: `equation*` (default). `equation`, `align*`, `align`, `gather*`, `gather`. 

* If `equation*` is selected, the package works as current. 
* If any other option is selected, such as `align`, KaTeX will wrap all `$$` blocks in `\begin{align}` and `\end{align}` or similar for the other options.

For example, if `displayMathEnvironment` is set to `align` then the Markdown code
```
$$
y &= 2x
&
z &= 5
$$
```
would be rendered as if it was
```
$$
\begin{align}
y &= 2x
&
z &= 5
\end{align}
$$
```
without the user needing to explicitly write the environment.

Potentially, a `smart` option that auto-switches between `align` and `gather` variants - centering multiple lines if there is no `&` and aligning them if `&` occurs - would also be an idea, plus its starred version. I generally redefine `\[` and `\]` to do this in my own LaTeX files with an implementation that relies on `in@` and `ifin@`. 

As a convenient by-product, this option also gives a clean way to automatically number all equations if one wants to do so.

**Describe alternatives you've considered:**

If using server-side rendering, one alternative is to wrap `render` with code that adds these environments. But in many cases, such as for instance in VS Code, KaTeX is loaded upstream and these API calls are not directly user-accessible without significant hacking. In parallel, there are widely-used extensions that allow one to change KaTeX' options, which is technically much less intrusive than monkey-patching `render` or similar. A package-wide option for such use cases would be helpful, otherwise one has to create extensions for each software individually.

**Comment by edemaine** [comment]
Thanks for the request. I don't think this feature makes sense for KaTeX, which aims to be compatible with LaTeX inputs. `$$...$$` has a well-defined meaning, which it's not easily possible to redefine.

Out of curiosity, why are you writing

```latex
$$
\begin{align}

\end{align}
$$
```

instead of just

```latex
\begin{align}

\end{align}
```

? At least LaTeX Workshop in VSCode supports rendering previews for the latter. Maybe other plugins do not, but that should be a bug report for those plugins.
