### ISSUE TITLE
i can show $$\left\{ x \right.$$ , but \[\left\{ x \right.\] will not show, I'm wondering why?

### ISSUE THREAD

**Issue by ericjiajia** [KaTeX/KaTeX#3994]
i can show ``` $$\left\{ x  \right.$$ ```, but ``` \[\left\{ x  \right.\] ``` will not show, I'm wondering why?

i have already used katex/contrib/auto-render：
![image](https://github.com/user-attachments/assets/b5a5ba3f-4411-416d-a748-2d5e39eb319f)

others ``` \[ ... \] ``` will be show correctly

this is our katex demo repo：[katex-demo-link](https://github.com/xinla/katex-test)

it uses VUE3 and node 18.20.4，u can use   pnpm run dev to run the project. and u will see latex examples in lines 25, 27, and 29 of App.vue in the project.

or u can see my [codesandbox-link](https://codesandbox.io/p/devbox/sc4qx2)

Lines 25 and 29 use the same identifier. Lines 27 and 29 use the same latex formula, but the identifiers are inconsistent. However, lines 25 and 27 can be rendered, regardless of line 29. Cannot be rendered in any way

**Comment by edemaine** [comment]
These lines are incorrect:

```js
{ left: '\(', right: '\)', display: false },
{ left: '\[', right: '\]', display: true },
```

Can you remove them? Or fix them to

```js
{ left: '\\(', right: '\\)', display: false },
{ left: '\\[', right: '\\]', display: true },
```

**Comment by ericjiajia** [comment]
> These lines are incorrect:
> 
> ```js
> { left: '\(', right: '\)', display: false },
> { left: '\[', right: '\]', display: true },
> ```
> 
> Can you remove them? Or fix them to
> 
> ```js
> { left: '\\(', right: '\\)', display: false },
> { left: '\\[', right: '\\]', display: true },
> ```
> 
> P.S. I can't access the CodeSandbox. Permissions issue?

i have invited u to my codesanbox: https://codesandbox.io/p/devbox/sc4qx2

this is my cases:
![image](https://github.com/user-attachments/assets/eede89f3-fae7-402a-9c1f-f602f7056813)

**Comment by edemaine** [comment]
I see now that you're rendering the text via `marked`. This causes the `\[` in the input to be converted to `[`, and then KaTeX can't find it.

If you want both `marked` and KaTeX, consider using a KaTeX extension for `marked`.
