### ISSUE TITLE
add \rddots

### ISSUE THREAD

**Issue by nschloe** [KaTeX/KaTeX#4002]
I need to represent reversed ddots for
```latex
\documentclass{article}

% https://tex.stackexchange.com/a/17687/13262
\def\rddots#1{\cdot^{\cdot^{\cdot^{#1}}}}

\begin{document}
\[
2^{2^{\rddots2}}
\]
\end{document}
```

![screenshot_2024-12-11-124240](https://github.com/user-attachments/assets/5db60f57-af99-455d-89c5-48f3253cc330)

Perhaps it'd be worthwhile adding this to KaTeX's dots line-up.

**Comment by edemaine** [comment]
You're welcome to define your own macros! (using either `\def` like this, or the `macros` option)

KaTeX doesn't generally implement random macros from TeX StackExchange; that's what custom macros are for.

KaTeX is more inclined to include macros from standard LaTeX packages. From that same StackExchange post, [mathdots](https://ctan.org/tex-archive/macros/generic/mathdots) and its `\iddots` seem reasonable. The macro definition for `\iddots` might even be reasonable to implement directly, as it mostly uses `\kern`, `\raisebox`, and `\ldotp` which we have. I believe this is a good translation:

```latex
\mkern1mu\raisebox{1pt}{$\ldotp$}
\mkern2mu\raisebox{4pt}{$\ldotp$}
\mkern2mu\raisebox{7pt}{$\ldotp$}
\rule{0pt}{14pt}
```

![image](https://github.com/user-attachments/assets/482d9f9a-df31-4c07-8157-79f6478f20b3)

![image](https://github.com/user-attachments/assets/3d443393-8e9e-4cfb-b888-77f6ad0b6fb1)

This seems to roughly match the LaTeX rendering, but is a bit ugly.
