### ISSUE TITLE
Add optional pre-process callback to the auto-renderer

### ISSUE THREAD

**Issue by netw0rkf10w** [KaTeX/KaTeX#450]
Hello,
It would be great adding an option for rendering inline math in display style (but not centering it). In MathJax, it suffices to add:

```
<script type="text/x-mathjax-config"> 
        MathJax.Hub.Register.StartupHook("TeX Jax Ready",function () { 
          var TEX = MathJax.InputJax.TeX; 
          var PREFILTER = TEX.prefilterMath; 
          TEX.Augment({ 
            prefilterMath: function (math,displaymode,script) { 
              math = "\\displaystyle{"+math+"}"; 
              return PREFILTER.call(TEX,math,displaymode,script); 
            } 
          }); 
        }); 
        </script>
```

Thank you in advance!

**Comment by sthoch** [comment]
The \displaystyle command is supported by KaTeX. Are you asking for an automated option that applies it to all TeX-code on a page?

**Comment by netw0rkf10w** [comment]
@sthoch: yes, that's exactly what I meant :D

**Comment by sthoch** [comment]
Then you are asking for an prefilter for the autorenderer. Consider renaming your issue accordingly.

**Comment by netw0rkf10w** [comment]
@sthoch : oh yes, you are right, this should be assigned to the autorenderer. Thanks.

**Comment by rdnz** [comment]
I just opened a new issue, actually I am looking for the same feature as this issue does.

**Comment by kevinbarabash** [comment]
The pre-filter idea is interesting.  I can see people using that function for other things like converting non-breaking spaces to normal spaces or rewriting `\align*` as `\aligned`.
