### ISSUE TITLE
\hbar is too thick

### ISSUE THREAD

**Issue by khrykin** [KaTeX/KaTeX#552]
KaTeX (OSX 10.10.5 Retina):
![image](https://cloud.githubusercontent.com/assets/5675885/19616674/3473252c-9822-11e6-8ce3-2927a1fea6ff.png)
LaTeX:
![image](https://cloud.githubusercontent.com/assets/5675885/19616676/38dc1b28-9822-11e6-812a-947f78f015e3.png)

Looks really bad at big font sizes.

**Comment by kevinbarabash** [comment]
Looks like that glyph is from the wrong font.  Looking at https://github.com/Khan/KaTeX/blob/master/metrics/mapping.pl it seems like we have the right glyph in KaTeX_Main.

**Comment by kevinbarabash** [comment]
It's interesting that even the regular `h` is a little heavy.  I think the MathJax fonts which the KaTeX fonts are based on made many of the glyphs a little heavier.

**Comment by kevinbarabash** [comment]
I checked and MathJax has the same issue.  See https://github.com/mathjax/MathJax/issues/1674 for details and a proposed solution.

**Comment by jakelishman** [comment]
I just wanted to bump this, because I think all that's needed is a redistribution of the fonts.

I rebuilt all the fonts using the `buildFonts.sh` script in the fonts submodule, and the resulting files were generated with a correctly weighted hbar at U+210F, with no changes to any generation code.

**Comment by kevinbarabash** [comment]
@jakelishman I just checked on katex.org and the weight of `\hbar` matches that of `h` so I think this is fixed now.  Thanks for taking the time to investigate this.

<img width="174" alt="Screen Shot 2020-08-01 at 11 11 36 PM" src="https://user-images.githubusercontent.com/1044413/89114611-6082a880-d44c-11ea-8579-545be9d4d449.png">
