### ISSUE TITLE
Error with same formula (probably encoding)

### ISSUE THREAD

**Issue by SamyPesse** [KaTeX/KaTeX#69]
I'm currently working on building a KaTex plugin for [GitBook](https://github.com/GitbookIO/gitbook) (as an alternative to MathJax).

But I have a problem with my tests, a formula is crashing when extracted from page (server-side using [cheerio](https://www.npmjs.org/package/cheerio), here is [the complete code](https://github.com/GitbookIO/plugin-katex/blob/master/index.js#L23)), but when running it directly, it's working fine: `katex.renderToString("x = {-c \pm \sqrt{b^2-4ac} \over 2a}.")`.

When crashing the error is (the first line is a log to be sure that the formula is the same):

```
convert 'x = {-c \pm \sqrt{b^2-4ac} \over 2a}.'
KaTeX parse error: Expected '}', got '\over' at position 32: {b^2-4ac} \over̲ 2a}.
```

I guess this is an encoding problem, but the same code is working for other formulas (only crashing for this one).

**Comment by ranjithnori** [comment]
@spicyj Since this is a very common use case, , I think I'm missing something here. 
How do we automatically escape the backslashes from a string that we give as input to katex.renderToString() ?

**Comment by spicyj** [comment]
Where does the string come from? If it is embedded as a JS string literal in your JS source code, you need to add the backslashes automatically. Otherwise, you shouldn't need to do anything.

**Comment by ranjithnori** [comment]
Thanks for clarifying! :)
