### ISSUE TITLE
process suggestion: open an issue and have it assigned before starting work

### ISSUE THREAD

**Issue by kevinbarabash** [KaTeX/KaTeX#843]
As more people are contributing to KaTeX, the possibility that multiple people might start working on the same thing or taking the same code in different directions increases.  One way that we can minimize the odds of this happening might be to request that people open an issue before starting work on a PR.  We can use the "Assignees" field to indicate who is working on something.  Contributors with push access can assign themselves.  New contributors should leave a message in either new or existing issues indicating their interest and someone will assign them.

**Comment by edemaine** [comment]
Maybe we can make use of assignees for PR review too?  Namely, assign it to yourself when you start reviewing.
