### ISSUE TITLE
support \includegraphics

### ISSUE THREAD

**Issue by kevinbarabash** [KaTeX/KaTeX#898]
There are multiple versions of this command.  I'm leaning towards the `graphicx` version because it requires nesting within `\rotatebox` and `\scalebox` for rotation and scaling operations.  It seems likes this would avoid duplicate code b/c we want those commands as well (#681).

There's a number of different options that `\includegraphics` can take.  I think to start with support `width` and `height` are probably the easiest.  The options are provided as a key-value list, e.g. 
```
\includegraphics[width=320,height=240]{my-awesome-image}
```

While the file extension can be included, https://www.sharelatex.com/learn/Inserting_Images advises not to as LaTeX will look for all sorts of different image types with the same name.  We probably want to avoid this behavior as it will be hard to implement in a performant way on the web.

A related command, `\graphicspath` provides a way to specify where to look for the images, e.g. 
```
\graphicspath{ {images/} }
```

After skimming through the [graphicx docs](http://muug.ca/mirror/ctan/macros/latex/required/graphics/grfguide.pdf) it's unclear to me whether the filename used in `\includegraphics` can include a full and/or relative path.

**Comment by edemaine** [comment]
Fixed by #1620.
